<?php

declare(strict_types=1);
namespace CetechDeliveryEngine\Tests\Unit\ServicePromise\Shipment;
use CetechDeliveryEngine\Application\ServicePromise\Calculation\DeterministicPromiseCalculator;
use CetechDeliveryEngine\Application\ServicePromise\Shipment\PaymentConfirmedPromisePrediction;
use CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime;
use CetechDeliveryEngine\Domain\ServicePromise\Handoff\PromiseHistoricalPacket;
use CetechDeliveryEngine\Domain\ServicePromise\Shipment\ShipmentCurrentPromise;
use CetechDeliveryEngine\Tests\Support\ServicePromise\Calculation\CalculationFixture as F;
use PHPUnit\Framework\TestCase;
require_once dirname(__DIR__,3).'/Support/ServicePromise/Calculation/CalculationFixture.php';
final class PaymentConfirmedPromisePredictionTest extends TestCase {
 private function packet(array $changes=[],array $calendars=[]):PromiseHistoricalPacket{$policy=F::policy(array_replace(['anchor'=>'payment_confirmed','late_payment_rule'=>'relative_after_payment'],$changes),$calendars);$input=F::input($policy);return PromiseHistoricalPacket::capture((new DeterministicPromiseCalculator(F::runtime()))->calculate($input,$calendars),'10–20 minutes after payment confirmation');}
 public function test_delayed_real_payment_predictions_retain_original_relative_packet_and_anchor():void{$packet=$this->packet();$before=$packet->to_private_json();$current=(new PaymentConfirmedPromisePrediction())->calculate($packet,RuleTime::parse('2026-10-11 12:00:00.000000'),F::runtime(),[],hash('sha256','event'));self::assertSame('absolute_window',$current->private_facts()['state']);self::assertSame('2026-10-11 12:10:00.000000',$current->private_facts()['views'][0]['from']);self::assertSame('2026-10-11 12:20:00.000000',$current->private_facts()['views'][0]['until']);self::assertSame($before,$packet->to_private_json());self::assertSame('payment_confirmed',$packet->input_facts()['anchor']['kind']);self::assertSame('relative_window',$packet->result_facts()['state']);}
 public function test_other_endpoint_graph_terminal_is_preserved_but_not_shown_in_current_view():void{$components=[F::component(),F::component('warehouse',['endpoint'=>'warehouse-counter','endpoint_kind'=>'pickup'])];$packet=$this->packet(['graph'=>['format_version'=>1,'components'=>$components,'terminal_component_ids'=>['delivery','warehouse']]]);$current=(new PaymentConfirmedPromisePrediction())->calculate($packet,RuleTime::parse('2026-10-11 12:00:00.000000'),F::runtime(),[],hash('sha256','event'));self::assertSame('absolute_window',$current->private_facts()['state']);self::assertCount(1,$current->private_facts()['views']);self::assertCount(2,$packet->result_facts()['body']['terminal_windows']);}
 public function test_native_whole_second_paid_anchor_handles_same_second_capture_without_fabricated_precision():void{$policy=F::policy(['anchor'=>'payment_confirmed','late_payment_rule'=>'relative_after_payment']);$input=F::input($policy,'2026-10-09 10:00:00.900000');$packet=PromiseHistoricalPacket::capture((new DeterministicPromiseCalculator(F::runtime()))->calculate($input,[]),'Original relative estimate');$paid=RuleTime::parse('2026-10-09 10:00:00.000000');$current=(new PaymentConfirmedPromisePrediction())->calculate($packet,$paid,F::runtime(),[],hash('sha256','event'));self::assertSame('absolute_window',$current->private_facts()['state']);self::assertSame($paid->sql(),$current->private_facts()['event_at']);self::assertSame('2026-10-09 10:10:00.000000',$current->private_facts()['views'][0]['from']);$earlier=(new PaymentConfirmedPromisePrediction())->calculate($packet,RuleTime::parse('2026-10-09 09:59:59.000000'),F::runtime(),[],hash('sha256','event'));self::assertSame('unavailable',$earlier->private_facts()['state']);}
 public function test_runtime_mismatch_records_unavailable_without_partial_views():void{$packet=$this->packet();$runtime=F::runtime();$runtime['digest']=hash('sha256','foreignruntime');$current=(new PaymentConfirmedPromisePrediction())->calculate($packet,RuleTime::parse('2026-10-11 12:00:00.000000'),$runtime,[],hash('sha256','event'));self::assertSame('unavailable',$current->private_facts()['state']);self::assertSame([],$current->private_facts()['views']);self::assertSame($packet->digest(),$current->private_facts()['original_packet_digest']);}
 public function test_paid_timestamp_before_original_capture_cannot_create_current_window():void{$current=(new PaymentConfirmedPromisePrediction())->calculate($this->packet(),RuleTime::parse('2026-10-09 09:59:59.999999'),F::runtime(),[],hash('sha256','event'));self::assertSame('unavailable',$current->private_facts()['state']);}
 public function test_absolute_original_is_never_reanchored_at_payment():void{$input=F::input();$packet=PromiseHistoricalPacket::capture((new DeterministicPromiseCalculator(F::runtime()))->calculate($input,[]),'Captured estimate');$current=(new PaymentConfirmedPromisePrediction())->calculate($packet,RuleTime::parse('2026-10-11 12:00:00.000000'),F::runtime(),[],hash('sha256','event'));self::assertSame('unavailable',$current->private_facts()['state']);self::assertSame('absolute_window',$packet->result_facts()['state']);}
 public function test_business_day_current_prediction_uses_exact_frozen_calendar_version():void{$calendar=F::calendar();$component=F::component();$component['duration']=['format_version'=>1,'min'=>1,'max'=>2,'unit'=>'business_days','calendar'=>$calendar->reference()->private_facts()];$packet=$this->packet(['graph'=>['format_version'=>1,'components'=>[$component],'terminal_component_ids'=>['delivery']]],[$calendar]);$current=(new PaymentConfirmedPromisePrediction())->calculate($packet,RuleTime::parse('2026-10-11 12:00:00.000000'),F::runtime(),[$calendar],hash('sha256','event'));self::assertSame('absolute_window',$current->private_facts()['state']);self::assertSame('2026-10-12 12:00:00.000000',$current->private_facts()['views'][0]['from']);self::assertSame('2026-10-13 12:00:00.000000',$current->private_facts()['views'][0]['until']);$missing=(new PaymentConfirmedPromisePrediction())->calculate($packet,RuleTime::parse('2026-10-11 12:00:00.000000'),F::runtime(),[],hash('sha256','event'));self::assertSame('unavailable',$missing->private_facts()['state']);$changed=F::calendar(['version'=>2]);$foreign=(new PaymentConfirmedPromisePrediction())->calculate($packet,RuleTime::parse('2026-10-11 12:00:00.000000'),F::runtime(),[$changed],hash('sha256','event'));self::assertSame('unavailable',$foreign->private_facts()['state']);}
 public function test_current_shopper_view_excludes_internal_staff_reason_runtime_and_source_identifiers():void{$current=(new PaymentConfirmedPromisePrediction())->calculate($this->packet(),RuleTime::parse('2026-10-11 12:00:00.000000'),F::runtime(),[],hash('sha256','event'));$facts=$current->private_facts();$facts['source']='staff_revision';$facts['reason']='Internal supplier scheduling issue';$staff=ShipmentCurrentPromise::from_array($facts);self::assertArrayNotHasKey('reason',$staff->public_facts());self::assertArrayNotHasKey('runtime',$staff->public_facts());self::assertArrayNotHasKey('event_key',$staff->public_facts());self::assertSame($staff->to_private_json(),ShipmentCurrentPromise::from_json($staff->to_private_json())->to_private_json());$this->expectException(\LogicException::class);json_encode($staff,JSON_THROW_ON_ERROR);}
 public function test_private_current_prediction_cannot_be_unserialized_generically():void{$class=ShipmentCurrentPromise::class;$this->expectException(\LogicException::class);unserialize('O:'.strlen($class).':"'.$class.'":0:{}');}
 public function test_current_prediction_closed_shape_refuses_extra_private_policy_or_unknown_source():void{$current=(new PaymentConfirmedPromisePrediction())->calculate($this->packet(),RuleTime::parse('2026-10-11 12:00:00.000000'),F::runtime(),[],hash('sha256','event'));$facts=$current->private_facts();$facts['policy']=$this->packet()->input_facts()['policy'];$this->expectException(\InvalidArgumentException::class);ShipmentCurrentPromise::from_array($facts);}
}
