<?php

declare(strict_types=1);
namespace CetechDeliveryEngine\Tests\Unit\ServicePromise\Shipment;

use CetechDeliveryEngine\Application\DeliveryQuote\NativeCartQuotePreparation;
use CetechDeliveryEngine\Application\Shipment\ShipmentOriginalPromiseReference;
use CetechDeliveryEngine\Domain\ServicePromise\Persistence\PromiseSiteBinding;
use CetechDeliveryEngine\Domain\ServicePromise\PromiseJson;
use CetechDeliveryEngine\Domain\ServicePromise\Shipment\{ShipmentPromiseStored,ShipmentRecordedPromiseReference};
use CetechDeliveryEngine\Domain\Shipment\Shipment;
use CetechDeliveryEngine\Tests\Unit\Shipment\ShipmentOriginalPromiseReferenceTest;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

require_once dirname(__DIR__,2).'/Shipment/ShipmentOriginalPromiseReferenceTest.php';

/** Synthetic domain links only; native SQL producer/authority is qualified separately. */
final class ShipmentPromiseStoredTest extends TestCase {
 private function captured(string $state='absolute_window'):array{$fixture=new ShipmentOriginalPromiseReferenceTest('test_optional_refusal_has_recorded_history_without_accepted_original_reference');return (new \ReflectionMethod($fixture,'captured'))->invoke($fixture,$state);}
 private function row(string $state='absolute_window'):array{[$envelope,$link]=$this->captured($state);$shipment=Shipment::create(100,'in_warehouse|delivery|1',id:10,fulfilment_choice:'delivery');$reference=ShipmentRecordedPromiseReference::from_recorded($shipment,$envelope,$link);$packet=$envelope->promise_packet()->group(NativeCartQuotePreparation::component_key($shipment->delivery_group_id));return ['id'=>'1','site_id'=>'1','site_key'=>$packet->input_facts()['site_id'],'shipment_id'=>'10','order_id'=>'100','delivery_group_id'=>$shipment->delivery_group_id,'revision'=>'2','original_json'=>$reference->to_private_json(),'original_digest'=>$reference->digest(),'packet_json'=>$packet->to_private_json(),'packet_digest'=>$packet->digest(),'current_json'=>null,'current_digest'=>null,'original_namespace_hash'=>hash('sha256','original-namespace'),'original_intent_hash'=>hash('sha256','original-intent'),'current_namespace_hash'=>null,'current_intent_hash'=>null,'created_at'=>'2026-10-09 10:00:00.000000','updated_at'=>'2026-10-09 10:00:00.000000'];}
 #[DataProvider('states')]
 public function test_saved_canonical_original_row_round_trips_without_associative_key_order_authority(string $state):void{$row=$this->row($state);$stored=ShipmentPromiseStored::from_row($row,PromiseSiteBinding::bind(1,$row['site_key']));self::assertSame($row['original_json'],$stored->row()['original_json']);self::assertSame($row['packet_digest'],$stored->packet()->digest());self::assertSame($state,$stored->packet()->result_facts()['state']);self::assertNull($stored->current());self::assertSame(PromiseJson::encode($stored->packet()->public_facts()),PromiseJson::encode($stored->original_public()));}
 public static function states():iterable{yield ['absolute_window'];yield ['relative_window'];yield ['unavailable'];}
 public function test_accepted_original_new_row_carrier_has_exact_retained_original_bytes_and_domain():void{[$envelope,$link]=$this->captured();$shipment=Shipment::create(100,'in_warehouse|delivery|1',id:10,fulfilment_choice:'delivery');$retained=ShipmentOriginalPromiseReference::from_original($shipment,$envelope,$link);$recorded=ShipmentRecordedPromiseReference::from_recorded($shipment,$envelope,$link);self::assertSame($retained->to_private_json(),$recorded->to_private_json());self::assertSame($retained->digest(),$recorded->digest());}
 public function test_stored_row_detaches_borrowed_scalar_references():void{$row=$this->row();$borrowed=$row['original_namespace_hash'];$row['original_namespace_hash']=&$borrowed;$stored=ShipmentPromiseStored::from_row($row,PromiseSiteBinding::bind(1,$row['site_key']));$borrowed=hash('sha256','mutated-caller-reference');self::assertSame(hash('sha256','original-namespace'),$stored->row()['original_namespace_hash']);}
 public function test_changed_original_shipment_link_refuses_even_with_recomputed_json_digest():void{$row=$this->row();$original=PromiseJson::decode($row['original_json']);$original['shipment']['order_id']=101;$row['original_json']=PromiseJson::encode($original);$row['original_digest']=hash('sha256','cetech-shipment-original-promise-reference-v1:'.$row['original_json']);$this->expectException(\InvalidArgumentException::class);ShipmentPromiseStored::from_row($row,PromiseSiteBinding::bind(1,$row['site_key']));}
 #[DataProvider('nested_mutations')]
 public function test_original_nested_schema_refuses_mutation_with_recomputed_digest_without_php_warning(array $path,string $mutation):void{$row=$this->row();$original=PromiseJson::decode($row['original_json']);$target=&$original;foreach($path as $field){$target=&$target[$field];}if('unknown'===$mutation){$target['unexpected']='untrusted';}elseif('missing'===$mutation){unset($target[array_key_first($target)]);}elseif('nonobject'===$mutation){$target='untrusted';}else{$target=$mutation;}unset($target);$row['original_json']=PromiseJson::encode($original);$row['original_digest']=hash('sha256','cetech-shipment-original-promise-reference-v1:'.$row['original_json']);set_error_handler(static function(int $severity,string $message):never{throw new \ErrorException($message,0,$severity);});try{ShipmentPromiseStored::from_row($row,PromiseSiteBinding::bind(1,$row['site_key']));self::fail('Changed original history must refuse.');}catch(\InvalidArgumentException){self::assertTrue(true);}finally{restore_error_handler();}}
 public static function nested_mutations():iterable{foreach([['shipment'],['promise'],['promise','original'],['promise','quote'],['promise','snapshot'],['promise','final_event']] as $path){foreach(['unknown','missing','nonobject'] as $mutation){yield implode('.',$path).':'.$mutation=>[$path,$mutation];}}yield 'foreign component'=>[['promise','component_key'],hash('sha256','foreign-group')];yield 'foreign quote site'=>[['promise','quote','site_id'],'2'];yield 'malformed quote uuid'=>[['promise','quote','quote_id'],'bad-uuid'];yield 'malformed placement uuid'=>[['promise','snapshot','placement_id'],'bad-uuid'];yield 'malformed snapshot digest'=>[['promise','snapshot','snapshot_digest'],'bad-digest'];yield 'wrong result state'=>[['promise','result_state'],'relative_window'];yield 'wrong final event'=>[['promise','final_event','kind'],'gateway_return'];yield 'noncanonical event time'=>[['promise','final_event','occurred_at'],'2026-10-09T10:00:00Z'];}
 public function test_noncanonical_original_json_refuses_even_with_matching_recomputed_digest():void{$row=$this->row();$row['original_json']=' '.$row['original_json'];$row['original_digest']=hash('sha256','cetech-shipment-original-promise-reference-v1:'.$row['original_json']);$this->expectException(\InvalidArgumentException::class);ShipmentPromiseStored::from_row($row,PromiseSiteBinding::bind(1,$row['site_key']));}
 public function test_generic_row_serialization_cannot_disclose_private_saved_packet():void{$row=$this->row();$stored=ShipmentPromiseStored::from_row($row,PromiseSiteBinding::bind(1,$row['site_key']));$this->expectException(\LogicException::class);serialize($stored);}
}
