<?php

declare(strict_types=1);
namespace CetechDeliveryEngine\Application\ServicePromise\Shipment;
use CetechDeliveryEngine\Application\DeliveryQuote\QuoteSavedOrderPlacementEvidenceReader;
use CetechDeliveryEngine\Application\Operation\{OperationCoordinator,OperationReadiness};
use CetechDeliveryEngine\Application\Order\{OrderDeliverySnapshotReader,OrderDeliveryPackageReadResult,OrderDeliveryLineReadResult,PromiseSnapshotCore};
use CetechDeliveryEngine\Domain\ServicePromise\Shipment\ShipmentRecordedPromiseReference;
use CetechDeliveryEngine\Domain\Contracts\{OperationIdentity,RequestContext,OperationOutcome,ContractError};
use CetechDeliveryEngine\Domain\Enum\ShipmentEventSource;
use CetechDeliveryEngine\Domain\Operation\{OperationAttemptResult,OperationConnectionFactory,OperationProfileRegistry};
use CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime;
use CetechDeliveryEngine\Domain\ServicePromise\{PromiseCalendarReference,PromiseJson};
use CetechDeliveryEngine\Domain\ServicePromise\Port\PromiseCalendarVersionLoader;
use CetechDeliveryEngine\Domain\ServicePromise\Persistence\PromiseSiteBinding;
use CetechDeliveryEngine\Domain\ServicePromise\Shipment\{ShipmentPromiseCommand,ShipmentPromiseStored,ShipmentCurrentPromise,ShipmentPaidEvidence,ShipmentPromiseGrant};
use CetechDeliveryEngine\Domain\Shipment\{Shipment,ShipmentItem,ShipmentRepositoryInterface,ShipmentAggregateWriteResult};
use CetechDeliveryEngine\Infrastructure\Persistence\WpdbShipmentPromiseRepository;

/** Native original capture plus separate current predictions. All host authority runs before/after SQL owners. */
final class ShipmentPromiseService implements ShipmentPromisePort {
 private \Closure $authority;private ?\Closure $runtime;
 public function __construct(private PromiseSiteBinding $binding,private OperationConnectionFactory $connections,private QuoteSavedOrderPlacementEvidenceReader $original_evidence,private ShipmentRepositoryInterface $shipments,callable $native_authority,private ?PromiseCalendarVersionLoader $calendars=null,?callable $runtime=null,private ?OperationReadiness $readiness=null){$this->authority=\Closure::fromCallable($native_authority);$this->runtime=null===$runtime?null:\Closure::fromCallable($runtime);}
 /** Null exclusively for an established legacy profile. A required promise never falls back. */
 public function create_aggregate(\WC_Order $order,Shipment $draft,array $items,ShipmentEventSource $source,?int $actor):?ShipmentAggregateWriteResult {
  $reader=new OrderDeliverySnapshotReader();$package=$reader->read_package($order);$envelope=$package->delivery_quote?->envelope;
  if(OrderDeliveryPackageReadResult::ERROR_NONE!==$package->error){throw new \RuntimeException('Shipment original promise unavailable.');}
  if(null===$envelope||!$envelope->is_promise()){return null;}
  if($draft->order_id!==$order->get_id()||true!==($this->authority)($order,'create',$actor)){throw new \RuntimeException('Shipment original promise unavailable.');}
  $before=$this->order_fingerprint($order);$linkage=$this->original_evidence->read_original_promise_linkage($order);if(null===$linkage){throw new \RuntimeException('Shipment original promise unavailable.');}
  // Structural original linkage covers packet+order+group. The exact saved line set covers shipment items.
  ShipmentRecordedPromiseReference::from_recorded($draft->withId(PHP_INT_MAX),$envelope,$linkage);$saved=[];
  foreach($order->get_items('line_item') as $line){if(!$line instanceof \WC_Order_Item_Product){throw new \RuntimeException('Shipment original promise unavailable.');}$read=$reader->read_line($line);if(OrderDeliveryLineReadResult::ERROR_NONE!==$read->error||null===$read->snapshot||null===$read->delivery_quote?->envelope||!$envelope->matches($read->delivery_quote->envelope)){throw new \RuntimeException('Shipment original promise unavailable.');}if($read->snapshot->delivery_group_id===$draft->delivery_group_id){$saved[$line->get_id()]=['quantity'=>(int)$line->get_quantity(),'product_id'=>(int)$line->get_product_id(),'variation_id'=>(int)$line->get_variation_id(),'name'=>(string)$line->get_name()];}}
  $actual=[];foreach($items as $item){if(!$item instanceof ShipmentItem||isset($actual[$item->order_item_id])||$item->order_id!==$draft->order_id){throw new \RuntimeException('Shipment original promise unavailable.');}$actual[$item->order_item_id]=['quantity'=>$item->quantity,'product_id'=>$item->product_id??0,'variation_id'=>$item->variation_id??0,'name'=>$item->product_name_snapshot];}ksort($saved);ksort($actual);if([]===$saved||$saved!==$actual||$before!==$this->order_fingerprint($order)||true!==($this->authority)($order,'create',$actor)){throw new \RuntimeException('Shipment original promise unavailable.');}
  $paid=null;if(null===$actor){$date=$order->get_date_paid();if(!$date instanceof \DateTimeInterface||$date->getTimestamp()<1){throw new \RuntimeException('Shipment native payment unavailable.');}$hpos=class_exists('\\Automattic\\WooCommerce\\Utilities\\OrderUtil')&&\Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled();$paid=new ShipmentPaidEvidence($order->get_id(),RuleTime::from_epoch_microseconds($date->getTimestamp()*1000000),$hpos);}$identity=$this->identity($draft,ShipmentPromiseCommand::CREATE,hash('sha256','original:'.$envelope->to_private_json()),$actor);$command=ShipmentPromiseCommand::create($identity,$this->binding,$draft,$items,$envelope,$linkage,$source,$actor,$paid);$result=$this->attempt($command,null,$order);
  if(!in_array($result->outcome->state,['accepted','not_applicable'],true)||$before!==$this->order_fingerprint($order)||true!==($this->authority)($order,'create',$actor)){throw new \RuntimeException('Shipment original promise outcome unavailable.');}
  $shipment=$this->shipments->findById($result->completion->result['shipment_id']);if(!$shipment instanceof Shipment||$shipment->order_id!==$draft->order_id||$shipment->delivery_group_id!==$draft->delivery_group_id){throw new \RuntimeException('Shipment original promise outcome unavailable.');}
  return new ShipmentAggregateWriteResult($shipment,$result->replayed||'not_applicable'===$result->outcome->state?ShipmentAggregateWriteResult::ALREADY_COMPLETE:ShipmentAggregateWriteResult::CREATED);
 }
 /** Called only by the genuine Woo payment-complete hook; persisted native payment is required too. */
 public function predict_paid_order(\WC_Order $order):void {
  try{$fresh=new \WC_Order($order->get_id());if($fresh->get_id()!==$order->get_id()||true!==($this->authority)($fresh,'payment_confirmed',null)||!method_exists($fresh,'get_date_paid')){return;}$date=$fresh->get_date_paid();if(!$date instanceof \DateTimeInterface||$date->getTimestamp()<1){return;}$paid=RuleTime::from_epoch_microseconds($date->getTimestamp()*1000000);$hpos=class_exists('\\Automattic\\WooCommerce\\Utilities\\OrderUtil')&&\Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled();$evidence=new ShipmentPaidEvidence($fresh->get_id(),$paid,$hpos);
   foreach($this->shipments->findByOrderId($fresh->get_id()) as $shipment){$stored=$this->read_for_order($shipment,$fresh);if(null===$stored||'relative_window'!==$stored->packet()->result_facts()['state']){continue;}$event=$evidence->event_key($shipment->delivery_group_id);if(null!==$stored->current()){continue;} // An already recorded event, or a later staff revision, never receives another payment prediction.
    $calendar_values=[];$runtime=[];try{$runtime=null===$this->runtime?[]:($this->runtime)();$refs=array_map(static fn(array $ref):PromiseCalendarReference=>PromiseCalendarReference::from_array($ref),$stored->packet()->input_facts()['calendar_refs']);if([]!==$refs){if(null===$this->calendars){throw new \RuntimeException('Original calendars unavailable.');}$calendar_values=$this->calendars->load_versions($refs);}}catch(\Throwable){$calendar_values=[];$runtime=[];}
    $prediction=(new PaymentConfirmedPromisePrediction())->calculate($stored->packet(),$paid,$runtime,$calendar_values,$event);if(null!==$this->runtime){try{if(($this->runtime)()!==$runtime){$prediction=(new PaymentConfirmedPromisePrediction())->calculate($stored->packet(),$paid,[],[],$event);}}catch(\Throwable){$prediction=(new PaymentConfirmedPromisePrediction())->calculate($stored->packet(),$paid,[],[],$event);}}$identity=$this->identity($shipment,ShipmentPromiseCommand::UPDATE,$event,null);$command=ShipmentPromiseCommand::update($identity,$this->binding,$shipment,$stored->row()['revision'],$prediction,null,$evidence);if(true===($this->authority)($fresh,'payment_confirmed',null)){$this->attempt($command,null,$fresh);}
   }
  }catch(\Throwable){/* Original relative promise and Woo payment history remain intact. */}
 }
 public function update_current(\WC_Order $order,int $shipment_id,int $expected_revision,ShipmentCurrentPromise $current,int $actor_user_id,string $idempotency_key,bool $reconcile=false):OperationAttemptResult {
  $request=RequestContext::create();try{$shipment=$this->shipments->findById($shipment_id);if(!$shipment instanceof Shipment||$shipment->order_id!==$order->get_id()||'staff_revision'!==$current->private_facts()['source']||true!==($this->authority)($order,'update_current',$actor_user_id)){throw new \RuntimeException();}$identity=$this->identity($shipment,ShipmentPromiseCommand::UPDATE,$idempotency_key,$actor_user_id);$command=ShipmentPromiseCommand::update($identity,$this->binding,$shipment,$expected_revision,$current,$actor_user_id);$result=$this->attempt($command,$request,$order,$reconcile);if(true!==($this->authority)($order,'update_current',$actor_user_id)){return new OperationAttemptResult(OperationOutcome::unconfirmed(new ContractError('outcome_unknown',$request,'reconcile_original_request')));}return $result;}catch(\Throwable){return new OperationAttemptResult(OperationOutcome::rejected(new ContractError('not_authorized',$request,'contact_support')));}
 }
 /** Authorized persisted immutable original/current history, independent of current policy availability. */
 public function read_for_order(Shipment $shipment,\WC_Order $order):?ShipmentPromiseStored {
  $session=null;try{if($shipment->id<1||$shipment->order_id!==$order->get_id()||true!==($this->authority)($order,'read',null)){return null;}$session=$this->connections->open();$this->binding->assert_session($session);($this->readiness??new ShipmentPromiseOperationReadiness())->assert_ready($session);if($session->in_transaction()||!$session->begin()){return null;}$repo=new WpdbShipmentPromiseRepository($session,$this->binding);$stored=$repo->load($shipment->id);if(null===$stored||$stored->row()['order_id']!==$shipment->order_id||$stored->row()['delivery_group_id']!==$shipment->delivery_group_id){return null;}$repo->assert_ack($stored);if(!$session->rollback()||!$session->retire()||true!==($this->authority)($order,'read',null)){return null;}return $stored;}catch(\Throwable){return null;}finally{if(null!==$session&&!$session->is_retired()){if($session->in_transaction()){try{$session->rollback();}catch(\Throwable){}}try{$session->retire();}catch(\Throwable){}}}
 }
 private function attempt(ShipmentPromiseCommand $command,?RequestContext $context,\WC_Order $order,bool $reconcile=false):OperationAttemptResult{$grant=ShipmentPromiseGrant::capture($command,$order,$this->authority,$this->connections,$this->readiness??new ShipmentPromiseOperationReadiness());$profile=ShipmentPromiseOperationProfile::for_command($command,$grant);$coordinator=new OperationCoordinator(new OperationProfileRegistry([$profile]),$this->connections,$this->readiness??new ShipmentPromiseOperationReadiness());return $reconcile?$coordinator->reconcile($command->identity,$command,$context??RequestContext::create()):$coordinator->attempt($command->identity,$command,$context??RequestContext::create());}
 private function identity(Shipment $shipment,string $action,string $key,?int $actor):OperationIdentity{return new OperationIdentity($this->binding->native_site_id(),'native-shipment-promise',null===$actor?'native-system':'staff:'.$actor,$action,1,ShipmentPromiseCommand::target_key($shipment),$key);}
 private function order_fingerprint(\WC_Order $order):string{$facts=[];foreach([\CetechDeliveryEngine\Application\Order\OrderDeliverySnapshot::META_ORDER_QUOTE_SNAPSHOT,\CetechDeliveryEngine\Application\Order\OrderDeliverySnapshot::META_ORDER_SNAPSHOT_VERSION,\CetechDeliveryEngine\Application\Order\DeliveryQuoteSnapshotEnvelope::META_FORMAT,\CetechDeliveryEngine\Application\Order\QuoteNativeOrderFacts::META_REFERENCE] as $key){$facts[$key]=$order->get_meta($key,true);}return hash('sha256',PromiseJson::encode($facts,65536));}
}
