<?php

declare(strict_types=1);
namespace CetechDeliveryEngine\Tests\Unit\DeliveryQuote;
use CetechDeliveryEngine\Application\DeliveryQuote\{QuoteNativeCaptureSource,QuoteNativeGroupRequest,QuoteNativeReceiptCapture,QuoteNativeState};
use CetechDeliveryEngine\Domain\DeliveryQuote\{QuoteMoney,QuoteOwner};
use CetechDeliveryEngine\Tests\Support\DeliveryQuote\QuoteFixtures;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
final class NativeReceiptTest extends TestCase {
 private static function source(array $edits=[]):NativeReceiptFixtureSource{return new NativeReceiptFixtureSource(array_replace(self::facts(),$edits));}
 private static function facts():array {
  $package=['group_id'=>'in_store|delivery|20','rate_id'=>'delivery_engine_selected_offer:1:abc','method_id'=>'delivery_engine_selected_offer','instance_id'=>1,'tax_status'=>'taxable','label'=>'Delivery','cost'=>'0.1','taxes'=>[['rate_id'=>1,'amount'=>'0.005'],['rate_id'=>2,'amount'=>'0.005']],'fresh_taxes'=>[['rate_id'=>1,'amount'=>'0.005'],['rate_id'=>2,'amount'=>'0.005']],'rounded_tax'=>'0.02','display_total'=>'0.12','members'=>[['line_key'=>'line_one','product_id'=>10,'variation_id'=>null,'quantity'=>'2']]];
  $source=['option_rows'=>[],'tax_rows'=>[],'tax_class_rows'=>[],'tax_location_rows'=>[],'method_rows'=>[],'session_row'=>[],'customer_rows'=>[],'selectors'=>['option_names'=>['woocommerce_currency'],'tax_class'=>'','method_instance_ids'=>[1],'session_key'=>'fixture-session','customer_id'=>0,'site_id'=>1,'table_prefix'=>'wp_']];
  return ['currency'=>'GHS','display_precision'=>2,'internal_precision'=>4,'exempt'=>false,'tax_class'=>'','location_digest'=>QuoteFixtures::digest('tax_location'),'destination_digest'=>QuoteFixtures::digest('destination'),'key_epoch'=>'fixture_key_1','rounding'=>'per_line','tax_enabled'=>true,'coupons'=>0,'unsupported_effects'=>false,'cart_shipping_total'=>'0.1','cart_shipping_tax'=>'0.02','packages'=>[$package],'source_facts'=>$source];
 }
 private static function requests(string $amount='0.1000',string $currency='GHS'):array{return [new QuoteNativeGroupRequest(QuoteFixtures::digest('component'),'in_store|delivery|20',QuoteMoney::from_array(['amount'=>$amount,'currency'=>$currency,'precision'=>4]))];}
 public function test_native_raw_rate_tax_and_rounded_display_charge_are_separate():void{$source=self::source();$receipt=(new QuoteNativeReceiptCapture($source))->capture(QuoteFixtures::owner(),self::requests());$group=$receipt->group(QuoteFixtures::digest('component'));self::assertSame('0.1000',$group->final_money()->amount());self::assertSame('0.0100',$group->tax_money()->amount());self::assertSame('0.1100',$group->total_money()->amount());self::assertSame('0.02',$group->native_tax_receipt()['rounded_tax']['amount']);self::assertSame('0.12',$group->native_money_receipt()['display_total']['amount']);self::assertSame('none',$group->promotion()['state']);self::assertSame('0.0000',$group->promotion()['amount']['amount']);self::assertTrue($receipt->unchanged());}
 public function test_subtotal_native_cart_uses_unrounded_rates_before_native_display_rounding():void{$facts=self::facts();$facts['rounding']='subtotal';$facts['cart_shipping_tax']='0.01';$facts['packages'][0]['rounded_tax']='0.01';$facts['packages'][0]['display_total']='0.11';$receipt=(new QuoteNativeReceiptCapture(new NativeReceiptFixtureSource($facts)))->capture(QuoteFixtures::owner(),self::requests());$group=$receipt->group(QuoteFixtures::digest('component'));self::assertSame('subtotal',$group->native_tax_receipt()['rounding']);self::assertSame('0.01',$group->native_tax_receipt()['rounded_tax']['amount']);self::assertSame('0.11',$group->native_money_receipt()['display_total']['amount']);}
 public function test_zero_charge_is_recorded_not_absent_or_unknown():void{$facts=self::facts();$facts['cart_shipping_total']='0';$facts['cart_shipping_tax']='0';$facts['packages'][0]=array_replace($facts['packages'][0],['cost'=>'0','taxes'=>[],'fresh_taxes'=>[],'rounded_tax'=>'0.00','display_total'=>'0.00']);$receipt=(new QuoteNativeReceiptCapture(new NativeReceiptFixtureSource($facts)))->capture(QuoteFixtures::owner(),self::requests('0.0000'));$group=$receipt->group(QuoteFixtures::digest('component'));self::assertTrue($group->final_money()->zero());self::assertSame('0.00',$group->native_money_receipt()['display_total']['amount']);self::assertSame([],$group->native_tax_receipt()['rates']);}
 public function test_bound_context_preserves_source_members_currency_and_destination():void{$receipt=(new QuoteNativeReceiptCapture(self::source()))->capture(QuoteFixtures::owner(),self::requests());$before=QuoteFixtures::context();$after=$receipt->bind_context($before);$facts=$before->private_facts();$facts['tax']=$receipt->tax_facts();self::assertSame($facts,$after->private_facts());self::assertNotSame($before->digest(),$after->digest());}
 #[DataProvider('context_changes')]
 public function test_forged_or_changed_native_context_is_not_bound(string $field):void{$receipt=(new QuoteNativeReceiptCapture(self::source()))->capture(QuoteFixtures::owner(),self::requests());$facts=QuoteFixtures::context()->private_facts();switch($field){case 'product':$facts['lines'][0]['product_id']=11;break;case 'quantity':$facts['lines'][0]['quantity']='3';break;case 'currency':$facts['currency']['charged']='USD';break;case 'destination':$facts['destination']['digest']=QuoteFixtures::digest('other');break;case 'key_epoch':$facts['destination']['key_epoch']='other';break;} $this->expectException(\InvalidArgumentException::class);$receipt->bind_context(\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteContext::from_array($facts));}
 public static function context_changes():array{return array_map(static fn(string $field):array=>[$field],['product','quantity','currency','destination','key_epoch']);}
 #[DataProvider('unsupported_inputs')]
 public function test_unsupported_or_mutated_native_effect_refuses(string $field):void{$facts=self::facts();switch($field){case 'coupon':$facts['coupons']=1;break;case 'foreign_effect':$facts['unsupported_effects']=true;break;case 'amount':$facts['packages'][0]['cost']='0.11';break;case 'fresh_tax':$facts['packages'][0]['fresh_taxes'][0]['amount']='0.006';break;case 'exempt_tax':$facts['exempt']=true;break;case 'method_none_tax':$facts['packages'][0]['tax_status']='none';break;case 'aggregate_charge':$facts['cart_shipping_total']='0.11';break;case 'aggregate_tax':$facts['cart_shipping_tax']='0.01';break;case 'missing_group':$facts['packages'][0]['group_id']='other';break;} $this->expectException(\RuntimeException::class);(new QuoteNativeReceiptCapture(new NativeReceiptFixtureSource($facts)))->capture(QuoteFixtures::owner(),self::requests());}
 public static function unsupported_inputs():array{return array_map(static fn(string $field):array=>[$field],['coupon','foreign_effect','amount','fresh_tax','exempt_tax','method_none_tax','aggregate_charge','aggregate_tax','missing_group']);}
 public function test_wrong_owner_is_denied_before_native_read():void{$source=self::source();$owner=QuoteFixtures::owner()->facts();$owner['principal_hash']=QuoteFixtures::digest('wrong');try{(new QuoteNativeReceiptCapture($source))->capture(QuoteOwner::from_array($owner),self::requests());self::fail();}catch(\RuntimeException){self::assertSame(0,$source->reads);}}
 public function test_owner_revocation_after_native_read_prevents_receipt():void{$source=self::source();$source->revoke_after_read=true;$this->expectException(\RuntimeException::class);(new QuoteNativeReceiptCapture($source))->capture(QuoteFixtures::owner(),self::requests());}
 public function test_live_mutation_after_capture_refuses_pure_fence():void{$source=self::source();$receipt=(new QuoteNativeReceiptCapture($source))->capture(QuoteFixtures::owner(),self::requests());$source->same=false;self::assertFalse($receipt->unchanged());self::assertSame(1,$source->reads);}
 #[DataProvider('bad_codec')]
 public function test_unknown_nested_types_payloads_and_bounds_refuse(string $field):void{$facts=self::facts();switch($field){case 'top_private':$facts['raw_address']='PRIVATE';break;case 'package_private':$facts['packages'][0]['supplier']='PRIVATE';break;case 'tax_decimal':$facts['packages'][0]['taxes'][0]['amount']='0.5junk';break;case 'bool_money':$facts['packages'][0]['cost']=false;break;case 'negative':$facts['packages'][0]['cost']='-1';break;case 'exponent':$facts['packages'][0]['cost']='1e-2';break;case 'unknown_sql_field':$facts['source_facts']['option_rows']=[['password'=>'PRIVATE']];break;case 'many_groups':$facts['packages']=array_fill(0,201,$facts['packages'][0]);break;case 'zero_quantity':$facts['packages'][0]['members'][0]['quantity']='0';break;} $this->expectException(\InvalidArgumentException::class);QuoteNativeState::from_array($facts);}
 public static function bad_codec():array{return array_map(static fn(string $field):array=>[$field],['top_private','package_private','tax_decimal','bool_money','negative','exponent','unknown_sql_field','many_groups','zero_quantity']);}
 public function test_private_carriers_reject_generic_json_and_php_serialization():void{$source=self::source();$receipt=(new QuoteNativeReceiptCapture($source))->capture(QuoteFixtures::owner(),self::requests());foreach([$receipt,$receipt->group(QuoteFixtures::digest('component')),QuoteNativeState::from_array(self::facts()),self::requests()[0]] as $carrier){foreach(['json','php'] as $format){try{if($format==='json'){json_encode($carrier,JSON_THROW_ON_ERROR);}else{serialize($carrier);}self::fail();}catch(\LogicException){self::assertTrue(true);}}}}
 public function test_current_owned_native_guard_reads_only_fixed_tables_and_current_locks():void {
  $receipt=(new QuoteNativeReceiptCapture(self::source()))->capture(QuoteFixtures::owner(),self::requests());$context=$receipt->bind_context(QuoteFixtures::context());$session=$this->native_session();$queries=[];
  $session->method('get_results')->willReturnCallback(static function(string $sql)use(&$queries):array{$queries[]=$sql;return [];});
  self::assertTrue($receipt->guard()->verify($session,QuoteFixtures::owner(),$context));self::assertCount(7,$queries);foreach($queries as $sql){self::assertStringEndsWith(' FOR UPDATE',$sql);self::assertStringNotContainsString('UPDATE `',$sql);}
 }
 public function test_current_physical_change_and_postread_revocation_refuse_disclosure():void {
  $source=self::source();$receipt=(new QuoteNativeReceiptCapture($source))->capture(QuoteFixtures::owner(),self::requests());$context=$receipt->bind_context(QuoteFixtures::context());$session=$this->native_session();$session->method('get_results')->willReturnCallback(static function(string $sql)use($source):array{$source->same=false;return [];});self::assertFalse($receipt->guard()->verify($session,QuoteFixtures::owner(),$context));
  $receipt=(new QuoteNativeReceiptCapture(self::source()))->capture(QuoteFixtures::owner(),self::requests());$session=$this->native_session();$session->method('get_results')->willReturnCallback(static function(string $sql):array{return str_contains($sql,'`wp_options`')?[['option_id'=>'1','option_name'=>'woocommerce_currency','option_value'=>'USD','autoload'=>'off']]:[];});self::assertFalse($receipt->guard()->verify($session,QuoteFixtures::owner(),$context));
 }
 public function test_native_pointer_and_rate_cache_changes_preserve_material_but_are_still_exact_sql_fences():void {
  $before=self::facts();$before['source_facts']['session_row']=[['session_id'=>'1','session_key'=>'fixture-session','session_value'=>serialize(['cart'=>'original_cart','chosen_shipping_methods'=>'original_rate']),'session_expiry'=>'1791400000']];$after=$before;$after['source_facts']['session_row'][0]['session_value']=serialize(['cart'=>'original_cart','chosen_shipping_methods'=>'original_rate','order_awaiting_payment'=>'701','cetech_de_quote_payment_continuation'=>serialize(['order_id'=>701]),'shipping_for_package_0'=>'original_rate_with_inert_quote_reference']);
  $first=(new QuoteNativeReceiptCapture(new NativeReceiptFixtureSource($before)))->capture(QuoteFixtures::owner(),self::requests());$fresh=(new QuoteNativeReceiptCapture(new NativeReceiptFixtureSource($after)))->capture(QuoteFixtures::owner(),self::requests());self::assertSame($first->tax_facts(),$fresh->tax_facts());$context=$first->bind_context(QuoteFixtures::context());self::assertSame($context->digest(),$fresh->bind_context(QuoteFixtures::context())->digest());self::assertNotSame($first->source_facts(),$fresh->source_facts());
  $session=$this->native_session();$session->method('get_results')->willReturnCallback(static fn(string $sql):array=>str_contains($sql,'`wp_woocommerce_sessions`')?$after['source_facts']['session_row']:[]);self::assertFalse($first->guard()->verify($session,QuoteFixtures::owner(),$context));self::assertTrue($fresh->guard()->verify($session,QuoteFixtures::owner(),$context));
 }
 #[DataProvider('material_native_sources')]
 public function test_projection_preserves_every_other_native_physical_source_and_owner_selector(string $source):void {
  $before=self::facts();$changed=$before;if('selectors'===$source){$changed['source_facts']['selectors']['session_key']='foreign-native-session';}else{$row=[];foreach(\CetechDeliveryEngine\Application\DeliveryQuote\QuoteNativeReceiptGuard::COLUMNS[$source] as $column){$row[$column]='1';}$changed['source_facts'][$source]=[$row];}self::assertNotSame(QuoteNativeReceiptCapture::tax_context_digest(QuoteNativeState::from_array($before)),QuoteNativeReceiptCapture::tax_context_digest(QuoteNativeState::from_array($changed)));
 }
 public static function material_native_sources():array{return array_map(static fn(string $source):array=>[$source],['option_rows','tax_rows','tax_class_rows','tax_location_rows','method_rows','customer_rows','selectors']);}
 public function test_private_tax_source_codec_round_trips_and_reuses_exact_digest_for_saved_current_scope():void {
  $facts=self::facts();$facts['source_facts']['tax_rows']=[['tax_rate_id'=>'1','tax_rate_country'=>'GH','tax_rate_state'=>'','tax_rate'=>'5.0000','tax_rate_name'=>'Original tax label','tax_rate_priority'=>'1','tax_rate_compound'=>'0','tax_rate_shipping'=>'1','tax_rate_order'=>'1','tax_rate_class'=>'']];$native=(new QuoteNativeReceiptCapture(new NativeReceiptFixtureSource($facts)))->capture(QuoteFixtures::owner(),self::requests());$original=$native->tax_source();$context=$native->bind_context(QuoteFixtures::context());$roundtrip=\CetechDeliveryEngine\Application\DeliveryQuote\QuoteNativeTaxSource::from_private_json($original->to_private_json());self::assertSame($original->private_facts(),$roundtrip->private_facts());self::assertTrue($roundtrip->matches_context($context));self::assertSame(QuoteNativeReceiptCapture::tax_context_digest(QuoteNativeState::from_array($facts)),$original->digest());self::assertArrayNotHasKey('session_row',$original->private_facts()['source']);
  $effective=$original->private_facts();unset($effective['format_version'],$effective['digest_version'],$effective['source']);$physical=$facts['source_facts'];$physical['session_row']=[['session_id'=>'1','session_key'=>'fixture-session','session_value'=>'inert-native-order-pointer','session_expiry'=>'1791400000']];self::assertTrue($original->with_current($physical,$effective)->matches_context($context));$physical['tax_rows'][0]['tax_rate_name']='Changed definition with identical tax amounts';self::assertFalse($original->with_current($physical,$effective)->matches_context($context));$physical['selectors']['session_key']='foreign-original-scope';$this->expectException(\InvalidArgumentException::class);$original->with_current($physical,$effective);
 }
 #[DataProvider('bad_tax_projection')]
 public function test_private_tax_source_refuses_unknown_versions_unbounded_or_extra_private_data(string $change):void {
  $facts=\CetechDeliveryEngine\Application\DeliveryQuote\QuoteNativeTaxSource::from_native_state(QuoteNativeState::from_array(self::facts()))->private_facts();switch($change){case 'format':$facts['format_version']=2;break;case 'digest':$facts['digest_version']=1;break;case 'session':$facts['source']['session_row']=[];break;case 'unknown':$facts['supplier_contact']='PRIVATE';break;case 'floating':$facts['precision']=2.0;break;case 'scope':$facts['source']['selectors']['option_names']=['arbitrary_shopper_setting'];break;case 'large':$facts['source']['customer_rows']=[['umeta_id'=>'1','user_id'=>'0','meta_key'=>'session_tokens','meta_value'=>str_repeat('x',65537)]];break;}$this->expectException(\InvalidArgumentException::class);\CetechDeliveryEngine\Application\DeliveryQuote\QuoteNativeTaxSource::from_private_facts($facts);
 }
 public static function bad_tax_projection():array{return array_map(static fn(string $case):array=>[$case],['format','digest','session','unknown','floating','scope','large']);}
 public function test_private_tax_source_requires_explicit_private_serialization():void {$source=\CetechDeliveryEngine\Application\DeliveryQuote\QuoteNativeTaxSource::from_native_state(QuoteNativeState::from_array(self::facts()));foreach([static fn()=>json_encode($source,JSON_THROW_ON_ERROR),static fn()=>serialize($source)] as $export){try{$export();self::fail('Taxsource was disclosed.');}catch(\LogicException){self::assertTrue(true);}}}
 public function test_wrong_owner_or_site_refuses_before_current_private_reads():void {
  $receipt=(new QuoteNativeReceiptCapture(self::source()))->capture(QuoteFixtures::owner(),self::requests());$context=$receipt->bind_context(QuoteFixtures::context());$session=$this->native_session();$session->expects(self::never())->method('get_results');$facts=QuoteFixtures::owner()->facts();$facts['principal_hash']=QuoteFixtures::digest('foreign');self::assertFalse($receipt->guard()->verify($session,QuoteOwner::from_array($facts),$context));
  $foreign=$this->createMock(\CetechDeliveryEngine\Domain\Operation\OperationSession::class);$foreign->method('site_id')->willReturn(2);$foreign->expects(self::never())->method('get_results');self::assertFalse($receipt->guard()->verify($foreign,QuoteFixtures::owner(),$context));
 }
 private function native_session():\CetechDeliveryEngine\Domain\Operation\OperationSession {
  $session=$this->createMock(\CetechDeliveryEngine\Domain\Operation\OperationSession::class);$session->method('site_id')->willReturn(1);$session->method('table_prefix')->willReturn('wp_');$session->method('prepare')->willReturnCallback(static function(string $sql,mixed ...$args):string{$value=$args[0];if(is_array($value)){$value=$value[0];}return "'".str_replace("'","''",(string)$value)."'";});$session->expects(self::never())->method('query');return $session;
 }

 public function test_state_detaches_reference_mutations():void{$facts=self::facts();$label='Delivery';$facts['packages'][0]['label']=&$label;$state=QuoteNativeState::from_array($facts);$label='PRIVATE';self::assertSame('Delivery',$state->facts()['packages'][0]['label']);}
}
/** Synthetic native attestation only. It does not qualify actual Woo money. */
final class NativeReceiptFixtureSource implements QuoteNativeCaptureSource {
 public int $reads=0;public bool $same=true;public bool $revoke_after_read=false;
 public function __construct(private array $facts){}
 public function current_owner():QuoteOwner{$facts=QuoteFixtures::owner()->facts();if($this->revoke_after_read&&$this->reads>0){$facts['principal_hash']=QuoteFixtures::digest('revoked');}return QuoteOwner::from_array($facts);}
 public function capture():QuoteNativeState{++$this->reads;return QuoteNativeState::from_array($this->facts);}
 public function unchanged():bool{return $this->same;}
}
