<?php

declare(strict_types=1);
namespace CetechDeliveryEngine\Tests\Unit\DeliveryQuote;
use CetechDeliveryEngine\Application\DeliveryQuote\{QuoteOperationProfile,QuoteRetentionCheckpoint,QuoteRetentionControl,QuoteRetentionProfile,QuoteRetentionReferenceInspector,QuoteRetentionRequest,QuoteRetentionService};
use CetechDeliveryEngine\Application\Operation\{OperationReadiness,OperationStorageException};
use CetechDeliveryEngine\Core\Versioning\{MigrationStatus,SchemaVersion};
use CetechDeliveryEngine\Domain\Contracts\{OperationIdentity,RequestContext};
use CetechDeliveryEngine\Domain\DeliveryQuote\{QuoteBudgetSlot,QuoteOwner,QuoteStoredRow,QuoteTime};
use CetechDeliveryEngine\Domain\Operation\{OperationCommitResult,OperationCompletion,OperationConnectionFactory,OperationMaterialEvent,OperationProfileRegistry,OperationSession};
use CetechDeliveryEngine\Infrastructure\Persistence\{DeliveryQuoteReadiness,DeliveryQuoteRepository,DeliveryQuoteSchema,OperationStoreSchema,RuleLifecycleSchema};
use CetechDeliveryEngine\Tests\Support\DeliveryQuote\{QuoteFixtures,QuoteStorageFixtures};
use PHPUnit\Framework\TestCase;
require_once dirname(__DIR__,2).'/Support/DeliveryQuote/QuoteStorageFixtures.php';
/** Owned SQLite protocol fixture; native missing-key concurrency proofs remain separate. */
final class RetentionTest extends TestCase {
 private RetentionUnitFactory $factory;private RetentionUnitReferences $refs;private RetentionUnitControl $control;private bool $authorized=true;
 protected function setUp():void { $this->factory=new RetentionUnitFactory();$this->refs=new RetentionUnitReferences();$this->control=new RetentionUnitControl(); }
 private function service(?callable $clock=null):QuoteRetentionService { return new QuoteRetentionService($this->factory,QuoteOperationProfile::registry(),fn(int $site):bool=>$this->authorized&&$site===1,$this->refs,$this->control,new class implements OperationReadiness { public function assert_ready(OperationSession $session):void {} },monotonic_clock:$clock); }
 private function run_retention():array { $service=$this->service();$start=$service->start(1,RequestContext::create());self::assertSame('accepted',$start->attempt->outcome->state);$batch=$service->batch($start->checkpoint,RequestContext::create());return [$start,$batch]; }
 public function test_exact_boundary_strips_only_body_and_replay_keeps_checkpoint_and_tombstones():void {
  $quote=$this->factory->seed();$before=$quote->row();[$start,$batch]=$this->run_retention();self::assertSame('accepted',$batch->attempt->outcome->state);self::assertSame(1,$batch->checkpoint->facts()['stripped']);$after=$this->factory->quote();self::assertNull($after['private_body_json']);self::assertSame($before['header_json'],$after['header_json']);self::assertSame($before['body_digest'],$after['body_digest']);self::assertSame(2,(int)$after['revision']);$events=$this->factory->count('operation_changes');$replay=$this->service()->attempt(QuoteRetentionRequest::from_private_array($batch->request->to_private_array()),RequestContext::create());self::assertTrue($replay->attempt->replayed);self::assertSame($batch->checkpoint->facts(),$replay->checkpoint->facts());self::assertSame($events,$this->factory->count('operation_changes'));self::assertSame(1,$this->factory->count('delivery_quotes'));
 }
 public function test_one_microsecond_before_boundary_retains():void { $this->factory->now=QuoteFixtures::time()->plus_seconds(2100)->epoch_microseconds()-1;$this->factory->seed();[, $batch]=$this->run_retention();self::assertSame(0,$batch->checkpoint->facts()['stripped']);self::assertNotNull($this->factory->quote()['private_body_json']); }
 public function test_unknown_history_owner_denial_and_binding_each_retain():void { foreach(['unknown','owner_denied','binding'] as $condition) { $this->setUp();$quote=$this->factory->seed();if($condition==='unknown') { $this->refs->status='unknown'; }if($condition==='owner_denied') { $this->refs->owner_allowed=false; }if($condition==='binding') { $this->factory->db->exec("INSERT INTO storage_delivery_engine_delivery_quote_bindings(id,site_id,quote_uuid) VALUES(1,1,'".$quote->header()->id()->value()."')"); }$before=$this->factory->quote();[, $batch]=$this->run_retention();self::assertSame(0,$batch->checkpoint->facts()['stripped']);self::assertSame($before,$this->factory->quote()); } }
 public function test_missing_issue_pending_accept_and_unknown_issue_evidence_retain():void { foreach(['missing','pending','malformed'] as $condition) { $this->setUp();$quote=$this->factory->seed();if($condition==='missing') { $this->factory->db->exec("DELETE FROM storage_delivery_engine_operation_changes;DELETE FROM storage_delivery_engine_operation_records"); }elseif($condition==='pending') { $this->factory->pending($quote,'accept'); }else { $this->factory->db->exec("UPDATE storage_delivery_engine_operation_records SET completion_json='{}'"); }$before=$this->factory->quote();[, $batch]=$this->run_retention();self::assertSame(0,$batch->checkpoint->facts()['stripped']);self::assertSame($before,$this->factory->quote()); } }
 public function test_no_effect_producer_with_an_orphan_event_retains_body():void { $quote=$this->factory->seed();$this->factory->pending($quote,'accept');$rid=(int)$this->factory->db->query("SELECT id FROM storage_delivery_engine_operation_records WHERE operation='delivery_quote.accept'")->fetchColumn();$this->factory->insert('operation_changes',['site_id'=>1,'operation_id'=>$rid,'event_format'=>1,'event_json'=>'{}','created_at'=>QuoteFixtures::time()->sql()]);$before=$this->factory->quote();[, $batch]=$this->run_retention();self::assertSame(0,$batch->checkpoint->facts()['stripped']);self::assertSame($before,$this->factory->quote()); }
 public function test_checkpoint_refusal_rolls_back_strip_and_cursor_and_original_retry_applies_once():void { $this->factory->seed();$service=$this->service();$start=$service->start(1,RequestContext::create());$request=QuoteRetentionRequest::next($start->checkpoint);$this->factory->refuse_completion=true;$before=$this->factory->quote();$failed=$service->attempt($request,RequestContext::create());self::assertSame('rejected',$failed->attempt->outcome->state);self::assertNull($failed->checkpoint);self::assertSame($before,$this->factory->quote());$retry=$service->attempt($request,RequestContext::create());self::assertSame('accepted',$retry->attempt->outcome->state);self::assertSame(1,$retry->checkpoint->facts()['stripped']); }
 public function test_lost_acknowledgement_reconcile_recovers_same_committed_checkpoint_without_second_strip():void { $this->factory->seed();$service=$this->service();$start=$service->start(1,RequestContext::create());$request=QuoteRetentionRequest::next($start->checkpoint);$this->factory->lost_ack=true;$uncertain=$service->attempt($request,RequestContext::create());self::assertSame('unconfirmed',$uncertain->attempt->outcome->state);self::assertNull($uncertain->checkpoint);self::assertNull($this->factory->quote()['private_body_json']);$events=$this->factory->count('operation_changes');$resolved=$service->reconcile(QuoteRetentionRequest::from_private_array($request->to_private_array()),RequestContext::create());self::assertSame('accepted',$resolved->attempt->outcome->state);self::assertSame(1,$resolved->checkpoint->facts()['stripped']);self::assertSame($events,$this->factory->count('operation_changes')); }
 public function test_fixed_ceiling_hundred_inspections_and_new_row_exclusion():void { for($i=0;$i<101;$i++) { $this->factory->seed(); }$service=$this->service();$start=$service->start(1,RequestContext::create());$late=$this->factory->seed();$page=$service->batch($start->checkpoint,RequestContext::create());self::assertSame(100,$page->checkpoint->facts()['inspected']);self::assertSame(100,$page->checkpoint->facts()['quote_cursor']);self::assertSame(101,$page->checkpoint->facts()['quote_ceiling']);$page2=$service->batch($page->checkpoint,RequestContext::create());self::assertSame(101,$page2->checkpoint->facts()['inspected']);self::assertNotNull($this->factory->quote($late->id())['private_body_json']); }
 public function test_soft_stop_reports_incomplete_without_advancing_uninspected_candidates():void { $this->factory->seed();$calls=0;$service=$this->service(static function()use(&$calls):float { return ++$calls<3?0.0:2.0; });$start=$service->start(1,RequestContext::create());$batch=$service->batch($start->checkpoint,RequestContext::create());self::assertSame('accepted',$batch->attempt->outcome->state);self::assertTrue($batch->checkpoint->facts()['soft_stopped']);self::assertSame(0,$batch->checkpoint->facts()['quote_cursor']);self::assertSame(0,$batch->checkpoint->facts()['inspected']);self::assertFalse($batch->checkpoint->complete()); }
 public function test_changed_generation_is_retained_without_inventing_a_new_target():void { $quote=$this->factory->seed();$this->factory->read_hook=function(string $sql)use($quote) { if(str_contains($sql,$quote->row()['issue_namespace_hash'])&&str_contains($sql,'FOR UPDATE')) { $this->factory->read_hook=null;$this->factory->db->exec("UPDATE storage_delivery_engine_delivery_quotes SET state='invalidated',revision=2,transition_at='2026-10-07 05:00:02.000000' WHERE id=1"); } };[, $batch]=$this->run_retention();self::assertSame(1,$batch->checkpoint->facts()['changed']);self::assertNotNull($this->factory->quote()['private_body_json']); }
 public function test_counter_profile_deletes_only_old_exact_minute_rows_and_never_admission_receipts():void { $this->factory->now=QuoteFixtures::time()->plus_seconds(86500)->epoch_microseconds();$this->factory->seed();$slot=QuoteStorageFixtures::budget(admission:false);$this->factory->insert('delivery_quote_budget_windows',$slot->row());$service=$this->service();$start=$service->start(1,RequestContext::create());$quotes=$service->batch($start->checkpoint,RequestContext::create());$counters=$service->batch($quotes->checkpoint,RequestContext::create());self::assertSame(1,$counters->checkpoint->facts()['counters_deleted']);self::assertSame(1,$this->factory->count('delivery_quote_budget_windows'));self::assertSame('admission',$this->factory->db->query('SELECT slot_kind FROM storage_delivery_engine_delivery_quote_budget_windows')->fetchColumn()); }
 public function test_unauthorized_initial_and_replay_do_not_load_private_storage():void { $this->authorized=false;$service=$this->service();$result=$service->start(1,RequestContext::create());self::assertSame('not_authorized',$result->attempt->outcome->error->code);self::assertSame(0,$this->factory->opens);$this->authorized=true;$start=$service->start(1,RequestContext::create());$opens=$this->factory->opens;$this->authorized=false;$denied=$service->reconcile($start->request,RequestContext::create());self::assertNull($denied->checkpoint);self::assertSame($opens,$this->factory->opens); }
 public function test_accepted_quote_and_historical_invalidated_acceptance_never_strip():void { foreach(['accepted','invalidated'] as $state) { $this->setUp();$this->factory->seed();$at=QuoteFixtures::time()->plus_seconds(1)->sql();$this->factory->db->exec("UPDATE storage_delivery_engine_delivery_quotes SET state='".$state."',revision=".($state==='accepted'?2:3).",accepted_at='".$at."',transition_at='".$at."' WHERE id=1");$before=$this->factory->quote();[, $batch]=$this->run_retention();self::assertSame(0,$batch->checkpoint->facts()['stripped']);self::assertSame($before,$this->factory->quote()); } }
 public function test_owner_revoked_inside_reference_loader_preserves_body_and_advances_only_protected_count():void { $this->factory->seed();$this->refs->on_inspect=function():void { $this->refs->owner_allowed=false; };$before=$this->factory->quote();[, $batch]=$this->run_retention();self::assertSame(1,$batch->checkpoint->facts()['protected']);self::assertSame(0,$batch->checkpoint->facts()['stripped']);self::assertSame($before,$this->factory->quote()); }
 public function test_site_authority_revoked_inside_reference_loader_rolls_back_body_and_checkpoint():void { $this->factory->seed();$service=$this->service();$start=$service->start(1,RequestContext::create());$this->refs->on_inspect=function():void { $this->authorized=false; };$before=$this->factory->quote();$batch=$service->batch($start->checkpoint,RequestContext::create());self::assertSame('not_authorized',$batch->attempt->outcome->error->code);self::assertNull($batch->checkpoint);self::assertSame($before,$this->factory->quote()); }
 public function test_default_unknown_reference_contract_has_no_implicit_history_absence_authority():void { $this->factory->seed();$service=new QuoteRetentionService($this->factory,QuoteOperationProfile::registry(),fn()=>true,null,$this->control,new class implements OperationReadiness { public function assert_ready(OperationSession $session):void {} });$start=$service->start(1,RequestContext::create());$batch=$service->batch($start->checkpoint,RequestContext::create());self::assertSame(1,$batch->checkpoint->facts()['protected']);self::assertNotNull($this->factory->quote()['private_body_json']); }
 public function test_oversized_malformed_quote_is_counted_and_retained_without_loading_body():void { $this->factory->seed();$this->factory->db->exec("UPDATE storage_delivery_engine_delivery_quotes SET private_body_json='".str_repeat('PRIVATE',10000)."' WHERE id=1");[, $batch]=$this->run_retention();self::assertSame(1,$batch->checkpoint->facts()['invalid']);self::assertSame(0,$batch->checkpoint->facts()['stripped']);self::assertSame(70000,strlen($this->factory->quote()['private_body_json'])); }
 public function test_checkpoint_phase_and_counters_cannot_claim_uninspected_work():void { $this->factory->seed();[$start]=$this->run_retention();$data=$start->checkpoint->facts();$data['phase']='counters';try { QuoteRetentionCheckpoint::from_completion($data,$start->checkpoint->namespace_hash());self::fail('Unexhausted quote ceiling accepted.'); }catch(\InvalidArgumentException) { self::assertTrue(true); }$data=$start->checkpoint->facts();$data['stripped']=1;$this->expectException(\InvalidArgumentException::class);QuoteRetentionCheckpoint::from_completion($data,$start->checkpoint->namespace_hash()); }
 public function test_revocation_during_connection_retirement_hides_committed_private_checkpoint():void { $this->factory->seed();$service=$this->service();$start=$service->start(1,RequestContext::create());$this->factory->retire_hook=function():void { $this->authorized=false; };$result=$service->batch($start->checkpoint,RequestContext::create());self::assertSame('unconfirmed',$result->attempt->outcome->state);self::assertNull($result->checkpoint);self::assertNull($result->attempt->completion);self::assertNull($this->factory->quote()['private_body_json']); }
 public function test_private_carriers_reject_generic_serialization_and_unknown_request_keys():void { $this->factory->seed();[$start,$batch]=$this->run_retention();foreach([$start->checkpoint,$batch->request] as $value) { try { json_encode($value,JSON_THROW_ON_ERROR);self::fail('Private retention facts escaped.'); }catch(\LogicException) { self::assertTrue(true); }try { serialize($value);self::fail('Private retention facts escaped.'); }catch(\LogicException) { self::assertTrue(true); } }$data=$batch->request->to_private_array();$data['address']='PRIVATE';$this->expectException(\InvalidArgumentException::class);QuoteRetentionRequest::from_private_array($data); }
}
final class RetentionUnitReferences implements QuoteRetentionReferenceInspector { public string $status='absent';public ?\Closure $on_inspect=null;public bool $owner_allowed=true;public function policy_digest():string { return hash('sha256','fixture-exact-reference-v1'); }public function transactional_tables(OperationSession $session):array { return []; }public function authorize_owner(QuoteOwner $owner):bool { return $this->owner_allowed&&$owner->site_id()===1; }public function inspect(OperationSession $session,QuoteStoredRow $quote):string { if(null!==$this->on_inspect) { ($this->on_inspect)(); }return $this->status; } }
final class RetentionUnitControl implements QuoteRetentionControl { public bool $enabled=true;public function transactional_tables(OperationSession $session):array { return []; }public function assert_enabled(OperationSession $session):void { if(!$this->enabled) { throw new OperationStorageException(); } } }
final class RetentionUnitFactory implements OperationConnectionFactory {
 public \PDO $db;public int $now;public int $opens=0;public bool $refuse_completion=false;public bool $lost_ack=false;public ?\Closure $read_hook=null;public ?\Closure $retire_hook=null;
 public function __construct() { $initial=new RetentionUnitSession();$this->db=$initial->raw();$this->now=QuoteFixtures::time()->plus_seconds(2100)->epoch_microseconds();$this->db->sqliteCreateFunction('UTC_NOW',fn()=>QuoteTime::from_epoch_microseconds($this->now)->sql());foreach(OperationStoreSchema::SUFFIXES as $suffix) { $columns=[];foreach(OperationStoreSchema::columns($suffix) as $name=>$definition) { $columns[]=$name.($name==='id'?' INTEGER PRIMARY KEY AUTOINCREMENT':(str_contains($definition[0],'int')?' INTEGER':' TEXT')); }$this->db->exec('CREATE TABLE storage_delivery_engine_'.$suffix.'('.implode(',',$columns).')');foreach(OperationStoreSchema::indexes($suffix) as $name=>$index) { if($name!=='PRIMARY') { $this->db->exec('CREATE '.($index['unique']?'UNIQUE ':'').'INDEX '.$suffix.'_'.$name.' ON storage_delivery_engine_'.$suffix.'('.implode(',',$index['columns']).')'); } } } }
 public function open():OperationSession { $this->opens++;$session=new RetentionUnitSession($this->db);$session->refuse_completion=$this->refuse_completion;$this->refuse_completion=false;$session->on_read=function($sql,$s) { if(null!==$this->read_hook) { ($this->read_hook)($sql); } };return new RetentionUnitWrapper($session,$this); }
 public function insert(string $suffix,array $row):int { unset($row['id']);$stmt=$this->db->prepare('INSERT INTO storage_delivery_engine_'.$suffix.'('.implode(',',array_keys($row)).') VALUES('.implode(',',array_fill(0,count($row),'?')).')');$stmt->execute(array_values($row));return (int)$this->db->lastInsertId(); }
 public function quote(int $id=1):array { return $this->db->query('SELECT * FROM storage_delivery_engine_delivery_quotes WHERE id='.$id)->fetch(\PDO::FETCH_ASSOC); }
 public function count(string $suffix):int { return (int)$this->db->query('SELECT COUNT(*) FROM storage_delivery_engine_'.$suffix)->fetchColumn(); }
 public function seed():QuoteStoredRow { $quote=QuoteStorageFixtures::quote();$raw=$quote->row();$raw['id']=$this->insert('delivery_quotes',$raw);$quote=QuoteStoredRow::from_row($raw);$profile=QuoteOperationProfile::registry()->get('delivery_quote.issue',1);$hash=$raw['issue_namespace_hash'];$facts=['quote_id'=>$raw['quote_uuid'],'quote_revision'=>1,'state'=>'issued','body_digest'=>$raw['body_digest'],'owner_digest'=>$raw['owner_digest'],'namespace_hash'=>$hash,'completed_at'=>QuoteFixtures::time()->epoch_microseconds(),'control_revision'=>1];$completion=OperationCompletion::accepted($profile,$facts,['site_id'=>1,'owner_digest'=>$raw['owner_digest'],'quote_id'=>$raw['quote_uuid'],'purpose'=>'private_quote_invalidation']);$identity=new OperationIdentity(1,'fixture','fixture','delivery_quote.issue',1,'quote:'.$raw['quote_uuid'],$hash);$event=OperationMaterialEvent::from_mutation($profile,$identity,RequestContext::create(),['authority_hash'=>hash('sha256','delivery_quote_customer'),'principal_hash'=>hash('sha256',$raw['owner_digest'])],['quote_id'=>$raw['quote_uuid'],'body_digest'=>$raw['body_digest'],'owner_digest'=>$raw['owner_digest'],'namespace_hash'=>$hash,'quote_revision'=>1,'binding_revision'=>0],$profile->reason_codes()[0],1,2,['quote','admission']);$record=['site_id'=>1,'namespace_hash'=>$hash,'intent_hash'=>hash('sha256','i'),'namespace_format'=>1,'intent_format'=>1,'record_format'=>1,'operation'=>'delivery_quote.issue','operation_version'=>1,'target_hash'=>hash('sha256','t'),'state'=>'accepted','publication_state'=>'published','completion_json'=>$completion->to_json(),'audit_id'=>1,'row_version'=>2,'created_at'=>QuoteFixtures::time()->sql(),'updated_at'=>QuoteFixtures::time()->sql(),'completed_at'=>QuoteFixtures::time()->sql()];$rid=$this->insert('operation_records',$record);$eid=$this->insert('operation_changes',['site_id'=>1,'operation_id'=>$rid,'event_format'=>1,'event_json'=>$event->to_json(),'created_at'=>QuoteFixtures::time()->sql()]);$this->db->exec('UPDATE storage_delivery_engine_operation_records SET audit_id='.$eid.' WHERE id='.$rid);$budget=QuoteStorageFixtures::budget()->row();$budget['admission_namespace_hash']=$hash;$budget['slot_key']=QuoteBudgetSlot::admission_slot_key($hash);$budget['lease_state']='consumed';$budget['revision']=2;$budget['consumed_quote_uuid']=$raw['quote_uuid'];$budget['consumed_at']=QuoteFixtures::time()->sql();$this->insert('delivery_quote_budget_windows',$budget);return $quote; }
 public function pending(QuoteStoredRow $quote,string $purpose):void { $hash=$quote->header()->namespace_hashes()[$purpose];$this->insert('operation_records',['site_id'=>1,'namespace_hash'=>$hash,'intent_hash'=>hash('sha256','i'),'namespace_format'=>1,'intent_format'=>1,'record_format'=>1,'operation'=>'delivery_quote.'.$purpose,'operation_version'=>1,'target_hash'=>hash('sha256','t'),'state'=>'pending','publication_state'=>'none','completion_json'=>null,'audit_id'=>null,'row_version'=>1,'created_at'=>QuoteFixtures::time()->sql(),'updated_at'=>QuoteFixtures::time()->sql(),'completed_at'=>null]); }
}
final class RetentionUnitWrapper implements OperationSession {
 private int $commits=0;public function __construct(private RetentionUnitSession $s,private RetentionUnitFactory $f) {}public function site_id():int { return $this->s->site_id(); }public function table_prefix():string { return $this->s->table_prefix(); }public function charset_collate():string { return $this->s->charset_collate(); }public function begin():bool { return $this->s->begin(); }public function commit():OperationCommitResult { $r=$this->s->commit();if(++$this->commits===2&&$this->f->lost_ack) { $this->f->lost_ack=false;$this->s->retire();return OperationCommitResult::Unconfirmed; }return $r; }public function rollback():bool { return $this->s->rollback(); }public function retire():bool { $result=$this->s->retire();if(null!==$this->f->retire_hook) { ($this->f->retire_hook)(); }return $result; }public function is_retired():bool { return $this->s->is_retired(); }public function in_transaction():bool { return $this->s->in_transaction(); }public function validate_tables(array $names):bool { return $this->s->validate_tables($names); }public function query(string $sql):int|false { return $this->s->query($sql); }public function get_row(string $sql):array|null|false { return $this->s->get_row($sql); }public function get_results(string $sql):array|false { return $this->s->get_results($sql); }public function prepare(string $sql,mixed ...$args):string { return $this->s->prepare($sql,...$args); }public function errno():int { return $this->s->errno(); }public function insert_id():int { return $this->s->insert_id(); }
}
final class RetentionUnitSession implements OperationSession {
	private \PDO $pdo; public ?\Closure $on_read=null; public bool $refuse_completion=false; private bool $retired = false; private int $error = 0;
	public array $statements = []; public int $writes = 0; public int $begins = 0; public int $commits = 0; public string $schema_version = '9'; public bool $wrong_engine = false; public bool $failed_read = false; public bool $duplicate_read = false; public bool $missing_marker = false; public array $last_quote_result = [];
	public function __construct(?\PDO $pdo=null) {
		$this->pdo = $pdo ?? new \PDO('sqlite::memory:',null,null,[\PDO::ATTR_ERRMODE=>\PDO::ERRMODE_EXCEPTION]);if(null!==$pdo) { return; } $this->pdo->sqliteCreateFunction( 'OCTET_LENGTH', static fn( $value ) => null === $value ? null : strlen( $value ), 1 );
		foreach ( DeliveryQuoteSchema::SUFFIXES as $suffix ) {
			$columns = []; foreach ( DeliveryQuoteSchema::columns( $suffix ) as $name => $definition ) { $columns[] = $name . ( 'id' === $name ? ' INTEGER PRIMARY KEY AUTOINCREMENT' : ( str_contains( $definition[0], 'int' ) ? ' INTEGER' : ' TEXT' ) . '' ); }
			$table = 'storage_delivery_engine_' . $suffix; $this->pdo->exec( 'CREATE TABLE ' . $table . '(' . implode( ',', $columns ) . ')' ); foreach ( DeliveryQuoteSchema::indexes( $suffix ) as $name => $index ) { if ( 'PRIMARY' !== $name ) { $this->pdo->exec( 'CREATE ' . ( $index['unique'] ? 'UNIQUE ' : '' ) . 'INDEX ' . $suffix . '_' . $name . ' ON ' . $table . '(' . implode( ',', $index['columns'] ) . ')' ); } }
		}
	}
	public function raw(): \PDO { return $this->pdo; }
	public function site_id(): int { return 1; } public function table_prefix(): string { return 'storage_'; } public function charset_collate(): string { return 'DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'; }
	public function begin(): bool { ++$this->begins; return ! $this->retired && $this->pdo->beginTransaction(); }
	public function commit(): OperationCommitResult { ++$this->commits; return $this->pdo->commit() ? OperationCommitResult::Acknowledged : OperationCommitResult::NotSent; }
	public function rollback(): bool { return $this->pdo->inTransaction() && $this->pdo->rollBack(); }
	public function retire(): bool { if ( $this->pdo->inTransaction() ) { $this->pdo->rollBack(); } $this->retired = true; return true; }
	public function is_retired(): bool { return $this->retired; } public function in_transaction(): bool { return ! $this->retired && $this->pdo->inTransaction(); }
	public function validate_tables(array $names):bool { return $this->in_transaction(); }
	public function query( string $sql ): int|false { $this->statements[] = $sql; ++$this->writes;if($this->refuse_completion&&str_contains($sql,'operation_records')&&str_starts_with($sql,'UPDATE')) { $this->refuse_completion=false;return false; } try { $this->error = 0; return $this->pdo->exec( $this->sql( $sql ) ); } catch ( \Throwable ) { $this->error = 1062; return false; } }
	public function get_row( string $sql ): array|null|false {
		$this->statements[] = $sql; $this->error = 0;if(null!==$this->on_read) { ($this->on_read)($sql,$this); }
		if ( str_starts_with( $sql, 'SHOW TABLE STATUS' ) ) { return [ 'Engine' => $this->wrong_engine ? 'MyISAM' : 'InnoDB', 'Collation' => 'utf8mb4_unicode_ci' ]; }
		if ( str_contains( $sql, SchemaVersion::OPTION_NAME ) ) { return [ 'option_value' => $this->schema_version ]; }
		if ( str_contains( $sql, MigrationStatus::OPTION_NAME ) ) { return [ 'option_value' => serialize( [ 'status' => 'success', 'to_version' => '9', 'migration_id' => DeliveryQuoteReadiness::MIGRATION_ID ] ) ]; }
		try { return $this->pdo->query( $this->sql( $sql ) )->fetch( \PDO::FETCH_ASSOC ) ?: null; } catch ( \Throwable ) { $this->error = 1; return false; }
	}
	public function get_results( string $sql ): array|false {
		$this->statements[] = $sql; $this->error = 0;if(null!==$this->on_read) { ($this->on_read)($sql,$this); }
		if ( str_starts_with( $sql, 'SHOW FULL COLUMNS' ) || str_starts_with( $sql, 'SHOW INDEX' ) ) { return $this->metadata( $sql ); }
		$quote_read = str_contains( $sql, 'FROM `storage_delivery_engine_delivery_quotes`' ); if ( $quote_read && $this->failed_read ) { $this->error = 1; return false; }
		try { $rows = $this->pdo->query( $this->sql( $sql ) )->fetchAll( \PDO::FETCH_ASSOC ); } catch ( \Throwable ) { $this->error = 1; return false; }
		if ( $quote_read ) { $this->last_quote_result = $rows; if ( $this->missing_marker ) { foreach ( $rows as &$row ) { unset( $row['payload_oversized'] ); } unset( $row ); } if ( $this->duplicate_read && [] !== $rows ) { $rows[] = $rows[0]; } }
		return $rows;
	}
	public function prepare( string $sql, mixed ...$args ): string { if ( 1 === count( $args ) && is_array( $args[0] ) ) { $args = $args[0]; } $i = 0; return preg_replace_callback( '/%[ds]/', function( array $match ) use ( &$i, $args ): string { $value = $args[$i++]; return '%d' === $match[0] ? (string) (int) $value : $this->pdo->quote( (string) $value ); }, $sql ); }
	public function errno(): int { return $this->error; } public function insert_id(): int { return (int) $this->pdo->lastInsertId(); }
	private function sql( string $sql ): string { return str_replace( [ ' FOR UPDATE', 'BINARY ', 'UTC_TIMESTAMP(6)' ], [ '', '', 'UTC_NOW()' ], $sql ); }
	private function metadata( string $sql ): array {
		preg_match( '/storage_delivery_engine_([a-z_]+)`/', $sql, $match ); $suffix = $match[1];
		if ( in_array( $suffix, DeliveryQuoteSchema::SUFFIXES, true ) ) { $columns = DeliveryQuoteSchema::columns( $suffix ); $indexes = DeliveryQuoteSchema::indexes( $suffix ); }
		elseif ( in_array( $suffix, RuleLifecycleSchema::SUFFIXES, true ) ) { $columns = RuleLifecycleSchema::columns( $suffix ); $indexes = RuleLifecycleSchema::indexes( $suffix ); }
		elseif ( in_array( $suffix, OperationStoreSchema::SUFFIXES, true ) ) { $columns = OperationStoreSchema::columns( $suffix ); $indexes = OperationStoreSchema::indexes( $suffix ); }
		else { $columns = DeliveryQuoteSchema::rate_columns(); $indexes = [ 'PRIMARY' => [ 'unique' => true, 'columns' => [ 'id' ] ], DeliveryQuoteSchema::RATE_INDEX => DeliveryQuoteSchema::rate_index() ]; }
		$out = [];
		if ( str_starts_with( $sql, 'SHOW FULL COLUMNS' ) ) { foreach ( $columns as $name => [ $type, $nullable, $default, $extra, $collation ] ) { $out[] = [ 'Field' => $name, 'Type' => $type, 'Null' => $nullable ? 'YES' : 'NO', 'Default' => $default, 'Extra' => $extra, 'Collation' => 'site' === $collation ? 'utf8mb4_unicode_ci' : $collation ]; } }
		else { foreach ( $indexes as $name => $definition ) { foreach ( $definition['columns'] as $position => $field ) { $out[] = [ 'Key_name' => $name, 'Seq_in_index' => $position + 1, 'Non_unique' => $definition['unique'] ? 0 : 1, 'Sub_part' => null, 'Index_type' => 'BTREE', 'Collation' => 'A', 'Column_name' => $field, 'Expression' => null, 'Visible' => 'YES', 'Ignored' => 'NO' ]; } } }
		return $out;
	}
}
