<?php
declare(strict_types=1);
namespace CetechDeliveryEngine\Tests\Integration\DeliveryQuote;
use CetechDeliveryEngine\Tests\Support\DataLifecycle\DataLifecycleProofDatabase as DB;
use CetechDeliveryEngine\Tests\Support\DeliveryQuote\{QuoteCartProofStack,QuoteProviderProofFixtures,QuoteProviderProofDatabase,QuoteCartProofDatabase,QuoteCartProofFixtures as CartF,QuoteLifecycleProofFactory as Factory,QuoteStorageProofWpdb,QuoteFixtures};
use CetechDeliveryEngine\Tests\Support\Operation\{OperationProofBarrier as Barrier,OperationProofProcess as Process};
use CetechDeliveryEngine\Application\DeliveryQuote\{CartQuoteSessionEnvelope as Envelope,NativeCartQuoteSessionStore as Store,QuotePreparationCommand};
use CetechDeliveryEngine\Domain\DeliveryQuote\{QuoteId,QuoteOwner};
use PHPUnit\Framework\Attributes\{DataProvider,Group};
use PHPUnit\Framework\TestCase;

/** New Q05 physical boundaries; native shopper/rendering qualification is separate. */
#[Group('quote-cart-real-db')]
final class DeliveryQuoteCartReferenceRealDatabaseTest extends TestCase {
	private \mysqli $database;
	private string $prefix;
	private array $factories=[];
	private array $stacks=[];
	private array $processes=[];
	private array $directories=[];
	private array $saved_globals=[];
	protected function setUp():void {
		foreach(['wpdb','blog_id'] as $key){$this->saved_globals[$key]=[array_key_exists($key,$GLOBALS),$GLOBALS[$key]??null];}
		$this->database=DB::connect();$this->prefix=DB::prefix();DB::install($this->database,$this->prefix);QuoteCartProofDatabase::install_sessions($this->database,$this->prefix);
		$GLOBALS['wpdb']=new QuoteStorageProofWpdb($this->database,$this->prefix);$GLOBALS['blog_id']=1;
	}
	protected function tearDown():void {
		foreach($this->processes as $p){$p->kill();}foreach($this->stacks as $s){$s->close_all();}foreach($this->factories as $f){$f->close_all();}foreach($this->directories as $d){Barrier::cleanup($d);}
		if(isset($this->database,$this->prefix)){DB::cleanup($this->database,$this->prefix);$this->database->close();}
		foreach($this->saved_globals as $key=>[$exists,$value]){if($exists){$GLOBALS[$key]=$value;}else{unset($GLOBALS[$key]);}}
	}
	private function stack(?callable $configure=null):QuoteCartProofStack { $s=new QuoteCartProofStack($this->prefix,null,$configure);$this->stacks[]=$s;return $s; }
	private function seed_provider():void {QuoteProviderProofFixtures::seed($this->database,$this->prefix);QuoteProviderProofDatabase::rate($this->database,$this->prefix);QuoteCartProofDatabase::install_native_receipt_tables($this->database,$this->prefix);}
	private function request():\CetechDeliveryEngine\Domain\Contracts\RequestContext{return \CetechDeliveryEngine\Domain\Contracts\RequestContext::create();}
	private function factory(?callable $configure=null):Factory{$f=new Factory($this->prefix);$f->configure=null===$configure?null:\Closure::fromCallable($configure);$this->factories[]=$f;return $f;}
	private function rows(string $suffix):array{$r=$this->database->query("SELECT * FROM `{$this->prefix}delivery_engine_{$suffix}` ORDER BY id");if(!$r instanceof \mysqli_result){throw new \RuntimeException('Native quote-cart rows refused.');}return $r->fetch_all(MYSQLI_ASSOC);}
	private function native_count(string $suffix):int{return (int)DB::scalar($this->database,"SELECT COUNT(*) FROM `{$this->prefix}delivery_engine_{$suffix}`");}
	private function directory():string{$d=Barrier::directory();$this->directories[]=$d;return $d;}
	private function worker(array $args):Process{$p=new Process([__DIR__.'/cart-reference-process-worker.php',json_encode(['prefix'=>$this->prefix]+$args,JSON_THROW_ON_ERROR)]);$this->processes[]=$p;return $p;}
	private function connection_signal(string $path,Process $p):int{Process::wait_for($path);$r=json_decode((string)file_get_contents($path),true,4,JSON_THROW_ON_ERROR);self::assertSame($p->pid(),$r['process_id']);self::assertGreaterThan(0,$r['connection_id']);return $r['connection_id'];}
	private function owner(string $session,?string $customer=null):QuoteOwner{return QuoteOwner::from_array(array_replace(CartF::owner()->facts(),['kind'=>null===$customer?'guest':'customer','principal_hash'=>QuoteFixtures::digest('principal:'.($customer??$session)),'session_hash'=>QuoteFixtures::digest('session:'.$session)]));}
	private function preparation(?QuoteOwner $owner=null,?string $token=null):QuotePreparationCommand {$owner??=CartF::owner();return QuotePreparationCommand::create($owner,\CetechDeliveryEngine\Tests\Support\DeliveryQuote\QuoteCartProofFixtures::draft($owner)->draft_digest(),$token??QuoteId::generate()->value(),'legacy_fixed_base_v1',1,'legacy_fixed_base_v1',1);}
	private function envelope(?QuoteOwner $owner=null,int $generation=1):Envelope{return Envelope::begin($this->preparation($owner),$generation,Factory::NOW+3600);}
	private function store(?Factory $factory=null,?QuoteOwner $owner=null,?callable $readiness=null):Store{$owner??=CartF::owner();return new Store($factory??$this->factory(),static fn(QuoteOwner $candidate,string $operation):bool=>$candidate->equals($owner),$readiness,'finite-q05-session-proof-secret',static fn():int=>Factory::NOW+3600);}
	private function customer_row():array{return DB::row($this->database,"SELECT * FROM `{$this->prefix}woocommerce_sessions` WHERE session_key='native-customer-row'");}
	public function test_actual_auxiliary_reference_has_a_separate_key_and_preserves_native_customer_bytes():void {
		$customer=$this->customer_row();$store=$this->store();$envelope=$this->envelope();self::assertTrue($store->compare_and_swap(CartF::owner(),null,$envelope));self::assertSame($envelope->to_private_json(),$store->load(CartF::owner())->to_private_json());self::assertNotSame('native-customer-row',$store->key_for(CartF::owner()));self::assertSame(32,strlen($store->key_for(CartF::owner())));self::assertSame($customer,$this->customer_row());self::assertCount(2,QuoteCartProofDatabase::sessions($this->database,$this->prefix));self::assertSame(0,$this->native_count('operation_records'));
	}
	public static function owner_pairs():array{return ['two guests'=>[null],'two carts of one customer'=>['one-customer']];}
	#[DataProvider('owner_pairs')]
	public function test_actual_reference_keys_isolate_two_sessions_even_for_one_customer(?string $customer):void {
		$a=$this->owner('cart-a',$customer);$b=$this->owner('cart-b',$customer);$as=$this->store(owner:$a);$bs=$this->store(owner:$b);$ae=$this->envelope($a);$be=$this->envelope($b);self::assertTrue($as->compare_and_swap($a,null,$ae));self::assertTrue($bs->compare_and_swap($b,null,$be));self::assertNotSame($as->key_for($a),$bs->key_for($b));self::assertSame($ae->to_private_json(),$as->load($a)->to_private_json());self::assertSame($be->to_private_json(),$bs->load($b)->to_private_json());self::assertFalse($bs->compare_and_swap($b,$be,$ae));self::assertSame($be->to_private_json(),$bs->load($b)->to_private_json());
	}
	public function test_late_old_generation_publication_cannot_overwrite_a_newer_reference():void {
		$store=$this->store();$begin=$this->envelope();self::assertTrue($store->compare_and_swap(CartF::owner(),null,$begin));$old=$begin->with_phase('failed');self::assertTrue($store->compare_and_swap(CartF::owner(),$begin,$old));$late=$this->envelope(generation:2);$new=$this->envelope(generation:2);self::assertTrue($store->compare_and_swap(CartF::owner(),$old,$new));self::assertFalse($store->compare_and_swap(CartF::owner(),$old,$late));self::assertSame($new->to_private_json(),$store->load(CartF::owner())->to_private_json());self::assertSame(0,$this->native_count('delivery_quotes'));
	}
	public static function session_table_conflicts():array{return ['wrong key type'=>['type'],'prefix-only unique key'=>['prefix'],'nontransactional engine'=>['engine']];}
	#[DataProvider('session_table_conflicts')]
	public function test_native_reference_table_conflict_refuses_without_rewriting_stored_bytes(string $conflict):void {
		$store=$this->store();$original=$this->envelope();self::assertTrue($store->compare_and_swap(CartF::owner(),null,$original));$before=QuoteCartProofDatabase::sessions($this->database,$this->prefix);$sql=match($conflict){'type'=>"ALTER TABLE `{$this->prefix}woocommerce_sessions` MODIFY session_key varchar(32) NOT NULL",'prefix'=>"ALTER TABLE `{$this->prefix}woocommerce_sessions` DROP INDEX session_key, ADD UNIQUE KEY session_key(session_key(8))",'engine'=>"ALTER TABLE `{$this->prefix}woocommerce_sessions` ENGINE=MyISAM"};DB::execute($this->database,$sql);self::assertFalse($store->compare_and_swap(CartF::owner(),$original,$original->with_phase('failed')));try{$store->load(CartF::owner());self::fail('Conflicting native reference metadata must refuse.');}catch(\RuntimeException){self::assertSame($before,QuoteCartProofDatabase::sessions($this->database,$this->prefix));}self::assertSame(0,$this->native_count('operation_records'));
	}
	public static function corrupted_values():array{return ['unknown mandatory format'=>['format'],'oversized reference'=>['size'],'malformed private JSON'=>['json']];}
	#[DataProvider('corrupted_values')]
	public function test_unknown_or_corrupt_private_reference_cannot_be_loaded_or_silently_replaced(string $conflict):void {
		$store=$this->store();$original=$this->envelope();self::assertTrue($store->compare_and_swap(CartF::owner(),null,$original));$key=$store->key_for(CartF::owner());$value=match($conflict){'format'=>str_replace('"format_version":1','"format_version":99',$original->to_private_json()),'size'=>str_repeat('x',Envelope::MAX_BYTES+1),'json'=>'{broken'};$value=$this->database->real_escape_string($value);DB::execute($this->database,"UPDATE `{$this->prefix}woocommerce_sessions` SET session_value='{$value}' WHERE session_key='{$key}'");$before=QuoteCartProofDatabase::sessions($this->database,$this->prefix);self::assertFalse($store->compare_and_swap(CartF::owner(),$original,$original->with_phase('failed')));try{$store->load(CartF::owner());self::fail('Unknown reference cannot load as legacy.');}catch(\RuntimeException){self::assertSame($before,QuoteCartProofDatabase::sessions($this->database,$this->prefix));}self::assertSame(0,$this->native_count('delivery_quotes'));
	}
	public function test_actual_refresh_creates_one_quote_and_confirmation_does_not_prepare_again():void {
		$this->seed_provider();$s=$this->stack();$token=QuoteId::generate()->value();$result=$s->service->refresh($token,0,$this->request());self::assertSame('review_required',$result->shopper_facts()['status']);self::assertSame(1,$s->environment->prepares);self::assertSame(1,$this->native_count('delivery_quotes'));self::assertSame(1,$this->native_count('operation_records'));self::assertSame(1,$this->native_count('operation_changes'));self::assertSame('consumed',$this->rows('delivery_quote_budget_windows')[2]['lease_state']);$opened=$s->sessions->load(CartF::owner());self::assertCount(1,$opened->rate_references());$component=$opened->original_issue()->context()->private_facts()['groups'][0]['component_key'];self::assertTrue($opened->rate_references()[0]->matches($opened->header(),$component,1));self::assertStringNotContainsString($opened->rate_references()[0]->public_fields()['component_handle'],json_encode($result->shopper_facts(),JSON_THROW_ON_ERROR));$result=$s->service->confirm(1,$this->request());self::assertSame('confirmed',$result->shopper_facts()['status']);self::assertSame(1,$s->environment->prepares);self::assertSame('accepted',$this->rows('delivery_quotes')[0]['state']);self::assertSame(2,$this->native_count('operation_records'));self::assertSame(2,$this->native_count('operation_changes'));$before=$this->rows('operation_changes');self::assertSame('confirmed',$s->service->confirm(1,$this->request())->shopper_facts()['status']);self::assertSame($before,$this->rows('operation_changes'));
	}

	public function test_two_os_processes_share_one_early_namespace_and_fresh_process_replay_never_prepares():void {
		$this->seed_provider();$d=$this->directory();$token=QuoteId::generate()->value();$a=$this->worker(['action'=>'refresh','token'=>$token,'generation'=>0,'prepare_ready'=>$d.'/ready','prepare_release'=>$d.'/release']);$this->connection_signal($d.'/ready',$a);self::assertSame(0,$this->native_count('operation_records'));self::assertSame(0,$this->native_count('delivery_quotes'));self::assertSame('granted',$this->rows('delivery_quote_budget_windows')[2]['lease_state']);
		try{$b=$this->worker(['action'=>'refresh','token'=>$token,'generation'=>0]);$br=$b->finish();self::assertNotSame($a->pid(),$br['process_id']);self::assertSame('unconfirmed',$br['status']);self::assertSame(0,$br['prepares']);self::assertSame(0,$br['source_captures']);self::assertSame(0,$br['native_reads']);}finally{Barrier::signal($d.'/release');}
		$ar=$a->finish();self::assertSame('review_required',$ar['status']);self::assertSame(1,$ar['prepares']);self::assertSame(1,$this->native_count('delivery_quotes'));self::assertSame(1,$this->native_count('operation_records'));self::assertSame(1,$this->native_count('operation_changes'));$budget=$this->rows('delivery_quote_budget_windows');self::assertSame([1,1,1],array_map(static fn(array $r):int=>(int)$r['attempt_count'],$budget));self::assertSame('consumed',$budget[2]['lease_state']);$quotes=$this->rows('delivery_quotes');$events=$this->rows('operation_changes');$records=$this->rows('operation_records');$sessions=QuoteCartProofDatabase::sessions($this->database,$this->prefix);$c=$this->worker(['action'=>'refresh','token'=>$token,'generation'=>0]);$cr=$c->finish();self::assertSame('review_required',$cr['status']);self::assertSame(0,$cr['prepares']);self::assertSame($quotes,$this->rows('delivery_quotes'));self::assertSame($events,$this->rows('operation_changes'));self::assertSame($records,$this->rows('operation_records'));self::assertSame($budget,$this->rows('delivery_quote_budget_windows'));self::assertSame($sessions,QuoteCartProofDatabase::sessions($this->database,$this->prefix));
	}
	public function test_delayed_old_generation_from_another_os_process_cannot_replace_current_reference():void {
		$s=$this->store();$begin=$this->envelope();self::assertTrue($s->compare_and_swap(CartF::owner(),null,$begin));$old=$begin->with_phase('failed');self::assertTrue($s->compare_and_swap(CartF::owner(),$begin,$old));$d=$this->directory();$a=$this->worker(['action'=>'cas','expected'=>$old->to_private_json(),'next'=>$this->envelope(generation:2)->to_private_json(),'dispatch_ready'=>$d.'/dispatch','dispatch_release'=>$d.'/release']);$this->connection_signal($d.'/dispatch',$a);$other=$this->owner('other-cart');$otherStore=$this->store(owner:$other);$otherEnvelope=$this->envelope($other);self::assertTrue($otherStore->compare_and_swap($other,null,$otherEnvelope));$customer=$this->customer_row();$new=$this->envelope(generation:2);try{self::assertTrue($s->compare_and_swap(CartF::owner(),$old,$new));}finally{Barrier::signal($d.'/release');}$r=$a->finish();self::assertFalse($r['cas']);self::assertSame(0,$r['lock_timeouts']);self::assertSame($new->to_private_json(),$s->load(CartF::owner())->to_private_json());self::assertSame($otherEnvelope->to_private_json(),$otherStore->load($other)->to_private_json());self::assertSame($customer,$this->customer_row());
	}

	public static function early_denials():array{return ['session quota'=>['session_minute',20],'site quota'=>['site_minute',200],'current pause'=>['pause',0],'schema downgrade'=>['schema',0]];}
	#[DataProvider('early_denials')]
	public function test_actual_early_denial_precedes_all_source_native_provider_and_c03_work(string $kind,int $limit):void {
		$s=$this->stack();if($limit>0){$r=$s->gate->admit($this->preparation(),\CetechDeliveryEngine\Application\DeliveryQuote\QuotePreparationAttempt::generate());self::assertSame('preparation_allowed',$r->status);DB::execute($this->database,"UPDATE `{$this->prefix}delivery_engine_delivery_quote_budget_windows` SET attempt_count={$limit},revision=revision+1 WHERE slot_kind='{$kind}'");}
		elseif('pause'===$kind){DB::insert_option($this->database,$this->prefix,\CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore::OPTION_NAME,\CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState::record_json(1,'checkout_suspended',2,'operator_pause',9,Factory::NOW));}
		else{$name=\CetechDeliveryEngine\Core\Versioning\SchemaVersion::OPTION_NAME;DB::execute($this->database,"UPDATE `{$this->prefix}options` SET option_value='8' WHERE option_name='{$name}'");}
		$before=$this->rows('delivery_quote_budget_windows');$r=$s->service->refresh(QuoteId::generate()->value(),0,$this->request());self::assertSame('unavailable',$r->shopper_facts()['status']);self::assertSame(0,$s->environment->prepares);self::assertSame(0,$s->environment->source_captures());self::assertSame(0,$s->environment->native_reads());self::assertSame(0,$this->native_count('delivery_quotes'));self::assertSame(0,$this->native_count('operation_records'));self::assertSame(0,$this->native_count('operation_changes'));self::assertSame($before,$this->rows('delivery_quote_budget_windows'));self::assertSame('failed',$s->sessions->load(CartF::owner())->phase());
	}
	public function test_preparation_failure_terminates_only_its_original_lease_before_c03_and_replay_does_not_prepare():void {
		$s=$this->stack();$s->environment->before_prepare=static function():void{throw new \RuntimeException('Finite fixture refuses preparation.');};$token=QuoteId::generate()->value();self::assertSame('unavailable',$s->service->refresh($token,0,$this->request())->shopper_facts()['status']);self::assertSame(1,$s->environment->prepares);self::assertSame(0,$s->environment->source_captures());self::assertSame(0,$s->environment->native_reads());self::assertSame('terminated',$this->rows('delivery_quote_budget_windows')[2]['lease_state']);self::assertSame(0,$this->native_count('operation_records'));self::assertSame(0,$this->native_count('delivery_quotes'));$before=$this->rows('delivery_quote_budget_windows');self::assertSame('unavailable',$s->service->refresh($token,0,$this->request())->shopper_facts()['status']);self::assertSame(1,$s->environment->prepares);self::assertSame($before,$this->rows('delivery_quote_budget_windows'));
	}
	public function test_lost_session_commit_ack_is_recovered_from_fresh_native_read_without_second_write():void {
		$factory=$this->factory(static function($t):void{$t->fault_commit=1;$t->commit_fault='lost_ack';});$store=$this->store($factory);$envelope=$this->envelope();self::assertFalse($store->compare_and_swap(CartF::owner(),null,$envelope));self::assertSame(1,$factory->transports[0]->sent_commits);self::assertTrue($factory->sessions[0]->is_retired());$before=QuoteCartProofDatabase::sessions($this->database,$this->prefix);$fresh=$this->store();self::assertSame($envelope->to_private_json(),$fresh->load(CartF::owner())->to_private_json());self::assertFalse($fresh->compare_and_swap(CartF::owner(),null,$envelope));self::assertSame($before,QuoteCartProofDatabase::sessions($this->database,$this->prefix));self::assertSame(0,$this->native_count('operation_changes'));
	}
	public function test_lost_quote_commit_ack_keeps_original_staged_reference_and_fresh_os_retry_finishes_without_preparation():void {
		$this->seed_provider();$s=$this->stack(static function($t):void{$t->before=static function(string $sql,$transport):void{if(str_starts_with($sql,'INSERT INTO ')&&str_contains($sql,'delivery_engine_delivery_quotes')){$transport->fault_commit=2;$transport->commit_fault='lost_ack';}};});$token=QuoteId::generate()->value();self::assertSame('unconfirmed',$s->service->refresh($token,0,$this->request())->shopper_facts()['status']);self::assertSame('staged',$s->sessions->load(CartF::owner())->phase());self::assertSame(1,$this->native_count('delivery_quotes'));self::assertSame(1,$this->native_count('operation_changes'));$before=$this->rows('delivery_quotes');$events=$this->rows('operation_changes');$records=$this->rows('operation_records');$budget=$this->rows('delivery_quote_budget_windows');$w=$this->worker(['action'=>'retry','generation'=>1]);$r=$w->finish();self::assertSame('review_required',$r['status']);self::assertSame(0,$r['prepares']);self::assertSame('issued',$s->sessions->load(CartF::owner())->phase());self::assertSame($before,$this->rows('delivery_quotes'));self::assertSame($events,$this->rows('operation_changes'));self::assertSame(1,$this->native_count('operation_records'));$after=$this->rows('operation_records');self::assertSame($records[0]['completion_json'],$after[0]['completion_json']);self::assertSame($records[0]['audit_id'],$after[0]['audit_id']);self::assertSame('published',$after[0]['publication_state']);self::assertSame((int)$records[0]['row_version']+1,(int)$after[0]['row_version']);self::assertSame($budget,$this->rows('delivery_quote_budget_windows'));self::assertSame(1,$s->environment->prepares);
	}

	private function exact_session_wait(int $waiter,int $blocker):void {
		self::assertNotSame($waiter,$blocker);$table=$this->prefix.'woocommerce_sessions';$sql="SELECT COUNT(*) FROM information_schema.INNODB_LOCK_WAITS w JOIN information_schema.INNODB_LOCKS l ON l.lock_id=w.requested_lock_id JOIN information_schema.INNODB_TRX r ON r.trx_id=w.requesting_trx_id JOIN information_schema.INNODB_TRX b ON b.trx_id=w.blocking_trx_id WHERE l.lock_table=CONCAT('`',DATABASE(),'`.`{$table}`') AND r.trx_mysql_thread_id={$waiter} AND b.trx_mysql_thread_id={$blocker} AND r.trx_state='LOCK WAIT'";$end=microtime(true)+1.5;do{if((int)DB::scalar($this->database,$sql)>0){self::assertTrue(true);return;}$remaining=$end-microtime(true);if($remaining<=0)break;usleep((int)min(120000,ceil($remaining*1000000)));}while(microtime(true)<$end);self::fail('Exact second native reference owner did not wait on first owner.');
	}
	public function test_two_native_session_cas_owners_serialize_and_the_loser_cannot_overwrite():void {
		$store=$this->store();$original=$this->envelope();self::assertTrue($store->compare_and_swap(CartF::owner(),null,$original));$next=$original->with_phase('failed');$d=$this->directory();$a=$this->worker(['action'=>'cas','expected'=>$original->to_private_json(),'next'=>$next->to_private_json(),'lock_ready'=>$d.'/locked','lock_release'=>$d.'/release']);$blocker=$this->connection_signal($d.'/locked',$a);$b=$this->worker(['action'=>'cas','expected'=>$original->to_private_json(),'next'=>$next->to_private_json(),'dispatch_ready'=>$d.'/dispatch']);$waiter=$this->connection_signal($d.'/dispatch',$b);try{$this->exact_session_wait($waiter,$blocker);}finally{Barrier::signal($d.'/release');}$ar=$a->finish();$br=$b->finish();self::assertTrue($ar['cas']);self::assertFalse($br['cas']);self::assertSame(0,$ar['lock_timeouts']+$br['lock_timeouts']);self::assertSame(0,$ar['deadlocks']+$br['deadlocks']);self::assertSame($next->to_private_json(),$store->load(CartF::owner())->to_private_json());
	}
	public static function tampered_issued_reference():array{return ['provider'=>['provider'],'component'=>['component'],'owner'=>['owner'],'acceptance handle'=>['handle']];}
	#[DataProvider('tampered_issued_reference')]
	public function test_actual_tampered_issued_reference_refuses_acceptance_without_c03_or_recapture(string $kind):void {
		$this->seed_provider();$s=$this->stack();self::assertSame('review_required',$s->service->refresh(QuoteId::generate()->value(),0,$this->request())->shopper_facts()['status']);$envelope=$s->sessions->load(CartF::owner());$facts=json_decode($envelope->to_private_json(),true,16,JSON_THROW_ON_ERROR);if('provider'===$kind){$facts['preparation']['provider_code']='other_provider';}elseif('owner'===$kind){$facts['preparation']['owner']=$this->owner('other')->facts();}elseif('handle'===$kind){$facts['reference']['acceptance_handle']=QuoteFixtures::digest('tampered_handle');}else{$facts['rate_references'][0]['component_key']=QuoteFixtures::digest('other_component');}$value=$this->database->real_escape_string(json_encode($facts,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES));$key=$s->sessions->key_for(CartF::owner());DB::execute($this->database,"UPDATE `{$this->prefix}woocommerce_sessions` SET session_value='{$value}' WHERE session_key='{$key}'");$before=$this->rows('delivery_quotes');$events=$this->rows('operation_changes');$records=$this->rows('operation_records');$sessions=QuoteCartProofDatabase::sessions($this->database,$this->prefix);$prepares=$s->environment->prepares;$native=$s->environment->native_reads();self::assertSame('unavailable',$s->service->confirm(1,$this->request())->shopper_facts()['status']);self::assertSame($prepares,$s->environment->prepares);self::assertSame($native,$s->environment->native_reads());self::assertSame($before,$this->rows('delivery_quotes'));self::assertSame($events,$this->rows('operation_changes'));self::assertSame($records,$this->rows('operation_records'));self::assertSame($sessions,QuoteCartProofDatabase::sessions($this->database,$this->prefix));
	}
	public static function changed_current_cart():array{return ['quantity'=>['quantity'],'current tariff'=>['rate'],'other owner'=>['owner']];}
	#[DataProvider('changed_current_cart')]
	public function test_current_cart_or_source_change_refuses_old_confirmation_and_keeps_recorded_history(string $kind):void {
		$this->seed_provider();$s=$this->stack();self::assertSame('review_required',$s->service->refresh(QuoteId::generate()->value(),0,$this->request())->shopper_facts()['status']);$before=$this->rows('delivery_quotes');$events=$this->rows('operation_changes');$records=$this->rows('operation_records');$budget=$this->rows('delivery_quote_budget_windows');$sessions=QuoteCartProofDatabase::sessions($this->database,$this->prefix);if('quantity'===$kind){$s->environment->loaded_draft=CartF::draft(CartF::owner(),3);}elseif('rate'===$kind){DB::execute($this->database,"UPDATE `{$this->prefix}delivery_engine_rate_cards` SET base_amount='15.0000' WHERE id=1");}else{$s->environment->loaded_draft=CartF::draft($this->owner('other'));}$r=$s->service->confirm(1,$this->request());self::assertContains($r->shopper_facts()['status'],['changed','unavailable']);self::assertFalse($r->shopper_facts()['can_confirm']);self::assertSame(1,$s->environment->prepares);self::assertSame($before,$this->rows('delivery_quotes'));self::assertSame($events,$this->rows('operation_changes'));self::assertSame($records,$this->rows('operation_records'));self::assertSame($budget,$this->rows('delivery_quote_budget_windows'));self::assertSame($sessions,QuoteCartProofDatabase::sessions($this->database,$this->prefix));
	}
	public function test_reader_readiness_downgrade_keeps_original_reference_and_recorded_quote_bytes():void {
		$this->seed_provider();$s=$this->stack();self::assertSame('review_required',$s->service->refresh(QuoteId::generate()->value(),0,$this->request())->shopper_facts()['status']);$before=$this->rows('delivery_quotes');$events=$this->rows('operation_changes');$records=$this->rows('operation_records');$sessions=QuoteCartProofDatabase::sessions($this->database,$this->prefix);$name=\CetechDeliveryEngine\Core\Versioning\SchemaVersion::OPTION_NAME;DB::execute($this->database,"UPDATE `{$this->prefix}options` SET option_value='8' WHERE option_name='{$name}'");self::assertSame('unavailable',$s->service->current($this->request())->shopper_facts()['status']);self::assertSame('unavailable',$s->service->confirm(1,$this->request())->shopper_facts()['status']);self::assertSame(1,$s->environment->prepares);self::assertSame($before,$this->rows('delivery_quotes'));self::assertSame($events,$this->rows('operation_changes'));self::assertSame($records,$this->rows('operation_records'));self::assertSame($sessions,QuoteCartProofDatabase::sessions($this->database,$this->prefix));
	}
	public function test_stale_generation_after_explicit_refresh_cannot_accept_new_quote_or_replace_current_reference():void {
		$this->seed_provider();$s=$this->stack();self::assertSame('review_required',$s->service->refresh(QuoteId::generate()->value(),0,$this->request())->shopper_facts()['status']);self::assertSame('review_required',$s->service->refresh(QuoteId::generate()->value(),1,$this->request())->shopper_facts()['status']);$before=$this->rows('delivery_quotes');$events=$this->rows('operation_changes');$sessions=QuoteCartProofDatabase::sessions($this->database,$this->prefix);self::assertSame('changed',$s->service->confirm(1,$this->request())->shopper_facts()['status']);self::assertSame(2,$s->environment->prepares);self::assertSame($before,$this->rows('delivery_quotes'));self::assertSame($events,$this->rows('operation_changes'));self::assertSame($sessions,QuoteCartProofDatabase::sessions($this->database,$this->prefix));self::assertSame(['issued','issued'],array_column($before,'state'));
	}

	public function test_lost_issue_staging_ack_never_sends_c03_and_expired_original_retry_closes_without_recapture():void {
		$this->seed_provider();$s=$this->stack(static function($t):void{$t->before=static function(string $sql,$transport):void{if(str_starts_with($sql,'UPDATE ')&&str_contains($sql,'woocommerce_sessions')&&str_contains($sql,'staged')){$transport->fault_commit=1;$transport->commit_fault='lost_ack';}};});$token=QuoteId::generate()->value();self::assertSame('unconfirmed',$s->service->refresh($token,0,$this->request())->shopper_facts()['status']);self::assertSame('staged',$s->sessions->load(CartF::owner())->phase());self::assertSame(0,$this->native_count('delivery_quotes'));self::assertSame(0,$this->native_count('operation_records'));self::assertSame(0,$this->native_count('operation_changes'));self::assertSame('granted',$this->rows('delivery_quote_budget_windows')[2]['lease_state']);$budget=$this->rows('delivery_quote_budget_windows');$first=$this->worker(['action'=>'retry','generation'=>1]);$fr=$first->finish();self::assertSame('unconfirmed',$fr['status']);self::assertSame(0,$fr['prepares']);self::assertSame($budget,$this->rows('delivery_quote_budget_windows'));self::assertSame(0,$this->native_count('operation_records'));$expired=$this->worker(['action'=>'retry','generation'=>1,'clock'=>Factory::NOW+60]);$er=$expired->finish();self::assertSame('unavailable',$er['status']);self::assertSame(0,$er['prepares']);self::assertSame(0,$er['source_captures']);self::assertSame(0,$er['native_reads']);self::assertSame('failed',$s->sessions->load(CartF::owner())->phase());self::assertSame('terminated',$this->rows('delivery_quote_budget_windows')[2]['lease_state']);self::assertSame(0,$this->native_count('delivery_quotes'));self::assertSame(0,$this->native_count('operation_changes'));self::assertSame(0,$this->native_count('operation_records'));self::assertSame(1,$s->environment->prepares);
	}
	public function test_lost_accept_staging_ack_preserves_original_reference_and_explicit_fresh_process_retry_accepts_once():void {
		$this->seed_provider();$s=$this->stack(static function($t):void{$t->before=static function(string $sql,$transport):void{if(str_starts_with($sql,'UPDATE ')&&str_contains($sql,'woocommerce_sessions')&&str_contains($sql,'accepting')){$transport->fault_commit=1;$transport->commit_fault='lost_ack';}};});self::assertSame('review_required',$s->service->refresh(QuoteId::generate()->value(),0,$this->request())->shopper_facts()['status']);$original=$s->sessions->load(CartF::owner());self::assertSame('unconfirmed',$s->service->confirm(1,$this->request())->shopper_facts()['status']);self::assertSame('accepting',$s->sessions->load(CartF::owner())->phase());self::assertSame('issued',$this->rows('delivery_quotes')[0]['state']);self::assertSame(1,$this->native_count('operation_records'));self::assertSame(1,$this->native_count('operation_changes'));$w=$this->worker(['action'=>'retry','generation'=>1]);$r=$w->finish();self::assertSame('confirmed',$r['status']);self::assertSame(0,$r['prepares']);$current=$s->sessions->load(CartF::owner());self::assertSame('confirmed',$current->phase());self::assertSame($original->reference()->public_fields(),$current->reference()->public_fields());self::assertSame($original->header()->to_private_json(),$current->header()->to_private_json());self::assertSame($original->rate_references()[0]->to_private_array(),$current->rate_references()[0]->to_private_array());self::assertSame('accepted',$this->rows('delivery_quotes')[0]['state']);self::assertSame(2,$this->native_count('operation_records'));self::assertSame(2,$this->native_count('operation_changes'));$quotes=$this->rows('delivery_quotes');$events=$this->rows('operation_changes');$records=$this->rows('operation_records');$sessions=QuoteCartProofDatabase::sessions($this->database,$this->prefix);$again=$this->worker(['action'=>'retry','generation'=>1]);$ar=$again->finish();self::assertSame('confirmed',$ar['status']);self::assertSame(0,$ar['prepares']);self::assertSame($quotes,$this->rows('delivery_quotes'));self::assertSame($events,$this->rows('operation_changes'));self::assertSame($records,$this->rows('operation_records'));self::assertSame($sessions,QuoteCartProofDatabase::sessions($this->database,$this->prefix));
		$this->assert_lost_accept_effect_ack_publishes_only_original_completion();
	}

	/** Actual effect COMMIT, then fresh OS replay; staging-ACK proof above remains separate. */
	private function assert_lost_accept_effect_ack_publishes_only_original_completion():void {
		$masked=null;
		$s=$this->stack(static function($t)use(&$masked):void {
			$t->before=static function(string $sql,$transport)use(&$masked):void {
				if(null!==$masked||!str_starts_with($sql,'UPDATE ')||!str_contains($sql,'delivery_engine_delivery_quotes')||!str_contains($sql,"`state`='accepted'")){return;}
				$masked=$transport;$transport->fault_commit=$transport->commits+1;$transport->commit_fault='lost_ack';
			};
		});
		self::assertSame('review_required',$s->service->refresh(QuoteId::generate()->value(),1,$this->request())->shopper_facts()['status']);
		$original=$s->sessions->load(CartF::owner());
		self::assertSame(2,$original->generation());
		$command=\CetechDeliveryEngine\Application\DeliveryQuote\QuoteDurableCommand::accept(CartF::owner(),$original->reference(),$original->header(),null);
		self::assertSame('unconfirmed',$s->service->confirm(2,$this->request())->shopper_facts()['status']);
		self::assertNotNull($masked);
		self::assertSame($masked->fault_commit,$masked->sent_commits);
		self::assertSame(2,$masked->sent_commits);
		self::assertSame('lost_ack',$masked->commit_fault);
		$owner_index=array_search($masked,$s->factory->transports,true);
		self::assertNotFalse($owner_index);
		self::assertTrue($s->factory->sessions[$owner_index]->is_retired());
		$quotes_before=$this->rows('delivery_quotes');$events_before=$this->rows('operation_changes');$records_before=$this->rows('operation_records');$budget_before=$this->rows('delivery_quote_budget_windows');$bindings_before=$this->rows('delivery_quote_bindings');
		$matching=array_values(array_filter($records_before,static fn(array $row):bool=>$row['namespace_hash']===$command->identity->namespace_digest()));
		self::assertCount(1,$matching);$record_before=$matching[0];
		self::assertSame('1',$record_before['site_id']);
		self::assertSame('delivery_quote.accept',$record_before['operation']);
		self::assertSame($command->intent()->fingerprint(),$record_before['intent_hash']);
		self::assertSame(\CetechDeliveryEngine\Infrastructure\Persistence\WpdbOperationRecordRepository::target_hash($command->identity),$record_before['target_hash']);
		self::assertSame('accepted',$record_before['state']);self::assertSame('pending',$record_before['publication_state']);
		self::assertSame(['accepted','accepted'],array_column($quotes_before,'state'));
		$retry=$this->worker(['action'=>'retry','generation'=>2,'clock'=>Factory::NOW+1])->finish();
		self::assertSame('confirmed',$retry['status']);self::assertSame(2,$retry['generation']);self::assertSame(0,$retry['prepares']);
		self::assertNotSame(getmypid(),$retry['process_id']);self::assertSame(0,$retry['lock_timeouts']+$retry['deadlocks']);
		$quotes_after=$this->rows('delivery_quotes');$events_after=$this->rows('operation_changes');$records_after=$this->rows('operation_records');$budget_after=$this->rows('delivery_quote_budget_windows');$bindings_after=$this->rows('delivery_quote_bindings');
		require_once dirname(__DIR__,3).'/scripts/qualification/opening-quote-cart-support.php';
		$history_before=['operation_records'=>$records_before,'operation_changes'=>$events_before,'delivery_quotes'=>$quotes_before,'delivery_quote_bindings'=>$bindings_before,'delivery_quote_budget_windows'=>$budget_before];
		$history_after=['operation_records'=>$records_after,'operation_changes'=>$events_after,'delivery_quotes'=>$quotes_after,'delivery_quote_bindings'=>$bindings_after,'delivery_quote_budget_windows'=>$budget_after];
		self::assertSame(['no_second_quote_mutation_or_audit'=>true,'one_original_accept_publication_marker'=>true,'all_other_history_unchanged'=>true],\CetechQuoteCartFixture::accept_retry_delta($history_before,$history_after,$command));
		$changes=[];foreach($records_before as $index=>$before){$after=$records_after[$index]??[];foreach($before as $field=>$value){if(($after[$field]??null)!==$value){$changes[$before['id']][]=$field;}}}
		self::assertSame($quotes_before,$quotes_after);self::assertSame($events_before,$events_after);self::assertSame($budget_before,$budget_after);self::assertSame($bindings_before,$bindings_after);
		self::assertCount(count($records_before),$records_after);
		$record_after=array_values(array_filter($records_after,static fn(array $row):bool=>$row['namespace_hash']===$command->identity->namespace_digest()))[0];
		self::assertSame('published',$record_after['publication_state']);
		self::assertSame((int)$record_before['row_version']+1,(int)$record_after['row_version']);
		self::assertSame(gmdate('Y-m-d H:i:s',Factory::NOW+1).'.000000',$record_after['updated_at']);
		self::assertSame([$record_before['id']=>['publication_state','row_version','updated_at']],$changes);
		$stable_after=$records_after;foreach($stable_after as &$record){if($record['id']!==$record_before['id']){continue;}foreach(['publication_state','row_version','updated_at'] as $field){$record[$field]=$record_before[$field];}}unset($record);
		self::assertSame($records_before,$stable_after);
		$current=$s->sessions->load(CartF::owner());self::assertSame('confirmed',$current->phase());self::assertSame(2,$current->generation());self::assertSame($original->reference()->public_fields(),$current->reference()->public_fields());self::assertSame($original->header()->to_private_json(),$current->header()->to_private_json());
		$sessions_after=QuoteCartProofDatabase::sessions($this->database,$this->prefix);
		$again=$this->worker(['action'=>'retry','generation'=>2,'clock'=>Factory::NOW+2])->finish();self::assertSame('confirmed',$again['status']);self::assertSame(0,$again['prepares']);
		self::assertSame($records_after,$this->rows('operation_records'));self::assertSame($quotes_after,$this->rows('delivery_quotes'));self::assertSame($events_after,$this->rows('operation_changes'));self::assertSame($budget_after,$this->rows('delivery_quote_budget_windows'));self::assertSame($bindings_after,$this->rows('delivery_quote_bindings'));self::assertSame($sessions_after,QuoteCartProofDatabase::sessions($this->database,$this->prefix));
	}

}
