<?php

declare(strict_types=1);

namespace CetechDeliveryEngine\Tests\Unit\EmergencyControl;

require_once dirname( __DIR__ ) . '/Operation/OperationCoordinatorTest.php';

use CetechDeliveryEngine\Application\EmergencyControl\EmergencyControlCommand;
use CetechDeliveryEngine\Application\EmergencyControl\EmergencyControlService;
use CetechDeliveryEngine\Application\Operation\OperationStorageException;
use CetechDeliveryEngine\Domain\Contracts\RequestContext;
use CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState;
use CetechDeliveryEngine\Domain\Operation\OperationCommitResult;
use CetechDeliveryEngine\Domain\Operation\OperationConnectionFactory;
use CetechDeliveryEngine\Domain\Operation\OperationSession;
use CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore;
use CetechDeliveryEngine\Tests\Unit\Operation\CoordinatorFixtureFactory;
use CetechDeliveryEngine\Tests\Unit\Operation\CoordinatorFixtureReadiness;
use PHPUnit\Framework\TestCase;

/** Actual SQLite transactions test C03 atomic behavior, not native gap locking. */
final class ControlServiceTest extends TestCase {
	private string $path; private ControlUnitFactory $factory; private ControlUnitStore $store; private EmergencyControlService $service; private object $grant;
	protected function setUp(): void {
		$this->path = tempnam( sys_get_temp_dir(), 'emergency-unit-' ); $this->factory = new ControlUnitFactory( new CoordinatorFixtureFactory( $this->path ) ); $this->grant = (object) [ 'allowed' => true ]; $grant = $this->grant;
		$this->store = new ControlUnitStore( static fn (): bool => false ); $this->service = new EmergencyControlService( $this->factory, static fn ( int $site, int $actor ): bool => 1 === $site && 7 === $actor && $grant->allowed, $this->store, new CoordinatorFixtureReadiness(), trusted_equivalent_route: true );
		$db = $this->factory->native->inspection(); $db->exec( 'CREATE TABLE unit_delivery_engine_operation_records (id INTEGER PRIMARY KEY AUTOINCREMENT, site_id INTEGER NOT NULL, namespace_hash TEXT NOT NULL, intent_hash TEXT NOT NULL, namespace_format INTEGER NOT NULL, intent_format INTEGER NOT NULL, record_format INTEGER NOT NULL, operation TEXT NOT NULL, operation_version INTEGER NOT NULL, target_hash TEXT NOT NULL, state TEXT NOT NULL, publication_state TEXT NOT NULL, completion_json TEXT NULL, audit_id INTEGER NULL, row_version INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, completed_at TEXT NULL, UNIQUE(site_id,namespace_hash))' ); $db->exec( 'CREATE TABLE unit_delivery_engine_operation_changes (id INTEGER PRIMARY KEY AUTOINCREMENT, site_id INTEGER NOT NULL, operation_id INTEGER NOT NULL, event_format INTEGER NOT NULL, event_json TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(site_id,operation_id))' ); $db->exec( 'CREATE TABLE unit_options (option_id INTEGER PRIMARY KEY AUTOINCREMENT,option_name TEXT NOT NULL UNIQUE,option_value TEXT NOT NULL,autoload TEXT NOT NULL)' );
	}
	protected function tearDown(): void { foreach ( $this->factory->native->sessions as $s ) { $s->retire(); } unlink( $this->path ); }
	private function pause( string $token = 'ORIGINAL_PRIVATE_TOKEN', ?EmergencyControlState $opened = null ): array { return [ EmergencyControlCommand::identity( 1, 7, $token ), EmergencyControlCommand::payload( $opened ?? EmergencyControlState::absent( 1 ), 'checkout_suspended', 'operator_pause' ) ]; }
	private function attempt( array $pair ): \CetechDeliveryEngine\Domain\Operation\OperationAttemptResult { return $this->service->transition( $pair[0], $pair[1], RequestContext::create() ); }
	private function events(): int { return (int) $this->factory->native->inspection()->query( 'SELECT COUNT(*) FROM unit_delivery_engine_operation_changes' )->fetchColumn(); }
	private function options(): array { return $this->factory->native->inspection()->query( 'SELECT * FROM unit_options' )->fetchAll( \PDO::FETCH_ASSOC ); }
	public function test_absence_read_is_virtual_and_final_confirm_releases_before_return(): void { $read = $this->service->read( 1 ); self::assertTrue( $read->available ); self::assertSame( 1, $read->state->revision ); self::assertFalse( $read->state->initialized ); $locked = false; $final = $this->service->confirm_enabled( 1, 1, function () use ( &$locked ): bool { $locked = end( $this->factory->native->sessions )->in_transaction(); return true; } ); self::assertTrue( $locked ); self::assertTrue( $final->available ); self::assertSame( [], $this->options() ); self::assertSame( 0, $this->factory->native->commits ); self::assertTrue( end( $this->factory->native->sessions )->is_retired() ); }
	public function test_first_change_commits_state_event_and_completion_once(): void { $accepted = $this->attempt( $this->pause() ); self::assertSame( 'accepted', $accepted->outcome->state ); $state = $this->service->read( 1 )->state; self::assertSame( 2, $state->revision ); self::assertSame( 'checkout_suspended', $state->state ); self::assertSame( 'off', $this->options()[0]['autoload'] ); self::assertSame( 1, $this->events() ); $event = $this->factory->native->inspection()->query( 'SELECT event_json FROM unit_delivery_engine_operation_changes' )->fetchColumn(); self::assertStringNotContainsString( 'ORIGINAL_PRIVATE_TOKEN', $event ); self::assertStringNotContainsString( 'opened_bytes', $event ); $facts = json_decode( $event, true, 32, JSON_THROW_ON_ERROR ); self::assertSame( 1, $facts['before_revision'] ); self::assertSame( 2, $facts['after_revision'] ); }
	public function test_same_state_absence_completes_without_initializing_or_event(): void { $r = $this->service->transition( EmergencyControlCommand::identity( 1, 7, 'same' ), EmergencyControlCommand::payload( EmergencyControlState::absent( 1 ), 'enabled', 'resume_verified' ), RequestContext::create() ); self::assertSame( 'not_applicable', $r->outcome->state ); self::assertSame( [], $this->options() ); self::assertSame( 0, $this->events() ); self::assertFalse( $r->completion->result['initialized'] ); self::assertSame( 1, $r->completion->result['revision'] ); }
	public function test_corrupt_no_change_completion_is_unknown_without_disclosure_or_state_write(): void { $id = EmergencyControlCommand::identity( 1, 7, 'same' ); $p = EmergencyControlCommand::payload( EmergencyControlState::absent( 1 ), 'enabled', 'resume_verified' ); $this->service->transition( $id, $p, RequestContext::create() ); $db = $this->factory->native->inspection(); $raw = json_decode( $db->query( 'SELECT completion_json FROM unit_delivery_engine_operation_records' )->fetchColumn(), true, 32, JSON_THROW_ON_ERROR ); $raw['result']['revision'] = 7; $q = $db->prepare( 'UPDATE unit_delivery_engine_operation_records SET completion_json=?' ); $q->execute( [ json_encode( $raw, JSON_THROW_ON_ERROR ) ] ); $retry = $this->service->reconcile( $id, $p, RequestContext::create() ); self::assertSame( 'unconfirmed', $retry->outcome->state ); self::assertNull( $retry->completion ); self::assertSame( [], $this->options() ); self::assertSame( 0, $this->events() ); }
	public function test_original_replay_after_newer_opposite_change_never_restores_old_state(): void { $pause = $this->pause(); $first = $this->attempt( $pause ); $opened = $this->service->read( 1 )->state; $resume = $this->service->transition( EmergencyControlCommand::identity( 1, 7, 'resume' ), EmergencyControlCommand::payload( $opened, 'enabled', 'resume_verified' ), RequestContext::create() ); self::assertSame( 'accepted', $resume->outcome->state ); $before = $this->options(); $replay = $this->attempt( $pause ); self::assertTrue( $replay->replayed ); self::assertSame( $first->completion->to_json(), $replay->completion->to_json() ); self::assertSame( 'checkout_suspended', $replay->completion->result['state'] ); self::assertSame( 'enabled', $this->service->read( 1 )->state->state ); self::assertSame( 3, $this->service->read( 1 )->state->revision ); self::assertSame( $before, $this->options() ); self::assertSame( 2, $this->events() ); }
	public function test_changed_intent_and_stale_revision_have_no_second_effect(): void { $p = $this->pause(); $this->attempt( $p ); $changed = $p; $changed[1]['reason_code'] = 'incident_pause'; $conflict = $this->attempt( $changed ); self::assertSame( 'intent_conflict', $conflict->outcome->error->code ); $stale = $this->attempt( $this->pause( 'new-token' ) ); self::assertSame( 'stale_revision', $stale->outcome->error->code ); self::assertSame( 1, $this->events() ); self::assertSame( 2, $this->service->read( 1 )->state->revision ); }
	public function test_audit_refusal_rolls_back_physical_insert_and_allows_original_retry(): void { $this->factory->native->reject_audit = true; $p = $this->pause(); $failed = $this->attempt( $p ); self::assertSame( 'rejected', $failed->outcome->state ); self::assertSame( [], $this->options() ); self::assertSame( 0, $this->events() ); self::assertSame( 1, $this->service->read( 1 )->state->revision ); $accepted = $this->attempt( $p ); self::assertSame( 'accepted', $accepted->outcome->state ); self::assertSame( 1, $this->events() ); }
	public function test_unsent_and_lost_acknowledged_commit_are_distinct(): void { $p = $this->pause(); $this->factory->native->not_sent_at = 2; $failed = $this->attempt( $p ); self::assertSame( 'rejected', $failed->outcome->state ); self::assertSame( [], $this->options() ); $this->factory->native->lost_ack_at = $this->factory->native->commits + 2; $lost = $this->attempt( $p ); self::assertSame( 'unconfirmed', $lost->outcome->state ); self::assertNull( $lost->completion ); self::assertSame( 1, $this->events() ); $resolved = $this->service->reconcile( $p[0], $p[1], RequestContext::create() ); self::assertSame( 'accepted', $resolved->outcome->state ); self::assertTrue( $resolved->replayed ); self::assertSame( 1, $this->events() ); }
	public function test_failed_retirement_after_commit_is_unknown_until_fresh_reconcile(): void { $this->factory->retirement_ok = false; $p = $this->pause(); $unknown = $this->attempt( $p ); self::assertSame( 'unconfirmed', $unknown->outcome->state ); self::assertNull( $unknown->completion ); self::assertSame( 1, $this->events() ); $this->factory->retirement_ok = true; self::assertSame( 'accepted', $this->service->reconcile( $p[0], $p[1], RequestContext::create() )->outcome->state ); self::assertSame( 1, $this->events() ); }
	public function test_invalidating_cache_only_and_pending_retry_preserve_newer_value(): void { $calls = []; $fail = true; $store = new ControlUnitStore( static function ( string $name, string $group ) use ( &$calls, &$fail ): bool { $calls[] = [ $name, $group ]; if ( $fail ) { throw new \RuntimeException( 'PRIVATE_PROVIDER' ); } return false; } ); $service = new EmergencyControlService( $this->factory, static fn (): bool => true, $store, new CoordinatorFixtureReadiness(), trusted_equivalent_route: true ); $p = $this->pause(); $pending = $service->transition( $p[0], $p[1], RequestContext::create() ); self::assertTrue( $pending->outcome->mutation_accepted ); self::assertTrue( $pending->outcome->publication_pending ); $opened = $service->read( 1 )->state; $this->service->transition( EmergencyControlCommand::identity( 1, 7, 'newer' ), EmergencyControlCommand::payload( $opened, 'enabled', 'resume_verified' ), RequestContext::create() ); $before = $this->options(); $fail = false; $confirmed = $service->transition( $p[0], $p[1], RequestContext::create() ); self::assertSame( 'accepted', $confirmed->outcome->state ); self::assertTrue( $confirmed->replayed ); self::assertSame( $before, $this->options() ); self::assertSame( [ [ EmergencyControlStore::OPTION_NAME, 'options' ], [ EmergencyControlStore::OPTION_NAME, 'options' ], [ 'alloptions', 'options' ], [ 'notoptions', 'options' ] ], $calls ); self::assertSame( 2, $this->events() ); }
	public function test_revoked_grant_cannot_disclose_replay_or_open_connection(): void { $p = $this->pause(); $this->attempt( $p ); $opens = $this->factory->native->opens; $this->grant->allowed = false; $denied = $this->service->reconcile( $p[0], $p[1], RequestContext::create() ); self::assertSame( 'not_authorized', $denied->outcome->error->code ); self::assertNull( $denied->completion ); self::assertSame( $opens, $this->factory->native->opens ); }
	public function test_revision_pause_fact_change_and_uncertain_release_never_grant_final_read(): void { self::assertSame( 'stale_revision', $this->service->confirm_enabled( 1, 2 )->code ); self::assertSame( 'stale_revision', $this->service->confirm_enabled( 1, 1, static fn (): bool => false )->code ); $this->factory->retirement_ok = false; self::assertSame( 'outcome_unknown', $this->service->confirm_enabled( 1, 1 )->code ); $this->factory->retirement_ok = true; $this->attempt( $this->pause() ); self::assertSame( 'checkout_suspended', $this->service->confirm_enabled( 1, 2 )->code ); }
	public function test_wrong_site_and_ambient_owner_do_not_query_control(): void { $this->factory->native->site = 2; self::assertSame( 'not_authorized', $this->service->read( 1 )->code ); self::assertSame( 0, $this->factory->native->queries ); $this->factory->native->site = 1; $this->factory->native->ambient = true; self::assertFalse( $this->service->read( 1 )->available ); self::assertSame( 0, $this->factory->native->queries ); }
	public function test_readiness_failure_and_corrupt_state_never_become_default_enabled(): void { $this->store->ready = false; self::assertFalse( $this->service->read( 1 )->available ); $this->store->ready = true; $q = $this->factory->native->inspection()->prepare( 'INSERT INTO unit_options(option_name,option_value,autoload)VALUES(?,?,?)' ); $q->execute( [ EmergencyControlStore::OPTION_NAME, '{"unknown":"PRIVATE_TOKEN"}', 'off' ] ); $read = $this->service->read( 1 ); self::assertFalse( $read->available ); self::assertNull( $read->state ); self::assertStringNotContainsString( 'PRIVATE_TOKEN', json_encode( $read->error->to_array(), JSON_THROW_ON_ERROR ) ); self::assertCount( 1, $this->options() ); }
	public function test_existing_autoload_and_exact_byte_compare_are_preserved(): void { $bytes = ' ' . EmergencyControlState::record_json( 1, 'checkout_suspended', 2, 'operator_pause', 7, 1791300000 ) . ' '; $q = $this->factory->native->inspection()->prepare( 'INSERT INTO unit_options(option_name,option_value,autoload)VALUES(?,?,?)' ); $q->execute( [ EmergencyControlStore::OPTION_NAME, $bytes, 'on' ] ); $opened = $this->service->read( 1 )->state; $result = $this->service->transition( EmergencyControlCommand::identity( 1, 7, 'enable' ), EmergencyControlCommand::payload( $opened, 'enabled', 'resume_verified' ), RequestContext::create() ); self::assertSame( 'accepted', $result->outcome->state ); self::assertSame( 'on', $this->options()[0]['autoload'] ); self::assertSame( $opened->row_id, $this->service->read( 1 )->state->row_id ); }
	public function test_backward_time_and_revision_overflow_refuse_without_replacement(): void { foreach ( [ [ 2, 1891331200 ], [ PHP_INT_MAX, 1791300000 ] ] as [ $revision, $at ] ) { $db = $this->factory->native->inspection(); $db->exec( 'DELETE FROM unit_options' ); $q = $db->prepare( 'INSERT INTO unit_options(option_name,option_value,autoload)VALUES(?,?,?)' ); $q->execute( [ EmergencyControlStore::OPTION_NAME, EmergencyControlState::record_json( 1, 'enabled', $revision, 'resume_verified', 7, $at ), 'off' ] ); $opened = $this->service->read( 1 )->state; $before = $this->options(); $failed = $this->attempt( $this->pause( 'clock-' . $revision, $opened ) ); self::assertSame( 'temporarily_unavailable', $failed->outcome->error->code ); self::assertSame( $before, $this->options() ); } self::assertSame( 0, $this->events() ); }
}

final class ControlUnitStore extends EmergencyControlStore { public bool $ready = true; public function assert_ready( OperationSession $session, int $site ): void { if ( ! $this->ready || ! $session->in_transaction() || $session->site_id() !== $site ) { throw new OperationStorageException(); } $session->validate_tables( [ $this->options_table( $session ) ] ); } }
final class ControlUnitFactory implements OperationConnectionFactory { public bool $retirement_ok = true; public function __construct( public CoordinatorFixtureFactory $native ) {} public function open(): OperationSession { return new ControlUnitSession( $this->native->open(), $this ); } }
final class ControlUnitSession implements OperationSession {
	public function __construct( private OperationSession $inner, private ControlUnitFactory $factory ) {}
	public function site_id(): int { return $this->inner->site_id(); } public function table_prefix(): string { return $this->inner->table_prefix(); } public function charset_collate(): string { return $this->inner->charset_collate(); } public function begin(): bool { return $this->inner->begin(); } public function commit(): OperationCommitResult { return $this->inner->commit(); } public function rollback(): bool { return $this->inner->rollback(); } public function retire(): bool { $this->inner->retire(); return $this->factory->retirement_ok; } public function is_retired(): bool { return $this->inner->is_retired(); } public function in_transaction(): bool { return $this->inner->in_transaction(); } public function validate_tables( array $table_names ): bool { return $this->inner->validate_tables( $table_names ); } public function query( string $sql ): int|false { return $this->inner->query( $this->translate( $sql ) ); } public function get_row( string $sql ): array|null|false { return $this->inner->get_row( $this->translate( $sql ) ); } public function get_results( string $sql ): array|false { return $this->inner->get_results( $this->translate( $sql ) ); } public function prepare( string $sql, mixed ...$args ): string { return $this->inner->prepare( $sql, ...$args ); } public function errno(): int { return $this->inner->errno(); } public function insert_id(): int { return $this->inner->insert_id(); }
	private function translate( string $sql ): string { return str_replace( [ ' FORCE INDEX (`option_name`)', 'BINARY ', 'OCTET_LENGTH(' ], [ '', '', 'LENGTH(' ], $sql ); }
}
