<?php
/** Actual complete uninstall.php loader in fresh WP SHORTINIT; no Composer or Woo. */
declare(strict_types=1);
$result=['status'=>'FAIL','process_id'=>getmypid()];$phase='configuration';$uninstall_status='unreported';$uninstall_code='unreported';ob_start();
try {
 $path=$argv[1]??null;if(PHP_SAPI!=='cli'||'1'!==getenv('CETECH_DE_NATIVE_OPENING_QUALIFICATION')||!is_string($path)||!is_file($path)||is_link($path)||(fileperms($path)&0777)!==0600||filesize($path)>32768)throw new RuntimeException('P06 standalone private configuration absent.');
 $config=json_decode((string)file_get_contents($path),true,16,JSON_THROW_ON_ERROR);if(!is_array($config)||array_keys($config)!==['wp_load','plugin_root','domain_suffixes','domain_digest']||!is_string($config['wp_load'])||!is_file($config['wp_load'])||!str_ends_with($config['wp_load'],'/wp-load.php')||!is_string($config['plugin_root'])||!is_dir($config['plugin_root'])||!is_array($config['domain_suffixes'])||39!==count($config['domain_suffixes'])||!array_is_list($config['domain_suffixes'])||count(array_unique($config['domain_suffixes']))!==39||!is_string($config['domain_digest'])||1!==preg_match('/\A[a-f0-9]{64}\z/D',$config['domain_digest']))throw new RuntimeException('P06 standalone config invalid.');
 $phase='wordpress';define('SHORTINIT',true);define('WP_ADMIN',true);require $config['wp_load'];
 $phase='authority';if(!defined('DB_HOST')||1!==preg_match('/\A127\.0\.0\.1(?::[0-9]+)?\z/D',DB_HOST)||!defined('DB_NAME')||1!==preg_match('/\Acetech_wp_opening_qualification(?:_[a-z0-9]+)?\z/D',DB_NAME)||'1'!==(string)get_option('cetech_opening_qualification_disposable')||get_class($GLOBALS['wpdb'])!==wpdb::class||WP_Object_Cache::class!==get_class($GLOBALS['wp_object_cache'])||realpath($config['plugin_root'])!==realpath(WP_CONTENT_DIR.'/plugins/cetech-woocommerce-delivery-engine')||is_file(WP_CONTENT_DIR.'/object-cache.php')||is_file(WP_CONTENT_DIR.'/db.php'))throw new RuntimeException('P06 standalone native authority invalid.');
 $phase='roles';foreach(['class-wp-role.php','class-wp-roles.php','capabilities.php']as$file)require_once ABSPATH.WPINC.'/'.$file;$GLOBALS['wp_roles']=new WP_Roles();
 $snapshot=static function()use($config):array{global$wpdb;$out=[];foreach($config['domain_suffixes']as$suffix){if(!is_string($suffix)||1!==preg_match('/\A[a-z_]+\z/D',$suffix))throw new RuntimeException('P06 standalone suffix refused.');$rows=$wpdb->get_results('SELECT * FROM `'.$wpdb->prefix.'delivery_engine_'.$suffix.'` ORDER BY id LIMIT 20001',ARRAY_A);if(!is_array($rows)||count($rows)>20000||''!==$wpdb->last_error)throw new RuntimeException('P06 standalone physical snapshot absent.');$out[$suffix]=$rows;}return $out;};
 $phase='snapshot';$before=$snapshot();$hash=hash('sha256',json_encode($before,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));if($hash!==$config['domain_digest'])throw new RuntimeException('P06 standalone original snapshot differs.');
 $phase='uninstall';define('WP_UNINSTALL_PLUGIN','cetech-p06-owned-native-standalone');require $config['plugin_root'].'/uninstall.php';$status=json_decode((string)get_option('cetech_de_data_lifecycle_uninstall_status',''),true);$uninstall_status=in_array($status['status']??null,['completed','incomplete','refused','outcome_unknown'],true)?$status['status']:'unreported';$uninstall_code=in_array($status['code']??null,['completed','not_requested','storage_refused','active_cleanup','batch_incomplete','retained_unknown_cache','cache_publication_pending','outcome_unknown','intent_publication_pending','intent_removal_refused','status_unconfirmed'],true)?$status['code']:'unreported';$phase='observations';$completed='completed'===($status['status']??null)&&false===get_option('cetech_de_delete_data_on_uninstall',false);$isolated=!class_exists('Composer\\Autoload\\ClassLoader',false)&&!class_exists('WooCommerce',false);$exact=$before===$snapshot();
 $result=['status'=>$completed&&$isolated&&$exact?'PASS':'FAIL','process_id'=>getmypid(),'private_config_0600'=>true,'complete_standalone_loader'=>class_exists(CetechDeliveryEngine\Bootstrap\DataLifecycleUninstallExecutor::class,false),'no_composer_or_woocommerce'=>$isolated,'all39_business_stores_preserved'=>$exact,'uninstall_completed'=>$completed];
}catch(Throwable$error){$class=get_class($error);$result['error_class']=in_array($class,['Error','TypeError','RuntimeException','JsonException','ValueError','InvalidArgumentException','ParseError','ErrorException','mysqli_sql_exception'],true)?$class:'OtherThrowable';}
finally{$result['phase']=$phase;$result['uninstall_status']=$uninstall_status;$result['uninstall_code']=$uninstall_code;ob_end_clean();echo json_encode($result,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);}
