<?php
/** Separate source-derived P06 operational lifecycle receipt; every retained proof remains mandatory. */
declare(strict_types=1);
require_once __DIR__.'/opening-promise-operational-lifecycle-support.php';CetechPromiseOperationalLifecycle::guard();
if(13!==count($args))throw new RuntimeException('P06 lifecycle requires report, storage mode and eleven preceding primary receipts.');
$report_path=$args[0];$mode=$args[1];$prior_paths=array_slice($args,2);
if(!is_string($report_path)||!is_dir(dirname($report_path))||file_exists($report_path)||is_link($report_path)||!in_array($mode,['hpos_on','hpos_off'],true)||('hpos_on'===$mode)!==Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled())throw new RuntimeException('P06 lifecycle report allocation or storage authority differs.');
$source=(string)getenv('CETECH_DE_QUALIFICATION_HEAD');$candidate=(string)getenv('CETECH_DE_QUALIFICATION_CANDIDATE_HEAD');$tree=(string)getenv('CETECH_DE_QUALIFICATION_TREE');foreach([$source,$candidate,$tree]as$id)if(1!==preg_match('/\A[a-f0-9]{40}\z/D',$id))throw new RuntimeException('P06 immutable execution identity absent.');
$installed=dirname((string)(new ReflectionClass(CetechDeliveryEngine\Bootstrap\Plugin::class))->getFileName(),3);$map=CetechPromiseOperationalLifecycle::map($installed);$counts=['native'=>495,'cpt'=>20,'http'=>143,'p02'=>19,'p03'=>49,'p04_hpos'=>33,'p04_cpt'=>33,'p04_http'=>14,'p05_hpos'=>27,'p05_cpt'=>27,'p05_http'=>19];$priors=[];
foreach(array_combine(array_keys($counts),$prior_paths)as$kind=>$path){if(!is_string($path)||!is_file($path)||is_link($path)||filesize($path)>4194304)throw new RuntimeException('P06 preceding original receipt unavailable.');$prior=json_decode((string)file_get_contents($path),true,512,JSON_THROW_ON_ERROR);if(!is_array($prior)||'PASS'!==($prior['status']??null)||$source!==($prior['source_head']??null)||$candidate!==($prior['candidate_head']??null)||$tree!==($prior['source_tree']??null)||$map!==($prior['installed_php_sources']??null)||!is_array($prior['cases']??null)||$counts[$kind]!==count($prior['cases']))throw new RuntimeException('P06 preceding exact source/case identity differs.');foreach($prior['cases']as$case)if(!is_array($case)||'PASS'!==($case['status']??null))throw new RuntimeException('P06 cannot compensate for an incomplete retained case.');$priors[$kind]=['sha256'=>hash_file('sha256',$path),'cases'=>$counts[$kind]];}
$packages=['current'=>CetechPromiseOperationalLifecycle::package('CETECH_DE_P06_CURRENT_PACKAGE',$source,$map),'previous'=>CetechPromiseOperationalLifecycle::package('CETECH_DE_P06_PREDECESSOR_PACKAGE','543275af6844d649268f9ac02db518420dac9fe6'),'reader'=>CetechPromiseOperationalLifecycle::package('CETECH_DE_P06_READER_PACKAGE','3b57ffc53b64f485aa9ad30e2d9e5d424afc3468')];
global$wpdb;
$report=['format'=>'cetech-opening-promise-operational-lifecycle-v1','source_head'=>$source,'candidate_head'=>$candidate,'source_tree'=>$tree,'installed_php_sources'=>$map,'installed_php_sources_hash'=>CetechPromiseOperationalLifecycle::digest($map),'environment'=>['php'=>PHP_VERSION,'wordpress'=>get_bloginfo('version'),'woocommerce'=>WC_VERSION,'database_version'=>(string)$wpdb->get_var('SELECT VERSION()'),'hpos'=>(string)get_option('woocommerce_custom_orders_table_enabled'),'schema_before'=>(string)get_option('cetech_de_db_version'),'context'=>'Fresh native P06 sealed promise and original/current shipment operational lifecycle; complete marked disposable physical history','background_requests'=>'WP Cron disabled; Action Scheduler async request runner suppressed in this process'],'limits'=>['Disposable native HPOS/CPT qualification only; all eleven retained primary receipts remain separately mandatory.','The sealed fixture is authored by current candidate; code-only exact accepted P05 to current package transition preserves it. Schema11 remains11; no reverse migration.','Supported P04 rollback is an isolated forward historical reader with exact production autoload and old plugin writers unmounted; compatible base storage readiness is observed, P05 shipment capabilities are absent, and P05/unknown bytes are preserved.','No live activation, deployment, release, target-stack cache/payment/pilot certification or destructive retention grant.'],'preceding_receipts'=>$priors,'package_inputs'=>$packages,'status'=>'RUNNING','cases'=>[]];
$write=static function()use(&$report,$report_path):void{if(false===file_put_contents($report_path,json_encode($report,JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES)."\n"))throw new RuntimeException('P06 lifecycle receipt write refused.');};
$check=static function(string$id,bool$condition,array$evidence)use(&$report,$write):void{if(1!==preg_match('/\ANATIVE-W2P06-[A-Z0-9-]+\z/D',$id)||[]===$evidence)throw new RuntimeException('P06 case protocol invalid.');foreach($report['cases']as$case)if($case['id']===$id)throw new RuntimeException('P06 duplicate case refused.');foreach($evidence as$name=>$value)if(!is_string($name)||1!==preg_match('/\A[a-z0-9_]+\z/D',$name)||!is_bool($value))throw new RuntimeException('P06 boolean observation invalid.');$passed=$condition&&!in_array(false,$evidence,true);$report['cases'][]=['id'=>$id,'status'=>$passed?'PASS':'FAIL','evidence'=>$evidence];$write();echo'opening_promise_operational_lifecycle_case='.$id.' result='.($passed?'PASS':'FAIL').PHP_EOL;if(!$passed)throw new RuntimeException('P06 lifecycle case diverged.');};
$write();add_filter('action_scheduler_allow_async_request_runner','__return_false',PHP_INT_MAX);
try{$module=require __DIR__.'/opening-promise-operational-lifecycle.php';$module($check,$mode);$report['status']='PASS';$write();echo'opening_promise_operational_lifecycle_qualification=PASS mode='.$mode.' cases='.count($report['cases']).PHP_EOL;}
catch(Throwable$error){$report['status']='FAIL';$report['error']=['class'=>get_class($error)];$write();throw$error;}
