<?php

declare(strict_types=1);

use CetechDeliveryEngine\Application\DeliveryQuote\LegacyQuoteProviderStack;
use CetechDeliveryEngine\Application\DeliveryQuote\QuoteAdmissionAttempt;
use CetechDeliveryEngine\Application\DeliveryQuote\QuoteDurableService;
use CetechDeliveryEngine\Domain\Contracts\RequestContext;
use CetechDeliveryEngine\Domain\DeliveryQuote\QuoteOwner;
use CetechDeliveryEngine\Infrastructure\Persistence\DeliveryQuoteReadiness;
use CetechDeliveryEngine\Infrastructure\Persistence\TableNames;

/** Actual retained matcher and native selected Woo cart; internal adopter only. */
return static function ( callable $check ): void {
	global $wpdb;
	if ( '1' !== getenv( 'CETECH_DE_NATIVE_OPENING_QUALIFICATION' ) || ! defined( 'WP_ADMIN' ) || ! WP_ADMIN || '1' !== (string) get_option( 'cetech_opening_qualification_disposable' ) || ! defined( 'DB_HOST' ) || 1 !== preg_match( '/^127\.0\.0\.1(?::[0-9]+)?$/D', DB_HOST ) || ! defined( 'DB_NAME' ) || 1 !== preg_match( '/^cetech_wp_opening_qualification(?:_[a-z0-9]+)?$/D', DB_NAME ) || ! $wpdb instanceof wpdb || wpdb::class !== get_class( $wpdb ) || is_multisite() || WP_Object_Cache::class !== get_class( $GLOBALS['wp_object_cache'] ) || is_file( WP_CONTENT_DIR . '/object-cache.php' ) || is_file( WP_CONTENT_DIR . '/db.php' ) ) { throw new RuntimeException( 'Native Q04 proof requires the marked native default-cache fixture.' ); }
	foreach ( get_included_files() as $included ) { if ( str_ends_with( str_replace( '\\', '/', $included ), '/tests/bootstrap.php' ) ) { throw new RuntimeException( 'Unit bootstrap is forbidden in native provider proof.' ); } }
	require_once __DIR__ . '/opening-quote-provider-support.php';
	$fixture = new CetechNativeQuoteProviderFixture( $wpdb ); $failure = null;
	try {
		( new DeliveryQuoteReadiness( $wpdb ) )->assert_ready(); $fixture->install(); $native_sale = $fixture->native_sale_facts();
		$stack = new LegacyQuoteProviderStack( $fixture->factory );
		$preparation_phase = 'not_started';
		$prepare = static function () use ( $fixture, $stack, &$preparation_phase ) { $preparation_phase = 'native_context'; [ $context, $groups ] = $fixture->capture_input(); $preparation_phase = 'stack_preparation'; $result = $stack->prepare_current( $fixture->owner, $context, $groups ); $preparation_phase = 'complete'; return $result; };
		$refused = static function ( callable $operation ): bool { try { $operation(); return false; } catch ( InvalidArgumentException | RuntimeException ) { return true; } };
		$source_hooks = ( new ReflectionClass( CetechDeliveryEngine\Application\DeliveryQuote\LegacyQuoteSourceLocalBinding::class ) )->getConstant( 'HOOKS' ); $registered_source_hooks = []; foreach ( $source_hooks as $hook ) { if ( has_filter( $hook ) ) { $registered_source_hooks[] = $hook; } } $registered_source_tuples = $fixture::source_hook_diagnostics( $registered_source_hooks );
		$preparation_probes = $fixture->preparation_probes(); $owner_opens_before = count( $fixture->factory->sessions );
		$before = $fixture->history(); $prepared = null; $preparation_error = null; $native_refusal_line = null;
		try { $prepared = $prepare(); } catch ( Throwable $error ) { $preparation_error = get_class( $error ); $native_refusal_line = $fixture::native_refusal_line( $error ); }
		$check( 'NATIVE-W2Q04-ACTUAL-SELECTED-CART-CURRENT-MEMBER-CAPTURE', null !== $prepared && true === $native_sale['physical_price_is_regular20'] && true === $native_sale['native_view_price_is_sale15'] && true === $native_sale['scheduled_sale_started_in_real_past'] && true === $native_sale['scheduled_sale_has_no_future_end'] && 0 === $native_sale['owned_pending_sale_actions'] && (float) $prepared->terms()->private_facts()['groups'][0]['final']['amount'] === 7.0 && 2 === count( $prepared->context()->private_facts()['lines'] ) && 1 === count( $prepared->context()->private_facts()['groups'] ) && 'legacy_fixed_base_v1' === $prepared->provider()->code() && '11' === (string) get_option( 'cetech_de_db_version' ) && 1 === count( WC()->cart->get_shipping_methods() ) && $before === $fixture->history() && $fixture->factory->all_retired(), [ 'actual_wp_load' => defined( 'ABSPATH' ), 'actual_wc_cart_selected_rate' => 1 === count( WC()->cart->get_shipping_methods() ), 'native_default_cache' => WP_Object_Cache::class === get_class( $GLOBALS['wp_object_cache'] ), 'member_count' => null === $prepared ? null : count( $prepared->context()->private_facts()['lines'] ), 'current_uncached_source_preparer' => true, 'preparation_error_class' => $preparation_error, 'preparation_phase' => $preparation_phase, 'native_refusal_line' => $native_refusal_line, 'owned_session_open_delta' => count( $fixture->factory->sessions ) - $owner_opens_before, ...$preparation_probes, 'registered_source_hook_names' => $registered_source_hooks, 'registered_source_hook_tuples' => $registered_source_tuples, 'native_term_count_nested_callback_count' => $fixture::term_count_nested_callback_count(), 'owned_read_counters_include_global_wpdb' => false, 'source_read_queries' => $fixture->factory->source_reads, 'native_receipt_read_queries' => $fixture->factory->native_reads, 'preparation_has_no_durable_effect' => $before === $fixture->history(), 'all_owned_connections_retired' => $fixture->factory->all_retired(), 'synthetic_quote_context' => false, 'shopper_adoption' => false, 'physical_merchandise_price_is_regular20' => $native_sale['physical_price_is_regular20'], 'native_merchandise_view_price_is_sale15' => $native_sale['native_view_price_is_sale15'], 'native_sale_started_in_real_past' => $native_sale['scheduled_sale_started_in_real_past'], 'native_sale_has_no_future_end' => $native_sale['scheduled_sale_has_no_future_end'], 'owned_pending_sale_actions' => $native_sale['owned_pending_sale_actions'], 'delivery_tariff_still7' => null !== $prepared && (float) $prepared->terms()->private_facts()['groups'][0]['final']['amount'] === 7.0 ] );
		$group = $prepared->terms()->private_facts()['groups'][0];
		$check( 'NATIVE-W2Q04-FIXED-SHIPMENT-ONCE-NATIVE-MONEY', (float) $group['final']['amount'] === 7.0 && (float) $group['tax']['amount'] === 0.7 && (float) $group['total']['amount'] === 7.7 && (float) $group['native_money_receipt']['display_total']['amount'] === 7.7 && (float) WC()->cart->get_shipping_total() === 7.0 && (float) WC()->cart->get_shipping_tax() === 0.7, [ 'charge_type' => 'fixed_per_shipment', 'total_quantity' => 3, 'native_ex_tax' => $group['final']['amount'], 'native_tax' => $group['tax']['amount'], 'native_display_total' => $group['native_money_receipt']['display_total']['amount'] ] );
		$check( 'NATIVE-W2Q04-NO-FX-NO-DELIVERY-PROMOTION-VERIFIED', $prepared->context()->private_facts()['currency'] === [ 'base' => 'GHS', 'charged' => 'GHS', 'precision' => 2, 'presentment' => 'GHS' ] && 'none' === $group['promotion']['state'] && (float) $group['promotion']['amount']['amount'] === 0.0 && $group['promotion']['provider'] === [ 'code' => 'native_no_delivery_promotion_v1', 'version' => 1 ] && $group['list'] === $group['final'] && 'unavailable' === $group['cost']['state'] && 'not_recorded' === $group['route']['state'] && 'recorded' === $group['native_money_receipt']['state'] && 'recorded' === $group['native_tax_receipt']['state'], [ 'conversion_performed' => false, 'promotion_provider' => $group['promotion']['provider']['code'], 'delivery_promotion' => $group['promotion']['state'], 'cost_state' => $group['cost']['state'], 'native_tax_source' => $group['native_tax_receipt']['source'] ] );
		[ $paused_context, $paused_groups ] = $fixture->capture_input(); $control_name = CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore::OPTION_NAME; $original_control = get_option( $control_name, null ); $revision = is_string( $original_control ) ? (int) ( json_decode( $original_control, true )['revision'] ?? 1 ) : 1;
		foreach ( [ 'PAUSED' => CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState::record_json( $fixture->owner->site_id(), 'checkout_suspended', max( 2, $revision + 1 ), 'maintenance_pause', 1, time() ), 'UNKNOWN' => '{"format_version":1}' ] as $label => $control_bytes ) {
			$fixture->set_option( $control_name, $control_bytes ); $probe = new CetechNativeQuoteProviderEpochSource( $fixture ); $probe_stack = new LegacyQuoteProviderStack( $fixture->factory, new CetechDeliveryEngine\Application\DeliveryQuote\QuoteNativeReceiptCapture( $probe ) ); $queries_before = [ $fixture->factory->source_reads, $probe->captures ]; $closed_before = $fixture->history();
			$control_refused = $refused( static fn () => $probe_stack->prepare_current( $fixture->owner, $paused_context, $paused_groups ) ); $queries_after = [ $fixture->factory->source_reads, $probe->captures ];
			$check( 'NATIVE-W2Q04-' . $label . '-CURRENT-C07-REFUSES-PREPARATION-BEFORE-CAPTURE', $control_refused && $queries_before === $queries_after && $closed_before === $fixture->history() && $fixture->factory->all_retired(), [ 'current_control_refused' => $control_refused, 'source_read_delta' => $queries_after[0] - $queries_before[0], 'native_capture_call_delta' => $queries_after[1] - $queries_before[1], 'quote_counter_completion_event_history_unchanged' => $closed_before === $fixture->history(), 'all_owned_connections_retired' => $fixture->factory->all_retired(), 'fixture_control_setup_only' => true, 'preparation_budget_claimed' => false ] ); $fixture->restore_option( $control_name );
		}
		$epoch_source = new CetechNativeQuoteProviderEpochSource( $fixture, CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState::record_json( $fixture->owner->site_id(), 'enabled', max( 3, $revision + 2 ), 'resume_verified', 1, time() ) ); $epoch_stack = new LegacyQuoteProviderStack( $fixture->factory, new CetechDeliveryEngine\Application\DeliveryQuote\QuoteNativeReceiptCapture( $epoch_source ) ); $epoch_before = $fixture->history();
		$epoch_refused = $refused( static fn () => $epoch_stack->prepare_current( $fixture->owner, $paused_context, $paused_groups ) ); $changed_control = json_decode( (string) get_option( $control_name ), true ); $epoch_changed = is_array( $changed_control ) && 'enabled' === ( $changed_control['state'] ?? null ) && max( 3, $revision + 2 ) === ( $changed_control['revision'] ?? null );
		$check( 'NATIVE-W2Q04-CURRENT-C07-EPOCH-CHANGED-DURING-PREPARE-REFUSES', $epoch_refused && $epoch_changed && 1 === $epoch_source->captures && $epoch_before === $fixture->history() && $fixture->factory->all_retired(), [ 'actual_native_capture_calls' => $epoch_source->captures, 'enabled_revision_changed_after_actual_capture' => $epoch_changed, 'prepared_capture_returned' => ! $epoch_refused, 'durable_history_unchanged' => $epoch_before === $fixture->history(), 'all_owned_connections_retired' => $fixture->factory->all_retired(), 'fixture_epoch_change_only' => true ] ); $fixture->restore_option( $control_name );
		$fixture->physical_update( 'rate_cards', $fixture->rate, [ 'charge_type' => 'fixed_per_item' ] ); $fixture->cart(); $item = $prepare(); $item_group = $item->terms()->private_facts()['groups'][0];
		$check( 'NATIVE-W2Q04-FIXED-ITEM-ALL-MEMBER-QUANTITY', (float) $item_group['final']['amount'] === 21.0 && (float) WC()->cart->get_shipping_total() === 21.0 && (float) $item_group['tax']['amount'] === 2.1 && 2 === count( $item->context()->private_facts()['lines'] ), [ 'charge_type' => 'fixed_per_item', 'members' => 2, 'total_quantity' => 3, 'native_ex_tax' => $item_group['final']['amount'] ] );
		$fixture->physical_update( 'rate_cards', $fixture->rate, [ 'charge_type' => 'fixed_per_shipment', 'base_amount' => '0.0000' ] ); $fixture->cart(); $zero = $prepare(); $zero_group = $zero->terms()->private_facts()['groups'][0];
		$check( 'NATIVE-W2Q04-CONFIGURED-ZERO-IS-KNOWN-NATIVE-AMOUNT', (float) $zero_group['final']['amount'] === 0.0 && (float) $zero_group['tax']['amount'] === 0.0 && (float) $zero_group['native_money_receipt']['display_total']['amount'] === 0.0 && 'recorded' === $zero_group['native_money_receipt']['state'] && 'none' === $zero_group['promotion']['state'], [ 'configured_amount' => '0.0000', 'known_zero' => true, 'native_total' => $zero_group['native_money_receipt']['display_total']['amount'] ] );
		$fixture->physical_update( 'rate_cards', $fixture->rate, [ 'status' => 'inactive' ] ); $empty_before = $fixture->history(); $unknown = $refused( $prepare );
		$check( 'NATIVE-W2Q04-UNKNOWN-PRICE-REFUSES-WITHOUT-DURABLE-EFFECT', $unknown && 'inactive' === $fixture->row( 'rate_cards', $fixture->rate )['status'] && $empty_before === $fixture->history(), [ 'active_candidate_absent' => 'inactive' === $fixture->row( 'rate_cards', $fixture->rate )['status'], 'known_refusal' => $unknown, 'no_quote_counter_completion_or_event' => $empty_before === $fixture->history() ] );
		$fixture->physical_update( 'rate_cards', $fixture->rate, [ 'status' => 'active', 'base_amount' => '7.0000', 'supplier_id' => $fixture->alternate_supplier ] ); $scoped_before = $fixture->history(); $scoped = $refused( $prepare );
		$check( 'NATIVE-W2Q04-POSITIVE-SCOPED-CARD-ABSENT-REQUEST-REFUSES', $scoped && $scoped_before === $fixture->history(), [ 'absent_request_dimension' => 'supplier', 'positive_scoped_price_refused' => $scoped, 'durable_history_unchanged' => $scoped_before === $fixture->history() ] );
		$fixture->physical_update( 'rate_cards', $fixture->rate, [ 'supplier_id' => null ] );
		foreach ( $fixture->rules as $rule_id ) { $fixture->physical_update( 'product_delivery_rules', $rule_id, [ 'supplier_id' => $fixture->alternate_supplier, 'origin_id' => $fixture->alternate_origin, 'logistics_profile_id' => $fixture->alternate_profile ] ); } $fixture->cart(); $known = $prepare(); $known_group = $known->context()->private_facts()['groups'][0];
		$check( 'NATIVE-W2Q04-HOMOGENEOUS-KNOWN-DIMENSIONS-NATIVE-PRICE', 'known' === $known_group['origin']['state'] && 'known' === $known_group['supplier']['state'] && 'known' === $known_group['profile']['state'] && 2 === count( $known_group['line_keys'] ) && (float) $known->terms()->private_facts()['groups'][0]['final']['amount'] === 7.0 && $scoped_before === $fixture->history(), [ 'all_members_share_known_dimensions' => true, 'member_count' => count( $known_group['line_keys'] ), 'native_ex_tax' => $known->terms()->private_facts()['groups'][0]['final']['amount'], 'durable_history_unchanged' => $scoped_before === $fixture->history(), 'private_dimension_ids_disclosed' => false ] ); foreach ( $fixture->rules as $rule_id ) { $fixture->physical_update( 'product_delivery_rules', $rule_id, [ 'supplier_id' => null, 'origin_id' => null, 'logistics_profile_id' => null ] ); }
		foreach ( [ [ 'supplier_id', $fixture->alternate_supplier, 'SUPPLIER' ], [ 'origin_id', $fixture->alternate_origin, 'ORIGIN' ], [ 'logistics_profile_id', $fixture->alternate_profile, 'PROFILE' ] ] as [ $field, $value, $label ] ) {
			$fixture->physical_update( 'product_delivery_rules', $fixture->rules[1], [ $field => $value ] ); $fixture->cart(); $forward = $refused( $prepare ); $fixture->cart( true ); $reverse = $refused( $prepare );
			$check( 'NATIVE-W2Q04-MIXED-' . $label . '-BOTH-MEMBER-ORDERS-REFUSE', $forward && $reverse && $scoped_before === $fixture->history(), [ 'member_count' => 2, 'forward_refused' => $forward, 'reverse_refused' => $reverse, 'retained_grouping_rewritten' => false, 'durable_history_unchanged' => $scoped_before === $fixture->history() ] );
			$fixture->physical_update( 'product_delivery_rules', $fixture->rules[1], [ $field => null ] );
		}
		$fixture->physical_update( 'rate_cards', $fixture->rate, [ 'base_amount' => '0.1000' ] ); $fixture->set_option( 'woocommerce_tax_round_at_subtotal', 'no' ); $fixture->cart(); $per_line = $prepare()->terms()->private_facts()['groups'][0];
		$fixture->set_option( 'woocommerce_tax_round_at_subtotal', 'yes' ); $fixture->cart(); $subtotal = $prepare()->terms()->private_facts()['groups'][0];
		$check( 'NATIVE-W2Q04-NATIVE-PER-RATE-VERSUS-SUBTOTAL-ROUNDING', 2 === count( $per_line['native_tax_receipt']['rates'] ) && 2 === count( $subtotal['native_tax_receipt']['rates'] ) && (float) $per_line['tax']['amount'] === 0.01 && (float) $subtotal['tax']['amount'] === 0.01 && '0.02' === $per_line['native_tax_receipt']['rounded_tax']['amount'] && '0.01' === $subtotal['native_tax_receipt']['rounded_tax']['amount'] && '0.12' === $per_line['native_money_receipt']['display_total']['amount'] && '0.11' === $subtotal['native_money_receipt']['display_total']['amount'], [ 'native_rate_count' => count( $per_line['native_tax_receipt']['rates'] ), 'raw_tax' => $per_line['tax']['amount'], 'per_rate_rounded_tax' => $per_line['native_tax_receipt']['rounded_tax']['amount'], 'subtotal_rounded_tax' => $subtotal['native_tax_receipt']['rounded_tax']['amount'], 'native_tax_engine' => 'WC_Tax' ] );
		$fixture->physical_update( 'rate_cards', $fixture->rate, [ 'base_amount' => '7.0000' ] ); $fixture->set_option( 'woocommerce_tax_round_at_subtotal', 'no' ); $fixture->method_tax_status( 'none' ); $fixture->cart(); $none = $prepare()->terms()->private_facts()['groups'][0];
		$check( 'NATIVE-W2Q04-METHOD-TAX-STATUS-NONE-IS-NATIVE-AUTHORITY', 'none' === $none['native_tax_receipt']['tax_status'] && (float) $none['tax']['amount'] === 0.0 && [] === $none['native_tax_receipt']['rates'] && (float) WC()->cart->get_shipping_tax() === 0.0, [ 'native_method_tax_status' => $none['native_tax_receipt']['tax_status'], 'offer_tax_class_used_as_authority' => false, 'native_tax' => $none['tax']['amount'] ] );
		$fixture->method_tax_status( 'taxable' ); WC()->customer->set_is_vat_exempt( true ); $fixture->cart(); $exempt = $prepare()->terms()->private_facts()['groups'][0];
		$check( 'NATIVE-W2Q04-CURRENT-NATIVE-EXEMPTION-CHANGES-RECEIPT', true === $exempt['native_tax_receipt']['exempt'] && 'taxable' === $exempt['native_tax_receipt']['tax_status'] && (float) $exempt['tax']['amount'] === 0.0 && [] === $exempt['native_tax_receipt']['rates'], [ 'native_exempt' => $exempt['native_tax_receipt']['exempt'], 'native_tax' => $exempt['tax']['amount'] ] );
		WC()->customer->set_is_vat_exempt( false ); WC()->customer->set_shipping_state( 'BB' ); $fixture->cart(); $location = $prepare()->terms()->private_facts()['groups'][0];
		$check( 'NATIVE-W2Q04-CURRENT-NATIVE-TAX-LOCATION-CHANGES-RECEIPT', (float) $location['tax']['amount'] === 0.0 && $location['native_tax_receipt']['location_digest'] !== $group['native_tax_receipt']['location_digest'], [ 'native_location_digest_changed' => $location['native_tax_receipt']['location_digest'] !== $group['native_tax_receipt']['location_digest'], 'native_tax' => $location['tax']['amount'], 'raw_location_disclosed' => false ] );
		WC()->customer->set_shipping_state( 'AA' ); $fixture->cart();
		$change_shipping = static function ( array $rates ): array { foreach ( $rates as $rate ) { if ( $rate instanceof WC_Shipping_Rate ) { $rate->set_cost( (float) $rate->get_cost() + 1 ); } } return $rates; };
		add_filter( 'woocommerce_package_rates', $change_shipping, PHP_INT_MAX ); $fixture->cart(); $modified_shipping = (float) WC()->cart->get_shipping_total() !== 7.0; $effect_before = $fixture->history(); $shipping_refused = $refused( $prepare ); remove_filter( 'woocommerce_package_rates', $change_shipping, PHP_INT_MAX ); $fixture->cart();
		$check( 'NATIVE-W2Q04-THIRD-PARTY-SHIPPING-EFFECT-FAILS-CLOSED', $modified_shipping && $shipping_refused && $effect_before === $fixture->history(), [ 'native_rate_was_modified' => $modified_shipping, 'unsupported_effect_refused' => $shipping_refused, 'durable_history_unchanged' => $effect_before === $fixture->history() ] );
		WC()->cart->set_applied_coupons( [ 'q04-unrecognized-coupon-' . $fixture->suffix ] ); $coupon_present = 1 === count( WC()->cart->get_applied_coupons() ); $coupon_before = $fixture->history(); $coupon_refused = $refused( $prepare ); WC()->cart->set_applied_coupons( [] ); $fixture->cart();
		$check( 'NATIVE-W2Q04-UNVERIFIED-COUPON-CONTEXT-FAILS-CLOSED', $coupon_present && $coupon_refused && $coupon_before === $fixture->history(), [ 'native_coupon_context_present' => $coupon_present, 'unknown_coupon_effect_refused' => $coupon_refused, 'durable_history_unchanged' => $coupon_before === $fixture->history() ] );
		$foreign = static fn ( string $currency ): string => 'USD'; add_filter( 'woocommerce_currency', $foreign, PHP_INT_MAX ); $foreign_before = $fixture->history(); $foreign_refused = $refused( $prepare ); remove_filter( 'woocommerce_currency', $foreign, PHP_INT_MAX );
		$check( 'NATIVE-W2Q04-UNKNOWN-CURRENCY-EFFECT-HAS-NO-FX-FALLBACK', $foreign_refused && $foreign_before === $fixture->history(), [ 'unsupported_currency_effect_refused' => $foreign_refused, 'fx_fallback_used' => false, 'durable_history_unchanged' => $foreign_before === $fixture->history() ] );
		$fixture->cart(); $prepared = $prepare(); $context = $prepared->context(); $authority = static fn ( QuoteOwner $candidate, string $purpose ): bool => $fixture->owner->equals( $candidate ) && str_starts_with( $purpose, 'delivery_quote.' );
		$service = new QuoteDurableService( $fixture->factory, $prepared->registry(), $authority, evidence: $prepared->guard() ); $command = $prepared->command( 'native-q04-' . $fixture->suffix ); $fixture->track_command( $command ); $issued = $service->issue( $command, QuoteAdmissionAttempt::generate(), RequestContext::create() ); $fixture->track( $issued );
		$check( 'NATIVE-W2Q04-VERIFIED-NATIVE-PROVIDER-DURABLE-ISSUE', 'accepted' === $issued->attempt->outcome->state && null !== $issued->quote && null !== $issued->command?->reference() && $prepared->terms()->to_private_json() === $issued->quote?->terms()?->to_private_json(), [ 'outcome' => $issued->attempt->outcome->state, 'native_terms_exactly_persisted' => $prepared->terms()->to_private_json() === $issued->quote?->terms()?->to_private_json(), 'internal_adopter_only' => true ] );
		if ( null === $issued->quote || null === $issued->command?->reference() ) { throw new RuntimeException( 'Native Q04 owned durable quote is unavailable.' ); }
		$opened = $issued->quote; $reference = $issued->command->reference(); $body = $opened->row()['private_body_json']; $quote_table = TableNames::for( 'delivery_quotes' ); $quote_row = static fn (): array => $wpdb->get_row( $wpdb->prepare( "SELECT * FROM `{$quote_table}` WHERE quote_uuid=%s AND site_id=%d", $opened->header()->id()->value(), $fixture->owner->site_id() ), ARRAY_A ); $event_before = count( $fixture->history()['operation_changes'] );
		$new_card = $fixture->new_rate( [ 'priority' => 0, 'base_amount' => '9.0000', 'created_at' => gmdate( 'Y-m-d H:i:s' ), 'updated_at' => gmdate( 'Y-m-d H:i:s' ) ] ); $accept_stale = $service->accept( $fixture->owner, $reference, $opened->header(), $context, RequestContext::create() ); $fixture->track( $accept_stale ); $physical = $quote_row();
		$check( 'NATIVE-W2Q04-NEW-PRECEDENCE-CANDIDATE-REFUSES-ACCEPT-NO-REPRICE', 'rejected' === $accept_stale->attempt->outcome->state && 'issued' === $physical['state'] && $body === $physical['private_body_json'] && $event_before === count( $fixture->history()['operation_changes'] ), [ 'new_candidate_visible_to_current_fence' => true, 'accept_outcome' => $accept_stale->attempt->outcome->state, 'immutable_body_preserved' => $body === $physical['private_body_json'], 'material_event_repeated' => $event_before !== count( $fixture->history()['operation_changes'] ) ] ); $fixture->remove_entity( 'rate_cards', $new_card );
		foreach ( [ [ 'ROUTE-FLAG', static fn () => $fixture->set_option( 'cetech_de_enable_effective_configuration_runtime', 1 ), static fn () => $fixture->set_option( 'cetech_de_enable_effective_configuration_runtime', 0 ) ], [ 'GEOGRAPHY', static fn () => $fixture->physical_update( 'destination_zones', $fixture->zone, [ 'priority' => 2 ] ), static fn () => $fixture->physical_update( 'destination_zones', $fixture->zone, [ 'priority' => 1 ] ) ], [ 'OFFER', static fn () => $fixture->physical_update( 'delivery_offers', $fixture->offer, [ 'service_level' => 'express' ] ), static fn () => $fixture->physical_update( 'delivery_offers', $fixture->offer, [ 'service_level' => 'standard' ] ) ] ] as [ $label, $mutate, $restore ] ) {
			$fixture->warm_sources(); $mutate(); $read = $service->current( $fixture->owner, $reference, $context, RequestContext::create() ); $physical = $quote_row();
			$check( 'NATIVE-W2Q04-WARM-' . $label . '-SOURCE-CURRENT-REFUSAL', 'unavailable' === $read->status && null === $read->quote && $body === $physical['private_body_json'] && $event_before === count( $fixture->history()['operation_changes'] ), [ 'native_sources_prewarmed' => true, 'current_read_status' => $read->status, 'private_quote_disclosed' => null !== $read->quote, 'immutable_body_preserved' => $body === $physical['private_body_json'], 'current_read_has_no_material_event' => $event_before === count( $fixture->history()['operation_changes'] ) ] ); $restore();
		}
		$fixture->warm_sources(); $stock = $wpdb->get_results( $wpdb->prepare( "SELECT meta_id,post_id,meta_key,meta_value FROM `{$wpdb->postmeta}` WHERE post_id=%d AND meta_key IN ('_stock','_stock_status','_backorders') ORDER BY meta_id", $fixture->products[0] ), ARRAY_A ); $wpdb->update( $wpdb->postmeta, [ 'meta_value' => '0' ], [ 'post_id' => $fixture->products[0], 'meta_key' => '_stock' ] ); $inventory_read = $service->current( $fixture->owner, $reference, $context, RequestContext::create() ); $physical = $quote_row();
		$check( 'NATIVE-W2Q04-WARM-INVENTORY-PHYSICAL-EDIT-CURRENT-REFUSAL', 'unavailable' === $inventory_read->status && null === $inventory_read->quote && $body === $physical['private_body_json'] && $event_before === count( $fixture->history()['operation_changes'] ), [ 'native_product_cache_prewarmed' => true, 'physical_stock_edited_without_cache_invalidation' => true, 'current_read_status' => $inventory_read->status, 'immutable_body_preserved' => $body === $physical['private_body_json'] ] ); foreach ( $stock as $row ) { $wpdb->update( $wpdb->postmeta, [ 'meta_value' => $row['meta_value'] ], [ 'meta_id' => (int) $row['meta_id'] ] ); }
		$accepted = $service->accept( $fixture->owner, $reference, $opened->header(), $context, RequestContext::create() ); $fixture->track( $accepted ); $accepted_history = $fixture->history(); $replay = $service->accept( $fixture->owner, $reference, $opened->header(), $context, RequestContext::create() ); $fixture->track( $replay );
		$check( 'NATIVE-W2Q04-SAME-NATIVE-OPENED-TERMS-ACCEPT-AND-REPLAY', 'accepted' === $accepted->attempt->outcome->state && 'accepted' === $replay->attempt->outcome->state && $replay->attempt->replayed && $accepted->attempt->completion?->to_json() === $replay->attempt->completion?->to_json() && $body === $quote_row()['private_body_json'] && $accepted_history === $fixture->history(), [ 'accept_outcome' => $accepted->attempt->outcome->state, 'replayed' => $replay->attempt->replayed, 'original_body_immutable' => $body === $quote_row()['private_body_json'], 'exact_completion' => $accepted->attempt->completion?->to_json() === $replay->attempt->completion?->to_json(), 'history_unchanged_on_replay' => $accepted_history === $fixture->history() ] );
		$fixture->variation_cart(); $variation_prepared = $prepare(); $variation_service = new QuoteDurableService( $fixture->factory, $variation_prepared->registry(), $authority, evidence: $variation_prepared->guard() ); $variation_command = $variation_prepared->command( 'native-q04-reparent-' . $fixture->suffix ); $fixture->track_command( $variation_command ); $variation_issue = $variation_service->issue( $variation_command, QuoteAdmissionAttempt::generate(), RequestContext::create() ); $fixture->track( $variation_issue );
		if ( 'accepted' !== $variation_issue->attempt->outcome->state || null === $variation_issue->quote || null === $variation_issue->command?->reference() ) { throw new RuntimeException( 'Native Q04 variation quote issuance failed.' ); } $variation_body = $variation_issue->quote->row()['private_body_json']; wc_get_product( $fixture->variation_id ); $variation_events = count( $fixture->history()['operation_changes'] ); $changed = $wpdb->update( $wpdb->posts, [ 'post_parent' => $fixture->alternate_parent ], [ 'ID' => $fixture->variation_id ] ); $variation_read = $variation_service->current( $fixture->owner, $variation_issue->command->reference(), $variation_prepared->context(), RequestContext::create() ); $stored_variation = $wpdb->get_row( $wpdb->prepare( "SELECT private_body_json FROM `{$quote_table}` WHERE quote_uuid=%s AND site_id=%d", $variation_issue->quote->header()->id()->value(), $fixture->owner->site_id() ), ARRAY_A ); $current_parent = (int) $wpdb->get_var( $wpdb->prepare( "SELECT post_parent FROM `{$wpdb->posts}` WHERE ID=%d", $fixture->variation_id ) );
		$check( 'NATIVE-W2Q04-WARM-VARIATION-REPARENT-CURRENT-REFUSAL', 1 === $changed && $current_parent === $fixture->alternate_parent && 'unavailable' === $variation_read->status && null === $variation_read->quote && $variation_body === $stored_variation['private_body_json'] && $variation_events === count( $fixture->history()['operation_changes'] ), [ 'actual_native_variation' => true, 'native_product_cache_prewarmed' => true, 'physical_parent_changed_without_cache_invalidation' => 1 === $changed, 'current_read_status' => $variation_read->status, 'immutable_body_preserved' => $variation_body === $stored_variation['private_body_json'], 'current_read_has_no_material_event' => $variation_events === count( $fixture->history()['operation_changes'] ) ] ); $wpdb->update( $wpdb->posts, [ 'post_parent' => $fixture->variation_parent ], [ 'ID' => $fixture->variation_id ] );
	} catch ( Throwable $error ) { $failure = $error; throw $error; }
	finally {
		$cleanup = [ 'cleanup_restored' => false ]; try { $cleanup = $fixture->cleanup(); } catch ( Throwable $cleanup_error ) { $cleanup['cleanup_stage'] = $fixture->cleanup_stage(); $cleanup['cleanup_error_class'] = get_class( $cleanup_error ); }
		if ( null === $failure ) { $check( 'NATIVE-W2Q04-OWNED-NATIVE-PROVIDER-FIXTURE-CLEANUP', true === $cleanup['cleanup_restored'], $cleanup ); } else { try { $check( 'NATIVE-W2Q04-OWNED-NATIVE-PROVIDER-FIXTURE-CLEANUP', true === $cleanup['cleanup_restored'], $cleanup ); } catch ( Throwable ) {} }
	}
};
