<?php
declare(strict_types=1);
use CetechDeliveryEngine\Domain\Contracts\RequestContext;
use CetechDeliveryEngine\Domain\ServicePromise\Persistence\PromiseVersionCommand;
use CetechDeliveryEngine\Domain\ServicePromise\PromiseJson;
use CetechDeliveryEngine\Application\DeliveryQuote\PromiseQuotePlacementActivation;
use CetechDeliveryEngine\Integrations\ServicePromise\Configuration\NativePromiseConfigurationAuthority;

/** Actual installed native configuration, separate from every retained P01-P04 proof. */
return static function(callable $check,string $mode='hpos_on'):void {
 global $wpdb;
 if('1'!==getenv('CETECH_DE_NATIVE_OPENING_QUALIFICATION')||!defined('WP_ADMIN')||true!==WP_ADMIN||'1'!==(string)get_option('cetech_opening_qualification_disposable')||!$wpdb instanceof wpdb||wpdb::class!==get_class($wpdb)||is_multisite()||('hpos_on'===$mode)!==Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled())throw new RuntimeException('P05 requires the exact marked native fixture.');
 require_once __DIR__.'/opening-promise-native-configuration-support.php';
 $fixture=null;$failure=null;$cleanup=['tracked_sources_restored'=>true,'all_connections_retired'=>true,'native_actor_restored'=>true];
 $refuses=static function(callable $work):bool {try{$work();return false;}catch(Throwable){return true;}};
 try {
  $check('NATIVE-W2P05-MARKED-INSTALLED-NATIVE-ENVIRONMENT',defined('ABSPATH')&&class_exists(WC_Order::class)&&'11'===(string)get_option('cetech_de_db_version'),['real_wp_load'=>defined('ABSPATH'),'native_woo_crud'=>class_exists(WC_Order::class),'schema11_forward_storage'=>'11'===(string)get_option('cetech_de_db_version')]);
  $fixture=new CetechPromiseNativeConfigurationFixture($wpdb);$calendar=$fixture->calendar();$policy=$fixture->policy($calendar);
  $check('NATIVE-W2P05-TRUSTED-NATIVE-ADMIN-AUTHORITY',$fixture->service->can_access()&&1===get_current_user_id()&&current_user_can('manage_delivery_settings'),['native_current_admin'=>1===get_current_user_id(),'native_capability_checked'=>current_user_can('manage_delivery_settings'),'site_binding_native'=>$fixture->binding->site_id()===get_current_blog_id()]);
  $create_payload=$fixture->payload('create',$calendar);$token=RequestContext::create()->request_id;$create=$fixture->command('create',$create_payload,$token);$once=$fixture->version_rows();$replay=$fixture->command('create',$create_payload,$token);$reconcile=$fixture->command('create',$create_payload,$token,true);
  $check('NATIVE-W2P05-ACTUAL-CALENDAR-CREATE-ORIGINAL-REPLAY','accepted'===$create->outcome->state&&'accepted'===$replay->outcome->state&&'accepted'===$reconcile->outcome->state&&$once===$fixture->version_rows(),['native_command_accepted'=>'accepted'===$create->outcome->state,'original_replay_accepted'=>'accepted'===$replay->outcome->state,'original_reconcile_accepted'=>'accepted'===$reconcile->outcome->state,'single_immutable_version'=>$once===$fixture->version_rows()&&1===count($once),'server_derived_author'=>1===(int)$once[0]['author_user_id']]);
  $forged=$create_payload;$forged['author_user_id']=99;$bad_identity=$refuses(fn()=>$fixture->service->version($fixture->binding,'promise.version.create',RequestContext::create()->request_id,$forged));
  $check('NATIVE-W2P05-CALLER-AUTHOR-FIELD-REFUSED',$bad_identity&&$once===$fixture->version_rows(),['closed_payload_excludes_author'=>$bad_identity,'physical_body_unchanged'=>$once===$fixture->version_rows(),'no_second_version'=>1===count($fixture->version_rows())]);
  $seal_payload=$fixture->payload('seal',$calendar);$sealed=$fixture->command('seal',$seal_payload);$published=$fixture->command('publish',$fixture->payload('publish',$calendar));$row=$fixture->version_rows()[0];
  $check('NATIVE-W2P05-ACTUAL-CALENDAR-SEAL-PUBLISH-IMMUTABLE-BODY','accepted'===$sealed->outcome->state&&'accepted'===$published->outcome->state&&'published'===$row['state']&&$row['body_json']===$calendar->to_private_json(),['native_seal_accepted'=>'accepted'===$sealed->outcome->state,'native_publish_accepted'=>'accepted'===$published->outcome->state,'published_original_bytes'=>$row['body_json']===$calendar->to_private_json(),'acknowledged_publication_receipt'=>is_string($row['publication_receipt_digest'])&&64===strlen($row['publication_receipt_digest'])]);
  $policy_create=$fixture->command('create',$fixture->payload('create',$policy));$policy_seal=$fixture->command('seal',$fixture->payload('seal',$policy));$policy_publish=$fixture->command('publish',$fixture->payload('publish',$policy));$policy_rows=$fixture->version_rows();
  $check('NATIVE-W2P05-ACTUAL-POLICY-CREATE-SEAL-PUBLISH','accepted'===$policy_create->outcome->state&&'accepted'===$policy_seal->outcome->state&&'accepted'===$policy_publish->outcome->state,['native_create_accepted'=>'accepted'===$policy_create->outcome->state,'native_seal_accepted'=>'accepted'===$policy_seal->outcome->state,'native_publish_accepted'=>'accepted'===$policy_publish->outcome->state,'two_exact_immutable_bodies'=>2===count($policy_rows)]);
  $preview=$fixture->service->preview($fixture->binding,$policy->to_private_json(),[$calendar->private_facts()]);$preview_json=PromiseJson::encode($preview);$public_only=!str_contains($preview_json,'source_id')&&!str_contains($preview_json,'policy_id')&&!str_contains($preview_json,'principal_hash')&&!str_contains($preview_json,'material_digest');
  $check('NATIVE-W2P05-PREVIEW-HYPOTHETICAL-SAFE-NO-AUTHORITY',true===$preview['hypothetical']&&false===$preview['admission']&&[]!==$preview['views']&&$public_only&&$policy_rows===$fixture->version_rows(),['explicit_hypothetical'=>true===$preview['hypothetical'],'no_admission'=>false===$preview['admission'],'shared_calculator_relative_view'=>'relative_window'===$preview['views'][0]['state'],'private_fields_excluded'=>$public_only,'preview_writes_no_policy'=>$policy_rows===$fixture->version_rows()]);
  $formatter=new CetechDeliveryEngine\Application\ServicePromise\Presentation\PublicPromiseFormatter();$relative_text=$formatter->text(CetechDeliveryEngine\Domain\ServicePromise\PublicPromiseView::from_array($preview['views'][0]));
  $absolute_policy=$fixture->policy($calendar,1,['anchor'=>'order_accepted','late_payment_rule'=>'refuse_if_infeasible']);$absolute_preview=$fixture->service->preview($fixture->binding,$absolute_policy->to_private_json(),[$calendar->private_facts()]);$absolute_text=$formatter->text(CetechDeliveryEngine\Domain\ServicePromise\PublicPromiseView::from_array($absolute_preview['views'][0]));
  $check('NATIVE-W2P05-RELATIVE-ABSOLUTE-TRUTHFUL-NATIVE-PRESENTATION','relative_window'===$preview['views'][0]['state']&&'absolute_window'===$absolute_preview['views'][0]['state']&&str_contains($relative_text,'after payment confirmation')&&str_contains($absolute_text,'UTC'),['actual_relative_preview_state'=>'relative_window'===$preview['views'][0]['state'],'relative_payment_anchor_visible'=>str_contains($relative_text,'after payment confirmation'),'actual_absolute_preview_state'=>'absolute_window'===$absolute_preview['views'][0]['state'],'absolute_display_zone_visible'=>str_contains($absolute_text,'UTC'),'hypothetical_both_without_admission'=>false===$preview['admission']&&false===$absolute_preview['admission']]);
  $unavailable_preview=$fixture->service->preview($fixture->binding,$policy->to_private_json(),[]);$unavailable_view=CetechDeliveryEngine\Domain\ServicePromise\PublicPromiseView::from_array($unavailable_preview['views'][0]);$unavailable_text=$formatter->text($unavailable_view);
  $check('NATIVE-W2P05-UNAVAILABLE-PREVIEW-NEVER-INVENTS-A-WINDOW','unavailable'===$unavailable_view->fields()['state']&&!isset($unavailable_view->fields()['from'])&&!isset($unavailable_view->fields()['min']),['actual_missing_immutable_calendar'=>'unavailable'===$unavailable_view->fields()['state'],'no_absolute_or_relative_winner'=>!isset($unavailable_view->fields()['from'])&&!isset($unavailable_view->fields()['min']),'honest_unavailable_text'=>str_contains($unavailable_text,'unavailable'),'no_checkout_admission'=>false===$unavailable_preview['admission']]);
  $native_translation=static fn(string $translated,string $source,string $domain):string=>'cetech-woocommerce-delivery-engine'===$domain&&'%1$s %2$s after payment confirmation (%3$s)'===$source?'%1$s %2$s après confirmation du paiement (%3$s)':$translated;add_filter('gettext',$native_translation,10,3);try{$localized=$formatter->text(CetechDeliveryEngine\Domain\ServicePromise\PublicPromiseView::from_array($preview['views'][0]));}finally{remove_filter('gettext',$native_translation,10);}
  $check('NATIVE-W2P05-NATIVE-LOCALIZATION-RETAINS-STRUCTURED-PROMISE',str_contains($localized,'après confirmation du paiement')&&str_contains($localized,'60–120')&&str_contains($localized,'UTC'),['actual_native_gettext_filter_used'=>str_contains($localized,'après confirmation du paiement'),'original_duration_range_visible'=>str_contains($localized,'60–120'),'original_display_zone_visible'=>str_contains($localized,'UTC'),'immutable_published_body_unmodified'=>$policy_rows===$fixture->version_rows()]);
  $inspection=$fixture->service->inspect_version($fixture->binding,'policy',$policy->reference()->policy_id(),1,['kind'=>'global','target_id'=>0]);
  $check('NATIVE-W2P05-AUTHORIZED-EXACT-HISTORICAL-EDITOR-READ','published'===($inspection['version']['state']??null)&&$policy->to_private_json()===($inspection['version']['body_json']??null),['native_read_authorized'=>'published'===($inspection['version']['state']??null),'exact_original_policy_bytes'=>$policy->to_private_json()===($inspection['version']['body_json']??null),'stored_revision_present'=>is_int($inspection['object_revision'])&&$inspection['object_revision']>0]);
  $next=$fixture->calendar(2);$stale_payload=$fixture->payload('create',$next);$new=$fixture->command('create',$stale_payload);$changed_token=RequestContext::create()->request_id;$stale=$fixture->command('create',$stale_payload,$changed_token);$current_rows=$fixture->version_rows();
  $check('NATIVE-W2P05-STALE-CAS-CANNOT-DUPLICATE-VERSION','accepted'===$new->outcome->state&&'accepted'!==$stale->outcome->state&&3===count($current_rows),['first_contender_accepted'=>'accepted'===$new->outcome->state,'stale_contender_refused'=>'accepted'!==$stale->outcome->state,'one_new_version'=>3===count($current_rows),'published_v1_body_preserved'=>$calendar->to_private_json()===$current_rows[0]['body_json']]);
  $scoped=$fixture->scoped_native_actors();wp_set_current_user($scoped['editor']);$scoped_id=$fixture->authority->identity($fixture->binding,'promise.preview','native-scoped-preview',RequestContext::create()->request_id);$own_allowed=$fixture->authority->authorize($scoped_id,$fixture->binding,['kind'=>'product','target_id'=>$scoped['owned']],0);$other_denied=!$fixture->authority->authorize($scoped_id,$fixture->binding,['kind'=>'product','target_id'=>$scoped['foreign']],0);$global_denied=!$fixture->authority->authorize($scoped_id,$fixture->binding,['kind'=>'global','target_id'=>0],0);
  $check('NATIVE-W2P05-NATIVE-PRODUCT-SCOPE-DOES-NOT-BECOME-GLOBAL-AUTHORITY',$own_allowed&&$other_denied&&$global_denied,['actual_own_product_edit_granted'=>$own_allowed,'actual_foreign_product_edit_denied'=>$other_denied,'global_policy_read_denied'=>$global_denied,'native_current_editor_principal'=>get_current_user_id()===$scoped['editor']]);
  wp_set_current_user($scoped['editor']);$scope_replacement=$fixture->policy($calendar,2,['scope'=>['kind'=>'product','target_id'=>$scoped['owned']]]);$scope_payload=$fixture->payload('create',$scope_replacement);$scope_attempt=$fixture->command('create',$scope_payload);wp_set_current_user(1);
  $check('NATIVE-W2P05-LOCKED-GLOBAL-LOGICAL-OBJECT-CANNOT-BE-SCOPE-TAKEN-OVER','accepted'!==$scope_attempt->outcome->state&&$current_rows===$fixture->version_rows(),['native_own_product_grant_present'=>$own_allowed,'different_scope_existing_head_refused'=>'accepted'!==$scope_attempt->outcome->state,'original_published_global_body_preserved'=>$current_rows===$fixture->version_rows(),'no_native_scope_substitution'=>$current_rows===$fixture->version_rows()]);
  wp_set_current_user($scoped['editor']);$parent_allowed=$fixture->authority->authorize($scoped_id,$fixture->binding,['kind'=>'variation','target_id'=>$scoped['variation']],0);wp_set_current_user(1);wp_update_post(['ID'=>$scoped['parent'],'post_author'=>$scoped['other']]);clean_post_cache($scoped['parent']);wp_set_current_user($scoped['editor']);$parent_denied=!$fixture->authority->authorize($scoped_id,$fixture->binding,['kind'=>'variation','target_id'=>$scoped['variation']],0);wp_set_current_user(1);
  $check('NATIVE-W2P05-VARIATION-REQUIRES-ACTUAL-PARENT-PERMISSION',$parent_allowed&&$parent_denied,['actual_owned_variation_and_parent_allowed'=>$parent_allowed,'actual_parent_permission_revocation_denied'=>$parent_denied,'unchanged_variation_parent_identity'=>wc_get_product($scoped['variation'])->get_parent_id()===$scoped['parent'],'no_global_fallback'=>$global_denied]);
  $shipment_module=require __DIR__.'/opening-promise-native-configuration-shipment.php';$shipment_module($check,$mode);
  wp_set_current_user(0);$guest_denied=!$fixture->authority->can_access()&&$refuses(fn()=>$fixture->service->preview($fixture->binding,$policy->to_private_json(),[$calendar->private_facts()]));wp_set_current_user(1);
  $check('NATIVE-W2P05-GUEST-PRIVATE-CONFIGURATION-REFUSED',$guest_denied&&$current_rows===$fixture->version_rows(),['native_guest_no_access'=>$guest_denied,'private_preview_denied'=>$guest_denied,'physical_history_unchanged'=>$current_rows===$fixture->version_rows()]);
 }catch(Throwable $error){$failure=$error;throw $error;}finally {
  if(null!==$fixture){try{$cleanup=$fixture->cleanup();}catch(Throwable){foreach($cleanup as &$value)$value=false;unset($value);}}
  try{$check('NATIVE-W2P05-TRACKED-NATIVE-CONFIGURATION-CLEANUP',!in_array(false,$cleanup,true),['exact_tracked_sources_restored'=>$cleanup['tracked_sources_restored'],'all_owned_connections_retired'=>$cleanup['all_connections_retired'],'original_native_actor_restored'=>$cleanup['native_actor_restored']]);}catch(Throwable $cleanup_error){if(null===$failure)throw $cleanup_error;}
 }
};
