<?php
/** P06 native sealed promise + original/current shipment through actual lifecycle entry points. */
declare(strict_types=1);
use CetechDeliveryEngine\Application\Order\{OrderDeliverySnapshot,OrderDeliverySnapshotReader,DeliveryQuoteSnapshotEnvelope,QuoteNativeOrderHistory};
use CetechDeliveryEngine\Application\Shipment\ShipmentService;
use CetechDeliveryEngine\Bootstrap\{DataLifecycleManifest,Plugin};
use CetechDeliveryEngine\Domain\Contracts\{OperationIdentity,RequestContext};
use CetechDeliveryEngine\Domain\ServicePromise\Shipment\{ShipmentCurrentPromise,ShipmentPromiseCommand};
use CetechDeliveryEngine\Domain\Shipment\ShipmentRepositoryInterface;
use CetechDeliveryEngine\Infrastructure\Persistence\TableNames;
use CetechDeliveryEngine\Integrations\ServicePromise\Shipment\NativeShipmentPromiseRuntime;

return static function(callable $check,string $mode='hpos_on'):void {
 global $wpdb;require_once __DIR__.'/opening-promise-operational-lifecycle-support.php';require_once __DIR__.'/opening-promise-handoff-support.php';CetechPromiseOperationalLifecycle::guard();
 if(!in_array($mode,['hpos_on','hpos_off'],true)||('hpos_on'===$mode)!==Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled())throw new RuntimeException('P06 exact native order authority differs.');
 $hooks_before=[];foreach($GLOBALS['wp_filter']as$name=>$hook){if(!$hook instanceof WP_Hook||WP_Hook::class!==get_class($hook))throw new RuntimeException('P06 native hook table differs.');$hooks_before[$name]=clone$hook;}
 $before=CetechPromiseOperationalLifecycle::domain();$original_actor=get_current_user_id();$fixture=null;$failure=null;$namespaces=[];$reader_root=null;$cleanup=true;
 $installed=dirname((string)(new ReflectionClass(Plugin::class))->getFileName(),3);$current_map=CetechPromiseOperationalLifecycle::map($installed);
 $current_package=CetechPromiseOperationalLifecycle::package('CETECH_DE_P06_CURRENT_PACKAGE',(string)getenv('CETECH_DE_QUALIFICATION_HEAD'),$current_map);$reader_package=CetechPromiseOperationalLifecycle::package('CETECH_DE_P06_READER_PACKAGE','3b57ffc53b64f485aa9ad30e2d9e5d424afc3468');
 $track_create=static function(WC_Order$order)use(&$namespaces):void{$read=(new OrderDeliverySnapshotReader())->read_package($order);$envelope=$read->delivery_quote?->envelope;if(null===$envelope||null===$read->snapshot)throw new RuntimeException('P06 create identity absent.');$key=hash('sha256','original:'.$envelope->to_private_json());foreach($read->snapshot->groups as$group){$draft=\CetechDeliveryEngine\Domain\Shipment\Shipment::create($order->get_id(),$group->group_id,fulfilment_choice:'delivery');$identity=new OperationIdentity(get_current_blog_id(),'native-shipment-promise','staff:1',ShipmentPromiseCommand::CREATE,1,ShipmentPromiseCommand::target_key($draft),$key);$namespaces[$identity->namespace_digest()]=ShipmentPromiseCommand::CREATE;}};
 $fresh=static function(int$id)use($mode):WC_Order{clean_post_cache($id);wc_get_container()->get(Automattic\WooCommerce\Caches\OrderCache::class)->remove($id);if('hpos_on'===$mode)wc_get_container()->get(Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore::class)->clear_cached_data([$id]);return new WC_Order($id);};
 try {
  $fixture=new CetechPromiseHandoffNativeFixture($wpdb);$fixture->prepare();$gateway=$fixture->native->register_gateway();$lost=new CetechQuotePlacementNativeFlow($fixture->native);$lost->payment_method=$gateway->id;$lost->create();$native_money=CetechPromiseOperationalLifecycle::digest(CetechPromiseOperationalLifecycle::order_facts($lost->order->get_id(),$mode));$original=$fixture->packet($lost->order)->to_private_json();$quote_bytes=$fixture->native->cart->row($lost->evidence->header()->id()->value())['private_body_json'];$fixture->native->factory->mask_next_binding_ack=true;$denied=$lost->admission->final_order($lost->order,'classic');$writes=$fixture->native->factory->binding_writes;$recovered=$fixture->replay_original_seal($lost);$route_switch=$lost->admission->final_order($lost->order,'store_api');$request=new CetechPromiseOperationalNativeRequest($fixture);$cross=$request->recover_store($fresh($lost->order->get_id()));
  $check('NATIVE-W2P06-PROMISE-CROSS-ROUTE-LOST-SEAL-RECOVERY',!$denied->allowed&&'accepted'===$recovered->attempt->outcome->state&&$cross, ['actual_promise_profile'=>'service_promise_v1'===$lost->evidence->header()->profile(),'classic_unknown_ack_refused'=>!$denied->allowed,'store_api_same_order_admitted'=>$cross,'original_route_guard_refuses_direct_switch'=>!$route_switch->allowed,'fresh_saved_order_payment_admission'=>'order_pay'===$request->last_route&&true===$request->last_admission?->allowed,'original_native_route_retained'=>'classic'===(WC()->session->get(\CetechDeliveryEngine\Integrations\DeliveryQuote\QuotePlacementRuntime::SESSION_CONTINUATION)['route']??null),'native_money_items_payment_preserved'=>$native_money===CetechPromiseOperationalLifecycle::digest(CetechPromiseOperationalLifecycle::order_facts($lost->order->get_id(),$mode)),'same_original_binding_sealed'=>'sealed'===$fixture->native->binding_row($lost->evidence->header()->id()->value())['state'],'one_binding_effect'=>$writes===$fixture->native->factory->binding_writes,'original_clock_packet_preserved'=>$original===$fixture->packet($lost->order)->to_private_json(),'original_quote_money_preserved'=>$quote_bytes===$fixture->native->cart->row($lost->evidence->header()->id()->value())['private_body_json'],'no_gateway_call'=>0===$gateway->native_payment_calls(),'uncertain_owner_retired'=>$fixture->native->factory->fault_retired()]);
  $first_cleanup=$fixture->cleanup();$fixture=null;if(in_array(false,$first_cleanup,true))throw new RuntimeException('P06 cross-route owned fixture cleanup failed.');
  $fixture=new CetechPromiseHandoffNativeFixture($wpdb);$fixture->prepare();$gateway=$fixture->native->register_gateway();$store=new CetechPromiseOperationalNativeRequest($fixture);$reverse=$store->create_store($gateway->id);$native_money=CetechPromiseOperationalLifecycle::digest(CetechPromiseOperationalLifecycle::order_facts($reverse['order']->get_id(),$mode));$original=$fixture->packet($reverse['order'])->to_private_json();$quote_bytes=$fixture->native->cart->row($reverse['evidence']->header()->id()->value())['private_body_json'];$fixture->native->factory->mask_next_binding_ack=true;$denied=$store->admission->final_order($reverse['order'],'store_api');$writes=$fixture->native->factory->binding_writes;$recovered=$store->replay_seal($reverse);$route_switch=$store->admission->final_order($reverse['order'],'classic');$request=new CetechPromiseOperationalNativeRequest($fixture);$cross=$request->recover_classic($fresh($reverse['order']->get_id()));
  $check('NATIVE-W2P06-PROMISE-REVERSE-CROSS-ROUTE-LOST-SEAL-RECOVERY',!$denied->allowed&&'accepted'===$recovered->attempt->outcome->state&&$cross, ['actual_promise_profile'=>'service_promise_v1'===$reverse['evidence']->header()->profile(),'store_api_unknown_ack_refused'=>!$denied->allowed,'classic_same_order_admitted'=>$cross,'original_route_guard_refuses_direct_switch'=>!$route_switch->allowed,'fresh_saved_order_payment_admission'=>'order_pay'===$request->last_route&&true===$request->last_admission?->allowed,'original_native_route_retained'=>'store_api'===(WC()->session->get(\CetechDeliveryEngine\Integrations\DeliveryQuote\QuotePlacementRuntime::SESSION_CONTINUATION)['route']??null),'native_money_items_payment_preserved'=>$native_money===CetechPromiseOperationalLifecycle::digest(CetechPromiseOperationalLifecycle::order_facts($reverse['order']->get_id(),$mode)),'same_original_binding_sealed'=>'sealed'===$fixture->native->binding_row($reverse['evidence']->header()->id()->value())['state'],'one_binding_effect'=>$writes===$fixture->native->factory->binding_writes,'original_clock_packet_preserved'=>$original===$fixture->packet($reverse['order'])->to_private_json(),'original_quote_money_preserved'=>$quote_bytes===$fixture->native->cart->row($reverse['evidence']->header()->id()->value())['private_body_json'],'no_gateway_call'=>0===$gateway->native_payment_calls(),'uncertain_owner_retired'=>$fixture->native->factory->fault_retired()]);
  $reverse_cleanup=$fixture->cleanup();$fixture=null;if(in_array(false,$reverse_cleanup,true))throw new RuntimeException('P06 reverse cross-route owned fixture cleanup failed.');
  $fixture=new CetechPromiseHandoffNativeFixture($wpdb);$fixture->prepare();$gateway=$fixture->native->register_gateway();$paused=new CetechQuotePlacementNativeFlow($fixture->native);$paused->payment_method=$gateway->id;$paused->create();$paused_original=$fixture->packet($paused->order)->to_private_json();$writes=$fixture->native->factory->binding_writes;
  $paused->before_seal=static function()use($fixture):void{$fixture->native->cart->native->set_option(\CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore::OPTION_NAME,\CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState::record_json(get_current_blog_id(),'checkout_suspended',990002,'operator_pause',1,time()));};$pause_denied=$paused->admission->final_order($paused->order,'classic');
  $check('NATIVE-W2P06-PROMISE-LATE-EMERGENCY-PAUSE-REFUSES-PAYMENT',!$pause_denied->allowed,['actual_promise_profile'=>'service_promise_v1'===$paused->evidence->header()->profile(),'native_pause_arrived_before_seal'=>!$pause_denied->allowed,'binding_stays_prepared'=>'prepared'===$fixture->native->binding_row($paused->evidence->header()->id()->value())['state'],'no_binding_seal_effect'=>$writes===$fixture->native->factory->binding_writes,'original_packet_preserved'=>$paused_original===$fixture->packet($paused->order)->to_private_json(),'no_gateway_call'=>0===$gateway->native_payment_calls()]);
  $pause_cleanup=$fixture->cleanup();$fixture=null;if(in_array(false,$pause_cleanup,true))throw new RuntimeException('P06 late pause owned fixture cleanup failed.');
  $fixture=new CetechPromiseHandoffNativeFixture($wpdb);$fixture->prepare();$fixture->native->cart->native->set_option('cetech_de_enable_shipment_records','1');foreach([\CetechDeliveryEngine\Application\Shipment\ShipmentCreationFailureStore::INDEX_OPTION,\CetechDeliveryEngine\Application\Shipment\CodAwaitingShipmentStore::INDEX_OPTION]as$index)$fixture->native->cart->native->set_option($index,get_option($index,[]));
  $flow=new CetechQuotePlacementNativeFlow($fixture->native);$flow->create();if(!$flow->admission->final_order($flow->order,'classic')->allowed)throw new RuntimeException('P06 actual sealed order unavailable.');$order=$fresh($flow->order->get_id());$track_create($order);wp_set_current_user(1);$container=Plugin::instance()->container();$creation=$container->get(ShipmentService::class);$shipments=$container->get(ShipmentRepositoryInterface::class);$runtime=$container->get(NativeShipmentPromiseRuntime::class);$created=$creation->create_from_historical_order_for_staff($order,1);$list=$shipments->findByOrderId($order->get_id());$shipment=$list[0]??null;$service=$runtime->service_for_order($fresh($order->get_id()));$stored=null===$shipment?null:$service?->read_for_order($shipment,$fresh($order->get_id()));if(!$created->outcome->is_success()||1!==count($list)||null===$stored)throw new RuntimeException('P06 genuine original shipment unavailable.');
  $view=$stored->packet()->public_facts()['views'][0]??null;if(!is_array($view)||'absolute_window'!==$view['state'])throw new RuntimeException('P06 original native absolute window unavailable.');$capture=(new \CetechDeliveryEngine\Integrations\ServicePromise\NativePromiseRuntimeCapture())->capture();$now=\CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime::from_epoch_microseconds(time()*1000000)->sql();
  $current=ShipmentCurrentPromise::from_array(['format'=>1,'source'=>'staff_revision','state'=>'absolute_window','original_packet_digest'=>$stored->packet()->digest(),'event_key'=>hash('sha256','p06-owned-current:'.$shipment->id),'event_at'=>$now,'reason'=>'Owned P06 lifecycle estimate preservation','runtime'=>$capture,'views'=>[['service_label'=>$view['service_label'],'display_timezone'=>$view['display_timezone'],'from'=>$view['from'],'until'=>$view['until']]]]);$key=RequestContext::create()->request_id;$identity=new OperationIdentity(get_current_blog_id(),'native-shipment-promise','staff:1',ShipmentPromiseCommand::UPDATE,1,ShipmentPromiseCommand::target_key($shipment),$key);$namespaces[$identity->namespace_digest()]=ShipmentPromiseCommand::UPDATE;$updated=$service->update_current($fresh($order->get_id()),$shipment->id,2,$current,1,$key);$stored=$service->read_for_order($shipment,$fresh($order->get_id()));if('accepted'!==$updated->outcome->state||null===$stored?->current())throw new RuntimeException('P06 acknowledged separate current estimate unavailable.');
  $envelope=$fixture->packet($fresh($order->get_id()));$unknown=wc_create_order();if(!$unknown instanceof WC_Order)throw new RuntimeException('P06 unknown reference order allocation failed.');$fixture->native->orders[]=$unknown->get_id();$raw=$order->get_meta(OrderDeliverySnapshot::META_ORDER_QUOTE_SNAPSHOT,true);$outer=\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteJson::decode($raw);$outer[DeliveryQuoteSnapshotEnvelope::MEMBER]['format']=99;$unknown_bytes=\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteJson::encode($outer);$unknown->update_meta_data(OrderDeliverySnapshot::META_ORDER_QUOTE_SNAPSHOT,$unknown_bytes);$unknown->update_meta_data(OrderDeliverySnapshot::META_ORDER_SNAPSHOT_VERSION,'3');$unknown->update_meta_data(DeliveryQuoteSnapshotEnvelope::META_FORMAT,'99');$unknown->save();
  $snapshot=CetechPromiseOperationalLifecycle::domain();$config=['action'=>'read','plugin_root'=>$installed,'php_map_hash'=>CetechPromiseOperationalLifecycle::digest($current_map),'php_map_count'=>count($current_map),'order_id'=>$order->get_id(),'unknown_order_id'=>$unknown->get_id(),'envelope_digest'=>hash('sha256',$envelope->to_private_json()),'packet_digest'=>hash('sha256',$envelope->promise_packet()->to_private_json()),'unknown_bytes_digest'=>hash('sha256',$unknown_bytes),'shipment_id'=>(int)$stored->row()['id'],'shipment_row_digest'=>CetechPromiseOperationalLifecycle::digest($fixture->rows($wpdb->prepare('SELECT * FROM `'.TableNames::for('shipment_promises').'` WHERE id=%d LIMIT 2',(int)$stored->row()['id']))[0]),'domain_digest'=>CetechPromiseOperationalLifecycle::digest($snapshot),'order_facts_digest'=>CetechPromiseOperationalLifecycle::digest(CetechPromiseOperationalLifecycle::order_facts($order->get_id(),$mode)),'mode'=>$mode];
  $check('NATIVE-W2P06-SEALED-ORIGINAL-CURRENT-UNKNOWN-HISTORY-SEEDED',39===count($snapshot),['schema11_current39'=>'11'===(string)get_option('cetech_de_db_version')&&39===count($snapshot),'actual_sealed_outer3_envelope2'=>QuoteNativeOrderHistory::verify($fresh($order->get_id()))&&$envelope->is_promise(),'genuine_original_shipment_acknowledged'=>$created->outcome->is_success(),'separate_current_estimate_audited'=>'accepted'===$updated->outcome->state&&3===$stored->row()['revision'],'unknown_future_saved_reference_persisted'=>$unknown_bytes===$fresh($unknown->get_id())->get_meta(OrderDeliverySnapshot::META_ORDER_QUOTE_SNAPSHOT,true),'native_items_money_saved'=>[]!==$order->get_items('line_item')&&(float)$order->get_total()>0]);
  $options=CetechPromiseOperationalLifecycle::options();
  $preceding_package=CetechPromiseOperationalLifecycle::package('CETECH_DE_P06_PREDECESSOR_PACKAGE','543275af6844d649268f9ac02db518420dac9fe6');
  try{
   CetechPromiseOperationalLifecycle::process([PHP_BINARY,CetechPromiseOperationalLifecycle::env_file('CETECH_DE_P06_WP_CLI'),'--allow-root','--path='.rtrim(ABSPATH,'/'),'--require='.__DIR__.'/admin-context.php','plugin','install',CetechPromiseOperationalLifecycle::env_file('CETECH_DE_P06_PREDECESSOR_PACKAGE'),'--force','--quiet'],60);
   $previous=CetechPromiseOperationalLifecycle::child(array_replace($config,['php_map_hash'=>$preceding_package['production_php_sources_hash'],'php_map_count'=>count($preceding_package['production_php_sources'])]));
   CetechPromiseOperationalLifecycle::process([PHP_BINARY,CetechPromiseOperationalLifecycle::env_file('CETECH_DE_P06_WP_CLI'),'--allow-root','--path='.rtrim(ABSPATH,'/'),'--require='.__DIR__.'/admin-context.php','plugin','install',CetechPromiseOperationalLifecycle::env_file('CETECH_DE_P06_CURRENT_PACKAGE'),'--force','--quiet'],60);$reinstalled=CetechPromiseOperationalLifecycle::map($installed)===$current_map;$upgrade=CetechPromiseOperationalLifecycle::child(array_replace($config,['action'=>'upgrade']));}
  finally{
   if(CetechPromiseOperationalLifecycle::map($installed)!==$current_map)CetechPromiseOperationalLifecycle::process([PHP_BINARY,CetechPromiseOperationalLifecycle::env_file('CETECH_DE_P06_WP_CLI'),'--allow-root','--path='.rtrim(ABSPATH,'/'),'--require='.__DIR__.'/admin-context.php','plugin','install',CetechPromiseOperationalLifecycle::env_file('CETECH_DE_P06_CURRENT_PACKAGE'),'--force','--quiet'],60);
   $restored=CetechPromiseOperationalLifecycle::restore_options($options,CetechPromiseOperationalLifecycle::options());
  }
  $check('NATIVE-W2P06-FRESH-PACKAGE-REINSTALL-NATIVE-UPGRADE-PRESERVES-HISTORY',$reinstalled&&$restored,['accepted_p05_package_read_before_current_upgrade'=>$previous['native_known_sealed_order_read']&&$previous['original_current_shipment_rows_preserved'],'actual_clean_zip_reinstalled'=>$reinstalled,'fresh_process_native_activation'=>true===$upgrade['exact_production_autoload'],'known_sealed_order_money_preserved'=>$upgrade['native_known_sealed_order_read'],'unknown_reference_preserved_refused'=>$upgrade['unknown_future_snapshot_preserved_refused'],'original_current_shipment_preserved'=>$upgrade['original_current_shipment_rows_preserved'],'all39_business_stores_preserved'=>$snapshot===CetechPromiseOperationalLifecycle::domain()&&$upgrade['all39_business_stores_preserved'],'fixed_lifecycle_options_restored'=>$restored,'private_child_config_removed'=>$upgrade['private_config_removed']]);
  $off= $fixture->activation->change(false,2,new OperationIdentity(get_current_blog_id(),'native-p04-internal','user:1','service_promise.adoption',1,'promise-adoption:'.$fixture->binding->site_key(),$fixture->binding->site_key().'-p06-disable'));$disabled=CetechPromiseOperationalLifecycle::child($config);
  $check('NATIVE-W2P06-DISABLE-PRESERVES-KNOWN-UNKNOWN-AND-SHIPMENT-HISTORY',$off&&!$fixture->activation->active(),['explicit_revisioned_adoption_disabled'=>$off&&!$fixture->activation->active(),'known_original_readable'=>$disabled['native_known_sealed_order_read'],'unknown_reference_preserved_refused'=>$disabled['unknown_future_snapshot_preserved_refused'],'original_current_shipment_preserved'=>$disabled['original_current_shipment_rows_preserved'],'all39_business_stores_preserved'=>$disabled['all39_business_stores_preserved'],'private_child_config_removed'=>$disabled['private_config_removed']]);
  $options=CetechPromiseOperationalLifecycle::options();try{$deactivated=CetechPromiseOperationalLifecycle::child(array_replace($config,['action'=>'deactivate']));}finally{$restored=CetechPromiseOperationalLifecycle::restore_options($options,CetechPromiseOperationalLifecycle::options());}
  $check('NATIVE-W2P06-DEACTIVATION-PRESERVES-SEALED-HISTORY',$restored,['fresh_native_deactivator'=>$deactivated['exact_production_autoload'],'known_original_readable'=>$deactivated['native_known_sealed_order_read'],'unknown_reference_preserved_refused'=>$deactivated['unknown_future_snapshot_preserved_refused'],'original_current_shipment_preserved'=>$deactivated['original_current_shipment_rows_preserved'],'all39_business_stores_preserved'=>$deactivated['all39_business_stores_preserved'],'fixed_lifecycle_options_restored'=>$restored,'private_child_config_removed'=>$deactivated['private_config_removed']]);
  $options=CetechPromiseOperationalLifecycle::options();try{$native=CetechPromiseOperationalLifecycle::child(array_replace($config,['action'=>'native_uninstall']));}finally{$restored=CetechPromiseOperationalLifecycle::restore_options($options,CetechPromiseOperationalLifecycle::options());}
  $check('NATIVE-W2P06-COMPOSER-UNINSTALL-PRESERVES-SEALED-HISTORY',$restored,['fresh_actual_composer_uninstall'=>$native['exact_production_autoload']&&$native['uninstall_completed'],'known_original_readable'=>$native['native_known_sealed_order_read'],'unknown_reference_preserved_refused'=>$native['unknown_future_snapshot_preserved_refused'],'original_current_shipment_preserved'=>$native['original_current_shipment_rows_preserved'],'all39_business_stores_preserved'=>$native['all39_business_stores_preserved'],'fixed_lifecycle_options_restored'=>$restored,'private_child_config_removed'=>$native['private_config_removed']]);
  $options=CetechPromiseOperationalLifecycle::options();try{CetechPromiseOperationalLifecycle::complete_original_expired_maintenance();update_option(DataLifecycleManifest::CAPABILITIES_MARKER,4,false);update_option(DataLifecycleManifest::UNINSTALL_INTENT,1,false);$standalone=CetechPromiseOperationalLifecycle::child(['wp_load'=>rtrim(ABSPATH,'/').'/wp-load.php','plugin_root'=>$installed,'domain_suffixes'=>array_keys($snapshot),'domain_digest'=>CetechPromiseOperationalLifecycle::digest($snapshot)],true);}finally{$restored=CetechPromiseOperationalLifecycle::restore_options($options,CetechPromiseOperationalLifecycle::options());}
  $check('NATIVE-W2P06-STANDALONE-UNINSTALL-PRESERVES-SEALED-HISTORY',$restored,['actual_complete_fixed_loader'=>$standalone['complete_standalone_loader'],'fresh_shortinit_without_composer_woo'=>$standalone['no_composer_or_woocommerce'],'explicit_uninstall_completed'=>$standalone['uninstall_completed'],'all39_business_stores_preserved'=>$standalone['all39_business_stores_preserved']&&$snapshot===CetechPromiseOperationalLifecycle::domain(),'known_native_money_items_payment_preserved'=>$config['order_facts_digest']===CetechPromiseOperationalLifecycle::digest(CetechPromiseOperationalLifecycle::order_facts($order->get_id(),$mode)),'unknown_native_snapshot_bytes_preserved'=>$unknown_bytes===$fresh($unknown->get_id())->get_meta(OrderDeliverySnapshot::META_ORDER_QUOTE_SNAPSHOT,true),'fixed_lifecycle_options_restored'=>$restored,'private_child_config_removed'=>$standalone['private_config_removed']]);
  $reader_root=CetechPromiseOperationalLifecycle::extract_reader(CetechPromiseOperationalLifecycle::env_file('CETECH_DE_P06_READER_PACKAGE'));$reader_map=CetechPromiseOperationalLifecycle::map($reader_root);if($reader_map!==$reader_package['production_php_sources'])throw new RuntimeException('P06 exact P04 extracted reader bytes differ.');$options=CetechPromiseOperationalLifecycle::options();try{$rollback=CetechPromiseOperationalLifecycle::child(array_replace($config,['action'=>'rollback','plugin_root'=>$reader_root,'php_map_hash'=>CetechPromiseOperationalLifecycle::digest($reader_map),'php_map_count'=>count($reader_map)]),false,true);}finally{$restored=CetechPromiseOperationalLifecycle::restore_options($options,CetechPromiseOperationalLifecycle::options());}
  $check('NATIVE-W2P06-SUPPORTED-P04-FORWARD-READER-PRESERVES-P05-UNKNOWN-DATA',$restored,['exact_p04_extracted_production_autoload'=>$rollback['exact_production_autoload'],'retained_known_p04_sealed_original_readable'=>$rollback['native_known_sealed_order_read'],'unknown_future_order_reference_refused_preserved'=>$rollback['unknown_future_snapshot_preserved_refused'],'p05_original_current_unknown_store_preserved'=>$rollback['original_current_shipment_rows_preserved'],'compatible_p04_base_storage_ready'=>$rollback['compatible_base_storage_ready'],'new_shipment_writer_unavailable'=>$rollback['new_shipment_writer_unavailable'],'old_plugin_writers_unmounted'=>$rollback['old_plugin_writers_unmounted']&&$rollback['supported_forward_reader_only'],'all39_business_stores_preserved'=>$rollback['all39_business_stores_preserved'],'no_reverse_migration'=>CetechPromiseOperationalLifecycle::map($installed)===$current_map&&'11'===(string)get_option('cetech_de_db_version'),'fixed_lifecycle_options_restored'=>$restored,'private_child_config_removed'=>$rollback['private_config_removed']]);
 }catch(Throwable$error){$failure=$error;throw$error;}
 finally {
  try{
   if(null!==$fixture){$owned=array_fill_keys($fixture->native->orders,true);$owned_shipments=[];foreach(CetechPromiseOperationalLifecycle::domain()['shipments']as$row)if(isset($owned[(int)$row['order_id']]))$owned_shipments[(int)$row['id']]=(int)$row['order_id'];
    foreach($namespaces as$namespace=>$operation){$records=CetechPromiseOperationalLifecycle::rows($wpdb->prepare('SELECT * FROM `'.TableNames::for('operation_records').'` WHERE site_id=%d AND namespace_hash=%s AND operation=%s LIMIT 2',get_current_blog_id(),$namespace,$operation));if(count($records)>1)throw new RuntimeException('P06 owned operation ambiguous.');foreach($records as$record){$cleanup=false!==$wpdb->delete(TableNames::for('operation_changes'),['site_id'=>get_current_blog_id(),'operation_id'=>(int)$record['id']])&&$cleanup;$cleanup=1===$wpdb->delete(TableNames::for('operation_records'),['site_id'=>get_current_blog_id(),'id'=>(int)$record['id']])&&$cleanup;}}
    foreach(['shipment_promises','shipment_events','shipment_items','audit_log','shipments']as$suffix){$initial=array_fill_keys(array_column($before[$suffix],'id'),true);foreach(CetechPromiseOperationalLifecycle::domain()[$suffix]as$row){if(isset($initial[$row['id']]))continue;$allowed='shipments'===$suffix?isset($owned_shipments[(int)$row['id']]):('audit_log'===$suffix?('order'===$row['entity_type']&&isset($owned[(int)$row['entity_id']])&&in_array($row['action'],['shipment_creation_failed','shipment_creation_succeeded','shipment_creation_idempotent'],true)):isset($owned_shipments[(int)$row['shipment_id']]));if(!$allowed)continue;if('shipment_promises'===$suffix&&($row['site_key']!==$fixture->binding->site_key()||(int)$row['order_id']!==$owned_shipments[(int)$row['shipment_id']]))throw new RuntimeException('P06 unknown shipment cleanup refused.');$cleanup=1===$wpdb->delete(TableNames::for($suffix),['id'=>(int)$row['id']])&&$cleanup;}}
    wp_set_current_user(0);$native_cleanup=$fixture->cleanup();$cleanup=!in_array(false,$native_cleanup,true)&&$cleanup;
   }
   $cleanup=$before===CetechPromiseOperationalLifecycle::domain()&&$cleanup;if(null!==$reader_root)$cleanup=CetechPromiseOperationalLifecycle::remove_reader(dirname($reader_root))&&$cleanup;
  }catch(Throwable){$cleanup=false;}
  $GLOBALS['wp_filter']=$hooks_before;$hooks_restored=array_keys($GLOBALS['wp_filter'])===array_keys($hooks_before);foreach($hooks_before as$name=>$hook)$hooks_restored=$GLOBALS['wp_filter'][$name]->callbacks===$hook->callbacks&&$hooks_restored;$cleanup=$hooks_restored&&$cleanup;
  wp_set_current_user($original_actor);
  try{$check('NATIVE-W2P06-TRACKED-OPERATIONAL-LIFECYCLE-CLEANUP',$cleanup,['all39_original_business_rows_restored'=>$cleanup,'only_registered_orders_shipments_sources_removed'=>$cleanup,'owned_sql_connections_retired'=>$cleanup,'original_native_actor_restored'=>$original_actor===get_current_user_id(),'complete_original_native_hook_table_restored'=>$hooks_restored,'original_installed_package_bytes_restored'=>CetechPromiseOperationalLifecycle::map($installed)===$current_map,'private_reader_tree_removed'=>$cleanup]);}catch(Throwable$cleanup_error){if(null===$failure)throw$cleanup_error;}
 }
};
