<?php
/** Tracked P02 publication/adoption setup and private observation; never places or pays. */
declare(strict_types=1);
$p04_bridge_args = $args ?? null; unset($args);
require_once __DIR__ . '/opening-http-quote-placement-support.php';
require_once __DIR__ . '/opening-promise-handoff-support.php';
if (is_array($p04_bridge_args)) { $args = $p04_bridge_args; } unset($p04_bridge_args);

use CetechDeliveryEngine\Application\DeliveryQuote\{PromiseQuotePlacementActivation,QuoteSavedOrderPlacementEvidenceReader};
use CetechDeliveryEngine\Application\Order\{DeliveryQuoteSnapshotEnvelope,OrderDeliverySnapshot,OrderDeliverySnapshotReader,QuoteNativeOrderStager,QuoteNativeOrderHistory};
use CetechDeliveryEngine\Domain\Contracts\{OperationIdentity,RequestContext};
use CetechDeliveryEngine\Domain\DeliveryQuote\{QuoteId,QuoteJson};
use CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime;
use CetechDeliveryEngine\Domain\ServicePromise\{BusinessCalendarVersion,ServicePromisePolicy};
use CetechDeliveryEngine\Domain\ServicePromise\Persistence\{PromiseSiteBinding,PromiseVersionCommand,PromiseAssignmentCommand};
use CetechDeliveryEngine\Application\ServicePromise\Persistence\{PromiseVersionLifecycleService,PromiseAssignmentService};
use CetechDeliveryEngine\Infrastructure\Persistence\TableNames;
use CetechDeliveryEngine\Integrations\ServicePromise\PromiseNativeServiceRegistry;

final class CetechPromiseHandoffHttpFixture {
    private static bool $registered = false;
    public static function rows(string $sql): array { global $wpdb; $rows=$wpdb->get_results($sql,ARRAY_A); if (!is_array($rows) || count($rows)>20000 || ''!==$wpdb->last_error) { throw new RuntimeException('P04 bounded physical observation refused.'); } return $rows; }
    public static function option(string $name): ?array { global $wpdb; $rows=self::rows($wpdb->prepare("SELECT option_id,option_name,option_value,autoload FROM `{$wpdb->options}` WHERE option_name=%s LIMIT 2",$name)); if(count($rows)>1){throw new RuntimeException('P04 ambiguous option.');}return $rows[0]??null; }
    public static function state(): array { $state=cetech_q05_state(); CetechQuotePlacementHttpFixture::guard($state); if (true!==($state['p04']['active']??null)) { throw new RuntimeException('P04 fixture is inactive.'); } return $state; }
    public static function context(array $state): array { global $wpdb; $binding=PromiseSiteBinding::from_array($state['p04']['binding']);$authority=new CetechPromiseHandoffNativeAuthorizer($binding,str_repeat('a',64));$factory=new CetechQuotePlacementFactory($wpdb);return [$binding,$authority,$factory]; }
    public static function activation(array $state): PromiseQuotePlacementActivation { [$binding,$authority,$factory]=self::context($state);$allowed=$authority->authorize_author($binding,1,[]);return new PromiseQuotePlacementActivation($factory,static fn():bool=>true,authorize:static fn(OperationIdentity $actor,PromiseSiteBinding $asked):bool=>$allowed&&$actor->site_id===$binding->site_id()&&'native-p04-internal'===$actor->authority&&'user:1'===$actor->principal&&$asked->digest()===$binding->digest()); }
    public static function adoption(array &$state,bool $enabled): void { $activation=self::activation($state);$status=$activation->status();$actor=new OperationIdentity($state['site_id'],'native-p04-internal','user:1','service_promise.adoption',1,'promise-adoption:'.$state['p04']['token'],$state['p04']['token'].'-adoption-'.($status['revision']??0).'-'.($enabled?'on':'off'));if(!$activation->change($enabled,$status['revision'],$actor)){throw new RuntimeException('P04 revisioned adoption did not acknowledge.');}$state['p04']['adoption_last']=self::option(PromiseQuotePlacementActivation::OPTION);cetech_q05_write($state); }
    public static function register_sources(array &$state): void {
        global $wpdb;$binding=PromiseSiteBinding::from_array($state['p04']['binding']);
        foreach(['promise_objects','promise_versions','promise_assignments'] as $suffix){foreach(self::rows($wpdb->prepare('SELECT * FROM `'.TableNames::for($suffix).'` WHERE site_id=%d AND site_key=%s ORDER BY id',$state['site_id'],$binding->site_key())) as $row){
            if(isset($row['logical_id'])&&!in_array($row['logical_id'],[$state['p04']['token'].'-calendar',$state['p04']['token'].'-policy'],true)){throw new RuntimeException('P04 refuses an unregistered source.');}
            if('promise_versions'===$suffix&&!isset($state['p04']['version_uuids'][$row['version_uuid']])){throw new RuntimeException('P04 version cleanup lacks prior UUID authority.');}
            if('promise_assignments'===$suffix&&($row['scope_kind']!=='global'||(int)$row['scope_id']!==0||$row['service_kind']!=='built_in'||$row['service_code']!=='standard'||$row['endpoint']!=='doorstep'||$row['endpoint_kind']!=='doorstep')){throw new RuntimeException('P04 assignment cleanup lacks prior key authority.');}
            $state['p04']['registered'][$suffix][(string)$row['id']]=$row;
        }}cetech_q05_write($state);
    }
    public static function version(array &$state,string $action,BusinessCalendarVersion|ServicePromisePolicy $body): void {
        global $wpdb;[$binding,$authority,$factory]=self::context($state);$kind=$body instanceof ServicePromisePolicy?'policy':'calendar';$facts=$body->private_facts();$logical=$facts[$kind.'_id'];
        $objects=self::rows($wpdb->prepare('SELECT * FROM `'.TableNames::for('promise_objects').'` WHERE site_id=%d AND site_key=%s AND kind=%s AND logical_id=%s LIMIT 2',$state['site_id'],$binding->site_key(),$kind,$logical));
        $versions=self::rows($wpdb->prepare('SELECT * FROM `'.TableNames::for('promise_versions').'` WHERE site_id=%d AND site_key=%s AND kind=%s AND logical_id=%s AND domain_version=%d LIMIT 2',$state['site_id'],$binding->site_key(),$kind,$logical,$facts['version']));
        if(count($objects)>1||count($versions)>1){throw new RuntimeException('P04 exact version guard ambiguous.');}$object=$objects[0]??null;$version=$versions[0]??null;$uuid=$version['version_uuid']??QuoteId::generate()->value();
        $actor=new OperationIdentity($state['site_id'],'native-p04-internal','user:1','promise.version.'.$action,1,PromiseVersionCommand::target_key($binding,$kind,$logical),$state['p04']['token'].'-'.$kind.'-'.$action.'-'.$facts['version']);
        $state['p04']['version_uuids'][$uuid]=true;$state['p04']['namespaces'][$actor->namespace_digest()]=$actor->operation;cetech_q05_write($state);
        $command=PromiseVersionCommand::from_array($actor,$binding,['kind'=>$kind,'logical_id'=>$logical,'domain_version'=>$facts['version'],'version_uuid'=>$uuid,'body_digest'=>$body->digest(),'scope'=>['kind'=>'global','target_id'=>0],'body_json'=>'create'===$action?$body->to_private_json():null,'declared_from'=>'policy'===$kind?$facts['effective_from']:'1970-01-01 00:00:00.000000','declared_until'=>'policy'===$kind?$facts['effective_until']:null,'author_user_id'=>1,'reason'=>'Tracked P04 authenticated HTTP fixture','scheduled_author_user_id'=>null,'preconditions'=>['object_revision'=>(int)($object['revision']??0),'version_revision'=>(int)($version['row_revision']??0),'published_version_id'=>(int)($object['published_version_id']??0)]]);
        $result=(new PromiseVersionLifecycleService($binding,$factory,$authority))->attempt($actor,$command,RequestContext::create());self::register_sources($state);if('accepted'!==$result->outcome->state||null===$result->completion){throw new RuntimeException('P04 actual immutable publication refused.');}
    }
    public static function assignment(array &$state,ServicePromisePolicy $policy): void {
        global $wpdb;[$binding,$authority,$factory]=self::context($state);$key=['scope_kind'=>'global','scope_id'=>0,'service_kind'=>'built_in','service_code'=>'standard','endpoint'=>'doorstep','endpoint_kind'=>'doorstep'];
        $rows=self::rows($wpdb->prepare('SELECT * FROM `'.TableNames::for('promise_assignments').'` WHERE site_id=%d AND site_key=%s AND scope_kind=%s AND scope_id=0 AND service_kind=%s AND service_code=%s AND endpoint=%s AND endpoint_kind=%s LIMIT 2',$state['site_id'],$binding->site_key(),'global','built_in','standard','doorstep','doorstep'));if(count($rows)>1){throw new RuntimeException('P04 exact assignment ambiguous.');}$old=$rows[0]??null;
        $actor=new OperationIdentity($state['site_id'],'native-p04-internal','user:1',PromiseAssignmentCommand::OPERATION,1,PromiseAssignmentCommand::target_key($binding,$key),$state['p04']['token'].'-assignment-'.$policy->private_facts()['version'].'-'.($old['revision']??0));$state['p04']['namespaces'][$actor->namespace_digest()]=$actor->operation;cetech_q05_write($state);
        $command=PromiseAssignmentCommand::from_array($actor,$binding,['key'=>$key,'mode'=>'assigned','policy_reference'=>$policy->reference()->private_facts(),'expected_revision'=>(int)($old['revision']??0),'expected_generation'=>(int)($old['generation']??0),'author_user_id'=>1,'reason'=>'Tracked P04 HTTP effective global assignment']);
        $result=(new PromiseAssignmentService($binding,$factory,$authority))->attempt($actor,$command,RequestContext::create());self::register_sources($state);if('accepted'!==$result->outcome->state||null===$result->completion){throw new RuntimeException('P04 actual assignment refused.');}
    }
    public static function policy(array &$state,?string $until=null): ServicePromisePolicy {
        $binding=PromiseSiteBinding::from_array($state['p04']['binding']);$calendar=BusinessCalendarVersion::from_array($state['p04']['calendar']);$from=RuleTime::from_epoch_microseconds((time()-60)*1000000)->sql();$facts=CetechNativePromiseBodies::policy($binding->site_key(),$from,$until??RuleTime::from_epoch_microseconds((time()+86400)*1000000)->sql(),$calendar->reference())->private_facts();
        $facts['policy_id']=$state['p04']['token'].'-policy';$facts['version']=$state['p04']['next_policy_version']++;$facts['endpoint']='doorstep';$facts['graph']['components'][0]['duration']=['format_version'=>1,'min'=>60,'max'=>120,'unit'=>'elapsed_minutes','calendar'=>null];$facts['graph']['components'][0]['operating_calendar']=null;$facts['graph']['components'][0]['completion_window_rule']='none';$facts['graph']['components'][0]['endpoint']='doorstep';$policy=ServicePromisePolicy::from_array($facts);
        foreach(['create','seal','publish'] as $action){self::version($state,$action,$policy);}self::assignment($state,$policy);$state['p04']['policy']=$policy->private_facts();cetech_q05_write($state);return $policy;
    }
    public static function inspect(array $state): array {
        $out=CetechQuotePlacementHttpFixture::snapshot($state);$factory=new CetechQuotePlacementFactory($GLOBALS['wpdb']);$runtime=CetechDeliveryEngine\Bootstrap\Plugin::instance()->container()->get(CetechDeliveryEngine\Integrations\DeliveryQuote\QuotePlacementRuntime::class);
        $evidence=new QuoteSavedOrderPlacementEvidenceReader($factory,new QuoteNativeOrderStager($factory),[$runtime,'authorize_saved_order']);
        foreach($out['orders'] as $id=>&$facts){$order=wc_get_order((int)$id);$read=(new OrderDeliverySnapshotReader())->read_package($order);$envelope=$read->delivery_quote?->envelope;$link=$evidence->read_original_promise_linkage($order);$packet=$envelope?->promise_packet();$deadline=null;foreach($packet?->private_facts()['groups']??[] as $group){$input=json_decode($group['packet']['input_json'],true,512,JSON_THROW_ON_ERROR);$deadline=$input['policy']['effective_until'];}
            $facts+=['promise_profile'=>$envelope?->is_promise()===true,'outer3'=>$read->snapshot?->snapshot_version==='3','marker2'=>$order->get_meta(DeliveryQuoteSnapshotEnvelope::META_FORMAT,true)==='2','original_seal_linked'=>null!==$link,'required_packet_present'=>null!==$packet,'quote_id'=>$envelope?->private_facts()['quote_id'],'quote_expires_at'=>$envelope?->private_facts()['expires_at'],'promise_deadline'=>$deadline];
        }unset($facts);$factory->close_all();$out['native_user_id']=get_current_user_id();$out['adoption']=self::activation($state)->status();$out['p04_fixture_nonce']=wp_create_nonce('cetech_p04_fixture');$out['p04_source_counts']=array_map('count',$state['p04']['registered']);return $out;
    }
    public static function register(): void {
        if(self::$registered){return;}self::$registered=true;
        add_action('template_redirect',static function():void{if(!isset($_GET['cetech_p04_fixture'])){return;}$state=self::state();$token=$_SERVER['HTTP_X_CETECH_P04_FIXTURE']??null;if(!CetechQuotePlacementHttpFixture::principal($state)||!is_string($token)||!hash_equals($state['fixture_token'],$token)){wp_send_json_error(['code'=>'fixture_forbidden'],403);}$mode=$_GET['cetech_p04_fixture'];if(!is_string($mode)||!in_array($mode,['inspect','adoption_off','adoption_on','deadline_policy','normal_policy'],true)){wp_send_json_error(['code'=>'fixture_mode'],400);}if('inspect'!==$mode&&('POST'!==($_SERVER['REQUEST_METHOD']??'')||!is_string($_POST['nonce']??null)||!wp_verify_nonce($_POST['nonce'],'cetech_p04_fixture'))){wp_send_json_error(['code'=>'fixture_nonce'],403);}if(!WC()->cart||!WC()->session){wc_load_cart();}WC()->cart->get_cart();WC()->session->set_customer_session_cookie(true);if('adoption_off'===$mode||'adoption_on'===$mode){self::adoption($state,'adoption_on'===$mode);}elseif('deadline_policy'===$mode){self::policy($state,RuleTime::from_epoch_microseconds((time()+120)*1000000)->sql());}elseif('normal_policy'===$mode){self::policy($state);}wp_send_json_success(self::inspect($state));},-115);
    }
}

if(defined('WP_CLI')&&WP_CLI&&isset($args)&&count($args)===3){
    require_once __DIR__.'/opening-http-fixture-common.php';[$mode,$state_path,$output_path]=$args;$state=opening_http_read_state($state_path);CetechQuotePlacementHttpFixture::guard($state);global $wpdb;
    if('preparepromise'===$mode){
        if(isset($state['p04'])||!CetechQuotePlacementHttpFixture::active($state)){throw new RuntimeException('P04 refuses existing or inactive fixture.');}$token='p04-http-'.bin2hex(random_bytes(6));$binding=PromiseSiteBinding::bind($state['site_id'],$token);
        $before=[];foreach(['promise_objects','promise_versions','promise_assignments']as$suffix){$before[$suffix]=CetechPromiseHandoffHttpFixture::rows('SELECT * FROM `'.TableNames::for($suffix).'` ORDER BY id');}
        $adoption_before=CetechPromiseHandoffHttpFixture::option(PromiseQuotePlacementActivation::OPTION);
        $state['p04']=['active'=>true,'token'=>$token,'binding'=>$binding->private_facts(),'registered'=>['promise_objects'=>[],'promise_versions'=>[],'promise_assignments'=>[]],'namespaces'=>[],'version_uuids'=>[],'before'=>$before,'adoption_before'=>$adoption_before,'adoption_last'=>$adoption_before,'next_policy_version'=>1];opening_http_write_json($state_path,$state,true);
        $native=CetechQuoteCartHttpFixture::hydrate_native($wpdb,$state['native']);$insert=new ReflectionMethod(CetechNativeQuoteProviderFixture::class,'insert');
        foreach($state['native']['products']as$product){$scopes=CetechPromiseHandoffHttpFixture::rows($wpdb->prepare('SELECT id FROM `'.TableNames::for('configuration_scopes').'` WHERE scope_type=%s AND scope_id=%d LIMIT 2','product',$product));if(count($scopes)!==1){throw new RuntimeException('P04 exact tracked native configuration missing.');}foreach(['origin_id'=>'alternate_origin','supplier_id'=>'alternate_supplier','logistics_profile_id'=>'alternate_profile']as$field=>$source){$id=$insert->invoke($native,'configuration_fields',['scope_row_id'=>(int)$scopes[0]['id'],'field_key'=>$field,'mode'=>'override','value_type'=>'int','value_text'=>(string)$state['native'][$source]]);if(!is_int($id)||$id<1){throw new RuntimeException('P04 origin allocation refused.');}$state['native']=CetechQuoteCartHttpFixture::export_native($native);opening_http_write_json($state_path,$state,true);}}
        $calendar=CetechNativePromiseBodies::calendar($binding->site_key())->private_facts();$calendar['calendar_id']=$token.'-calendar';$state['p04']['calendar']=$calendar;cetech_q05_write($state);$calendar=BusinessCalendarVersion::from_array($calendar);foreach(['create','seal','publish']as$action){CetechPromiseHandoffHttpFixture::version($state,$action,$calendar);}CetechPromiseHandoffHttpFixture::policy($state);
        $registry=new PromiseNativeServiceRegistry([['native_service_id'=>$state['native']['offer'],'service_kind'=>'built_in','service_code'=>'standard','origin_endpoint'=>'native-origin','origin_kind'=>'origin','destination_endpoint'=>'doorstep','destination_kind'=>'doorstep']]);$activation=CetechPromiseHandoffHttpFixture::activation($state);$actor=new OperationIdentity($state['site_id'],'native-p04-internal','user:1','service_promise.adoption',1,'promise-adoption:'.$token,$token.'-configure');if(!$activation->configure($binding,$registry,0,$actor)){throw new RuntimeException('P04 protected configuration refused.');}$configured=$activation->status();$state['p04']['configured_off']=$configured['enabled']===false&&$configured['revision']===1;$state['p04']['adoption_last']=CetechPromiseHandoffHttpFixture::option(PromiseQuotePlacementActivation::OPTION);cetech_q05_write($state);CetechPromiseHandoffHttpFixture::adoption($state,true);opening_http_write_json($output_path,['ready'=>true,'configured_off'=>$state['p04']['configured_off'],'source_counts'=>array_map('count',$state['p04']['registered'])]);
    }elseif('cleanuppromise'===$mode){
        if(!isset($state['p04'])){opening_http_write_json($output_path,['cleanup_restored'=>true,'original_promise_history_restored'=>true,'adoption_restored'=>true,'exact_owned_namespaces_removed'=>true]);return;}$ok=true;
        if(true===($state['p04']['cleanup_done']??false)){opening_http_write_json($output_path,$state['p04']['cleanup']);return;}
        foreach(['promise_assignments','promise_versions','promise_objects']as$suffix){foreach($state['p04']['registered'][$suffix]as$id=>$row){$current=CetechPromiseHandoffHttpFixture::rows($wpdb->prepare('SELECT * FROM `'.TableNames::for($suffix).'` WHERE id=%d AND site_id=%d AND site_key=%s LIMIT 2',(int)$id,$state['site_id'],$state['p04']['token']));if(count($current)>1||($current&&$current[0]!==$row)){throw new RuntimeException('P04 refuses changed tracked source cleanup.');}$ok=false!==$wpdb->delete(TableNames::for($suffix),['id'=>(int)$id,'site_id'=>$state['site_id'],'site_key'=>$state['p04']['token']])&&$ok;}}
        foreach($state['p04']['namespaces']as$namespace=>$operation){$records=CetechPromiseHandoffHttpFixture::rows($wpdb->prepare('SELECT id,operation FROM `'.TableNames::for('operation_records').'` WHERE site_id=%d AND namespace_hash=%s LIMIT 2',$state['site_id'],$namespace));if(count($records)>1){throw new RuntimeException('P04 ambiguous namespace cleanup.');}foreach($records as$row){if($row['operation']!==$operation){throw new RuntimeException('P04 foreign namespace cleanup.');}$ok=false!==$wpdb->delete(TableNames::for('operation_changes'),['site_id'=>$state['site_id'],'operation_id'=>(int)$row['id']])&&$ok;$ok=false!==$wpdb->delete(TableNames::for('operation_records'),['site_id'=>$state['site_id'],'id'=>(int)$row['id']])&&$ok;}}
        $current=CetechPromiseHandoffHttpFixture::option(PromiseQuotePlacementActivation::OPTION);if($current!==$state['p04']['adoption_last']){throw new RuntimeException('P04 refuses changed adoption cleanup.');}$prior=$state['p04']['adoption_before'];$ok=false!==(null===$prior?$wpdb->delete($wpdb->options,['option_name'=>PromiseQuotePlacementActivation::OPTION]):$wpdb->replace($wpdb->options,$prior))&&$ok;foreach([PromiseQuotePlacementActivation::OPTION,'notoptions','alloptions']as$key){wp_cache_delete($key,'options');}$history=true;foreach($state['p04']['before']as$suffix=>$rows){$history=$rows===CetechPromiseHandoffHttpFixture::rows('SELECT * FROM `'.TableNames::for($suffix).'` ORDER BY id')&&$history;}$state['p04']['active']=false;$state['p04']['cleanup_done']=true;$state['p04']['cleanup']=['cleanup_restored'=>$ok&&$history,'original_promise_history_restored'=>$history,'adoption_restored'=>$prior===CetechPromiseHandoffHttpFixture::option(PromiseQuotePlacementActivation::OPTION),'exact_owned_namespaces_removed'=>$ok];cetech_q05_write($state);opening_http_write_json($output_path,$state['p04']['cleanup']);
    }else{throw new RuntimeException('P04 private CLI mode refused.');}
}
