<?php

declare(strict_types=1);

use CetechDeliveryEngine\Application\DeliveryQuote\{QuoteAdmissionAttempt, QuoteDurableService, QuoteIssueCommand, QuoteProviderRegistry};
use CetechDeliveryEngine\Application\ServicePromise\Persistence\{PromiseAssignmentService, PromiseVersionLifecycleService, PromiseVersionReadService};
use CetechDeliveryEngine\Bootstrap\{DataLifecycleManifest, Deactivator, Uninstaller};
use CetechDeliveryEngine\Core\Versioning\{MigrationRunner, MigrationStatus, SchemaVersion};
use CetechDeliveryEngine\Domain\Contracts\{OperationIdentity, RequestContext};
use CetechDeliveryEngine\Domain\DeliveryQuote\{QuoteOwner, QuoteStoredRow};
use CetechDeliveryEngine\Domain\Operation\OperationCommitResult;
use CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime;
use CetechDeliveryEngine\Domain\ServicePromise\{PromiseCalendarReference, PromisePolicyReference};
use CetechDeliveryEngine\Domain\ServicePromise\Persistence\{PromiseAssignmentCommand, PromiseSiteBinding, PromiseStoredVersion, PromiseVersionCommand};
use CetechDeliveryEngine\Infrastructure\Persistence\{DeliveryQuoteReadiness, DeliveryQuoteRepository, DeliveryQuoteSchema, PromiseStorageReadiness, PromiseStorageSchema};
use CetechDeliveryEngine\Support\Logger;
use CetechDeliveryEngine\Tests\Support\DeliveryQuote\{QuoteFixtures, QuoteStorageFixtures};

/** P02 storage only. This explicit internal adopter is never mounted on checkout or public routes. */
return static function ( callable $check ): void {
	global $wpdb;
	if ( '1' !== getenv( 'CETECH_DE_NATIVE_OPENING_QUALIFICATION' ) || ! defined( 'WP_ADMIN' ) || true !== WP_ADMIN || '1' !== (string) get_option( 'cetech_opening_qualification_disposable' ) || ! defined( 'DB_HOST' ) || 1 !== preg_match( '/^127\.0\.0\.1(?::[0-9]+)?$/D', DB_HOST ) || ! defined( 'DB_NAME' ) || 1 !== preg_match( '/^cetech_wp_opening_qualification(?:_[a-z0-9]+)?$/D', DB_NAME ) || ! $wpdb instanceof wpdb || wpdb::class !== get_class( $wpdb ) || is_multisite() || WP_Object_Cache::class !== get_class( $GLOBALS['wp_object_cache'] ) || is_file( WP_CONTENT_DIR . '/object-cache.php' ) || is_file( WP_CONTENT_DIR . '/db.php' ) ) { throw new RuntimeException( 'P02 requires the marked disposable native fixture.' ); }
	foreach ( get_included_files() as $file ) { if ( str_ends_with( str_replace( '\\', '/', $file ), '/tests/bootstrap.php' ) ) { throw new RuntimeException( 'Unit bootstrap is forbidden in P02 native proof.' ); } }
	$root = dirname( __DIR__, 2 ); require_once __DIR__ . '/opening-promise-storage-support.php'; require_once $root . '/tests/Support/DeliveryQuote/QuoteStorageFixtures.php';
	$main = $wpdb; $original = []; foreach ( [ 'wpdb', 'wp_roles', 'wp_user_roles', 'wp_object_cache', 'wp_rewrite', 'current_user', 'user_ID', 'blog_id' ] as $key ) { $original[$key] = [ array_key_exists( $key, $GLOBALS ), $GLOBALS[$key] ?? null ]; }
	$main_snapshot = static function () use ( $main ): array { $out = []; foreach ( DataLifecycleManifest::DOMAIN_TABLE_SUFFIXES as $suffix ) { $rows = $main->get_results( "SELECT * FROM `{$main->prefix}delivery_engine_{$suffix}` ORDER BY id", ARRAY_A ); if ( ! is_array( $rows ) || '' !== $main->last_error ) { throw new RuntimeException( 'P02 main physical snapshot is unavailable.' ); } $out[$suffix] = $rows; } $out['publication'] = $main->get_results( $main->prepare( "SELECT option_id,option_name,option_value,autoload FROM `{$main->options}` WHERE option_name IN (%s,%s) ORDER BY option_name", SchemaVersion::OPTION_NAME, MigrationStatus::OPTION_NAME ), ARRAY_A ); return $out; };
	$main_before = $main_snapshot(); $fixture = null; $standalone = null; $failure = null; $publication_filter = false; $flush_filter = false;
	$deny_calls = 0; $deny = static function ( mixed $new, mixed $old ) use ( &$deny_calls ): mixed { ++$deny_calls; return 1 === $deny_calls ? $old : $new; }; $no_flush = static fn(): bool => false;
	$refuses = static function ( callable $work ): bool { try { $work(); return false; } catch ( Throwable ) { return true; } };
	try {
		$ready = new PromiseStorageReadiness( $main ); $ready->assert_ready(); $ready->verify_stored_records();
		$check( 'NATIVE-W2P02-CURRENT-SCHEMA10-EXACT-38-STORES', '10' === SchemaVersion::TARGET && '10' === (string) get_option( SchemaVersion::OPTION_NAME ) && 38 === count( DataLifecycleManifest::DOMAIN_TABLE_SUFFIXES ) && [ 'ready' => true, 'code' => 'ready' ] === $ready->get_status(), [ 'schema10' => '10' === (string) get_option( SchemaVersion::OPTION_NAME ), 'table_census38' => 38 === count( $main_before ) - 1, 'physical_ready' => $ready->get_status()['ready'] ] );
		$fixture = new CetechNativePromiseStorageFixture( $main ); $fixture->install_schema9(); $fixture->select();
		$owner = QuoteOwner::from_array( array_replace( QuoteFixtures::owner()->facts(), [ 'site_id' => $fixture->site ] ) ); $context = QuoteFixtures::context(); $fixture->factory->fixture_time( QuoteFixtures::time() );
		$fixture->write_option( CetechNativeQuoteLifecycleEvidence::OPTION, CetechNativeQuoteLifecycleEvidence::value( $owner, $context ) );
		$old_provider = new CetechNativeQuoteLifecycleProvider( $context, $fixture->factory );
		$old_service = new QuoteDurableService( $fixture->factory, new QuoteProviderRegistry( [ $old_provider ] ), static fn( QuoteOwner $candidate, string $operation ): bool => $owner->equals( $candidate ) && str_starts_with( $operation, 'delivery_quote.' ), evidence: new CetechNativeQuoteLifecycleEvidence() );
		$old_command = QuoteIssueCommand::create( $owner, $context, 'fixture_v1', 1, 'fixture_v1', 1, 'native-p02-retained-quote' );
		$issued = $old_service->issue( $old_command, QuoteAdmissionAttempt::generate(), RequestContext::create() );
		if ( 'accepted' !== $issued->attempt->outcome->state || null === $issued->quote || null === $issued->command?->reference() ) { throw new RuntimeException( 'P02 retained issue seed did not acknowledge.' ); }
		$accepted = $old_service->accept( $owner, $issued->command->reference(), $issued->quote->header(), $context, RequestContext::create() );
		$old_quote_rows = $fixture->rows( "SELECT * FROM `{$fixture->prefix}delivery_engine_delivery_quotes` ORDER BY id" );
		if ( 'accepted' !== $accepted->attempt->outcome->state || 1 !== count( $old_quote_rows ) ) { throw new RuntimeException( 'P02 retained acceptance seed did not acknowledge.' ); }
		$accepted_row = QuoteStoredRow::from_row( $old_quote_rows[0] ); $old_binding = QuoteStorageFixtures::binding( $accepted_row );
		$seed_owner = $fixture->factory->open(); if ( ! $seed_owner->begin() || ! $seed_owner->validate_tables( DeliveryQuoteSchema::tables( $fixture->prefix ) ) || 1 !== ( new DeliveryQuoteRepository( $seed_owner ) )->insert_binding( $old_binding ) || OperationCommitResult::Acknowledged !== $seed_owner->commit() || ! $seed_owner->retire() ) { throw new RuntimeException( 'P02 synthetic retained binding seed did not acknowledge.' ); }
		$retained_before = $fixture->snapshot( DataLifecycleManifest::RETAINED_QUOTE_DOMAIN_TABLE_SUFFIXES ); $definitions_before = $fixture->definitions( DataLifecycleManifest::RETAINED_QUOTE_DOMAIN_TABLE_SUFFIXES );
		$old_ack = 2 === count( $retained_before['operation_records'] ) && 2 === count( $retained_before['operation_changes'] ) && 'accepted' === $accepted_row->state() && $old_binding->row() === \CetechDeliveryEngine\Domain\DeliveryQuote\QuoteBinding::from_row( $retained_before['delivery_quote_bindings'][0], $accepted_row )->row();
		$check( 'NATIVE-W2P02-SCHEMA9-RETAINED-Q03-ACKNOWLEDGED-HISTORY', '9' === (string) get_option( SchemaVersion::OPTION_NAME ) && 36 === $fixture->table_count() && $old_ack && 1 === $old_provider->captures, [ 'historical_schema9' => '9' === (string) get_option( SchemaVersion::OPTION_NAME ), 'actual_c03_issue_accept' => $old_ack, 'synthetic_binding_declared' => 'fixture_v1' === $accepted_row->header()->profile(), 'old35_snapshot' => 35 === count( $retained_before ) ] );
		$partial = $fixture->prefix . 'delivery_engine_promise_objects'; $ddl = PromiseStorageSchema::create_table_statements( $GLOBALS['wpdb']->get_charset_collate(), $fixture->prefix . 'delivery_engine_' );
		$fixture->execute( $ddl['promise_objects'] ); $fixture->execute( "ALTER TABLE `{$partial}` DROP INDEX site_object" );
		// SHOW FULL COLUMNS.Key summarizes indexes; the repaired index is checked separately.
		$column_definitions = static function () use ( $fixture, $partial ): array { return array_map( static function ( array $column ): array { unset( $column['Key'] ); return $column; }, $fixture->rows( "SHOW FULL COLUMNS FROM `{$partial}`" ) ); }; $partial_columns = $column_definitions();
		$migration = require $root . '/database/migrations/20261009091124_create_promise_storage_tables.php'; $runner = new MigrationRunner( new Logger() ); $runner->set_migrations( [ $migration ] );
		add_filter( 'pre_update_option_' . SchemaVersion::OPTION_NAME, $deny, PHP_INT_MAX, 2 ); $publication_filter = true; $runner->run();
		remove_filter( 'pre_update_option_' . SchemaVersion::OPTION_NAME, $deny, PHP_INT_MAX ); $publication_filter = false;
		$index = $fixture->rows( "SHOW INDEX FROM `{$partial}` WHERE Key_name='site_object'" ); usort( $index, static fn( array $a, array $b ): int => (int) $a['Seq_in_index'] <=> (int) $b['Seq_in_index'] ); $repaired = 4 === count( $index ) && array_column( $index, 'Column_name' ) === [ 'site_id', 'site_key', 'kind', 'logical_id' ] && array_reduce( $index, static fn( bool $valid, array $row ): bool => $valid && '0' === $row['Non_unique'] && null === $row['Sub_part'] && 'BTREE' === $row['Index_type'], true ) && $partial_columns === $column_definitions();
		$check( 'NATIVE-W2P02-COMPATIBLE-PARTIAL-NATIVE-DBDELTA-REPAIR', $repaired && function_exists( 'dbDelta' ) && 39 === $fixture->table_count(), [ 'named_index_repaired' => $repaired, 'native_dbdelta' => function_exists( 'dbDelta' ), 'original_columns_unchanged' => $partial_columns === $column_definitions(), 'complete_owned_census39' => 39 === $fixture->table_count() ] );
		$failed = MigrationStatus::get(); $old_blocked = $old_service->issue( QuoteIssueCommand::create( $owner, $context, 'fixture_v1', 1, 'fixture_v1', 1, 'native-p02-failed-marker-writer' ), QuoteAdmissionAttempt::generate(), RequestContext::create() );
		$fenced = ! ( new PromiseStorageReadiness() )->get_status()['ready'] && ! ( new DeliveryQuoteReadiness() )->get_status()['ready'] && 'accepted' !== $old_blocked->attempt->outcome->state && null === $old_blocked->quote && $retained_before === $fixture->snapshot( DataLifecycleManifest::RETAINED_QUOTE_DOMAIN_TABLE_SUFFIXES );
		$check( 'NATIVE-W2P02-REFUSED-PUBLICATION-FENCES-RETAINED-WRITER', 1 === $deny_calls && '9' === (string) get_option( SchemaVersion::OPTION_NAME ) && 'failed' === ( $failed['status'] ?? null ) && '10' === ( $failed['to_version'] ?? null ) && $fenced, [ 'simulated_native_option_refusal' => 1 === $deny_calls, 'physical_schema9' => '9' === (string) get_option( SchemaVersion::OPTION_NAME ), 'failed_marker_blocks_both_readiness' => $fenced, 'retained_writer_no_effect' => $retained_before === $fixture->snapshot( DataLifecycleManifest::RETAINED_QUOTE_DOMAIN_TABLE_SUFFIXES ) ] );
		$runner->run(); $status = MigrationStatus::get(); $ready = new PromiseStorageReadiness(); $ready->assert_ready(); $ready->verify_stored_records();
		$preserved = $retained_before === $fixture->snapshot( DataLifecycleManifest::RETAINED_QUOTE_DOMAIN_TABLE_SUFFIXES ) && $definitions_before === $fixture->definitions( DataLifecycleManifest::RETAINED_QUOTE_DOMAIN_TABLE_SUFFIXES );
		$check( 'NATIVE-W2P02-NATIVE-FORWARD-MIGRATION-PRESERVES-OLD35', '10' === (string) get_option( SchemaVersion::OPTION_NAME ) && 'success' === ( $status['status'] ?? null ) && PromiseStorageReadiness::MIGRATION_ID === ( $status['migration_id'] ?? null ) && $preserved && wpdb::class === get_class( $GLOBALS['wpdb'] ), [ 'physical_schema10' => '10' === (string) get_option( SchemaVersion::OPTION_NAME ), 'native_wpdb' => wpdb::class === get_class( $GLOBALS['wpdb'] ), 'old35_rows_and_ddl_unchanged' => $preserved, 'migration_acknowledged' => 'success' === ( $status['status'] ?? null ) ] );
		$versions_table = $fixture->prefix . 'delivery_engine_promise_versions'; $fixture->execute( "ALTER TABLE `{$versions_table}` MODIFY body_digest char(63) CHARACTER SET ascii COLLATE ascii_bin NOT NULL" ); $corrupt_definitions = $fixture->definitions( DataLifecycleManifest::DOMAIN_TABLE_SUFFIXES );
		$preflight_refused = $refuses( static fn() => $migration->up() ); $preflight_preserved = $corrupt_definitions === $fixture->definitions( DataLifecycleManifest::DOMAIN_TABLE_SUFFIXES ) && $retained_before === $fixture->snapshot( DataLifecycleManifest::RETAINED_QUOTE_DOMAIN_TABLE_SUFFIXES );
		$fixture->execute( "ALTER TABLE `{$versions_table}` MODIFY body_digest char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL" ); $ready->verify();
		$check( 'NATIVE-W2P02-INCOMPATIBLE-SCHEMA-PREFLIGHT-NO-ALTER', $preflight_refused && $preflight_preserved, [ 'incompatible_column_refused' => $preflight_refused, 'all38_ddl_preserved' => $preflight_preserved, 'retained_business_rows_preserved' => $retained_before === $fixture->snapshot( DataLifecycleManifest::RETAINED_QUOTE_DOMAIN_TABLE_SUFFIXES ) ] );
		$captured = RuleTime::parse( (string) $main->get_var( 'SELECT UTC_TIMESTAMP(6)' ) ); $from = RuleTime::from_epoch_microseconds( $captured->epoch_microseconds() - 86400000000 )->sql(); $until = RuleTime::from_epoch_microseconds( $captured->epoch_microseconds() + 604800000000 )->sql(); $fixture->factory->fixture_time( \CetechDeliveryEngine\Domain\DeliveryQuote\QuoteTime::parse( $captured->sql() ) );
		$binding = PromiseSiteBinding::bind( $fixture->site, 'native-site-' . bin2hex( random_bytes( 6 ) ) ); $authority = new CetechNativePromiseAuthorizer( $binding ); $lifecycle = new PromiseVersionLifecycleService( $binding, $fixture->factory, $authority ); $assignments = new PromiseAssignmentService( $binding, $fixture->factory, $authority ); $reads = new PromiseVersionReadService( $binding, $fixture->factory, $authority );
		$actor = new OperationIdentity( $fixture->site, 'native-p02-internal', 'user:1', 'promise.versions.read', 1, 'promise-versions:' . $binding->site_key(), 'native-p02-private-read' );
		$stored_version = static function ( string $kind, string $id, int $version ) use ( $fixture, $binding ): PromiseStoredVersion { $rows = $fixture->rows( "SELECT * FROM `{$fixture->prefix}delivery_engine_promise_versions` WHERE kind=" . $fixture->literal( $kind ) . ' AND logical_id=' . $fixture->literal( $id ) . ' AND domain_version=' . $version ); if ( 1 !== count( $rows ) ) { throw new RuntimeException( 'P02 fixture exact stored version is unavailable.' ); } return PromiseStoredVersion::from_row( $rows[0], $binding ); };
		$command = static function ( string $action, $body, string $token ) use ( $fixture, $binding, $from, $until ): PromiseVersionCommand { $data = $body->private_facts(); $kind = isset( $data['policy_id'] ) ? 'policy' : 'calendar'; $id = $data['policy_id'] ?? $data['calendar_id']; $objects = $fixture->rows( "SELECT * FROM `{$fixture->prefix}delivery_engine_promise_objects` WHERE kind=" . $fixture->literal( $kind ) . ' AND logical_id=' . $fixture->literal( $id ) ); $versions = $fixture->rows( "SELECT * FROM `{$fixture->prefix}delivery_engine_promise_versions` WHERE kind=" . $fixture->literal( $kind ) . ' AND logical_id=' . $fixture->literal( $id ) . ' AND domain_version=' . $data['version'] ); $object = $objects[0] ?? []; $version = $versions[0] ?? []; $identity = new OperationIdentity( $fixture->site, 'native-p02-internal', 'user:1', $action, 1, PromiseVersionCommand::target_key( $binding, $kind, $id ), $token ); return PromiseVersionCommand::from_array( $identity, $binding, [ 'kind' => $kind, 'logical_id' => $id, 'domain_version' => $data['version'], 'version_uuid' => $version['version_uuid'] ?? RequestContext::create()->request_id, 'body_digest' => $body->digest(), 'scope' => [ 'kind' => 'global', 'target_id' => 0 ], 'body_json' => 'promise.version.create' === $action ? $body->to_private_json() : null, 'declared_from' => $data['effective_from'] ?? $from, 'declared_until' => $data['effective_until'] ?? $until, 'author_user_id' => 1, 'scheduled_author_user_id' => null, 'reason' => 'Native P02 explicit internal fixture', 'preconditions' => [ 'object_revision' => (int) ( $object['revision'] ?? 0 ), 'version_revision' => 'promise.version.create' === $action ? 0 : (int) ( $version['row_revision'] ?? 0 ), 'published_version_id' => (int) ( $object['published_version_id'] ?? 0 ) ] ] ); };
		$attempt = static function ( PromiseVersionCommand $cmd ) use ( $lifecycle ) { return $lifecycle->attempt( $cmd->identity, $cmd, RequestContext::create() ); }; $require_accepted = static function ( $result ): void { if ( 'accepted' !== $result->outcome->state || null === $result->completion ) { throw new RuntimeException( 'P02 explicit lifecycle operation did not acknowledge.' ); } };
		$calendar = CetechNativePromiseBodies::calendar( $binding->site_key() ); $policy = CetechNativePromiseBodies::policy( $binding->site_key(), $from, $until, $calendar->reference() );
		$calendar_create = $command( 'promise.version.create', $calendar, 'calendar-create' ); $policy_create = $command( 'promise.version.create', $policy, 'policy-create' ); $require_accepted( $attempt( $calendar_create ) ); $require_accepted( $attempt( $policy_create ) );
		$draft_refused = $refuses( static fn() => $reads->load_policy_versions( $actor, [ $policy->reference() ] ) ) && $refuses( static fn() => $reads->load_calendar_versions( $actor, [ $calendar->reference() ] ) );
		$check( 'NATIVE-W2P02-TYPED-DRAFT-CREATION-NO-HISTORICAL-DISCLOSURE', $draft_refused && 'draft' === $stored_version( 'policy', 'native-standard', 1 )->state() && 'draft' === $stored_version( 'calendar', 'native-picking', 1 )->state(), [ 'canonical_policy_calendar_bodies' => $policy->to_private_json() === $stored_version( 'policy', 'native-standard', 1 )->body()->to_private_json(), 'both_drafts_refused' => $draft_refused, 'explicit_native_opaque_binding' => $binding->native_site_id() === $fixture->site && (string) $fixture->site !== $binding->site_key() ] );
		$guard_before = $fixture->snapshot( PromiseStorageSchema::SUFFIXES ); $guard = $attempt( $command( 'promise.version.seal', $policy, 'policy-seal-before-calendar' ) ); $source_fenced = 'rejected' === $guard->outcome->state && $guard_before === $fixture->snapshot( PromiseStorageSchema::SUFFIXES );
		$check( 'NATIVE-W2P02-POLICY-SEAL-REFUSES-DRAFT-CALENDAR', $source_fenced, [ 'draft_calendar_source_refused' => 'rejected' === $guard->outcome->state, 'promise_objects_versions_assignments_unchanged' => $source_fenced ] );
		$require_accepted( $attempt( $command( 'promise.version.seal', $calendar, 'calendar-seal' ) ) ); $calendar_publish = $command( 'promise.version.publish', $calendar, 'calendar-publish' ); $require_accepted( $attempt( $calendar_publish ) ); $require_accepted( $attempt( $command( 'promise.version.seal', $policy, 'policy-seal' ) ) ); $policy_publish = $command( 'promise.version.publish', $policy, 'policy-publish' ); $published = $attempt( $policy_publish ); $require_accepted( $published );
		$loaded = $reads->load_policy_versions( $actor, [ $policy->reference() ] ); $loaded_calendar = $reads->load_calendar_versions( $actor, [ $calendar->reference() ] ); $pubrow = $stored_version( 'policy', 'native-standard', 1 ); $ready->verify_stored_records();
		$check( 'NATIVE-W2P02-PUBLISHED-POLICY-CALENDAR-ORIGINAL-C03-LINKS', count( $loaded ) === 1 && count( $loaded_calendar ) === 1 && $loaded[0]->digest() === $policy->digest() && $loaded_calendar[0]->digest() === $calendar->digest() && 'published' === $pubrow->state() && $pubrow->published_at()?->sql() === $captured->sql() && $from !== $pubrow->published_at()?->sql(), [ 'exact_private_bodies' => $loaded[0]->to_private_json() === $policy->to_private_json() && $loaded_calendar[0]->to_private_json() === $calendar->to_private_json(), 'physical_acknowledgment_backlinks_verified' => null !== $pubrow->publication_receipt(), 'authored_interval_distinct_from_publication' => $from !== $pubrow->published_at()?->sql(), 'captured_native_sql_clock' => $pubrow->published_at()?->sql() === $captured->sql() ] );
		$replay_before = $fixture->snapshot(); $replay = $lifecycle->reconcile( $policy_publish->identity, $policy_publish, RequestContext::create() ); $replay_exact = 'accepted' === $replay->outcome->state && $replay->replayed && $published->completion->to_json() === $replay->completion?->to_json() && $replay_before === $fixture->snapshot();
		$check( 'NATIVE-W2P02-ORIGINAL-PUBLISH-REPLAY-NO-CURRENT-REPEAT', $replay_exact, [ 'original_completion_exact' => $replay_exact, 'all38_history_unchanged' => $replay_before === $fixture->snapshot() ] );
		$key = [ 'scope_kind' => 'global', 'scope_id' => 0, 'service_kind' => 'built_in', 'service_code' => 'standard', 'endpoint' => 'doorstep', 'endpoint_kind' => 'doorstep' ];
		$assign = static function ( string $mode, int $revision, int $generation, string $token ) use ( $fixture, $binding, $key, $policy ): PromiseAssignmentCommand { $id = new OperationIdentity( $fixture->site, 'native-p02-internal', 'user:1', PromiseAssignmentCommand::OPERATION, 1, PromiseAssignmentCommand::target_key( $binding, $key ), $token ); return PromiseAssignmentCommand::from_array( $id, $binding, [ 'key' => $key, 'mode' => $mode, 'policy_reference' => 'assigned' === $mode ? $policy->reference()->private_facts() : null, 'expected_revision' => $revision, 'expected_generation' => $generation, 'author_user_id' => 1, 'reason' => 'Native P02 assignment fixture' ] ); };
		$assign_cmd = $assign( 'assigned', 0, 0, 'assignment-first' ); $require_accepted( $assignments->attempt( $assign_cmd->identity, $assign_cmd, RequestContext::create() ) ); $assignment_rows = $fixture->snapshot( [ 'promise_assignments' ] ); $stale_assign = $assign( 'disabled', 0, 0, 'assignment-stale' ); $stale_result = $assignments->attempt( $stale_assign->identity, $stale_assign, RequestContext::create() );
		$assignment_actor = new OperationIdentity( $fixture->site, 'native-p02-internal', 'user:1', 'promise.assignment.read', 1, PromiseAssignmentCommand::target_key( $binding, $key ), 'native-p02-private-assignment-read' ); $effective = $reads->capture_assignment( $assignment_actor, $key, $captured ); $at_end = $reads->capture_assignment( $assignment_actor, $key, RuleTime::parse( $until ) );
		$check( 'NATIVE-W2P02-ASSIGNMENT-CAS-AND-CAPTURED-EFFECTIVE-BOUNDS', 'rejected' === $stale_result->outcome->state && $assignment_rows === $fixture->snapshot( [ 'promise_assignments' ] ) && 'assigned' === $effective->state() && 'unavailable' === $at_end->state(), [ 'stale_assignment_refused' => 'rejected' === $stale_result->outcome->state, 'assignment_row_unchanged' => $assignment_rows === $fixture->snapshot( [ 'promise_assignments' ] ), 'captured_instant_eligible' => 'assigned' === $effective->state(), 'exclusive_end_ineligible' => 'unavailable' === $at_end->state() ] );
		$policy2 = CetechNativePromiseBodies::policy( $binding->site_key(), $from, $until, $calendar->reference(), 2 ); $create2 = $command( 'promise.version.create', $policy2, 'policy2-create' ); $require_accepted( $attempt( $create2 ) ); $stale_identity = new OperationIdentity( $fixture->site, 'native-p02-internal', 'user:1', $create2->identity->operation, 1, $create2->identity->target_key, 'policy2-stale-original' ); $stale_cmd = PromiseVersionCommand::from_array( $stale_identity, $binding, $create2->private_facts() ); $stale_before = $fixture->snapshot( PromiseStorageSchema::SUFFIXES ); $stale_version = $attempt( $stale_cmd ); $stale_unchanged = $stale_before === $fixture->snapshot( PromiseStorageSchema::SUFFIXES );
		$require_accepted( $attempt( $command( 'promise.version.seal', $policy2, 'policy2-seal' ) ) ); $require_accepted( $attempt( $command( 'promise.version.publish', $policy2, 'policy2-publish' ) ) ); $old_loaded = $reads->load_policy_versions( $actor, [ $policy->reference(), $policy2->reference() ] );
		$check( 'NATIVE-W2P02-SUCCESSOR-RETIRES-HEAD-PRESERVES-EXACT-HISTORY', 'rejected' === $stale_version->outcome->state && 'retired' === $stored_version( 'policy', 'native-standard', 1 )->state() && count( $old_loaded ) === 2 && $old_loaded[0]->to_private_json() === $policy->to_private_json() && $old_loaded[1]->to_private_json() === $policy2->to_private_json(), [ 'stale_version_revision_refused' => 'rejected' === $stale_version->outcome->state && $stale_unchanged, 'former_published_body_retained' => $old_loaded[0]->to_private_json() === $policy->to_private_json(), 'successor_body_exact' => $old_loaded[1]->to_private_json() === $policy2->to_private_json(), 'old_head_retired' => 'retired' === $stored_version( 'policy', 'native-standard', 1 )->state() ] );
		$authority->admitted = false; $denied = $refuses( static fn() => $reads->load_policy_versions( $actor, [ $policy->reference() ] ) ); $authority->admitted = true; $foreign = $policy->reference()->private_facts(); $foreign['site_id'] = 'foreign-native-site'; $foreign_refused = $refuses( static fn() => $reads->load_policy_versions( $actor, [ PromisePolicyReference::from_array( $foreign ) ] ) ); $missing = $calendar->reference()->private_facts(); $missing['calendar_id'] = 'not-stored'; $mixed_refused = $refuses( static fn() => $reads->load_calendar_versions( $actor, [ $calendar->reference(), PromiseCalendarReference::from_array( $missing ) ] ) );
		$check( 'NATIVE-W2P02-PRIVATE-LOAD-REAUTHORIZES-COMPLETE-EXACT-SET', $denied && $foreign_refused && $mixed_refused, [ 'revoked_permission_refused' => $denied, 'foreign_opaque_site_refused' => $foreign_refused, 'missing_bulk_member_refuses_entire_load' => $mixed_refused ] );
		$private_before = $fixture->snapshot(); $historical = $stored_version( 'policy', 'native-standard', 1 ); $bad_body = json_decode( $historical->row()['body_json'], true, 512, JSON_THROW_ON_ERROR ); $bad_body['format_version'] = 2; $body_corruptions = [ json_encode( $bad_body, JSON_THROW_ON_ERROR ), ' ' . $historical->row()['body_json'] ]; $corrupt_refused = true;
		foreach ( $body_corruptions as $bytes ) { $fixture->execute( "UPDATE `{$versions_table}` SET body_json=" . $fixture->literal( $bytes ) . ' WHERE id=' . $historical->id() ); $corrupt_refused = $refuses( static fn() => $reads->load_policy_versions( $actor, [ $policy->reference() ] ) ) && $refuses( static fn() => $ready->verify_stored_records() ) && $corrupt_refused; }
		$fixture->execute( "UPDATE `{$versions_table}` SET body_json=" . $fixture->literal( $historical->row()['body_json'] ) . ' WHERE id=' . $historical->id() );
		$source = $historical->publication_receipt()->private_facts(); $record_table = $fixture->prefix . 'delivery_engine_operation_records'; $ack_row = $fixture->rows( "SELECT id,completion_json FROM `{$record_table}` WHERE namespace_hash=" . $fixture->literal( $source['namespace_hash'] ) )[0]; $fixture->execute( "UPDATE `{$record_table}` SET completion_json='{}' WHERE id=" . (int) $ack_row['id'] ); $backlink_refused = $refuses( static fn() => $reads->load_policy_versions( $actor, [ $policy->reference() ] ) ) && $refuses( static fn() => $ready->verify_stored_records() ); $fixture->execute( "UPDATE `{$record_table}` SET completion_json=" . $fixture->literal( $ack_row['completion_json'] ) . ' WHERE id=' . (int) $ack_row['id'] );
		$check( 'NATIVE-W2P02-CORRUPT-BODY-OR-ACK-BACKLINK-REFUSES', $corrupt_refused && $backlink_refused && $private_before === $fixture->snapshot(), [ 'unknown_body_format_refused' => $corrupt_refused, 'noncanonical_body_refused' => $corrupt_refused, 'original_ack_backlink_refused' => $backlink_refused, 'tracked_stimulus_bytes_restored' => $private_before === $fixture->snapshot() ] );
		$alloptions = wp_cache_get( 'alloptions', 'options' ); $alloptions = is_array( $alloptions ) ? $alloptions : []; $alloptions[SchemaVersion::OPTION_NAME] = '9'; wp_cache_set( 'alloptions', $alloptions, 'options' ); wp_cache_set( SchemaVersion::OPTION_NAME, '9', 'options' ); $advisory = (string) get_option( SchemaVersion::OPTION_NAME ); $physical_loaded = $reads->load_policy_versions( $actor, [ $policy->reference() ] ); $physical_ready = $ready->get_status()['ready']; $GLOBALS['wp_object_cache'] = new WP_Object_Cache();
		$installed_root = dirname( (string) ( new ReflectionClass( CetechDeliveryEngine\Bootstrap\Plugin::class ) )->getFileName(), 3 );
		$child = CetechNativePromiseStorageFixture::reader( [ 'wp_load' => rtrim( ABSPATH, '/' ) . '/wp-load.php', 'plugin_root' => $installed_root, 'prefix' => $fixture->prefix, 'site' => $fixture->site, 'site_key' => $binding->site_key(), 'policy_reference' => $policy->reference()->private_facts(), 'calendar_reference' => $calendar->reference()->private_facts(), 'policy_body_hash' => hash( 'sha256', $policy->to_private_json() ), 'calendar_body_hash' => hash( 'sha256', $calendar->to_private_json() ) ] );
		$fresh = true === ( $child['transport_complete'] ?? null ) && 'PASS' === ( $child['status'] ?? null ) && is_int( $child['process_id'] ?? null ) && getmypid() !== $child['process_id'] && true === ( $child['wp_load'] ?? null ) && true === ( $child['installed_candidate_autoload'] ?? null ) && true === ( $child['default_object_cache'] ?? null ) && true === ( $child['exact_historical_bodies'] ?? null ) && true === ( $child['all_owners_retired'] ?? null );
		$check( 'NATIVE-W2P02-PHYSICAL-CACHE-AUTHORITY-AND-FRESH-WP-LOAD', '9' === $advisory && $physical_ready && $physical_loaded[0]->digest() === $policy->digest() && $fresh, [ 'warmed_advisory_schema9' => '9' === $advisory, 'physical_schema10_ready' => $physical_ready, 'fresh_os_wp_load_installed_autoload' => $fresh, 'fresh_exact_historical_bodies' => true === ( $child['exact_historical_bodies'] ?? null ), 'fresh_native_owners_retired' => true === ( $child['all_owners_retired'] ?? null ) ] );
		$fixture->prepare_scheduler(); $preserved_all = $fixture->snapshot(); if ( is_object( $original['wp_rewrite'][1] ) ) { $GLOBALS['wp_rewrite'] = clone $original['wp_rewrite'][1]; } add_filter( 'flush_rewrite_rules_hard', $no_flush, PHP_INT_MAX ); $flush_filter = true; Deactivator::deactivate();
		$check( 'NATIVE-W2P02-DEACTIVATION-PRESERVES-ALL38-HISTORY', $preserved_all === $fixture->snapshot(), [ 'native_deactivator' => $preserved_all === $fixture->snapshot(), 'all38_exact_full_rows_preserved' => $preserved_all === $fixture->snapshot() ] );
		$fixture->reset_roles(); update_option( DataLifecycleManifest::CAPABILITIES_MARKER, 4, false ); update_option( DataLifecycleManifest::UNINSTALL_INTENT, 1, false ); Uninstaller::uninstall(); $uninstall = json_decode( (string) get_option( DataLifecycleManifest::UNINSTALL_STATUS, '' ), true );
		$check( 'NATIVE-W2P02-COMPOSER-EXPLICIT-UNINSTALL-PRESERVES-ALL38', 'completed' === ( $uninstall['status'] ?? null ) && false === get_option( DataLifecycleManifest::UNINSTALL_INTENT, false ) && $preserved_all === $fixture->snapshot(), [ 'native_uninstall_completed' => 'completed' === ( $uninstall['status'] ?? null ), 'all38_exact_full_rows_preserved' => $preserved_all === $fixture->snapshot(), 'intent_consumed' => false === get_option( DataLifecycleManifest::UNINSTALL_INTENT, false ) ] );
		$fixture->reset_roles(); update_option( DataLifecycleManifest::CAPABILITIES_MARKER, 4, false ); update_option( DataLifecycleManifest::UNINSTALL_INTENT, 1, false ); $standalone = sys_get_temp_dir() . '/cetech-q02-standalone-' . bin2hex( random_bytes( 8 ) ); CetechNativeQuoteStorageFixture::copy_standalone( $root, $standalone );
		$fallback = CetechNativeQuoteStorageFixture::child( __DIR__ . '/opening-data-lifecycle-uninstall-reader.php', [ 'wp_load' => rtrim( ABSPATH, '/' ) . '/wp-load.php', 'uninstall' => $standalone . '/uninstall.php', 'prefix' => $fixture->prefix, 'site' => $fixture->site ] );
		$check( 'NATIVE-W2P02-FRESH-WP-ONLY-UNINSTALL-PRESERVES-ALL38', 'PASS' === ( $fallback['status'] ?? null ) && 'completed' === ( $fallback['uninstall_status'] ?? null ) && false === ( $fallback['intent_present'] ?? null ) && false === ( $fallback['composer_loaded'] ?? null ) && false === ( $fallback['woocommerce_loaded'] ?? null ) && $preserved_all === $fixture->snapshot(), [ 'fresh_wp_only_uninstall_completed' => 'completed' === ( $fallback['uninstall_status'] ?? null ), 'no_vendor_or_woocommerce_loaded' => false === ( $fallback['composer_loaded'] ?? null ) && false === ( $fallback['woocommerce_loaded'] ?? null ), 'all38_exact_full_rows_preserved' => $preserved_all === $fixture->snapshot(), 'intent_consumed' => false === ( $fallback['intent_present'] ?? null ) ] );
	} catch ( Throwable $error ) { $failure = $error; throw $error; }
	finally {
		if ( $publication_filter ) { remove_filter( 'pre_update_option_' . SchemaVersion::OPTION_NAME, $deny, PHP_INT_MAX ); } if ( $flush_filter ) { remove_filter( 'flush_rewrite_rules_hard', $no_flush, PHP_INT_MAX ); }
		$owned_cleanup = true; if ( null !== $fixture ) { try { $fixture->factory->fixture_time( null ); $owned_cleanup = $fixture->cleanup(); } catch ( Throwable ) { $owned_cleanup = false; } } $private_removed = null === $standalone || CetechNativeQuoteStorageFixture::remove_standalone( $standalone );
		foreach ( $original as $key => [ $exists, $value ] ) { if ( $exists ) { $GLOBALS[$key] = $value; } else { unset( $GLOBALS[$key] ); } }
		$main_preserved = $main_before === $main_snapshot(); $context_restored = $GLOBALS['wpdb'] === $main && $GLOBALS['wp_object_cache'] === $original['wp_object_cache'][1] && get_current_blog_id() === (int) $original['blog_id'][1]; $schema10 = '10' === (string) get_option( SchemaVersion::OPTION_NAME );
		try { $check( 'NATIVE-W2P02-TRACKED-FIXTURE-AND-MAIN-CLEANUP', $owned_cleanup && $private_removed && $main_preserved && $context_restored && $schema10, [ 'pre_registered_owned_tables_removed' => $owned_cleanup, 'all_native_owners_retired' => $owned_cleanup, 'private_standalone_files_removed' => $private_removed, 'main38_rows_and_publication_unchanged' => $main_preserved, 'native_context_restored' => $context_restored, 'main_schema10_preserved' => $schema10 ] ); } catch ( Throwable $cleanup_error ) { if ( null === $failure ) { throw $cleanup_error; } }
	}
};
