<?php

declare(strict_types=1);

use CetechDeliveryEngine\Domain\Contracts\RequestContext;
use CetechDeliveryEngine\Domain\DeliveryQuote\QuoteId;
use CetechDeliveryEngine\Domain\DeliveryQuote\QuoteTime;
use CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState;
use CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore;
use CetechDeliveryEngine\Integrations\DeliveryQuote\QuoteReviewRuntime;

return static function ( callable $check ): void {
	require_once __DIR__ . '/opening-quote-cart-support.php';
	global $wpdb; $fixture = new CetechQuoteCartFixture( $wpdb ); $phase = 'native_fixture'; $completed = [];
	$case = static function ( string $id, bool $condition, array $evidence ) use ( $check, &$completed ): void { $completed[] = $id; $check( $id, $condition, $evidence ); };
	$first_id = 'NATIVE-W2Q05-CART-PREPARED-MOUNT-OFF-NO-EFFECT';
	$phase_ids = [ 'native_fixture' => $first_id, 'readonly' => 'NATIVE-W2Q05-CART-READ-TOTALS-NO-QUOTE-ACCEPTANCE', 'refresh' => 'NATIVE-W2Q05-CART-EXPLICIT-REFRESH-EARLY-ADMISSION-REAL-PRICE', 'confirm' => 'NATIVE-W2Q05-CART-EXPLICIT-CONFIRM-REPLAY-ONE-ACCEPT', 'changed' => 'NATIVE-W2Q05-CART-WARM-SOURCE-CHANGE-IMMUTABLE-BODY', 'new_review' => 'NATIVE-W2Q05-CART-REFRESH-NEW-PRICE-BEFORE-CONFIRM-CHOICES', 'stale_generation' => 'NATIVE-W2Q05-CART-STALE-GENERATION-CANNOT-ACCEPT-NEW-QUOTE', 'lost_ack' => 'NATIVE-W2Q05-CART-LOST-ACCEPT-ACK-ORIGINAL-RETRY', 'expiry' => 'NATIVE-W2Q05-CART-DATABASE-EXPIRY-RETAINS-CHOICES', 'pause' => 'NATIVE-W2Q05-CART-PAUSED-REFRESH-NO-PREPARATION-NO-QUOTE', 'privacy' => 'NATIVE-W2Q05-CART-SHOPPER-DTO-FINITE-NO-PRIVATE-FACTS' ];
	try {
		$fixture->prepare(); $runtime = new QuoteReviewRuntime( $fixture->service, true ); $baseline = $fixture->history(); $placement_baseline = CetechQuoteCartHttpFixture::placement_counts( $wpdb ); $choices = $fixture->choice_digest();
		$off = new QuoteReviewRuntime( $fixture->service ); $off->register(); $off_view = $off->current_facts();
		$case( $first_id, 'unavailable' === $off_view['status'] && $baseline === $fixture->history() && 'WP_Object_Cache' === get_class( $GLOBALS['wp_object_cache'] ), [ 'actual_installed_native_wp' => true, 'default_object_cache' => 'WP_Object_Cache' === get_class( $GLOBALS['wp_object_cache'] ), 'default_mount_off' => 'unavailable' === $off_view['status'], 'no_effects' => $baseline === $fixture->history() ] );
		$phase = 'readonly'; $before = $fixture->history(); $read = $runtime->current_facts(); WC()->cart->calculate_totals(); $read_after = $runtime->current_facts();
		$case( 'NATIVE-W2Q05-CART-READ-TOTALS-NO-QUOTE-ACCEPTANCE', 'no_quote' === $read['status'] && 'no_quote' === $read_after['status'] && $before === $fixture->history(), [ 'status_before' => $read['status'], 'status_after_totals' => $read_after['status'], 'quote_operation_budget_history_unchanged' => $before === $fixture->history() ] );
		$phase = 'refresh'; $fixture->factory->timeline = []; $first_token = QuoteId::generate()->value(); $review = $runtime->dispatch( [ 'action' => 'refresh', 'generation' => 0, 'review_token' => $first_token ] );
		$gate_at = array_search( 'budget_commit', $fixture->factory->timeline, true ); $source_at = array_search( 'owned_source_read', $fixture->factory->timeline, true ); $quote_a = $review['quote']['quote_id'] ?? null;
		$refresh_ok = 'review_required' === $review['status'] && true === $review['can_confirm'] && is_string( $quote_a ) && '7.70' === ( $review['quote']['money'][0]['display_total']['amount'] ?? null ) && false !== $gate_at && false !== $source_at && $gate_at < $source_at;
		$refresh_evidence = [ 'status' => $review['status'], 'generation' => $review['generation'], 'real_retained_native_capture' => is_string( $quote_a ), 'native_display_amount' => $review['quote']['money'][0]['display_total']['amount'] ?? null, 'early_gate_commit_before_owned_source_read' => false !== $gate_at && false !== $source_at && $gate_at < $source_at, 'setup_native_cart_calculation_is_separate' => true ];
		if ( ! $refresh_ok ) { $after_refresh = $fixture->history(); $old_quote_ids = array_column( $baseline['delivery_quotes'], 'id' ); $new_quote_states = []; foreach ( $after_refresh['delivery_quotes'] as $row ) { if ( ! in_array( $row['id'], $old_quote_ids, true ) && $row['owner_digest'] === $fixture->owner()->digest() ) { $new_quote_states[] = in_array( $row['state'], [ 'issued', 'accepted', 'invalidated', 'stripped' ], true ) ? $row['state'] : 'unknown'; } } $refresh_evidence['diagnostics'] = [ ...$fixture->observed_environment->diagnostics, 'observed_owned_source_reads' => $fixture->factory->source_reads, 'observed_quote_writes' => $fixture->factory->quote_writes, 'observed_budget_writes' => $fixture->factory->budget_writes, 'physical_new_owned_quote_count' => count( $new_quote_states ), 'physical_new_owned_quote_states' => $new_quote_states, 'physical_new_event_count' => count( $after_refresh['operation_changes'] ) - count( $baseline['operation_changes'] ), 'owned_observations_do_not_cover_all_global_native_sql' => true ];
			// This later read-only observation is not the original swallowed failure timing.
			$writes_before_followup = [ $fixture->factory->quote_writes, $fixture->factory->budget_writes ];
			$followup = $fixture->observed_environment->readonly_followup();
			$followup['history_unchanged'] = $after_refresh === $fixture->history();
			$followup['owned_effect_writes_unchanged'] = $writes_before_followup === [ $fixture->factory->quote_writes, $fixture->factory->budget_writes ];
			$followup['all_owned_connections_retired'] = $fixture->factory->close_all() && $fixture->factory->all_retired();
			$refresh_evidence['diagnostics']['followup'] = $followup;
		}
		$case( 'NATIVE-W2Q05-CART-EXPLICIT-REFRESH-EARLY-ADMISSION-REAL-PRICE', $refresh_ok, $refresh_evidence );
		$phase = 'confirm'; $confirmed = $runtime->dispatch( [ 'action' => 'confirm', 'generation' => $review['generation'] ] ); $accepted_history = $fixture->history(); $replay = $runtime->dispatch( [ 'action' => 'confirm', 'generation' => $review['generation'] ] );
		$case( 'NATIVE-W2Q05-CART-EXPLICIT-CONFIRM-REPLAY-ONE-ACCEPT', 'confirmed' === $confirmed['status'] && 'confirmed' === $replay['status'] && 'accepted' === $fixture->row( $quote_a )['state'] && $accepted_history === $fixture->history(), [ 'first_status' => $confirmed['status'], 'replay_status' => $replay['status'], 'physical_accepted' => 'accepted' === $fixture->row( $quote_a )['state'], 'replay_history_unchanged' => $accepted_history === $fixture->history(), 'placement_bindings_unchanged' => $baseline['delivery_quote_bindings'] === $fixture->history()['delivery_quote_bindings'] ] );
		$phase = 'changed'; $body_a = $fixture->row( $quote_a )['private_body_json']; $fixture->native->warm_sources(); $fixture->native->physical_update( 'rate_cards', $fixture->native->rate, [ 'base_amount' => '9.0000' ] ); $changed = $runtime->current_facts();
		$case( 'NATIVE-W2Q05-CART-WARM-SOURCE-CHANGE-IMMUTABLE-BODY', in_array( $changed['status'], [ 'changed', 'unavailable' ], true ) && ! $changed['can_confirm'] && $body_a === $fixture->row( $quote_a )['private_body_json'], [ 'current_status' => $changed['status'], 'confirmation_refused' => ! $changed['can_confirm'], 'accepted_body_unchanged' => $body_a === $fixture->row( $quote_a )['private_body_json'], 'warm_cache_was_populated' => true ] );
		$phase = 'new_review'; $fixture->native->recalculate(); $new = $runtime->dispatch( [ 'action' => 'refresh', 'generation' => $review['generation'], 'review_token' => QuoteId::generate()->value() ] ); $quote_b = $new['quote']['quote_id'] ?? null;
		$case( 'NATIVE-W2Q05-CART-REFRESH-NEW-PRICE-BEFORE-CONFIRM-CHOICES', 'review_required' === $new['status'] && true === $new['can_confirm'] && is_string( $quote_b ) && $quote_a !== $quote_b && '9.90' === ( $new['quote']['money'][0]['display_total']['amount'] ?? null ) && 'issued' === $fixture->row( $quote_b )['state'] && $choices === $fixture->choice_digest(), [ 'status' => $new['status'], 'native_display_amount' => $new['quote']['money'][0]['display_total']['amount'] ?? null, 'different_quote' => $quote_a !== $quote_b, 'physical_still_issued' => is_string( $quote_b ) && 'issued' === $fixture->row( $quote_b )['state'], 'choices_destination_unchanged' => $choices === $fixture->choice_digest() ] );
		$phase = 'stale_generation'; $before_stale = $fixture->history(); $stale = $runtime->dispatch( [ 'action' => 'confirm', 'generation' => $review['generation'] ] );
		$case( 'NATIVE-W2Q05-CART-STALE-GENERATION-CANNOT-ACCEPT-NEW-QUOTE', 'changed' === $stale['status'] && $before_stale === $fixture->history() && 'issued' === $fixture->row( $quote_b )['state'], [ 'status' => $stale['status'], 'history_unchanged' => $before_stale === $fixture->history(), 'new_quote_stays_issued' => 'issued' === $fixture->row( $quote_b )['state'] ] );
		$phase = 'lost_ack'; $opened_accept = $fixture->sessions->load( $fixture->owner() ); $original_accept = CetechDeliveryEngine\Application\DeliveryQuote\QuoteDurableCommand::accept( $opened_accept->owner(), $opened_accept->reference(), $opened_accept->header(), null );
		$fixture->factory->mask_next_quote_ack = true; $uncertain = $runtime->dispatch( [ 'action' => 'confirm', 'generation' => $new['generation'] ] ); $unknown_history = $fixture->history(); $retried = $runtime->dispatch( [ 'action' => 'retry', 'generation' => $new['generation'] ] ); $published_history = $fixture->history();
		$retry_delta = CetechQuoteCartFixture::accept_retry_delta( $unknown_history, $published_history, $original_accept ); $retried_again = $runtime->dispatch( [ 'action' => 'retry', 'generation' => $new['generation'] ] ); $second_retry_unchanged = 'confirmed' === $retried_again['status'] && $published_history === $fixture->history(); $generation_retained = $new['generation'] === $uncertain['generation'] && $new['generation'] === $retried['generation'] && $new['generation'] === $retried_again['generation'];
		$case( 'NATIVE-W2Q05-CART-LOST-ACCEPT-ACK-ORIGINAL-RETRY', 'unconfirmed' === $uncertain['status'] && $uncertain['can_retry'] && ! $uncertain['can_refresh'] && 1 === $fixture->factory->masked_quote_acks && $fixture->factory->fault_retired() && 'confirmed' === $retried['status'] && ! in_array( false, $retry_delta, true ) && $second_retry_unchanged && $generation_retained, [ 'first_status' => $uncertain['status'], 'retry_status' => $retried['status'], 'actually_sent_ack_masked_once' => 1 === $fixture->factory->masked_quote_acks, 'uncertain_owner_retired' => $fixture->factory->fault_retired(), ...$retry_delta, 'subsequent_retry_history_unchanged' => $second_retry_unchanged, 'original_generation_retained' => $generation_retained ] );
		$phase = 'expiry'; $header = $fixture->sessions->load( $fixture->owner() )->header(); $fixture->factory->clock = $header->expires_at(); $expired = $runtime->current_facts(); $expired_history = $fixture->history(); $confirm_expired = $runtime->dispatch( [ 'action' => 'confirm', 'generation' => $new['generation'] ] );
		$case( 'NATIVE-W2Q05-CART-DATABASE-EXPIRY-RETAINS-CHOICES', 'expired' === $expired['status'] && 'expired' === ( $expired['quote']['status'] ?? null ) && false === ( $expired['quote']['currently_applicable'] ?? null ) && 'expired' === $confirm_expired['status'] && $choices === $fixture->choice_digest() && $expired_history === $fixture->history(), [ 'status' => $expired['status'], 'nested_status' => $expired['quote']['status'] ?? null, 'nested_currently_applicable' => $expired['quote']['currently_applicable'] ?? null, 'verified_native_sql_clock' => $fixture->factory->verified_clocks > 0, 'clock_source' => 'disposable_per_connection_SET_timestamp', 'choices_destination_unchanged' => $choices === $fixture->choice_digest(), 'no_new_acceptance' => $expired_history === $fixture->history() ] ); $fixture->factory->clock = null;
		$phase = 'pause'; $fixture->native->set_option( EmergencyControlStore::OPTION_NAME, EmergencyControlState::record_json( get_current_blog_id(), 'checkout_suspended', 900002, 'operator_pause', 1, time() ) ); $before_pause = $fixture->history(); $reads_before = $fixture->factory->source_reads; $quote_writes_before = $fixture->factory->quote_writes;
		$paused = $runtime->dispatch( [ 'action' => 'refresh', 'generation' => $new['generation'], 'review_token' => QuoteId::generate()->value() ] );
		$case( 'NATIVE-W2Q05-CART-PAUSED-REFRESH-NO-PREPARATION-NO-QUOTE', 'unavailable' === $paused['status'] && $reads_before === $fixture->factory->source_reads && $quote_writes_before === $fixture->factory->quote_writes && $before_pause === $fixture->history(), [ 'status' => $paused['status'], 'observed_owned_source_reads_unchanged' => $reads_before === $fixture->factory->source_reads, 'quote_writes_unchanged' => $quote_writes_before === $fixture->factory->quote_writes, 'quote_operation_budget_history_unchanged' => $before_pause === $fixture->history(), 'native_cart_setup_not_counted_as_quote_preparation' => true ] ); $fixture->native->restore_option( EmergencyControlStore::OPTION_NAME );
		$phase = 'privacy'; $safe = CetechQuoteCartFixture::public_safe( $review ) && CetechQuoteCartFixture::public_safe( $uncertain ) && CetechQuoteCartFixture::public_safe( $expired );
		$case( 'NATIVE-W2Q05-CART-SHOPPER-DTO-FINITE-NO-PRIVATE-FACTS', $safe && $baseline['delivery_quote_bindings'] === $fixture->history()['delivery_quote_bindings'] && $placement_baseline === CetechQuoteCartHttpFixture::placement_counts( $wpdb ), [ 'strict_shopper_allowlist' => $safe, 'private_references_cost_sources_absent' => $safe, 'placement_bindings_unchanged' => $baseline['delivery_quote_bindings'] === $fixture->history()['delivery_quote_bindings'], 'no_order_writer_activated' => $placement_baseline === CetechQuoteCartHttpFixture::placement_counts( $wpdb ) ] );
	} catch ( Throwable $error ) {
		$active_id = $phase_ids[$phase]; if ( ! in_array( $active_id, $completed, true ) ) { $check( $active_id, false, [ 'phase' => $phase, 'error_class' => $error instanceof Error ? 'Error' : ( $error instanceof InvalidArgumentException ? 'InvalidArgumentException' : 'RuntimeException' ), 'native_refusal_line' => CetechNativeQuoteProviderFixture::native_refusal_line( $error ), 'required_case_incomplete' => true ] ); }
		throw $error;
	} finally {
		try { $cleanup = $fixture->cleanup(); $check( 'NATIVE-W2Q05-CART-FIXTURE-CLEANUP', true === $cleanup['cleanup_restored'], $cleanup ); }
		catch ( Throwable $error ) { if ( ! isset( $cleanup ) ) { $check( 'NATIVE-W2Q05-CART-FIXTURE-CLEANUP', false, [ 'cleanup_restored' => false, 'error_class' => $error instanceof Error ? 'Error' : ( $error instanceof InvalidArgumentException ? 'InvalidArgumentException' : 'RuntimeException' ) ] ); } else { throw $error; } }
	}
};
