<?php
declare(strict_types=1);

use CetechDeliveryEngine\Application\EmergencyControl\EmergencyCheckoutAdmissionService;
use CetechDeliveryEngine\Application\EmergencyControl\EmergencyCheckoutQuoteValidator;
use CetechDeliveryEngine\Application\EmergencyControl\EmergencyControlCommand;
use CetechDeliveryEngine\Application\EmergencyControl\EmergencyControlProjection;
use CetechDeliveryEngine\Application\EmergencyControl\EmergencyOwnership;
use CetechDeliveryEngine\Application\EmergencyControl\EmergencyOwnershipClassifier;
use CetechDeliveryEngine\Application\EmergencyControl\EmergencyOwnershipLatch;
use CetechDeliveryEngine\Bootstrap\DataLifecycleManifest;
use CetechDeliveryEngine\Bootstrap\Plugin;
use CetechDeliveryEngine\Domain\Contracts\ContractError;
use CetechDeliveryEngine\Domain\Contracts\RequestContext;
use CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlDiagnostics;
use CetechDeliveryEngine\Integrations\EmergencyControl\EmergencyCheckoutHooks;
use CetechDeliveryEngine\Integrations\EmergencyControl\EmergencyControlResponse;
use CetechDeliveryEngine\Integrations\EmergencyControl\EmergencyControlRuntime;

/** Actual default-cache WordPress/Woo boundaries; no unit bootstrap or fake product source. */
return static function ( callable $check, ?array $history = null ): void {
	global $wpdb;
	if ( '1' !== getenv( 'CETECH_DE_NATIVE_OPENING_QUALIFICATION' ) || true !== WP_ADMIN || '1' !== (string) get_option( 'cetech_opening_qualification_disposable' ) || ! preg_match( '/^127\.0\.0\.1(?::[0-9]+)?$/D', DB_HOST ) || ! preg_match( '/^cetech_wp_opening_qualification(?:_[a-z0-9]+)?$/D', DB_NAME ) || ! $wpdb instanceof wpdb || is_multisite() || WP_Object_Cache::class !== get_class( $GLOBALS['wp_object_cache'] ) ) { throw new RuntimeException( 'C07 native proof requires the marked default-cache site.' ); }
	foreach ( get_included_files() as $file ) { if ( str_ends_with( str_replace( '\\', '/', $file ), '/tests/bootstrap.php' ) ) { throw new RuntimeException( 'Unit bootstrap is forbidden in native C07 proof.' ); } }
	require_once __DIR__ . '/opening-emergency-fixture-support.php';
	$old_user = get_current_user_id(); $fixture = new CetechOpeningEmergencyFixture(); $failure = null;
	try {
		$fixture->prepare(); wp_set_current_user( $fixture->state['user_id'] );
		$service = CetechOpeningEmergencyFixture::service(); $site = get_current_blog_id();
		if ( null !== $history ) {
			if ( ! is_callable( $history['physical'] ?? null ) || ! is_callable( $history['historical'] ?? null ) ) { throw new RuntimeException( 'Invalid C07 history probe.' ); }
			$bytes = $history['physical'](); $facts = $history['historical']();
			$paused = $fixture->transition( 'checkout_suspended', 'maintenance_pause' ); $enabled = $fixture->transition( 'enabled', 'resume_verified' );
			$check( 'NATIVE-C07-HPOS-V1V2-MALFORMED-HISTORICAL-PAUSE-RESUME-PRESERVED', 'accepted' === $paused->outcome->state && 'accepted' === $enabled->outcome->state && $bytes === $history['physical']() && $facts === $history['historical'](), [ 'actual_hpos_history' => true, 'protected_meta_rows_unchanged' => $bytes === $history['physical'](), 'historical_planner_unchanged' => $facts === $history['historical']() ] );
			return;
		}
		$container = Plugin::instance()->container(); $classifier = $container->get( EmergencyOwnershipClassifier::class ); $quote = $container->get( EmergencyCheckoutQuoteValidator::class );
		$fresh = static function () use ( $service, $classifier, $quote ): array { $latch = new EmergencyOwnershipLatch(); $admission = new EmergencyCheckoutAdmissionService( $service, $classifier, $quote, $latch ); return [ $admission, new EmergencyControlRuntime( $service, $classifier, $latch, $admission ), $latch ]; };
		$read = $service->read( $site );
		$check( 'NATIVE-C07-DEFAULT-CACHE-NATIVE-READY-READ', $read->available && null !== $read->state && $read->state->site_id === $site && WP_Object_Cache::class === get_class( $GLOBALS['wp_object_cache'] ), [ 'native_default_object_cache' => true, 'no_object_cache_dropin' => ! file_exists( WP_CONTENT_DIR . '/object-cache.php' ) ] );
		$managed = $fixture->order(); $legacy = $fixture->order( legacy: true ); $missing = $fixture->order( missing: true ); $pickup = $fixture->order( 'pickup' ); $ordinary = $fixture->order( 'unmanaged' ); $paid = $fixture->order(); $paid->set_date_paid( time() ); $paid->set_status( 'processing' ); $paid->save();
		$product_ownership = []; foreach ( [ 'managed', 'pickup', 'unmanaged' ] as $kind ) { $product_ownership[$kind] = $classifier->product( $fixture->state[$kind . '_product_id'] ); }
		// The assertion remains exact; diagnostics disclose only finite classifications,
		// identity booleans and bounded source counts, never rule/configuration payloads.
		$source_summary = static function ( callable $load, int $product_id ): array {
			try {
				$runtime = $load(); $result = $runtime->result; $category_candidates = 0; $product_candidates = 0;
				foreach ( $result->candidate_hierarchy as $candidate ) { if ( is_array( $candidate ) ) { $category_candidates += 'category' === ( $candidate['target_type'] ?? null ) ? 1 : 0; $product_candidates += 'product' === ( $candidate['target_type'] ?? null ) ? 1 : 0; } }
				$counts = [ 'matched' => count( $result->matched_rules ), 'chosen' => count( $result->chosen_rules ), 'skipped' => count( $result->skipped_rules ), 'category_candidates' => $category_candidates, 'product_candidates' => $product_candidates ];
				$limited = false; foreach ( $counts as &$count ) { $limited = $limited || $count > 200; $count = min( 201, $count ); } unset( $count );
				return [ 'returned' => true, 'source' => in_array( $runtime->source, [ 'legacy', 'ecr' ], true ) ? $runtime->source : 'other', 'success' => $result->success, 'input_identity_matches' => 'product' === $result->input_target_type && $product_id === $result->input_target_id, 'contract_supported' => '1' === $result->contract_version, 'error_present' => null !== $result->error, 'counts' => $counts, 'count_limit_exceeded' => $limited, 'exception_kind' => 'none' ];
			} catch ( Throwable $error ) { return [ 'returned' => false, 'exception_kind' => $error instanceof TypeError ? 'type_error' : ( $error instanceof LogicException ? 'logic_error' : ( $error instanceof RuntimeException ? 'runtime_error' : 'other_error' ) ) ]; }
		};
		$ownership_diagnostics = []; $physical_probe = new CetechDeliveryEngine\Application\EmergencyControl\WpdbEmergencyConfigurationOwnershipProbe();
		foreach ( [ 'managed', 'pickup', 'unmanaged' ] as $kind ) {
			$product_id = $fixture->state[$kind . '_product_id']; $native_product = wc_get_product( $product_id );
			$ownership_diagnostics[$kind] = [
				'classification' => $product_ownership[$kind]->value,
				'physical_scope_classification' => $physical_probe->ownership( $product_id, null )->value,
				'native_product_exists' => $native_product instanceof WC_Product,
				'native_identity_matches' => $native_product instanceof WC_Product && $product_id === $native_product->get_id(),
				'native_product_type' => ! $native_product instanceof WC_Product ? 'unavailable' : ( $native_product->is_type( 'simple' ) ? 'simple' : ( $native_product->is_type( 'variable' ) ? 'variable' : ( $native_product->is_type( 'variation' ) ? 'variation' : 'other' ) ) ),
				'legacy' => $source_summary( static fn () => ( new CetechDeliveryEngine\Application\Runtime\LegacyProductDeliveryConfigurationSource( $container->get( CetechDeliveryEngine\Application\ProductRule\ProductDeliveryRuleResolver::class ) ) )->resolve( 'product', $product_id ), $product_id ),
				'ecr' => $source_summary( static fn () => ( new CetechDeliveryEngine\Application\Runtime\EcrProductDeliveryConfigurationSource( $container->get( CetechDeliveryEngine\Application\Configuration\EffectiveConfigurationResolver::class ), $container->get( CetechDeliveryEngine\Application\Runtime\EcrToRuntimeConfigurationAdapter::class ), $container->get( CetechDeliveryEngine\Application\Runtime\VariationRelationshipInspectorInterface::class ) ) )->resolve( 'product', $product_id ), $product_id ),
			];
		}
		$check( 'NATIVE-C07-AUTHORITATIVE-MANAGED-UNMANAGED-PRODUCTS', EmergencyOwnership::Managed === $product_ownership['managed'] && EmergencyOwnership::Managed === $product_ownership['pickup'] && EmergencyOwnership::Unmanaged === $product_ownership['unmanaged'], $ownership_diagnostics );
		$check( 'NATIVE-C07-NEW-LEGACY-MISSING-ORDER-OWNERSHIP', EmergencyOwnership::Managed === $classifier->order( $managed ) && EmergencyOwnership::Managed === $classifier->order( $legacy ) && EmergencyOwnership::Managed === $classifier->order( $missing ) && EmergencyOwnership::Unmanaged === $classifier->order( $ordinary ) );
		$before = CetechOpeningEmergencyFixture::order_bytes( $fixture->state['orders'] );
		$paused = $fixture->transition( 'checkout_suspended', 'incident_pause' );
		$check( 'NATIVE-C07-PAUSE-COMMITTED-AUTOLOAD-OFF', 'accepted' === $paused->outcome->state && 'checkout_suspended' === $service->read( $site )->state?->state && 'off' === CetechOpeningEmergencyFixture::option( $fixture::CONTROL )['autoload'] );
		[ $admission, $runtime ] = $fresh();
		$writer_before = $fixture::option( $fixture::CONTROL ); $writer_events = $fixture::rows( 'operation_changes' ); $writer_history = $fixture::order_bytes( $fixture->state['orders'] );
		ob_start(); try { ( new CetechDeliveryEngine\Presentation\Admin\EmergencyControlSettings( $service, $container->get( CetechDeliveryEngine\Presentation\Admin\AdminActionHandler::class ), false ) )->render(); $writer_html = ob_get_contents(); } finally { ob_end_clean(); }
		$check( 'NATIVE-C07-WRITER-DISABLED-RETAINS-PAUSE-AND-GUARDS', is_string( $writer_html ) && str_contains( $writer_html, 'New delivery and pickup checkouts are paused.' ) && str_contains( $writer_html, 'The recorded state is preserved.' ) && ! str_contains( $writer_html, '<form' ) && $writer_before === $fixture::option( $fixture::CONTROL ) && $writer_events === $fixture::rows( 'operation_changes' ) && $writer_history === $fixture::order_bytes( $fixture->state['orders'] ) && ! $runtime->product_allowed( $fixture->state['managed_product_id'] ) && current_user_can( 'manage_delivery_settings' ), [ 'actual_native_authorized_render' => true, 'server_constructor_writer_switch' => false, 'no_control_form_or_post' => true, 'live_guard_denies_managed' => true ] );
		$check( 'NATIVE-C07-MANAGED-DELIVERY-AND-PICKUP-EARLY-DENIED', ! $runtime->product_allowed( $fixture->state['managed_product_id'] ) && ! $runtime->product_allowed( $fixture->state['pickup_product_id'] ) && $runtime->product_allowed( $fixture->state['unmanaged_product_id'] ) );
		foreach ( [ 'new' => $managed, 'legacy' => $legacy, 'missing' => $missing, 'pickup' => $pickup ] as $name => $order ) { $decision = $fresh()[0]->final_order( $order, 'order_pay' ); $check( 'NATIVE-C07-UNPAID-' . strtoupper( $name ) . '-ORDER-PAY-PAUSED', ! $decision->allowed && 'checkout_suspended' === $decision->code && ! $order->is_paid(), [ 'actual_unpaid_order' => true, 'no_payment_invoked' => true ] ); }
		$check( 'NATIVE-C07-PAID-AND-UNMANAGED-ORDERS-CONTINUE', $fresh()[0]->final_order( $paid, 'order_pay' )->allowed && $fresh()[0]->final_order( $ordinary, 'order_pay' )->allowed );
		$check( 'NATIVE-C07-PAUSE-READS-DO-NOT-REWRITE-ORDER-HISTORY', $before === CetechOpeningEmergencyFixture::order_bytes( $fixture->state['orders'] ), [ 'physical_orders_items_meta_identical' => true ] );
		$rates = [ 'ordinary' => new WC_Shipping_Rate( 'flat_rate:1', 'C07 ordinary', 4, [], 'flat_rate', 1 ), 'engine' => new WC_Shipping_Rate( 'delivery_engine_selected_offer:1', 'C07 managed', 7, [], 'delivery_engine_selected_offer', 1 ) ];
		$hooks = new EmergencyCheckoutHooks( $runtime ); $managed_package = [ 'contents' => [ 'c07_managed' => $fixture->item() ] ]; $ordinary_package = [ 'contents' => [ 'c07_unmanaged' => $fixture->item( 'unmanaged' ) ] ];
		$check( 'NATIVE-C07-PAUSED-MANAGED-RATES-NO-NATIVE-FREE-FALLBACK', [] === $hooks->package_rates( $rates, $managed_package ) && $rates === $hooks->package_rates( $rates, $ordinary_package ) );
		$flags = [ 'enable_classic_checkout_adapter', 'enable_woocommerce_shipping_rate_calculation', 'enable_order_delivery_snapshot_persistence', 'enable_effective_configuration_runtime', 'enable_variable_product_ecr_runtime' ]; foreach ( $flags as $name ) { update_option( 'cetech_de_' . $name, 0, false ); }
		$check( 'NATIVE-C07-INACTIVE-RUNTIME-FLAGS-DO-NOT-BYPASS-PAUSE', EmergencyOwnership::Managed === $classifier->product( $fixture->state['managed_product_id'] ) && ! $fresh()[1]->product_allowed( $fixture->state['managed_product_id'] ) && [] === $hooks->package_rates( $rates, $managed_package ) );
		foreach ( [ 'enable_classic_checkout_adapter', 'enable_woocommerce_shipping_rate_calculation', 'enable_order_delivery_snapshot_persistence' ] as $name ) { update_option( 'cetech_de_' . $name, 1, false ); }
		$stopped = false; $redirected = null; $notices = [];
		$response = new EmergencyControlResponse( static function ( string $message ) use ( &$notices ): void { $notices[] = $message; }, static fn (): string => wc_get_checkout_url(), static function ( string $url, int $status ) use ( &$redirected ): bool { $redirected = [ $url, $status ]; return true; }, static function ( bool $redirect, string $message ) use ( &$stopped ): never { $stopped = $redirect; throw new LogicException( 'C07 trusted fixture terminal.' ); } );
		try { ( new EmergencyCheckoutHooks( $fresh()[1], $response ) )->before_pay( $managed ); } catch ( LogicException $error ) { if ( 'C07 trusted fixture terminal.' !== $error->getMessage() ) { throw $error; } }
		$check( 'NATIVE-C07-ORDER-PAY-SAFE-REDIRECT-AND-TERMINATION', $stopped && [ wc_get_checkout_url(), 303 ] === $redirected && 1 === count( $notices ) && str_contains( $notices[0], 'temporarily paused' ) && str_contains( $notices[0], 'Reference:' ), [ 'server_checkout_url_only' => true, 'trusted_fixture_stopped_before_gateway' => true ] );
		$shopper = EmergencyControlProjection::for_shopper( $admission->final_order( $managed, 'classic' ), RequestContext::create() );
		$check( 'NATIVE-C07-SHOPPER-PROJECTION-EXACT-PRIVATE-EXCLUSION', [ 'contract_version', 'decision_kind', 'status', 'message_key', 'message', 'recovery_action', 'correlation_id' ] === array_keys( $shopper ) && 'cetech.checkout.paused' === $shopper['message_key'] && ! str_contains( json_encode( $shopper ), 'PRIVATE-C07' ) );
		$loads = 0; $denied = EmergencyControlProjection::for_diagnostics( $site, RequestContext::create(), static fn (): bool => false, static function () use ( &$loads ): void { ++$loads; } );
		$check( 'NATIVE-C07-DIAGNOSTICS-DENIES-BEFORE-LOADER', $denied instanceof ContractError && 'not_authorized' === $denied->code && 0 === $loads );
		$checks = 0; $revoked = EmergencyControlProjection::for_settings( $site, RequestContext::create(), static function () use ( &$checks ): bool { return 1 === ++$checks; }, static fn () => $service->read( $site ) );
		$check( 'NATIVE-C07-ADMIN-DISCLOSURE-RECHECKS-CURRENT-AUTHORITY', $revoked instanceof ContractError && 'not_authorized' === $revoked->code && 2 === $checks );
		$diagnostics = EmergencyControlProjection::for_diagnostics( $site, RequestContext::create(), static fn (): bool => current_user_can( 'view_delivery_diagnostics' ), static fn () => new EmergencyControlDiagnostics( $site, $service->read( $site ), 'unknown', observed_lines: 200, observed_packages: 200, observed_complete: false ) );
		$check( 'NATIVE-C07-IMPACT-IS-BOUNDED-INCOMPLETE-ESTIMATE', is_array( $diagnostics ) && 'bounded_observed_estimate' === $diagnostics['observed_impact']['kind'] && false === $diagnostics['observed_impact']['complete'] && 200 === $diagnostics['observed_impact']['limit'] && 'checkout_suspended' === $diagnostics['effective_state'] && 'unknown' === $diagnostics['module_readiness'] );
		$cached = get_option( $fixture::CONTROL ); wp_cache_set( $fixture::CONTROL, 'PRIVATE-STALE-CONTROL-CACHE', 'options' ); $autoload = wp_load_alloptions(); $autoload[$fixture::CONTROL] = 'PRIVATE-STALE-ALL-OPTIONS'; wp_cache_set( 'alloptions', $autoload, 'options' );
		$check( 'NATIVE-C07-CURRENT-NATIVE-READ-IGNORES-POISONED-OPTION-CACHES', 'checkout_suspended' === $service->read( $site )->state?->state && 'PRIVATE-STALE-ALL-OPTIONS' === get_option( $fixture::CONTROL ) );
		$enabled = $fixture->transition( 'enabled', 'resume_verified' );
		$check( 'NATIVE-C07-RESUME-INVALIDATES-NATIVE-OPTION-AND-ALLOPTIONS', 'accepted' === $enabled->outcome->state && CetechOpeningEmergencyFixture::option( $fixture::CONTROL )['option_value'] === get_option( $fixture::CONTROL ) && 'enabled' === $service->read( $site )->state?->state );
		$wpdb->update( $wpdb->options, [ 'autoload' => 'on' ], [ 'option_name' => $fixture::CONTROL ] ); $fixture::invalidate( $fixture::CONTROL ); wp_load_alloptions(); $on = $fixture->transition( 'checkout_suspended', 'operator_pause' );
		$check( 'NATIVE-C07-AUTOLOAD-ON-UPDATE-RETAINS-PARITY', 'accepted' === $on->outcome->state && 'on' === CetechOpeningEmergencyFixture::option( $fixture::CONTROL )['autoload'] && CetechOpeningEmergencyFixture::option( $fixture::CONTROL )['option_value'] === get_option( $fixture::CONTROL ) );
		$opened = $service->read( $site )->state; $token = 'c07_native_replay_' . bin2hex( random_bytes( 5 ) ); $identity = EmergencyControlCommand::identity( $site, get_current_user_id(), $token ); $fixture->state['namespaces'][] = $identity->namespace_digest(); $payload = EmergencyControlCommand::payload( $opened, 'enabled', 'resume_verified' ); $accepted = $service->transition( $identity, $payload, RequestContext::create() ); $count = count( $fixture::rows( 'operation_changes' ) ); $control_bytes = $fixture::option( $fixture::CONTROL ); $replay = $service->transition( $identity, $payload, RequestContext::create() );
		$check( 'NATIVE-C07-ORIGINAL-TOKEN-REPLAY-NO-SECOND-AUDIT', 'accepted' === $accepted->outcome->state && 'accepted' === $replay->outcome->state && $replay->replayed && $count === count( $fixture::rows( 'operation_changes' ) ) && $control_bytes === $fixture::option( $fixture::CONTROL ) );
		$no_change = $fixture->transition( 'enabled', 'resume_verified' ); $check( 'NATIVE-C07-SAME-STATE-NO-OPTION-WRITE-NO-MATERIAL-AUDIT', 'not_applicable' === $no_change->outcome->state && $count === count( $fixture::rows( 'operation_changes' ) ) && $control_bytes === $fixture::option( $fixture::CONTROL ) );
		$quote_bytes = $fixture::order_bytes( [ $managed->get_id(), $pickup->get_id() ] );
		$quote->fingerprint( $managed ); $native_line = array_values( $managed->get_items( 'line_item' ) )[0]; $native_meta = $native_line->get_meta_data(); $native_shipping = $managed->get_items( 'shipping' ); $queries_before_local = $wpdb->num_queries; $local = CetechDeliveryEngine\Application\EmergencyControl\EmergencyCheckoutLocalBinding::capture( $managed ); $local_unchanged = null !== $local && $local->unchanged(); $native_line->set_quantity( 2 ); $local_changed = null !== $local && ! $local->unchanged(); $native_line->set_quantity( 1 ); $local_queries = $wpdb->num_queries - $queries_before_local;
		$check( 'NATIVE-C07-LOCAL-BINDING-NATIVE-DATES-META-AND-ITEM-MUTATION', $managed->get_date_created() instanceof WC_DateTime && [] !== $native_meta && [] === array_filter( $native_meta, static fn ( mixed $meta ): bool => ! $meta instanceof WC_Meta_Data ) && $local_unchanged && $local_changed && 0 === $local_queries && $quote_bytes === $fixture::order_bytes( [ $managed->get_id(), $pickup->get_id() ] ), [ 'actual_native_woo_dates_and_metadata' => $managed->get_date_created() instanceof WC_DateTime && [] !== $native_meta, 'prewarmed_request_facts' => true, 'native_order_class' => WC_Order::class === get_class( $managed ), 'native_line_class' => WC_Order_Item_Product::class === get_class( $native_line ), 'shipping_items_loaded' => count( $native_shipping ), 'metadata_items_loaded' => count( $native_meta ), 'local_capture_available' => null !== $local, 'local_unchanged' => $local_unchanged, 'in_memory_quantity_change_detected' => $local_changed, 'local_query_count' => $local_queries, 'no_order_save_or_database_write' => 0 === $local_queries ] );
		$resumed_managed = $fresh()[0]->final_order( $managed, 'order_pay' ); $resumed_pickup = $fresh()[0]->final_order( $pickup, 'order_pay' ); $resumed_history_same = $quote_bytes === $fixture::order_bytes( [ $managed->get_id(), $pickup->get_id() ] );
		$resume_diagnostics = static function ( WC_Order $order ) use ( $quote, $container ): array {
			$diagnostic = [ 'fingerprint_available' => null !== $quote->fingerprint( $order ), 'quote_validator_accepted' => $quote->validate_order( $order, 'order_pay' ), 'diagnostic_complete' => false ];
			try {
				$reader = new CetechDeliveryEngine\Application\Order\OrderDeliverySnapshotReader(); $items = array_values( $order->get_items( 'line_item' ) ); $shipping = array_values( $order->get_items( 'shipping' ) );
				$package_read = $reader->read_package( $order ); $line_read = isset( $items[0] ) && $items[0] instanceof WC_Order_Item_Product ? $reader->read_line( $items[0] ) : null;
				$error_code = static fn ( ?string $code ): string => null === $code ? 'unavailable' : ( '' === $code ? 'none' : ( in_array( $code, [ 'missing', 'malformed', 'version_mismatch', 'partial' ], true ) ? $code : 'other' ) );
				$diagnostic += [ 'line_count' => min( 201, count( $items ) ), 'shipping_count' => min( 201, count( $shipping ) ), 'line_reader_error' => $error_code( $line_read?->error ), 'package_reader_error' => $error_code( $package_read->error ), 'native_taxes_enabled' => wc_tax_enabled(), 'order_shipping_money_valid' => null !== EmergencyCheckoutQuoteValidator::money_units( $order->get_shipping_total( 'edit' ) ), 'order_shipping_tax_is_string' => is_string( $order->get_shipping_tax( 'edit' ) ) ];
				$line = $line_read?->snapshot; $package = $package_read->snapshot;
				if ( null !== $line && isset( $items[0] ) ) {
					$runtime = $container->get( CetechDeliveryEngine\Application\Runtime\ProductDeliveryConfigurationSourceInterface::class )->resolve( null === $line->variation_id ? 'product' : 'variation', $line->variation_id ?? $line->product_id ); $result = $runtime->result; $eligible = false;
					foreach ( $container->get( CetechDeliveryEngine\Application\Selector\ProductDeliveryOptionsBuilder::class )->buildFromResolution( $result ) as $option ) { if ( $option->is_available && $option->fulfilment_availability === $line->fulfilment_availability && $option->fulfilment_choice === $line->fulfilment_choice && $option->delivery_offer_id === $line->delivery_offer_id && ( 'store_pickup' !== $line->fulfilment_choice || $option->pickup_location_id === $line->pickup_location_id ) ) { $eligible = true; break; } }
					$context = CetechDeliveryEngine\Domain\CustomerContext\CustomerCartContext::fromArray( [ 'contract_version' => $line->customer_context_version, 'fulfilment_choice' => $line->fulfilment_choice, 'delivery_offer_id' => $line->delivery_offer_id, 'pickup_location_id' => $line->pickup_location_id, 'matching_location' => $line->matching_location, 'delivery_address' => $line->delivery_address ] );
					$intent = [ 'fulfilment_availability' => $line->fulfilment_availability, 'fulfilment_choice' => $line->fulfilment_choice, 'delivery_offer_id' => $line->delivery_offer_id ]; $expected_group = null === $context ? CetechDeliveryEngine\Application\Shipping\DeliveryGroupIdentity::fromIntent( $intent ) : CetechDeliveryEngine\Application\Shipping\DeliveryGroupIdentity::forHistorical( $intent, $context );
					$diagnostic += [ 'current_source' => in_array( $runtime->source, [ 'legacy', 'ecr', 'legacy_category_compatibility' ], true ) ? $runtime->source : 'other', 'current_source_success' => $result->success, 'current_source_error_present' => null !== $result->error, 'current_source_identity_matches' => $result->input_target_type === ( null === $line->variation_id ? 'product' : 'variation' ) && $result->input_target_id === ( $line->variation_id ?? $line->product_id ), 'current_matched_count' => min( 201, count( $result->matched_rules ) ), 'current_chosen_count' => min( 201, count( $result->chosen_rules ) ), 'eligible_choice_matches' => $eligible, 'line_quote_status' => in_array( $line->quote_status, [ 'quoted', 'selection_only', 'skipped' ], true ) ? $line->quote_status : 'other', 'line_amount_present' => null !== $line->quoted_amount, 'line_amount_valid' => null !== EmergencyCheckoutQuoteValidator::money_units( $line->quoted_amount ), 'line_identity_matches' => $line->product_id === $items[0]->get_product_id() && $line->variation_id === ( $items[0]->get_variation_id() > 0 ? $items[0]->get_variation_id() : null ), 'line_quantity_matches' => $line->quantity === CetechDeliveryEngine\Application\EmergencyControl\EmergencyCheckoutFacts::quantity( $items[0]->get_quantity() ), 'line_currency_matches' => $line->currency_code === $order->get_currency( 'edit' ), 'context_available' => null !== $context, 'context_complete' => null !== $context && ( $context->isPickup() ? $context->isPickupComplete() : $context->hasCompleteDeliveryAddress() ), 'matching_identity_matches' => null !== $context && $context->matching_identity === $line->matching_identity, 'delivery_identity_matches' => null !== $context && $context->delivery_location_identity === $line->delivery_location_identity, 'expected_group_available' => null !== $expected_group, 'line_group_matches' => null !== $expected_group && $line->delivery_group_id === $expected_group ];
					if ( isset( $shipping[0] ) ) { $taxes = $shipping[0]->get_taxes( 'edit' ); $diagnostic += [ 'shipping_method_matches' => 'delivery_engine_selected_offer' === $shipping[0]->get_method_id(), 'shipping_group_matches' => null !== $expected_group && $shipping[0]->get_meta( 'cetech_de_group_id', true ) === $expected_group, 'shipping_money_valid' => null !== EmergencyCheckoutQuoteValidator::money_units( $shipping[0]->get_total( 'edit' ) ), 'shipping_tax_is_string' => is_string( $shipping[0]->get_total_tax( 'edit' ) ), 'shipping_tax_total_list_available' => is_array( $taxes ) && isset( $taxes['total'] ) && is_array( $taxes['total'] ), 'shipping_tax_total_count' => is_array( $taxes ) && isset( $taxes['total'] ) && is_array( $taxes['total'] ) ? min( 201, count( $taxes['total'] ) ) : 0, 'order_shipping_total_matches' => EmergencyCheckoutQuoteValidator::money_units( $order->get_shipping_total( 'edit' ) ) === EmergencyCheckoutQuoteValidator::money_units( $shipping[0]->get_total( 'edit' ) ) ]; }
					if ( null !== $package ) { $diagnostic += [ 'package_currency_matches' => $package->currency_code === $order->get_currency( 'edit' ), 'package_money_valid' => null !== EmergencyCheckoutQuoteValidator::money_units( $package->package_total_delivery_amount ), 'package_group_count' => min( 201, count( $package->groups ) ), 'package_group_matches' => isset( $package->groups[0] ) && null !== $expected_group && $package->groups[0]->group_id === $expected_group, 'package_shipping_money_matches' => isset( $shipping[0] ) && EmergencyCheckoutQuoteValidator::money_units( $package->package_total_delivery_amount ) === EmergencyCheckoutQuoteValidator::money_units( $shipping[0]->get_total( 'edit' ) ) ]; }
				}
				$diagnostic['diagnostic_complete'] = true; $diagnostic['exception_kind'] = 'none';
			} catch ( Throwable $error ) { $diagnostic['exception_kind'] = $error instanceof TypeError ? 'type_error' : ( $error instanceof LogicException ? 'logic_error' : ( $error instanceof RuntimeException ? 'runtime_error' : 'other_error' ) ); }
			return $diagnostic;
		};
		$check( 'NATIVE-C07-RESUME-REVALIDATES-FROZEN-DELIVERY-AND-PICKUP', $resumed_managed->allowed && $resumed_pickup->allowed && $resumed_history_same, [ 'delivery_allowed' => $resumed_managed->allowed, 'delivery_code' => $resumed_managed->code, 'pickup_allowed' => $resumed_pickup->allowed, 'pickup_code' => $resumed_pickup->code, 'physical_history_unchanged' => $resumed_history_same, 'delivery_diagnostics' => $resume_diagnostics( $managed ), 'pickup_diagnostics' => $resume_diagnostics( $pickup ) ] );
		$wpdb->update( CetechDeliveryEngine\Infrastructure\Persistence\TableNames::for( 'rate_cards' ), [ 'base_amount' => '9.0000' ], [ 'id' => $fixture->state['rate_id'] ] ); $mismatch = $fresh()[0]->final_order( $managed, 'order_pay' );
		$check( 'NATIVE-C07-RESUME-PRICE-MISMATCH-DENIED-WITHOUT-REPRICING', ! $mismatch->allowed && 'checkout_revalidation_required' === $mismatch->code && $quote_bytes === $fixture::order_bytes( [ $managed->get_id(), $pickup->get_id() ] ) );
		$wpdb->update( CetechDeliveryEngine\Infrastructure\Persistence\TableNames::for( 'rate_cards' ), [ 'base_amount' => '7.0000' ], [ 'id' => $fixture->state['rate_id'] ] );
		$check( 'NATIVE-C07-MISSING-FACTS-DENIED-WITHOUT-ACCEPTANCE-INFERENCE', ! $fresh()[0]->final_order( $missing, 'order_pay' )->allowed && $before === $fixture::order_bytes( $fixture->state['orders'] ) );
		$valid = $fixture::option( $fixture::CONTROL ); $wpdb->update( $wpdb->options, [ 'option_value' => '{"format_version":1,"state":"enabled"}' ], [ 'option_name' => $fixture::CONTROL ] ); $fixture::invalidate( $fixture::CONTROL ); $bad = $service->read( $site );
		$check( 'NATIVE-C07-MALFORMED-CONTROL-FAILS-CLOSED-UNMANAGED-CONTINUES', ! $bad->available && ! $fresh()[1]->product_allowed( $fixture->state['managed_product_id'] ) && $fresh()[1]->product_allowed( $fixture->state['unmanaged_product_id'] ) ); $wpdb->replace( $wpdb->options, $valid ); $fixture::invalidate( $fixture::CONTROL );
		$over_limit = []; for ( $i = 0; $i < 201; ++$i ) { $over_limit[ 'c07_limit_' . $i ] = $fixture->item(); } $changes_before = count( $fixture::rows( 'operation_changes' ) );
		$check( 'NATIVE-C07-201-LINE-LIMIT-REFUSES-WITHOUT-PARTIAL-ADMISSION', ! $fresh()[1]->lines_allowed( $over_limit ) && $changes_before === count( $fixture::rows( 'operation_changes' ) ), [ 'observed_lines' => 201, 'supported_limit' => 200 ] );
		$in_flight = $fixture->order(); $in_flight_admission = $fresh()[0]->final_order( $in_flight, 'classic' );
		$package_epoch_before = $fresh()[1]->decorate_packages( [ $managed_package ] ); $fixture->transition( 'checkout_suspended', 'operator_pause' ); $package_epoch_after = $fresh()[1]->decorate_packages( [ $managed_package ] );
		$check( 'NATIVE-C07-PACKAGE-CACHE-EPOCH-CHANGES-AFTER-PAUSE', $package_epoch_before !== $package_epoch_after && ! str_contains( json_encode( $package_epoch_after ), 'actor_user_id' ) );
		update_option( 'cetech_de_enable_shipment_records', 1, false );
		$in_flight->payment_complete( 'c07-private-fixture-transaction' ); $reloaded = wc_get_order( $in_flight->get_id() );
		$check( 'NATIVE-C07-ALREADY-ADMITTED-PAYMENT-CALLBACK-COMPLETES-AFTER-PAUSE', $in_flight_admission->allowed && $reloaded instanceof WC_Order && null !== $reloaded->get_date_paid() && 'checkout_suspended' === $service->read( $site )->state?->state, [ 'admission_confirmed_before_pause' => true, 'actual_woo_payment_complete_after_pause' => true ] );
		$creation = $container->get( CetechDeliveryEngine\Application\Shipment\ShipmentService::class )->create_for_paid_order( $paid );
		$check( 'NATIVE-C07-PAID-HISTORICAL-SHIPMENT-CREATION-CONTINUES', $creation->is_success() && 1 === count( $creation->shipments ) && 'checkout_suspended' === $service->read( $site )->state?->state && current_user_can( 'manage_shipments' ), [ 'actual_native_repository' => true, 'existing_staff_authority' => true ] );
		$shipment = $creation->shipments[0]; $tracking = $container->get( CetechDeliveryEngine\Application\Shipment\ShipmentTrackingService::class )->save( $shipment->id, new CetechDeliveryEngine\Application\Shipment\ShipmentTrackingInput( 'C07 synthetic carrier', 'C07-SYNTHETIC-TRACK', 'https://example.invalid/c07-track', gmdate( 'Y-m-d' ), 'C07 synthetic tracking note' ), get_current_user_id() );
		$status = $container->get( CetechDeliveryEngine\Application\Shipment\ShipmentStatusService::class )->change( $shipment->id, CetechDeliveryEngine\Domain\Enum\ShipmentStatus::Processing, CetechDeliveryEngine\Application\Shipment\ShipmentStatusChangeRequest::staff_normal( 'C07 synthetic progress', get_current_user_id() ) );
		$check( 'NATIVE-C07-EXISTING-SHIPMENT-TRACKING-STATUS-CONTINUES', $tracking->ok && $status->ok && 'processing' === $status->shipment?->status->value && 'C07-SYNTHETIC-TRACK' === $tracking->shipment?->tracking_number && 'checkout_suspended' === $service->read( $site )->state?->state );
		$cod = $fixture->order(); $cod->set_payment_method( 'cod' ); $cod->set_status( 'on-hold' ); $cod->save(); $container->get( CetechDeliveryEngine\Application\Shipment\CodAwaitingShipmentEvaluator::class )->sync( $cod );
		$check( 'NATIVE-C07-EXISTING-COD-MANUAL-AUTHORITY-PRESERVED', $container->get( CetechDeliveryEngine\Application\Shipment\CodAwaitingShipmentStore::class )->is_awaiting( $cod ) && null === $cod->get_date_paid() && current_user_can( 'manage_shipments' ) && 'checkout_suspended' === $service->read( $site )->state?->state, [ 'existing_cod_task_index' => true, 'no_payment_confirmation_inferred' => true ] );
	} catch ( Throwable $error ) { $failure = $error; throw $error; }
	finally {
		if ( isset( $fixture->state['user_id'] ) ) { try {
			// Track exact new native operational rows in this single-process disposable
			// phase. Cleanup deletes only these captured IDs, never an order/table sweep.
			foreach ( [ 'shipments', 'shipment_items', 'shipment_events', 'audit_log' ] as $suffix ) { if ( ! in_array( $suffix, DataLifecycleManifest::DOMAIN_TABLE_SUFFIXES, true ) || ! isset( $fixture->state['domain_before'][ $suffix ] ) || ! is_array( $fixture->state['domain_before'][ $suffix ] ) ) { throw new RuntimeException( 'C07 tracked operational cleanup baseline is unavailable.' ); } $baseline = array_column( $fixture->state['domain_before'][ $suffix ], 'id' ); $already = array_map( static fn ( array $item ): int => $item[0] === $suffix ? $item[1] : 0, $fixture->state['entities'] ); foreach ( $fixture::rows( $suffix ) as $row ) { if ( ! in_array( $row['id'], $baseline, true ) && ! in_array( (int) $row['id'], $already, true ) ) { $fixture->state['entities'][] = [ $suffix, (int) $row['id'] ]; } } }
			$cleanup = $fixture->cleanup(); $check( null === $history ? 'NATIVE-C07-EXACT-FIXTURE-CLEANUP-ALL32-CONTROL-PRESERVED' : 'NATIVE-C07-HISTORY-HOOK-FIXTURE-CLEANUP', $cleanup['cleanup_restored'] && ! $cleanup['role_exists'] && ! $cleanup['user_exists'], $cleanup );
		} catch ( Throwable $cleanup_error ) { if ( null === $failure ) { throw $cleanup_error; } } finally { wp_set_current_user( 0 ); wp_set_current_user( $old_user ); } }
		else { wp_set_current_user( 0 ); wp_set_current_user( $old_user ); }
	}
};
