<?php

declare(strict_types=1);

use CetechDeliveryEngine\Application\DeliveryQuote\QuotePlacementProof;
use CetechDeliveryEngine\Application\EmergencyControl\EmergencyCheckoutLocalBinding;
use CetechDeliveryEngine\Application\Order\QuoteNativeOrderHistory;
use CetechDeliveryEngine\Domain\Contracts\RequestContext;
use CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState;
use CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore;

/** Actual Woo CRUD/pre-freeze/C03 proof. HTTP/native gateway continuation is separate. */
return static function ( callable $check, string $mode = 'hpos_on' ): void {
	global $wpdb;
	$hpos = Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled();
	if ( ! in_array( $mode, [ 'hpos_on', 'hpos_off' ], true ) || ( 'hpos_on' === $mode ) !== $hpos || '1' !== getenv( 'CETECH_DE_NATIVE_OPENING_QUALIFICATION' ) || true !== WP_ADMIN || '1' !== (string) get_option( 'cetech_opening_qualification_disposable' ) || ! $wpdb instanceof wpdb || is_multisite() || WP_Object_Cache::class !== get_class( $GLOBALS['wp_object_cache'] ) ) { throw new RuntimeException( 'Q06 native proof requires the marked default-cache site and exact order store.' ); }
	foreach ( get_included_files() as $file ) { if ( str_ends_with( str_replace( '\\', '/', $file ), '/tests/bootstrap.php' ) ) { throw new RuntimeException( 'Unit bootstrap is forbidden in native Q06 proof.' ); } }
	require_once __DIR__ . '/opening-quote-placement-support.php';
	$fixture = new CetechQuotePlacementFixture( $wpdb ); $phase = 'NATIVE-W2Q06-PLACEMENT-ENVIRONMENT'; $completed = [];
	$case = static function ( string $id, bool $condition, array $evidence ) use ( $check, $mode, &$completed ): void {
		if ( ! CetechQuotePlacementObservation::valid( $evidence ) ) { throw new RuntimeException( 'Q06 native observation protocol refused.' ); }
		$completed[] = $id; $check( 'hpos_off' === $mode ? str_replace( 'NATIVE-W2Q06-', 'NATIVE-W2Q06-HPOS-OFF-', $id ) : $id, $condition, $evidence );
	};
	$known = static fn ( $result ): bool => null !== $result && 'accepted' === $result->attempt->outcome->state && null !== $result->binding;
	$prior_cleanup = [ 'cleanup_restored' => true, 'owned_orders_removed' => true, 'quote_operation_history_restored' => true, 'owned_connections_retired' => true ];
	$isolate = static function () use ( &$fixture, &$prior_cleanup, $wpdb ): void {
		$cleanup = $fixture->cleanup(); foreach ( $prior_cleanup as $key => $ok ) { $prior_cleanup[$key] = $ok && $cleanup[$key]; }
		if ( ! $cleanup['cleanup_restored'] ) { throw new RuntimeException( 'Native Q06 isolated checkout fixture did not restore its exact rows.' ); }
		$fixture = new CetechQuotePlacementFixture( $wpdb ); $fixture->prepare();
	};
	try {
		$fixture->prepare();
		$case( 'NATIVE-W2Q06-PLACEMENT-ENVIRONMENT', true, [ 'actual_installed_native_wp' => true, 'actual_hpos_enabled' => $hpos ] );
		$phase = 'NATIVE-W2Q06-NATIVE-CACHED-RATE-REFERENCES'; $flow = new CetechQuotePlacementNativeFlow( $fixture );
		$cached = WC()->session->get( 'shipping_for_package_0' );
		$rate_history = $fixture->cart->history(); $rate_quote = $fixture->cart->row( $flow->evidence->header()->id()->value() )['private_body_json'];
		$native_session_row = static function () use ( $wpdb ): array {
			$row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM `{$wpdb->prefix}woocommerce_sessions` WHERE session_key=%s", WC()->session->get_customer_id() ), ARRAY_A );
			if ( ! is_array( $row ) || '' !== $wpdb->last_error ) { throw new RuntimeException( 'Native Q06 original session observation unavailable.' ); }
			return $row;
		};
		$session_before = $native_session_row(); $fixture->rate_projection->reset();
		// A genuine current read restores the cached native calculation and applies
		// its production projection. No recalculation or session save completes it.
		$current = ( new CetechDeliveryEngine\Application\DeliveryQuote\QuoteCartPlacementEvidenceReader( $fixture->cart->environment, $fixture->cart->sessions, $fixture->factory ) )->current( RequestContext::create() );
		$current_read = null !== $current && $current->header()->id()->value() === $flow->evidence->header()->id()->value();
		$current_cache = WC()->session->get( 'shipping_for_package_0' ); $projected = $fixture->rate_projection->after; $restored = $fixture->rate_projection->before;
		$refs = 1 === $fixture->rate_projection->calls && [] !== $projected; $money = [] !== $restored; $objects = [] !== $restored && array_keys( $restored ) === array_keys( $projected );
		foreach ( $projected as $package_key => $rates ) {
			$objects = $objects && array_keys( $rates ) === array_keys( $restored[$package_key] ?? [] );
			foreach ( $rates as $rate_key => $rate ) {
				$original = $restored[$package_key][$rate_key] ?? null; $meta = $rate['meta'];
				$refs = $refs && ( $meta[CetechDeliveryEngine\Integrations\DeliveryQuote\QuoteRateReferenceRuntime::META_QUOTE_ID] ?? null ) === $flow->evidence->header()->id()->value() && is_string( $meta[CetechDeliveryEngine\Integrations\DeliveryQuote\QuoteRateReferenceRuntime::META_COMPONENT_HANDLE] ?? null ) && is_int( $meta[CetechDeliveryEngine\Integrations\DeliveryQuote\QuoteRateReferenceRuntime::META_GENERATION] ?? null );
				$objects = $objects && null !== $original && $original['object'] === $rate['object']; $money = $money && null !== $original && $original['data'] === $rate['data'];
			}
		}
		$cache_hit = is_array( $cached ) && is_array( $current_cache ) && is_string( $cached['package_hash'] ?? null ) && $cached['package_hash'] === ( $current_cache['package_hash'] ?? null );
		$session_unchanged = $session_before === $native_session_row();
		$case( 'NATIVE-W2Q06-NATIVE-CACHED-RATE-REFERENCES', $current_read && $cache_hit && $refs && $objects && $money && $session_unchanged && $rate_history === $fixture->cart->history() && $rate_quote === $fixture->cart->row( $flow->evidence->header()->id()->value() )['private_body_json'], [ 'native_current_read_succeeded' => $current_read, 'native_shipping_cache_hit' => $cache_hit, 'rate_references_attached' => $refs, 'native_rate_objects_unchanged' => $objects, 'native_rate_money_unchanged' => $money, 'native_session_bytes_unchanged' => $session_unchanged, 'quote_body_unchanged' => $rate_quote === $fixture->cart->row( $flow->evidence->header()->id()->value() )['private_body_json'], 'no_second_binding_effect' => $rate_history === $fixture->cart->history() ] );
		$phase = 'NATIVE-W2Q06-CLASSIC-PREFREEZE-EXACT-SAVED-CONTEXT'; $native_gateway = $fixture->register_gateway(); $flow->payment_method = $native_gateway->id; $flow->create();
		$order = $flow->order; $before = $fixture->snapshot_bytes( $order ); $quote_id = $flow->evidence->header()->id()->value(); $body = $fixture->cart->row( $quote_id )['private_body_json'];
		$case( 'NATIVE-W2Q06-CLASSIC-PREFREEZE-EXACT-SAVED-CONTEXT', $flow->prefreeze_staged && $known( $flow->prepared ) && $known( $flow->verified ) && QuoteNativeOrderHistory::verify( $order ) && [] !== $before['order'] && 2 === count( $order->get_items( 'line_item' ) ), [ 'actual_native_woo_order' => true, 'actual_native_checkout_create_order' => true, 'binding_prepared' => 'prepared' === $flow->prepared?->binding?->state(), 'binding_verified' => 2 === $flow->verified?->binding?->revision(), 'historical_reader_supported' => QuoteNativeOrderHistory::verify( $order ), 'native_logical_mapping_matches' => $flow->mapping === $flow->saved?->mapping(), 'native_items_saved' => [] !== $before['items'], 'native_line_count' => count( $order->get_items( 'line_item' ) ), 'native_shipping_count' => count( $order->get_items( 'shipping' ) ) ] );
		$phase = 'NATIVE-W2Q06-PREPARE-ORIGINAL-REPLAY-ONE-BINDING'; $history = $fixture->cart->history(); $retry = $flow->service->prepare( $order->get_id(), $flow->mapping, RequestContext::create() ); $fixture->track_result( $retry );
		$case( 'NATIVE-W2Q06-PREPARE-ORIGINAL-REPLAY-ONE-BINDING', $known( $retry ) && $retry->binding->row() === $flow->verified->binding->row() && $history === $fixture->cart->history(), [ 'acknowledged' => $known( $retry ), 'same_original_binding' => $retry->binding?->id() === $flow->prepared->binding->id(), 'no_second_binding_effect' => $history === $fixture->cart->history(), 'snapshot_bytes_unchanged' => $before === $fixture->snapshot_bytes( $order ) ] );
		$phase = 'NATIVE-W2Q06-VERIFIED-SAVED-WRITER-REENTRY-NO-RETIMESTAMP'; $again = $flow->stager->stage( $order, $flow->evidence, $flow->verified->binding, 'classic' );
		$case( 'NATIVE-W2Q06-VERIFIED-SAVED-WRITER-REENTRY-NO-RETIMESTAMP', $before === $fixture->snapshot_bytes( $order ) && $again->context_digest() === $flow->saved->context_digest() && $again->snapshot_digest() === $flow->saved->snapshot_digest() && $history === $fixture->cart->history(), [ 'snapshot_bytes_unchanged' => $before === $fixture->snapshot_bytes( $order ), 'quote_body_unchanged' => $body === $fixture->cart->row( $quote_id )['private_body_json'], 'no_second_binding_effect' => $history === $fixture->cart->history() ] );
		$phase = 'NATIVE-W2Q06-SAVED-PHYSICAL-MUTATION-REFUSED';
		$item = array_values( $order->get_items( 'line_item' ) )[0]; $physical = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM `{$wpdb->prefix}woocommerce_order_itemmeta` WHERE order_item_id=%d AND meta_key='_qty'", $item->get_id() ), ARRAY_A );
		if ( ! is_array( $physical ) || '' !== $wpdb->last_error ) { throw new RuntimeException( 'Native Q06 tracked quantity observation unavailable.' ); }
		if ( 1 !== $wpdb->update( $wpdb->prefix . 'woocommerce_order_itemmeta', [ 'meta_value' => '99' ], [ 'meta_id' => $physical['meta_id'] ] ) ) { throw new RuntimeException( 'Native Q06 tracked quantity mutation failed.' ); }
		$session = $fixture->factory->open(); try { if ( ! $session->begin() ) { throw new RuntimeException( 'Native Q06 physical guard unavailable.' ); } $changed = ! $flow->saved->verify( $session, $flow->verified->binding ); } finally { if ( $session->in_transaction() ) { $session->rollback(); } $session->retire(); $wpdb->replace( $wpdb->prefix . 'woocommerce_order_itemmeta', $physical ); }
		$case( 'NATIVE-W2Q06-SAVED-PHYSICAL-MUTATION-REFUSED', $changed && $before === $fixture->snapshot_bytes( $order ), [ 'physical_mutation_detected' => $changed, 'snapshot_bytes_unchanged' => $before === $fixture->snapshot_bytes( $order ), 'no_payment_invoked' => true ] );
		$phase = 'NATIVE-W2Q06-C07-FINAL-ACKNOWLEDGED-SEALED-RECEIPT'; $final = $flow->admission->final_order( $order, 'classic' );
		$case( 'NATIVE-W2Q06-C07-FINAL-ACKNOWLEDGED-SEALED-RECEIPT', $final->allowed && 'sealed' === $fixture->binding_row( $quote_id )['state'] && 3 === (int) $fixture->binding_row( $quote_id )['revision'] && $before === $fixture->snapshot_bytes( $order ), [ 'acknowledged' => $final->allowed, 'binding_sealed' => 'sealed' === $fixture->binding_row( $quote_id )['state'], 'snapshot_bytes_unchanged' => $before === $fixture->snapshot_bytes( $order ), 'binding_commits' => $fixture->factory->binding_commits, 'no_payment_invoked' => true ] );
		$phase = 'NATIVE-W2Q06-C07-SAME-REQUEST-NO-SECOND-PLACEMENT'; $sealed_history = $fixture->cart->history(); $same = $flow->admission->final_order( $order, 'classic' );
		$case( 'NATIVE-W2Q06-C07-SAME-REQUEST-NO-SECOND-PLACEMENT', $same->allowed && $sealed_history === $fixture->cart->history() && $before === $fixture->snapshot_bytes( $order ), [ 'acknowledged' => $same->allowed, 'no_second_binding_effect' => $sealed_history === $fixture->cart->history(), 'snapshot_bytes_unchanged' => $before === $fixture->snapshot_bytes( $order ) ] );
		$phase = 'NATIVE-W2Q06-HISTORY-AFTER-RATE-CURRENCY-TAX-CONFIG-CHANGE'; $fixture->cart->native->physical_update( 'rate_cards', $fixture->cart->native->rate, [ 'base_amount' => '99.0000', 'status' => 'inactive' ] ); $fixture->cart->native->set_option( 'woocommerce_currency', 'USD' ); $fixture->cart->native->set_option( 'woocommerce_calc_taxes', 'no' );
		$historical = new WC_Order( $order->get_id() );
		$case( 'NATIVE-W2Q06-HISTORY-AFTER-RATE-CURRENCY-TAX-CONFIG-CHANGE', QuoteNativeOrderHistory::verify( $historical ) && $before === $fixture->snapshot_bytes( $historical ) && $body === $fixture->cart->row( $quote_id )['private_body_json'], [ 'historical_reader_supported' => QuoteNativeOrderHistory::verify( $historical ), 'snapshot_bytes_unchanged' => $before === $fixture->snapshot_bytes( $historical ), 'quote_body_unchanged' => $body === $fixture->cart->row( $quote_id )['private_body_json'] ] );
		$phase = 'NATIVE-W2Q06-ACTUAL-PAID-CALLBACKS-KEEP-SEALED-HISTORY'; add_filter( 'pre_wp_mail', static fn (): bool => true ); $available = WC()->payment_gateways()->get_available_payment_gateways(); $guarded_gateway = $available[$native_gateway->id] ?? null; if ( ! $guarded_gateway instanceof CetechDeliveryEngine\Integrations\DeliveryQuote\QuoteOrderPayGateway || 0 !== $native_gateway->native_payment_calls() ) { throw new RuntimeException( 'Native Q06 acknowledged gateway adapter unavailable.' ); } $guarded_gateway->validate_fields(); $payment = $guarded_gateway->process_payment( $historical->get_id() ); $paid = new WC_Order( $historical->get_id() );
		$case( 'NATIVE-W2Q06-ACTUAL-PAID-CALLBACKS-KEEP-SEALED-HISTORY', $paid->is_paid() && 1 === $native_gateway->native_payment_calls() && 'success' === ( $payment['result'] ?? null ) && QuoteNativeOrderHistory::verify( $paid ) && $before === $fixture->snapshot_bytes( $paid ) && 'sealed' === $fixture->binding_row( $quote_id )['state'], [ 'binding_sealed' => 'sealed' === $fixture->binding_row( $quote_id )['state'], 'historical_reader_supported' => QuoteNativeOrderHistory::verify( $paid ), 'snapshot_bytes_unchanged' => $before === $fixture->snapshot_bytes( $paid ), 'gateway_calls' => $native_gateway->native_payment_calls(), 'no_payment_invoked' => false ] );
		$phase = 'NATIVE-W2Q06-C07-POSTSTAMP-NATIVE-MUTATION-DENIED'; $sealed_history = $fixture->cart->history(); $old_quantity = $item->get_quantity(); $item->set_quantity( 99 ); $mutated = $flow->admission->final_order( $order, 'classic' ); $item->set_quantity( $old_quantity );
		$case( 'NATIVE-W2Q06-C07-POSTSTAMP-NATIVE-MUTATION-DENIED', ! $mutated->allowed && $sealed_history === $fixture->cart->history(), [ 'final_admission_denied' => ! $mutated->allowed, 'local_mutation_detected' => ! $mutated->allowed, 'no_second_binding_effect' => $sealed_history === $fixture->cart->history(), 'no_payment_invoked' => true ] );
		$isolate();
		$phase = 'NATIVE-W2Q06-PREPARE-LOST-ACK-ORIGINAL-REPLAY'; $lost_prepare = new CetechQuotePlacementNativeFlow( $fixture ); $faults = $fixture->factory->masked_binding_acks; $lost_prepare->create( 'prepare_ack' ); $writes = $fixture->factory->binding_writes;
		$denied = $lost_prepare->admission->final_order( $lost_prepare->order, 'classic' ); $recovered = $lost_prepare->service->prepare( $lost_prepare->order->get_id(), $lost_prepare->mapping, RequestContext::create() ); $fixture->track_result( $recovered );
		$case( 'NATIVE-W2Q06-PREPARE-LOST-ACK-ORIGINAL-REPLAY', $lost_prepare->creation_refused && ! $denied->allowed && $known( $recovered ) && 1 === $recovered->binding->revision() && $faults + 1 === $fixture->factory->masked_binding_acks && $fixture->factory->fault_retired() && $writes === $fixture->factory->binding_writes, [ 'original_envelope_reconciled' => $known( $recovered ), 'binding_prepared' => 1 === $recovered->binding?->revision(), 'final_admission_denied' => ! $denied->allowed, 'uncertain_connection_retired' => $fixture->factory->fault_retired(), 'no_second_binding_effect' => $writes === $fixture->factory->binding_writes, 'masked_binding_acks' => $fixture->factory->masked_binding_acks, 'no_payment_invoked' => true ] );
		if ( ! $lost_prepare->recover_original() ) { throw new RuntimeException( 'Native Q06 original prepare recovery unavailable.' ); }
		$phase = 'NATIVE-W2Q06-VERIFY-LOST-ACK-ORIGINAL-PHYSICAL-REPLAY'; $lost_verify = new CetechQuotePlacementNativeFlow( $fixture ); $faults = $fixture->factory->masked_binding_acks; $lost_verify->create( 'verify_ack' ); $writes = $fixture->factory->binding_writes; $unknown_bytes = $fixture->snapshot_bytes( $lost_verify->order ); $denied = $lost_verify->admission->final_order( $lost_verify->order, 'classic' );
		$original = $lost_verify->physical_binding; $recovered = $lost_verify->service->verify( $original, $lost_verify->saved, RequestContext::create() ); $fixture->track_result( $recovered );
		$case( 'NATIVE-W2Q06-VERIFY-LOST-ACK-ORIGINAL-PHYSICAL-REPLAY', $lost_verify->creation_refused && ! $denied->allowed && $known( $recovered ) && 2 === $recovered->binding->revision() && $faults + 1 === $fixture->factory->masked_binding_acks && $fixture->factory->fault_retired() && $writes === $fixture->factory->binding_writes && $unknown_bytes === $fixture->snapshot_bytes( $lost_verify->order ), [ 'original_envelope_reconciled' => $known( $recovered ), 'binding_verified' => 2 === $recovered->binding?->revision(), 'final_admission_denied' => ! $denied->allowed, 'uncertain_connection_retired' => $fixture->factory->fault_retired(), 'no_second_binding_effect' => $writes === $fixture->factory->binding_writes, 'snapshot_bytes_unchanged' => $unknown_bytes === $fixture->snapshot_bytes( $lost_verify->order ), 'no_payment_invoked' => true ] );
		if ( ! $lost_verify->recover_original() ) { throw new RuntimeException( 'Native Q06 original verification recovery unavailable.' ); }
		$phase = 'NATIVE-W2Q06-SEAL-LOST-ACK-NO-ADMISSION-ORIGINAL-REPLAY'; $lost_seal = new CetechQuotePlacementNativeFlow( $fixture ); $lost_seal->create(); $faults = $fixture->factory->masked_binding_acks; $fixture->factory->mask_next_binding_ack = true; $denied = $lost_seal->admission->final_order( $lost_seal->order, 'classic' ); $writes = $fixture->factory->binding_writes; $unknown_bytes = $fixture->snapshot_bytes( $lost_seal->order );
		$recovered = $lost_seal->replay_seal();
		$case( 'NATIVE-W2Q06-SEAL-LOST-ACK-NO-ADMISSION-ORIGINAL-REPLAY', ! $denied->allowed && 'sealed' === $fixture->binding_row( $lost_seal->evidence->header()->id()->value() )['state'] && $known( $recovered ) && 'sealed' === $recovered->binding->state() && $faults + 1 === $fixture->factory->masked_binding_acks && $fixture->factory->fault_retired() && $writes === $fixture->factory->binding_writes && $unknown_bytes === $fixture->snapshot_bytes( $lost_seal->order ), [ 'original_envelope_reconciled' => $known( $recovered ), 'binding_sealed' => 'sealed' === $recovered->binding?->state(), 'final_admission_denied' => ! $denied->allowed, 'uncertain_connection_retired' => $fixture->factory->fault_retired(), 'no_second_binding_effect' => $writes === $fixture->factory->binding_writes, 'snapshot_bytes_unchanged' => $unknown_bytes === $fixture->snapshot_bytes( $lost_seal->order ), 'no_payment_invoked' => true ] );
		if ( ! $lost_seal->recover_original() ) { throw new RuntimeException( 'Native Q06 original sealed recovery unavailable.' ); }
		$phase = 'NATIVE-W2Q06-PREFREEZE-NATIVE-MONEY-MUTATION-DENIED'; $money_mutation = new CetechQuotePlacementNativeFlow( $fixture );
		$money_mutation->before_freeze = static function ( WC_Order $order ): void { array_values( $order->get_items( 'line_item' ) )[0]->set_total( '99' ); };
		$money_mutation->create(); $writes = $fixture->factory->binding_writes; $denied = $money_mutation->admission->final_order( $money_mutation->order, 'classic' );
		$case( 'NATIVE-W2Q06-PREFREEZE-NATIVE-MONEY-MUTATION-DENIED', $money_mutation->prefreeze_staged && ! $denied->allowed && $writes === $fixture->factory->binding_writes && 'prepared' === $fixture->binding_row( $money_mutation->evidence->header()->id()->value() )['state'], [ 'final_admission_denied' => ! $denied->allowed, 'local_mutation_detected' => ! $denied->allowed, 'binding_verified' => 2 === $money_mutation->physical_binding->revision(), 'no_second_binding_effect' => $writes === $fixture->factory->binding_writes, 'no_payment_invoked' => true ] );
		$isolate();
		$phase = 'NATIVE-W2Q06-PREFREEZE-NATIVE-METADATA-MUTATION-DENIED'; $meta_mutation = new CetechQuotePlacementNativeFlow( $fixture );
		$meta_mutation->before_freeze = static function ( WC_Order $order ): void { $order->update_meta_data( CetechDeliveryEngine\Application\Order\QuoteNativeOrderFacts::META_TAX_SOURCE, 'SYNTHETIC-Q06-PREFREEZE-MUTATION' ); };
		$meta_mutation->create(); $writes = $fixture->factory->binding_writes; $denied = $meta_mutation->admission->final_order( $meta_mutation->order, 'classic' );
		$case( 'NATIVE-W2Q06-PREFREEZE-NATIVE-METADATA-MUTATION-DENIED', $meta_mutation->prefreeze_staged && ! $denied->allowed && $writes === $fixture->factory->binding_writes && 'prepared' === $fixture->binding_row( $meta_mutation->evidence->header()->id()->value() )['state'], [ 'final_admission_denied' => ! $denied->allowed, 'local_mutation_detected' => ! $denied->allowed, 'binding_verified' => 2 === $meta_mutation->physical_binding->revision(), 'no_second_binding_effect' => $writes === $fixture->factory->binding_writes, 'no_payment_invoked' => true ] );
		$isolate();
		$phase = 'NATIVE-W2Q06-LATE-PAUSE-BEFORE-FINAL-RECEIPT-WINS'; $paused = new CetechQuotePlacementNativeFlow( $fixture ); $paused->create(); $writes = $fixture->factory->binding_writes;
		$paused->before_seal = static function () use ( $fixture ): void { $fixture->cart->native->set_option( EmergencyControlStore::OPTION_NAME, EmergencyControlState::record_json( get_current_blog_id(), 'checkout_suspended', 990002, 'operator_pause', 1, time() ) ); };
		$denied = $paused->admission->final_order( $paused->order, 'classic' );
		$case( 'NATIVE-W2Q06-LATE-PAUSE-BEFORE-FINAL-RECEIPT-WINS', ! $denied->allowed && $writes === $fixture->factory->binding_writes && 'prepared' === $fixture->binding_row( $paused->evidence->header()->id()->value() )['state'], [ 'late_pause_won' => ! $denied->allowed, 'final_admission_denied' => ! $denied->allowed, 'binding_prepared' => 'prepared' === $fixture->binding_row( $paused->evidence->header()->id()->value() )['state'], 'no_second_binding_effect' => $writes === $fixture->factory->binding_writes, 'no_payment_invoked' => true ] );
		$phase = 'NATIVE-W2Q06-EXPLICIT-NEW-QUOTE-AFTER-KNOWN-TERMINAL-REJECTION'; $old_quote_id = $paused->evidence->header()->id()->value(); $old_binding = $fixture->binding_row( $old_quote_id ); $old_quote = $fixture->cart->row( $old_quote_id )['private_body_json']; $old_order_bytes = $fixture->snapshot_bytes( $paused->order );
		$rejection_receipt = static function () use ( $fixture, $old_binding ): array { $history = $fixture->cart->history(); $records = array_values( array_filter( $history['operation_records'], static fn ( array $row ): bool => $row['namespace_hash'] === $old_binding['seal_namespace_hash'] && 'delivery_quote.seal' === $row['operation'] ) ); $ids = array_column( $records, 'id' ); $events = array_values( array_filter( $history['operation_changes'], static fn ( array $row ): bool => in_array( $row['operation_id'], $ids, true ) ) ); return [ 'records' => $records, 'events' => $events ]; }; $old_rejection = $rejection_receipt();
		$fixture->cart->native->set_option( EmergencyControlStore::OPTION_NAME, EmergencyControlState::record_json( get_current_blog_id(), 'enabled', 990003, 'resume_verified', 1, time() ) );
		$new_intent = new CetechQuotePlacementNativeFlow( $fixture ); $new_intent->create(); $new_final = $new_intent->admission->final_order( $new_intent->order, 'classic' ); $new_quote_id = $new_intent->evidence->header()->id()->value();
		$receipt_preserved = 1 === count( $old_rejection['records'] ) && 'rejected' === $old_rejection['records'][0]['state'] && [] === $old_rejection['events'] && $old_rejection === $rejection_receipt();
		$preserved = $receipt_preserved && $old_binding === $fixture->binding_row( $old_quote_id ) && $old_quote === $fixture->cart->row( $old_quote_id )['private_body_json'] && $old_order_bytes === $fixture->snapshot_bytes( $paused->order );
		$case( 'NATIVE-W2Q06-EXPLICIT-NEW-QUOTE-AFTER-KNOWN-TERMINAL-REJECTION', $new_final->allowed && $new_quote_id !== $old_quote_id && $new_intent->order->get_id() !== $paused->order->get_id() && 'sealed' === $fixture->binding_row( $new_quote_id )['state'] && $preserved, [ 'acknowledged' => $new_final->allowed, 'binding_sealed' => 'sealed' === $fixture->binding_row( $new_quote_id )['state'], 'snapshot_bytes_unchanged' => $old_order_bytes === $fixture->snapshot_bytes( $paused->order ), 'quote_body_unchanged' => $old_quote === $fixture->cart->row( $old_quote_id )['private_body_json'], 'same_original_binding' => $old_binding === $fixture->binding_row( $old_quote_id ), 'original_rejection_receipt_unchanged' => $receipt_preserved, 'no_payment_invoked' => true ] );
		$isolate();
		$phase = 'NATIVE-W2Q06-DATABASE-EXPIRY-BEFORE-FINAL-RECEIPT-WINS'; $expired = new CetechQuotePlacementNativeFlow( $fixture ); $expired->create(); $writes = $fixture->factory->binding_writes;
		$expired->before_seal = static function () use ( $fixture, $expired ): void { $fixture->factory->clock = $expired->evidence->header()->expires_at(); }; $denied = $expired->admission->final_order( $expired->order, 'classic' ); $fixture->factory->clock = null;
		$case( 'NATIVE-W2Q06-DATABASE-EXPIRY-BEFORE-FINAL-RECEIPT-WINS', ! $denied->allowed && $fixture->factory->verified_clocks > 0 && $writes === $fixture->factory->binding_writes && 'prepared' === $fixture->binding_row( $expired->evidence->header()->id()->value() )['state'], [ 'late_expiry_won' => ! $denied->allowed, 'final_admission_denied' => ! $denied->allowed, 'verified_sql_clocks' => $fixture->factory->verified_clocks, 'binding_prepared' => 'prepared' === $fixture->binding_row( $expired->evidence->header()->id()->value() )['state'], 'no_payment_invoked' => true ] );
	} catch ( Throwable $error ) {
		if ( ! in_array( $phase, $completed, true ) ) { $check( 'hpos_off' === $mode ? str_replace( 'NATIVE-W2Q06-', 'NATIVE-W2Q06-HPOS-OFF-', $phase ) : $phase, false, [ 'required_case_incomplete' => true, 'error_class' => CetechQuotePlacementObservation::error_class( $error ) ] ); }
		throw $error;
	} finally {
		$cleanup = $fixture->cleanup(); foreach ( $prior_cleanup as $key => $ok ) { $cleanup[$key] = $ok && $cleanup[$key]; } $case( 'NATIVE-W2Q06-EXACT-FIXTURE-CLEANUP', $cleanup['cleanup_restored'], $cleanup );
	}
};
