<?php
declare(strict_types=1);

use CetechDeliveryEngine\Application\DeliveryQuote\{PromiseQuotePaymentBoundary, PromiseQuotePlacementActivation, QuoteDurableService, QuoteProviderRegistry};
use CetechDeliveryEngine\Application\Order\{DeliveryQuoteSnapshotEnvelope, DeliveryQuoteSnapshotReader, OrderDeliverySnapshot, OrderDeliverySnapshotReader, QuoteNativeOrderHistory, RequiredPromiseSnapshotReadiness, SnapshotExtensionParser};
use CetechDeliveryEngine\Domain\Contracts\RequestContext;
use CetechDeliveryEngine\Domain\DeliveryQuote\{QuoteBinding, QuoteContext, QuoteHeader, QuoteStoredRow, QuoteTerms, QuoteTime};
use CetechDeliveryEngine\Domain\ServicePromise\Handoff\{PromiseHistoricalPacket, PromiseQuotePacket};
use CetechDeliveryEngine\Integrations\ServicePromise\NativePromiseRuntimeCapture;

/** Separate P04 facts from real native capture, Woo saved bytes and original acknowledged placement. */
return static function ( callable $check, string $mode = 'hpos_on' ): void {
	global $wpdb;
	if ( '1' !== getenv( 'CETECH_DE_NATIVE_OPENING_QUALIFICATION' ) || true !== WP_ADMIN || '1' !== (string) get_option( 'cetech_opening_qualification_disposable' ) || ! $wpdb instanceof wpdb || wpdb::class !== get_class( $wpdb ) || ( 'hpos_on' === $mode ) !== Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled() || is_multisite() || WP_Object_Cache::class !== get_class( $GLOBALS['wp_object_cache'] ) ) { throw new RuntimeException( 'P04 requires the exact marked native storage fixture.' ); }
	foreach ( get_included_files() as $file ) { if ( str_ends_with( str_replace( '\\', '/', $file ), '/tests/bootstrap.php' ) ) { throw new RuntimeException( 'P04 native qualification forbids the unit bootstrap.' ); } }
	require_once __DIR__ . '/opening-promise-handoff-support.php';
	$fixture = null; $failure = null; $cleanup = [ 'cleanup_restored' => true, 'owned_orders_removed' => true, 'original_quote_history_restored' => true, 'original_promise_history_restored' => true, 'all_owned_connections_retired' => true, 'default_adoption_restored' => true ];
	$isolate = static function ( array $changes = [] ) use ( &$fixture, &$cleanup, $wpdb ): void { if ( null !== $fixture ) { foreach ( $fixture->cleanup() as $key => $ok ) { $cleanup[$key] = $cleanup[$key] && $ok; } if ( ! $cleanup['cleanup_restored'] ) { throw new RuntimeException( 'P04 prior tracked fixture cleanup differs.' ); } } $fixture = new CetechPromiseHandoffNativeFixture( $wpdb ); $fixture->prepare( $changes ); };
	$refuses = static function ( callable $work ): bool { try { $work(); return false; } catch ( Throwable ) { return true; } };
	$durable = static function ( $flow ) use ( &$fixture ): QuoteDurableService { return new QuoteDurableService( $fixture->native->factory, new QuoteProviderRegistry(), [ $flow->evidence, 'authorize' ], evidence: $flow->evidence->guard() ); };
	try {
		$check( 'NATIVE-W2P04-MARKED-INSTALLED-NATIVE-ENVIRONMENT', defined( 'ABSPATH' ) && class_exists( WC_Order::class ) && '10' === (string) get_option( 'cetech_de_db_version' ), [ 'real_wp_load' => defined( 'ABSPATH' ), 'native_woo_crud' => class_exists( WC_Order::class ), 'schema10_unchanged' => '10' === (string) get_option( 'cetech_de_db_version' ) ] );
		$readiness = RequiredPromiseSnapshotReadiness::contract(); $default = PromiseQuotePlacementActivation::decode( null ); $optional = ( new SnapshotExtensionParser() )->read( [ 'extensions' => [ 'promise' => [ 'version' => 1, 'required' => true, 'data' => [] ] ] ] );
		$check( 'NATIVE-W2P04-READER-FIRST-DEFAULT-OFF-DISTINCT-C05', false === $default['enabled'] && true === $readiness['reader_only'] && true === $readiness['supports_required'] && RequiredPromiseSnapshotReadiness::supports( '3', 2, DeliveryQuoteSnapshotEnvelope::PROMISE_PROFILE, 1 ) && ! RequiredPromiseSnapshotReadiness::supports( '2', 1, DeliveryQuoteSnapshotEnvelope::PROFILE, 1 ) && ! $optional->required_semantics_supported(), [ 'default_new_writes_off' => false === $default['enabled'], 'compiled_reader_only' => true === $readiness['reader_only'], 'new_required_capability' => true === $readiness['supports_required'], 'legacy_c05_required_refused' => ! $optional->required_semantics_supported(), 'exact_new_format_readiness' => RequiredPromiseSnapshotReadiness::supports( '3', 2, DeliveryQuoteSnapshotEnvelope::PROMISE_PROFILE, 1 ) ] );
		$isolate(); $flow = new CetechQuotePlacementNativeFlow( $fixture->native ); $header = $flow->evidence->header(); $quote_id = $header->id()->value(); $body = $fixture->native->cart->row( $quote_id ); $context = $flow->evidence->context(); $terms = $flow->evidence->terms(); $packet = $terms->promise_packet();
		$check( 'NATIVE-W2P04-LEGACY-QUOTE-BYTES-AND-DOMAINS-PRESERVED', $fixture->legacy_bytes === $fixture->native->cart->row( $fixture->legacy->header()->id()->value() ) && 1 === $fixture->legacy->header()->format_version() && 'legacy_fixed_base_v1' === $fixture->legacy->header()->profile(), [ 'old_physical_full_row_identical' => $fixture->legacy_bytes === $fixture->native->cart->row( $fixture->legacy->header()->id()->value() ), 'old_header_format1' => 1 === $fixture->legacy->header()->format_version(), 'old_profile_unchanged' => 'legacy_fixed_base_v1' === $fixture->legacy->header()->profile() ] );
		$sources = $fixture->source_rows(); $acked_sources = 2 === count( $sources ); foreach ( $sources as $source ) { $acked_sources = $acked_sources && 'published' === $source['state'] && null !== $source['published_at'] && null !== $source['publication_receipt_digest'] && 64 === strlen( $source['publication_receipt_digest'] ); }
		$check( 'NATIVE-W2P04-ACTUAL-P02-PUBLICATION-AND-ASSIGNMENT-CAPTURE', $acked_sources && 2 === $context->format_version() && $context->private_facts()['promise_capture']['site_key'] === $fixture->binding->site_key(), [ 'physical_policy_calendar_published' => $acked_sources, 'trusted_native_opaque_binding' => $context->private_facts()['promise_capture']['site_key'] === $fixture->binding->site_key(), 'captured_assignment_receipt_present' => [] !== $context->promise_groups() && 64 === strlen( $context->promise_groups()[0]['assignment_receipt_digest'] ) ] );
		$runtime = ( new NativePromiseRuntimeCapture() )->capture(); $runtime_exact = true; foreach ( $packet->private_facts()['groups'] as $group ) { $runtime_exact = $runtime_exact && CetechDeliveryEngine\Domain\ServicePromise\PromiseJson::encode( PromiseHistoricalPacket::from_array( $group['packet'] )->input_facts()['runtime'] ) === CetechDeliveryEngine\Domain\ServicePromise\PromiseJson::encode( $runtime ); }
		$check( 'NATIVE-W2P04-NATIVE-RUNTIME-CONTENT-ATTESTATION', $runtime_exact, [ 'actual_native_collector_tuple' => $runtime_exact, 'private_runtime_digest_present' => 64 === strlen( $runtime['digest'] ?? '' ) ] );
		$clock = true; foreach ( $packet->private_facts()['groups'] as $group ) { $input = PromiseHistoricalPacket::from_array( $group['packet'] )->input_facts(); $clock = $clock && $input['evaluated_at'] === $header->created_at()->sql() && $input['anchor']['quote_expires_at'] === $header->expires_at()->sql() && $input['material']['material_digest'] === $context->base_material_digest(); }
		$check( 'NATIVE-W2P04-ORIGINAL-ISSUE-CLOCK-AND-DISTINCT-MATERIAL', $clock && 300000000 === $header->expires_at()->epoch_microseconds() - $header->created_at()->epoch_microseconds() && $context->digest() !== $context->base_material_digest(), [ 'every_group_original_issue_clock' => $clock, 'ttl_exactly_300_seconds' => 300000000 === $header->expires_at()->epoch_microseconds() - $header->created_at()->epoch_microseconds(), 'new_complete_material_domain' => $context->digest() !== $context->base_material_digest() ] );
		$base_money = $terms->base_terms()->private_facts(); $native_money_same = $base_money['groups'] === $terms->private_facts()['groups'];
		$check( 'NATIVE-W2P04-DISTINCT-PROFILE-RETAINS-NATIVE-MONEY', 2 === $header->format_version() && 2 === $terms->format_version() && 'service_promise_v1' === $header->profile() && $native_money_same, [ 'quote_context_terms_header_v2' => 2 === $header->format_version() && 2 === $context->format_version() && 2 === $terms->format_version(), 'new_profile_explicit' => 'service_promise_v1' === $header->profile(), 'base_native_money_unchanged' => $native_money_same ] );
		$bad_context = $context->private_facts(); $bad_context['caller_claimed'] = true; $bad_terms = $terms->private_facts(); $bad_terms['format_version'] = 3; $bad_header = $header->private_facts(); $bad_header['format_version'] = 3;
		$check( 'NATIVE-W2P04-CLOSED-QUOTE-FUTURE-AND-EXTRA-FIELDS-REFUSE', $refuses( static fn() => QuoteContext::from_array( $bad_context ) ) && $refuses( static fn() => QuoteTerms::from_array( $bad_terms ) ) && $refuses( static fn() => QuoteHeader::from_array( $bad_header ) ), [ 'extra_context_refused' => $refuses( static fn() => QuoteContext::from_array( $bad_context ) ), 'future_terms_refused' => $refuses( static fn() => QuoteTerms::from_array( $bad_terms ) ), 'future_header_refused' => $refuses( static fn() => QuoteHeader::from_array( $bad_header ) ) ] );
		$gateway = $fixture->native->register_gateway(); $flow->payment_method = $gateway->id; $flow->create(); $order = $flow->order; $physical = $fixture->native->snapshot_bytes( $order ); $envelope = $fixture->packet( $order );
		$check( 'NATIVE-W2P04-ACTUAL-HPOS-CPT-MANDATORY-OUTER3-ENVELOPE2', QuoteNativeOrderHistory::verify( $order ) && '3' === (string) $order->get_meta( OrderDeliverySnapshot::META_ORDER_SNAPSHOT_VERSION, true ) && '2' === (string) $order->get_meta( DeliveryQuoteSnapshotEnvelope::META_FORMAT, true ) && 2 === $envelope->format(), [ 'actual_native_saved_order' => $order->get_id() > 0, 'outer_version3' => '3' === (string) $order->get_meta( OrderDeliverySnapshot::META_ORDER_SNAPSHOT_VERSION, true ), 'mandatory_marker2' => '2' === (string) $order->get_meta( DeliveryQuoteSnapshotEnvelope::META_FORMAT, true ), 'exact_envelope2_read' => 2 === $envelope->format(), 'physical_protected_packet_present' => [] !== $physical['order'] && [] !== $physical['items'] ] );
		$all_groups = $envelope->promise_packet()->to_private_json() === $packet->to_private_json(); foreach ( $order->get_items( 'line_item' ) as $item ) { $read = ( new OrderDeliverySnapshotReader() )->read_line( $item ); $all_groups = $all_groups && 'recorded' === $read->delivery_quote?->status && $read->delivery_quote->envelope->promise_packet()->to_private_json() === $packet->to_private_json(); }
		$check( 'NATIVE-W2P04-EVERY-PHYSICAL-LINE-CARRIES-EXACT-GROUP-PACKET', $all_groups, [ 'native_line_packet_equals_quote' => $all_groups, 'order_packet_equals_quote' => $envelope->promise_packet()->to_private_json() === $packet->to_private_json(), 'protected_history_reader_supported' => QuoteNativeOrderHistory::verify( $order ) ] );
		$reader = new DeliveryQuoteSnapshotReader(); $future = $envelope->private_facts(); $future['format'] = 3; $malformed = $envelope->private_facts(); $malformed['promise_packet_digest'] = str_repeat( '0', 64 );
		$check( 'NATIVE-W2P04-FUTURE-MALFORMED-MISSING-READER-NO-FALLBACK', 'unsupported' === $reader->read( [ 'snapshot_version' => '3', 'delivery_quote' => $future ], true, '3' )->status && 'malformed' === $reader->read( [ 'snapshot_version' => '3', 'delivery_quote' => $malformed ], true, '2' )->status && 'missing' === $reader->read( [ 'snapshot_version' => '3' ], true, '2' )->status, [ 'future_packet_unsupported' => 'unsupported' === $reader->read( [ 'snapshot_version' => '3', 'delivery_quote' => $future ], true, '3' )->status, 'changed_digest_malformed' => 'malformed' === $reader->read( [ 'snapshot_version' => '3', 'delivery_quote' => $malformed ], true, '2' )->status, 'owned_missing_refused' => 'missing' === $reader->read( [ 'snapshot_version' => '3' ], true, '2' )->status, 'original_physical_bytes_preserved' => $physical === $fixture->native->snapshot_bytes( $order ) ] );
		$line_item = array_values( $order->get_items( 'line_item' ) )[0]; $itemmeta = $wpdb->prefix . 'woocommerce_order_itemmeta';
		$line_packet = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM `{$itemmeta}` WHERE order_item_id=%d AND meta_key=%s", $line_item->get_id(), OrderDeliverySnapshot::META_LINE_SNAPSHOT ), ARRAY_A );
		if ( ! is_array( $line_packet ) || '' !== $wpdb->last_error || 1 !== $wpdb->update( $itemmeta, [ 'meta_value' => '{"format":99}' ], [ 'meta_id' => (int) $line_packet['meta_id'] ] ) ) { throw new RuntimeException( 'P04 tracked physical packet mutation is unavailable.' ); }
		$packet_owner = $fixture->native->factory->open(); try { if ( ! $packet_owner->begin() ) { throw new RuntimeException( 'P04 physical packet guard owner is unavailable.' ); } $packet_changed = ! $flow->saved->verify( $packet_owner, $flow->physical_binding ); } finally { if ( $packet_owner->in_transaction() ) { $packet_owner->rollback(); } $packet_owner->retire(); if ( false === $wpdb->replace( $itemmeta, $line_packet ) ) { throw new RuntimeException( 'P04 tracked physical packet restoration failed.' ); } }
		$check( 'NATIVE-W2P04-PHYSICAL-PRIVATE-PACKET-MUTATION-REFUSED', $packet_changed && $physical === $fixture->native->snapshot_bytes( $order ), [ 'actual_native_physical_packet_changed' => $packet_changed, 'same_owned_sql_guard_refused' => $packet_changed, 'exact_packet_restored' => $physical === $fixture->native->snapshot_bytes( $order ), 'no_gateway_before_repair' => 0 === $gateway->native_payment_calls(), 'original_owner_retired' => $packet_owner->is_retired() ] );
		$duplicate_row = $line_packet; unset( $duplicate_row['meta_id'] ); if ( false === $wpdb->insert( $itemmeta, $duplicate_row ) || $wpdb->insert_id < 1 ) { throw new RuntimeException( 'P04 tracked duplicate packet allocation failed.' ); } $duplicate_id = (int) $wpdb->insert_id;
		$census_owner = $fixture->native->factory->open(); try { if ( ! $census_owner->begin() ) { throw new RuntimeException( 'P04 census guard owner is unavailable.' ); } $duplicate_refused = ! $flow->saved->verify( $census_owner, $flow->physical_binding ); } finally { if ( $census_owner->in_transaction() ) { $census_owner->rollback(); } $census_owner->retire(); if ( 1 !== $wpdb->delete( $itemmeta, [ 'meta_id' => $duplicate_id, 'order_item_id' => $line_item->get_id() ] ) ) { throw new RuntimeException( 'P04 exact tracked duplicate cleanup failed.' ); } }
		$check( 'NATIVE-W2P04-FULL-PHYSICAL-PACKET-CENSUS-REFUSES-DUPLICATE', $duplicate_refused && $physical === $fixture->native->snapshot_bytes( $order ), [ 'native_duplicate_packet_refused' => $duplicate_refused, 'exact_tracked_duplicate_removed' => $physical === $fixture->native->snapshot_bytes( $order ), 'saved_money_and_packet_preserved' => $physical === $fixture->native->snapshot_bytes( $order ), 'census_owner_retired' => $census_owner->is_retired() ] );
		$before_link = $durable( $flow )->acknowledged_promise_seal( $flow->evidence->owner(), $flow->evidence->reference(), $header, $flow->physical_binding, $flow->saved );
		$check( 'NATIVE-W2P04-Q05-CONFIRM-IS-NOT-FINAL-PROMISE-ACCEPTANCE', null === $before_link && 'prepared' === $flow->physical_binding->state() && 0 === $gateway->native_payment_calls(), [ 'confirmed_quote_not_final_event' => null === $before_link, 'no_gateway_before_seal' => 0 === $gateway->native_payment_calls(), 'original_q05_acceptance_preserved' => $body['accepted_at'] === $fixture->native->cart->row( $quote_id )['accepted_at'] ] );
		$final = $flow->admission->final_order( $order, 'classic' ); $sealed = QuoteBinding::from_row( $fixture->native->binding_row( $quote_id ), $flow->evidence->quote_record() ); $linkage = $durable( $flow )->acknowledged_promise_seal( $flow->evidence->owner(), $flow->evidence->reference(), $header, $sealed, $flow->saved );
		$check( 'NATIVE-W2P04-ACKNOWLEDGED-ORIGINAL-Q06-SEAL-LINKAGE', $final->allowed && null !== $linkage && 'q06_placement_sealed' === $linkage->private_facts()['final_event']['kind'] && $linkage->private_facts()['snapshot_digest'] === $sealed->row()['snapshot_digest'], [ 'final_admission_acknowledged' => $final->allowed, 'actual_q06_sealed_event' => null !== $linkage && 'q06_placement_sealed' === $linkage->private_facts()['final_event']['kind'], 'original_physical_snapshot_link' => null !== $linkage && $linkage->private_facts()['snapshot_digest'] === $sealed->row()['snapshot_digest'], 'no_post_seal_snapshot_rewrite' => $physical === $fixture->native->snapshot_bytes( $order ) ] );
		$boundary = new PromiseQuotePaymentBoundary( $flow->evidence->quote_record(), $sealed, $linkage, $flow->evidence->guard() ); $expiry = $header->expires_at();
		$check( 'NATIVE-W2P04-EXCLUSIVE-ORIGINAL-TTL-AND-PROMISE-DEADLINE', $boundary->eligible_at( $header->created_at() ) && ! $boundary->eligible_at( $expiry ) && ! $packet->feasibility_at( $expiry ), [ 'original_capture_eligible' => $boundary->eligible_at( $header->created_at() ), 'ttl_equality_denied' => ! $boundary->eligible_at( $expiry ), 'promise_deadline_equality_denied' => ! $packet->feasibility_at( $expiry ), 'original_expiry_unchanged' => $body['expires_at'] === $fixture->native->cart->row( $quote_id )['expires_at'] ] );
		$history = $fixture->native->cart->history(); $same = $flow->admission->final_order( $order, 'classic' );
		$check( 'NATIVE-W2P04-SAME-ORIGINAL-RETRY-ONE-SEALED-EFFECT', $same->allowed && $history === $fixture->native->cart->history() && $physical === $fixture->native->snapshot_bytes( $order ), [ 'same_request_admission' => $same->allowed, 'no_second_quote_or_binding_effect' => $history === $fixture->native->cart->history(), 'original_snapshot_bytes' => $physical === $fixture->native->snapshot_bytes( $order ), 'original_private_quote_body' => $body['private_body_json'] === $fixture->native->cart->row( $quote_id )['private_body_json'] ] );
		add_filter( 'pre_wp_mail', '__return_true', PHP_INT_MAX ); $available = WC()->payment_gateways()->get_available_payment_gateways(); $guarded = $available[$gateway->id] ?? null; if ( ! $guarded instanceof CetechDeliveryEngine\Integrations\DeliveryQuote\QuoteOrderPayGateway ) { throw new RuntimeException( 'P04 actual guarded native gateway is unavailable.' ); } $guarded->validate_fields(); $paid_result = $guarded->process_payment( $order->get_id() ); $paid = new WC_Order( $order->get_id() );
		$check( 'NATIVE-W2P04-ACTUAL-NATIVE-GATEWAY-AFTER-PROMISE-SEAL', 1 === $gateway->native_payment_calls() && $paid->is_paid() && 'success' === ( $paid_result['result'] ?? null ) && QuoteNativeOrderHistory::verify( $paid ), [ 'gateway_exactly_once' => 1 === $gateway->native_payment_calls(), 'native_payment_completed' => $paid->is_paid(), 'sealed_binding_before_payment' => 'sealed' === $fixture->native->binding_row( $quote_id )['state'], 'full_packet_unchanged_after_payment' => $physical === $fixture->native->snapshot_bytes( $paid ) ] );
		$original_refs = $linkage->accepted_groups();
		$check( 'NATIVE-W2P04-STRUCTURED-ORIGINAL-REFERENCE-FROM-ACKNOWLEDGED-PACKET', count( $original_refs ) === count( $packet->private_facts()['groups'] ) && $original_refs[0]['final_event'] === $linkage->private_facts()['final_event'], [ 'every_group_has_structured_original' => count( $original_refs ) === count( $packet->private_facts()['groups'] ), 'exact_q06_event_reference' => $original_refs[0]['final_event'] === $linkage->private_facts()['final_event'], 'original_packet_digest_reference' => $original_refs[0]['quote']['promise_packet_digest'] === $packet->digest() ] );
		$fixture->assignment( 'disabled', null ); $changed_capture = $refuses( fn() => $fixture->capture->capture( $context->base_context(), $flow->evidence->owner(), CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime::parse( QuoteTime::now()->sql() ), $fixture->registry->create_demands( $context->base_context() ) ) ); $changed_order = new WC_Order( $paid->get_id() );
		$check( 'NATIVE-W2P04-ASSIGNMENT-MUTATION-REFUSES-NEW-CAPTURE-KEEPS-HISTORY', $changed_capture && QuoteNativeOrderHistory::verify( $changed_order ) && $envelope->to_private_json() === $fixture->packet( $changed_order )->to_private_json(), [ 'changed_policy_selection_refused' => $changed_capture, 'original_saved_history_readable' => QuoteNativeOrderHistory::verify( $changed_order ), 'original_packet_bytes_frozen' => $envelope->to_private_json() === $fixture->packet( $changed_order )->to_private_json() ] );
		$removed = $fixture->remove_sources(); $deleted_order = new WC_Order( $paid->get_id() );
		// The typed shipment selects an actual saved group and native line only;
		// original acceptance authority comes solely from the concrete SQL ACK reader.
		$package_groups = ( new OrderDeliverySnapshotReader() )->read_package( $deleted_order )->snapshot->groups;
		$selected_group = $package_groups[0]->group_id;
		$selected_native_line = false; foreach ( $deleted_order->get_items( 'line_item' ) as $native_item ) { $native_line = ( new OrderDeliverySnapshotReader() )->read_line( $native_item ); $selected_native_line = $selected_native_line || $native_line->snapshot?->delivery_group_id === $selected_group; }
		$shipment = CetechDeliveryEngine\Domain\Shipment\Shipment::create( $deleted_order->get_id(), $selected_group, fulfilment_choice: 'delivery', id: 1 );
		$exact_native_access = static fn( WC_Order $requested ): bool => $requested->get_id() === $deleted_order->get_id() && 1 === get_current_user_id() && current_user_can( 'manage_woocommerce' );
		$history_globals = []; foreach ( [ 'current_user', 'user_ID', 'userdata', 'user_login', 'user_level', 'user_email', 'user_url', 'user_identity' ] as $native_global ) { $history_globals[$native_global] = [ array_key_exists( $native_global, $GLOBALS ), $GLOBALS[$native_global] ?? null ]; }
		try {
			// Separate native staff history access: the checkout fixture itself is a guest.
			wp_set_current_user( 1 ); $deleted_order->get_order_key();
			$original_reader = new CetechDeliveryEngine\Application\Shipment\ShipmentOriginalPromiseReferenceReader( new CetechDeliveryEngine\Application\DeliveryQuote\QuoteSavedOrderPlacementEvidenceReader( $fixture->native->factory, $flow->stager, $exact_native_access ) );
			$shipment_reference = $original_reader->read( $shipment, $deleted_order );
		} finally { foreach ( $history_globals as $native_global => [ $existed, $value ] ) { if ( $existed ) { $GLOBALS[$native_global] = $value; } else { unset( $GLOBALS[$native_global] ); } } }
		$shipment_original_ack = null !== $shipment_reference && $shipment_reference->private_facts()['promise']['final_event'] === $linkage->private_facts()['final_event'] && $shipment_reference->private_facts()['promise']['quote']['promise_packet_digest'] === $packet->digest();
		$check( 'NATIVE-W2P04-DELETED-LIVE-POLICY-CALENDAR-ORIGINAL-HISTORY', $removed && QuoteNativeOrderHistory::verify( $deleted_order ) && $envelope->to_private_json() === $fixture->packet( $deleted_order )->to_private_json(), [ 'tracked_live_sources_removed' => $removed && [] === $fixture->source_rows(), 'original_order_reader_independent' => QuoteNativeOrderHistory::verify( $deleted_order ), 'exact_original_input_result_projection' => $envelope->to_private_json() === $fixture->packet( $deleted_order )->to_private_json(), 'concrete_authorized_original_shipment_ack' => $shipment_original_ack, 'exact_saved_group_native_line_scope' => $selected_native_line, 'physical_saved_bytes_after_authorized_read' => $physical === $fixture->native->snapshot_bytes( $deleted_order ) ] );
		$timezone = date_default_timezone_get(); try { date_default_timezone_set( 'Pacific/Auckland' ); $history_packet = PromiseQuotePacket::from_json( $packet->to_private_json() ); } finally { date_default_timezone_set( $timezone ); }
		$check( 'NATIVE-W2P04-HISTORY-USES-FROZEN-TIMEZONE-AND-TEXT', $history_packet->public_groups() === $packet->public_groups(), [ 'native_default_timezone_changed' => 'Pacific/Auckland' !== $timezone, 'frozen_structured_local_projection' => $history_packet->public_groups() === $packet->public_groups(), 'frozen_captured_customer_text' => $history_packet->public_groups()[0]['customer_text'] === $packet->public_groups()[0]['customer_text'] ] );
		$fresh = CetechPromiseHandoffNativeFixture::fresh_reader( $deleted_order, $envelope );
		$check( 'NATIVE-W2P04-FRESH-NATIVE-HISTORY-WITHOUT-LIVE-SOURCES', 'PASS' === ( $fresh['status'] ?? null ), [ 'separate_native_process' => is_int( $fresh['process_id'] ?? null ) && $fresh['process_id'] !== getmypid(), 'native_production_autoload' => true === ( $fresh['installed_production_autoload'] ?? null ), 'changed_native_locale' => true === ( $fresh['native_locale_changed'] ?? null ), 'changed_native_timezone' => true === ( $fresh['native_timezone_changed'] ?? null ), 'original_envelope_and_packet' => true === ( $fresh['exact_original_envelope'] ?? null ) && true === ( $fresh['exact_original_promise_packet'] ?? null ), 'original_frozen_projection' => true === ( $fresh['exact_original_public_projection'] ?? null ), 'bounded_private_child_completed' => true === ( $fresh['transport_complete'] ?? null ) ] );
		$boundary_session = $fixture->native->factory->open(); try { if ( ! $boundary_session->begin() ) { throw new RuntimeException( 'P04 native late payment boundary owner unavailable.' ); } $late = ! $boundary->verify_at( $boundary_session, $sealed, $expiry ); } finally { if ( $boundary_session->in_transaction() ) { $boundary_session->rollback(); } $boundary_session->retire(); }
		$check( 'NATIVE-W2P04-LATE-PAYMENT-EXACT-PHYSICAL-BOUNDARY-DENIED', $late && $physical === $fixture->native->snapshot_bytes( $deleted_order ), [ 'exclusive_late_boundary_denied' => $late, 'original_packet_and_order_unchanged' => $physical === $fixture->native->snapshot_bytes( $deleted_order ), 'native_owner_retired' => $boundary_session->is_retired(), 'no_second_gateway_call' => 1 === $gateway->native_payment_calls() ] );
		$lifecycle = CetechPromiseHandoffNativeFixture::fresh_reader( $deleted_order, $envelope, true );
		$check( 'NATIVE-W2P04-ACTUAL-DISABLE-UNINSTALL-PRESERVES-ORIGINAL-V3-HISTORY', 'PASS' === ( $lifecycle['status'] ?? null ), [ 'native_expired_checkpoint_completed' => true === ( $lifecycle['native_expired_checkpoint_completed'] ?? null ), 'native_deactivation_all38_preserved' => true === ( $lifecycle['native_deactivation_preserved'] ?? null ), 'explicit_native_uninstall_completed' => true === ( $lifecycle['native_explicit_uninstall_completed'] ?? null ), 'native_uninstall_all38_preserved' => true === ( $lifecycle['native_uninstall_business_rows_preserved'] ?? null ), 'actual_original_v3_packet_readable' => true === ( $lifecycle['exact_original_envelope'] ?? null ) && true === ( $lifecycle['exact_original_promise_packet'] ?? null ), 'fixed_fixture_options_exactly_restored' => true === ( $lifecycle['native_fixture_options_restored'] ?? null ), 'bounded_fresh_child_completed' => true === ( $lifecycle['transport_complete'] ?? null ) ] );
		$isolate(); $lost = new CetechQuotePlacementNativeFlow( $fixture->native ); $lost->create(); $lost_header = $lost->evidence->header(); $lost_packet = $fixture->packet( $lost->order )->to_private_json(); $fixture->native->factory->mask_next_binding_ack = true; $denied = $lost->admission->final_order( $lost->order, 'classic' ); $writes = $fixture->native->factory->binding_writes; $recovered = $fixture->replay_original_seal( $lost );
		$check( 'NATIVE-W2P04-LOST-SEAL-ACK-REFUSES-PAYMENT-ORIGINAL-RECOVERY', ! $denied->allowed && 'accepted' === $recovered->attempt->outcome->state && 'sealed' === $recovered->binding?->state() && $writes === $fixture->native->factory->binding_writes && $fixture->native->factory->fault_retired(), [ 'unknown_ack_admission_denied' => ! $denied->allowed, 'original_seal_reconciled' => 'accepted' === $recovered->attempt->outcome->state && 'sealed' === $recovered->binding?->state(), 'one_original_binding_effect' => $writes === $fixture->native->factory->binding_writes, 'original_packet_clock_unchanged' => $lost_packet === $fixture->packet( $lost->order )->to_private_json(), 'unknown_owner_retired' => $fixture->native->factory->fault_retired() ] );
		$clone = new WC_Order( $lost->order->get_id() ); $clone->update_meta_data( DeliveryQuoteSnapshotEnvelope::META_FORMAT, '9' ); $unknown = ( new OrderDeliverySnapshotReader() )->read_package( $clone );
		$check( 'NATIVE-W2P04-UNKNOWN-MARKER-REMAINS-QUOTE-OWNED', QuoteNativeOrderHistory::owned( $clone ) && ! QuoteNativeOrderHistory::verify( $clone ) && 'unsupported' === $unknown->delivery_quote?->status, [ 'unknown_new_owner_marker_protected' => QuoteNativeOrderHistory::owned( $clone ), 'unknown_reader_refuses' => 'unsupported' === $unknown->delivery_quote?->status, 'weaker_legacy_history_refused' => ! QuoteNativeOrderHistory::verify( $clone ) ] );
		$missing = new WC_Order( $lost->order->get_id() ); $missing_outer = CetechDeliveryEngine\Domain\DeliveryQuote\QuoteJson::decode( $missing->get_meta( OrderDeliverySnapshot::META_ORDER_QUOTE_SNAPSHOT, true ) ); unset( $missing_outer[DeliveryQuoteSnapshotEnvelope::MEMBER] ); $missing->update_meta_data( OrderDeliverySnapshot::META_ORDER_QUOTE_SNAPSHOT, CetechDeliveryEngine\Domain\DeliveryQuote\QuoteJson::encode( $missing_outer ) ); $missing_read = ( new OrderDeliverySnapshotReader() )->read_package( $missing );
		$check( 'NATIVE-W2P04-MISSING-OWNED-PACKET-REMAINS-PROTECTED', QuoteNativeOrderHistory::owned( $missing ) && ! QuoteNativeOrderHistory::verify( $missing ) && 'missing' === $missing_read->delivery_quote?->status, [ 'ownership_marker_survives_missing_packet' => QuoteNativeOrderHistory::owned( $missing ), 'missing_reader_refuses' => 'missing' === $missing_read->delivery_quote?->status, 'no_legacy_history_fallback' => ! QuoteNativeOrderHistory::verify( $missing ) ] );
		$off_fence = $fixture->activation->fence(); $off_actor = new CetechDeliveryEngine\Domain\Contracts\OperationIdentity( get_current_blog_id(), 'native-p04-internal', 'user:1', 'service_promise.adoption', 1, 'promise-adoption:' . $fixture->binding->site_key(), 'native-p04-off-' . CetechDeliveryEngine\Domain\DeliveryQuote\QuoteId::generate()->value() );
		$off = $fixture->activation->change( false, 2, $off_actor ); $off_owner = $fixture->native->factory->open(); try { if ( ! $off_owner->begin() ) { throw new RuntimeException( 'P04 adoption OFF guard owner is unavailable.' ); } $off_denied = ! $off_fence->verify( $off_owner, $recovered->binding ); } finally { if ( $off_owner->in_transaction() ) { $off_owner->rollback(); } $off_owner->retire(); }
		$check( 'NATIVE-W2P04-ADOPTION-OFF-KEEPS-SAVED-QUOTE-PROTECTED', $off && $off_denied && QuoteNativeOrderHistory::owned( $lost->order ) && QuoteNativeOrderHistory::verify( $lost->order ), [ 'revisioned_native_adoption_off' => $off && ! $fixture->activation->active(), 'original_adoption_fence_refused' => $off_denied, 'saved_order_still_quote_owned' => QuoteNativeOrderHistory::owned( $lost->order ), 'original_packet_history_supported' => QuoteNativeOrderHistory::verify( $lost->order ), 'original_packet_clock_preserved' => $lost_packet === $fixture->packet( $lost->order )->to_private_json() ] );
		$promise_until = CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime::from_epoch_microseconds( QuoteTime::now()->epoch_microseconds() + 120000000 ); $isolate( [ 'effective_until' => $promise_until->sql() ] ); $short = new CetechQuotePlacementNativeFlow( $fixture->native ); $short->create(); $short_final = $short->admission->final_order( $short->order, 'classic' ); $short_binding = QuoteBinding::from_row( $fixture->native->binding_row( $short->evidence->header()->id()->value() ), $short->evidence->quote_record() ); $short_link = $durable( $short )->acknowledged_promise_seal( $short->evidence->owner(), $short->evidence->reference(), $short->evidence->header(), $short_binding, $short->saved );
		$short_boundary = new PromiseQuotePaymentBoundary( $short->evidence->quote_record(), $short_binding, $short_link, $short->evidence->guard() ); $deadline = QuoteTime::parse( $promise_until->sql() ); $just_before = QuoteTime::from_epoch_microseconds( $deadline->epoch_microseconds() - 1 );
		$check( 'NATIVE-W2P04-PROMISE-DEADLINE-EQUALITY-BEFORE-QUOTE-TTL-DENIED', $short_final->allowed && $short_boundary->eligible_at( $just_before ) && ! $short_boundary->eligible_at( $deadline ), [ 'actual_published_policy_before_quote_ttl' => $deadline->compare( $short->evidence->header()->expires_at() ) < 0, 'acknowledged_original_seal' => $short_final->allowed && null !== $short_link, 'native_packet_one_microsecond_before_eligible' => $short_boundary->eligible_at( $just_before ), 'exact_native_promise_deadline_denied' => ! $short_boundary->eligible_at( $deadline ), 'original_quote_still_unexpired_at_refusal' => $deadline->compare( $short->evidence->header()->expires_at() ) < 0 ] );
		$isolate(); $fixture->make_free(); $free = new CetechQuotePlacementNativeFlow( $fixture->native ); $free->create(); $free_bytes = $fixture->native->snapshot_bytes( $free->order ); $free_final = $free->admission->final_order( $free->order, 'classic' ); $free_completions = 0; $observe_free = static function ( int $id ) use ( $free, &$free_completions ): void { if ( $id === $free->order->get_id() ) { ++$free_completions; } }; add_action( 'woocommerce_payment_complete', $observe_free, PHP_INT_MAX, 1 );
		try { if ( $free_final->allowed && 0.0 === (float) $free->order->get_total() ) { $free->order->payment_complete(); } } finally { remove_action( 'woocommerce_payment_complete', $observe_free, PHP_INT_MAX ); }
		$completed_free = new WC_Order( $free->order->get_id() );
		$check( 'NATIVE-W2P04-ACTUAL-FREE-COMPLETION-AFTER-ORIGINAL-SEAL', $free_final->allowed && 1 === $free_completions && $completed_free->is_paid(), [ 'actual_native_zero_total' => 0.0 === (float) $completed_free->get_total(), 'original_binding_sealed_before_completion' => 'sealed' === $fixture->native->binding_row( $free->evidence->header()->id()->value() )['state'], 'native_free_completion_exactly_once' => 1 === $free_completions, 'native_order_completed' => $completed_free->is_paid(), 'original_packet_bytes_preserved' => $free_bytes === $fixture->native->snapshot_bytes( $completed_free ) ] );
		$isolate( [ 'capacity_mode' => 'required', 'capacity_source' => [ 'format_version' => 1, 'site_id' => 'replace-after-binding', 'source_id' => 'declared-required-capacity', 'version' => 1, 'digest' => hash( 'sha256', 'required-capacity-fixture' ) ] ] ); $required_history = $fixture->native->cart->history();
		$required_draft = $fixture->native->cart->environment->draft(); if ( null === $required_draft ) { throw new RuntimeException( 'P04 required-capacity native base draft is unavailable.' ); } $required_base = ( new CetechDeliveryEngine\Application\DeliveryQuote\NativeCartQuotePreparation( $fixture->native->factory ) )->prepare( $required_draft ); $required_demands = $fixture->registry->create_demands( $required_base->context() ); $capacity_refused = false; try { $fixture->capture->capture( $required_base->context(), $required_base->owner(), CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime::parse( QuoteTime::now()->sql() ), $required_demands ); } catch ( RuntimeException $capacity_error ) { $capacity_refused = 'Required native promise capacity is unavailable.' === $capacity_error->getMessage(); }
		$check( 'NATIVE-W2P04-MISSING-REQUIRED-CAPACITY-NEVER-BECOMES-NONE', $capacity_refused && $required_history === $fixture->native->cart->history(), [ 'actual_native_required_capture_refused' => $capacity_refused, 'trusted_native_demands_present_before_capacity_refusal' => [] !== $required_demands && $required_base->context()->checkout_acceptable(), 'no_quote_binding_or_payment_effect' => $required_history === $fixture->native->cart->history(), 'no_capacity_hold_inferred' => 'required' === $fixture->policy->capacity_mode() ] );
	} catch ( Throwable $error ) { $failure = $error; throw $error; }
	finally {
		if ( null !== $fixture ) { try { foreach ( $fixture->cleanup() as $key => $ok ) { $cleanup[$key] = $cleanup[$key] && $ok; } } catch ( Throwable ) { foreach ( $cleanup as &$ok ) { $ok = false; } unset( $ok ); } }
		try { $check( 'NATIVE-W2P04-TRACKED-NATIVE-FIXTURE-CLEANUP', ! in_array( false, $cleanup, true ), [ 'exact_tracked_fixture_rows_restored' => $cleanup['cleanup_restored'], 'tracked_native_orders_removed' => $cleanup['owned_orders_removed'], 'original_quote_history_preserved' => $cleanup['original_quote_history_restored'], 'original_promise_history_preserved' => $cleanup['original_promise_history_restored'], 'all_owned_sql_connections_retired' => $cleanup['all_owned_connections_retired'], 'original_default_adoption_restored' => $cleanup['default_adoption_restored'] ] ); } catch ( Throwable $cleanup_error ) { if ( null === $failure ) { throw $cleanup_error; } }
	}
};
