<?php

declare(strict_types=1);

use CetechDeliveryEngine\Application\EmergencyControl\{EmergencyControlCommand,EmergencyControlService};
use CetechDeliveryEngine\Application\DeliveryQuote\QuotePlacementActivation;
use CetechDeliveryEngine\Application\Shipment\ShipmentService;
use CetechDeliveryEngine\Bootstrap\Plugin;
use CetechDeliveryEngine\Domain\Contracts\{OperationIdentity,RequestContext};
use CetechDeliveryEngine\Domain\Enum\ShipmentEventSource;
use CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime;
use CetechDeliveryEngine\Domain\ServicePromise\Shipment\{ShipmentCurrentPromise,ShipmentPromiseCommand};
use CetechDeliveryEngine\Domain\Shipment\ShipmentRepositoryInterface;
use CetechDeliveryEngine\Infrastructure\Persistence\TableNames;
use CetechDeliveryEngine\Integrations\ServicePromise\Shipment\NativeShipmentPromiseRuntime;

/** Actual mounted native shipment originals/current estimates; exact owned fixture cleanup only. */
return static function(callable $check,string $mode='hpos_on'):void {
 global $wpdb;
 if('1'!==getenv('CETECH_DE_NATIVE_OPENING_QUALIFICATION')||!defined('WP_ADMIN')||true!==WP_ADMIN||'1'!==(string)get_option('cetech_opening_qualification_disposable')||!$wpdb instanceof wpdb||wpdb::class!==get_class($wpdb)||is_multisite()||('hpos_on'===$mode)!==Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled())throw new RuntimeException('P05 shipment proof requires the exact marked native fixture.');
 require_once __DIR__.'/opening-promise-handoff-support.php';
 $fixture=null;$failure=null;$namespaces=[];$cleanup_ok=true;$old_actor=get_current_user_id();$suffixes=['shipments','shipment_items','shipment_events','audit_log','shipment_promises','operation_records','operation_changes'];
 $rows=static function(string $suffix)use($wpdb):array{$value=$wpdb->get_results('SELECT * FROM `'.TableNames::for($suffix).'` ORDER BY id',ARRAY_A);if(!is_array($value)||count($value)>20000||''!==$wpdb->last_error)throw new RuntimeException('P05 bounded physical fixture observation unavailable.');return $value;};
 $paid_sql=static function(int $id)use($wpdb,$mode):array{$queries='hpos_on'===$mode?[$wpdb->prepare("SELECT id,status FROM `{$wpdb->prefix}wc_orders` WHERE id=%d LIMIT 2",$id),$wpdb->prepare("SELECT order_id,date_paid_gmt FROM `{$wpdb->prefix}wc_order_operational_data` WHERE order_id=%d LIMIT 2",$id)]:[$wpdb->prepare("SELECT ID,post_status FROM `{$wpdb->posts}` WHERE ID=%d LIMIT 2",$id),$wpdb->prepare("SELECT meta_value FROM `{$wpdb->postmeta}` WHERE post_id=%d AND meta_key='_date_paid' ORDER BY meta_id LIMIT 2",$id)];$out=[];foreach($queries as $query){$value=$wpdb->get_results($query,ARRAY_A);if(!is_array($value)||count($value)>1||''!==$wpdb->last_error)throw new RuntimeException('P05 exact paid physical observation unavailable.');$out[]=$value;}return $out;};
 $before=[];foreach($suffixes as $suffix)$before[$suffix]=$rows($suffix);
 $control_row=static function()use($wpdb):?array{$value=$wpdb->get_results($wpdb->prepare("SELECT option_id,option_name,option_value,autoload FROM `{$wpdb->options}` WHERE BINARY option_name=%s LIMIT 2",\CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore::OPTION_NAME),ARRAY_A);if(!is_array($value)||count($value)>1||''!==$wpdb->last_error)throw new RuntimeException('P05 exact checkout control observation unavailable.');return $value[0]??null;};
 $control_before=$control_row();$control_latest=$control_before;$control_prepared=$control_before;
 $track_control=static function($attempt)use($control_row,&$control_latest):void{if('accepted'!==$attempt->completion?->state)return;$facts=$attempt->completion->result;$row=$control_row();if(null===$row||null===$facts)throw new RuntimeException('P05 owned checkout control receipt unavailable.');$state=\CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState::from_physical(get_current_blog_id(),(int)$row['option_id'],$row['option_value']);if($facts['site_id']!==$state->site_id||$facts['row_id']!==$state->row_id||$facts['state']!==$state->state||$facts['revision']!==$state->revision||$facts['actor_user_id']!==1||$facts['actor_user_id']!==$state->actor_user_id||$facts['reason_code']!==$state->reason_code||$facts['changed_at_epoch']!==$state->changed_at_epoch||$facts['bytes_hash']!==hash('sha256',$row['option_value']))throw new RuntimeException('P05 owned checkout control receipt mismatch.');$control_latest=$row;};
 $promise_rows=static function()use(&$fixture,$rows,&$namespaces):array{$out=[];foreach($rows('shipment_promises') as $row){if(null===$fixture||!in_array((int)$row['order_id'],$fixture->native->orders,true))continue;if($row['site_key']!==$fixture->binding->site_key()||(int)$row['site_id']!==get_current_blog_id())throw new RuntimeException('P05 owned shipment promise binding mismatch.');$namespaces[$row['original_namespace_hash']]=ShipmentPromiseCommand::CREATE;if(null!==$row['current_namespace_hash'])$namespaces[$row['current_namespace_hash']]=ShipmentPromiseCommand::UPDATE;$out[]=$row;}return $out;};
 // Shipment attempt metadata is a separate operational history. Freeze exact quote
 // handoff metadata and every retained physical item/money/line selector instead.
 $snapshot=static function(WC_Order $order)use(&$fixture):array{$bytes=$fixture->native->snapshot_bytes($order);$keys=[\CetechDeliveryEngine\Application\Order\OrderDeliverySnapshot::META_ORDER_QUOTE_SNAPSHOT,\CetechDeliveryEngine\Application\Order\OrderDeliverySnapshot::META_ORDER_SNAPSHOT_VERSION,\CetechDeliveryEngine\Application\Order\DeliveryQuoteSnapshotEnvelope::META_FORMAT,\CetechDeliveryEngine\Application\Order\QuoteNativeOrderFacts::META_REFERENCE,\CetechDeliveryEngine\Application\Order\QuoteNativeOrderFacts::META_DRAFT,\CetechDeliveryEngine\Application\Order\QuoteNativeOrderFacts::META_TAX_SOURCE];$bytes['order']=array_values(array_filter($bytes['order'],static fn(array $row):bool=>in_array($row['meta_key'],$keys,true)));return $bytes;};
 $history=static function()use($rows):array{return ['shipments'=>$rows('shipments'),'items'=>$rows('shipment_items'),'events'=>$rows('shipment_events'),'promise'=>$rows('shipment_promises'),'operations'=>$rows('operation_records'),'changes'=>$rows('operation_changes')];};
 $track_create=static function(WC_Order $order)use(&$namespaces):void{$read=(new \CetechDeliveryEngine\Application\Order\OrderDeliverySnapshotReader())->read_package($order);$envelope=$read->delivery_quote?->envelope;if(null===$envelope||!$envelope->is_promise()||null===$read->snapshot)throw new RuntimeException('P05 owned original create identity unavailable.');$key=hash('sha256','original:'.$envelope->to_private_json());foreach($read->snapshot->groups as $group){$draft=\CetechDeliveryEngine\Domain\Shipment\Shipment::create($order->get_id(),$group->group_id,fulfilment_choice:'delivery');foreach([null,1] as $actor){$identity=new OperationIdentity(get_current_blog_id(),'native-shipment-promise',null===$actor?'native-system':'staff:'.$actor,ShipmentPromiseCommand::CREATE,1,ShipmentPromiseCommand::target_key($draft),$key);$namespaces[$identity->namespace_digest()]=ShipmentPromiseCommand::CREATE;}}};
 $track_staff=static function($shipment,string $key)use(&$namespaces):void{$identity=new OperationIdentity(get_current_blog_id(),'native-shipment-promise','staff:1',ShipmentPromiseCommand::UPDATE,1,ShipmentPromiseCommand::target_key($shipment),$key);$namespaces[$identity->namespace_digest()]=ShipmentPromiseCommand::UPDATE;};
 $installed_root=dirname((string)(new ReflectionClass(Plugin::class))->getFileName(),3);$php_map=[];foreach(['src','database'] as $directory){foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($installed_root.'/'.$directory,FilesystemIterator::SKIP_DOTS)) as $file){if($file->isFile()&&'php'===$file->getExtension())$php_map[substr($file->getPathname(),strlen($installed_root)+1)]=hash_file('sha256',$file->getPathname());}}foreach(['cetech-woocommerce-delivery-engine.php','uninstall.php'] as $name)$php_map[$name]=hash_file('sha256',$installed_root.'/'.$name);ksort($php_map,SORT_STRING);
 $refresh_order=static function(int $id)use($mode):WC_Order{clean_post_cache($id);wc_get_container()->get(Automattic\WooCommerce\Caches\OrderCache::class)->remove($id);if('hpos_on'===$mode)wc_get_container()->get(Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore::class)->clear_cached_data([$id]);return new WC_Order($id);};
 $pay_fresh=static function(WC_Order $order,string $stimulus='order_pay')use(&$fixture,$mode,$wpdb,$installed_root,$php_map,&$cleanup_ok):array {
  $path=tempnam(sys_get_temp_dir(),'p05-native-payment-');$lease_path=tempnam(sys_get_temp_dir(),'p05-native-payment-lease-');$parent_nonce=bin2hex(random_bytes(32));$process=null;$pipes=[];$child_pid=null;$result=null;$payment_error=null;$parent_absence=false;
  $remove_private=static function(string $owned_path):bool{$removed=unlink($owned_path);clearstatcache(true,$owned_path);return $removed&&!file_exists($owned_path)&&!is_link($owned_path);};
  if(false===$path||false===$lease_path){foreach([$path,$lease_path]as$owned_path){if(is_string($owned_path))$cleanup_ok=$remove_private($owned_path)&&$cleanup_ok;}throw new RuntimeException('P05 private native payment setup unavailable.');}
  try {
   if(!chmod($path,0600)||!chmod($lease_path,0600))throw new RuntimeException('P05 private native payment setup unavailable.');
   $envelope=(new \CetechDeliveryEngine\Application\Order\OrderDeliverySnapshotReader())->read_package($order)->delivery_quote?->envelope;if(null===$envelope||!$envelope->is_promise())throw new RuntimeException('P05 exact child handoff packet unavailable.');
   $config=['wp_load'=>rtrim(ABSPATH,'/').'/wp-load.php','plugin_root'=>$installed_root,'php_map_hash'=>hash('sha256',json_encode($php_map,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)),'php_map_count'=>count($php_map),'lease_path'=>$lease_path,'parent_nonce'=>$parent_nonce,'stimulus'=>$stimulus,'order_id'=>$order->get_id(),'order_key'=>$order->get_order_key('edit'),'method'=>'cetech_q06_native_gateway','mode'=>$mode,'site_id'=>get_current_blog_id(),'snapshot_digest'=>hash('sha256',$envelope->to_private_json())];
   if(false===file_put_contents($path,json_encode($config,JSON_THROW_ON_ERROR)))throw new RuntimeException('P05 private native payment setup unavailable.');
   $transport_started=hrtime(true);$process=proc_open([PHP_BINARY,__DIR__.'/opening-promise-native-configuration-shipment-payment.php',$path],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);if(!is_resource($process))throw new RuntimeException('P05 native payment process unavailable.');$status=proc_get_status($process);$child_pid=$status['pid'];fclose($pipes[0]);unset($pipes[0]);foreach($pipes as $pipe)stream_set_blocking($pipe,false);$out='';$errors='';$exit=-1;$deadline=microtime(true)+12;
   do{$out.=stream_get_contents($pipes[1]);$errors.=stream_get_contents($pipes[2]);$status=proc_get_status($process);if(!$status['running']){$exit=$status['exitcode'];break;}if(strlen($out)>4096||strlen($errors)>16384)break;usleep(10000);}while(microtime(true)<$deadline);
   $stop_reason=!$status['running']?'completed':(strlen($out)>4096?'stdout_overflow':(strlen($errors)>16384?'stderr_overflow':'deadline'));
   if($status['running'])proc_terminate($process,9);$out.=stream_get_contents($pipes[1]);$errors.=stream_get_contents($pipes[2]);foreach($pipes as $pipe)fclose($pipe);$pipes=[];$closed=proc_close($process);$process=null;$result=json_decode($out,true);$json_valid=JSON_ERROR_NONE===json_last_error();
   if($status['running']||strlen($out)>4096||strlen($errors)>16384||0!==($exit>=0?$exit:$closed)||!is_array($result)||($result['process_id']??null)!==$child_pid){
    // Finite structural facts only: never emit captured bytes, keys, paths,
    // process identities, child messages or configuration from this boundary.
    $transport_diagnostic=['format'=>'p05-native-payment-transport-v1','stop_reason'=>$stop_reason,'elapsed_ms'=>max(0,(int)((hrtime(true)-$transport_started)/1000000)),'running_at_stop'=>(bool)$status['running'],'timed_out'=>'deadline'===$stop_reason,'stdout_bytes'=>strlen($out),'stderr_bytes'=>strlen($errors),'stdout_overflow'=>strlen($out)>4096,'stderr_overflow'=>strlen($errors)>16384,'exit_code'=>$exit>=0?$exit:$closed,'exit_ok'=>0===($exit>=0?$exit:$closed),'json_valid'=>$json_valid,'json_array'=>is_array($result),'pid_matches'=>is_array($result)&&($result['process_id']??null)===$child_pid];
    fwrite(STDERR,'p05_native_payment_transport='.json_encode($transport_diagnostic,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES).PHP_EOL);
    throw new RuntimeException('P05 bounded native payment transport unavailable.');
   }
   if('PASS'!==($result['status']??null)){$diagnostic='';foreach(['saved_order_authorized','saved_order_history_valid','saved_order_fingerprint_available','saved_tax_hooks_supported','saved_capture_service_present','saved_order_evidence_ready','saved_order_validate_ready','saved_quote_time_valid','saved_runtime_equal'] as $fact){$diagnostic.=' '.$fact.'='.(true===($result[$fact]??null)?'yes':(false===($result[$fact]??null)?'no':'unknown'));}throw new RuntimeException('P05 fresh native payment failed: phase='.($result['phase']??'unknown').' refusal='.($result['refusal_code']??'none').' error_class='.($result['error_class']??'none').' session_cleanup='.(true===($result['session_cleanup']??null)?'yes':'no').$diagnostic);}
  }catch(Throwable $error){$payment_error=$error;}finally {
   foreach($pipes as $pipe){if(is_resource($pipe))fclose($pipe);}if(is_resource($process)){proc_terminate($process,9);proc_close($process);}
   try {
    clearstatcache(true,$lease_path);if(!is_file($lease_path)||is_link($lease_path)||(fileperms($lease_path)&0777)!==0600||filesize($lease_path)>2048)throw new RuntimeException('P05 private session lease unavailable.');$lease_bytes=(string)file_get_contents($lease_path);
    if(''!==$lease_bytes){$lease=json_decode($lease_bytes,true,8,JSON_THROW_ON_ERROR);if(!is_array($lease)||array_keys($lease)!==['format','site_id','session_key','child_pid','parent_nonce']||1!==$lease['format']||get_current_blog_id()!==$lease['site_id']||$child_pid!==$lease['child_pid']||$parent_nonce!==$lease['parent_nonce']||!is_string($lease['session_key'])||!str_starts_with($lease['session_key'],'t_')||strlen($lease['session_key'])>191||1!==preg_match('/\A[a-zA-Z0-9_]+\z/D',$lease['session_key']))throw new RuntimeException('P05 private session lease refused.');$present=$wpdb->get_results($wpdb->prepare("SELECT session_id FROM `{$wpdb->prefix}woocommerce_sessions` WHERE session_key=%s LIMIT 2",$lease['session_key']),ARRAY_A);if(!is_array($present)||count($present)>1||''!==$wpdb->last_error)throw new RuntimeException('P05 exact child session cleanup unavailable.');if([]!==$present&&1!==$wpdb->delete($wpdb->prefix.'woocommerce_sessions',['session_key'=>$lease['session_key']]))throw new RuntimeException('P05 exact child session removal failed.');$absent=$wpdb->get_results($wpdb->prepare("SELECT session_id FROM `{$wpdb->prefix}woocommerce_sessions` WHERE session_key=%s LIMIT 2",$lease['session_key']),ARRAY_A);$parent_absence=[]===$absent&&''===$wpdb->last_error;if(!$parent_absence)throw new RuntimeException('P05 exact child session absence unavailable.');}
    elseif(null!==$result&&'PASS'===$result['status'])throw new RuntimeException('P05 successful child lacks its native session lease.');
   }catch(Throwable $lease_error){$cleanup_ok=false;$payment_error=$lease_error;}
   $config_removed=$remove_private($path);$lease_removed=$remove_private($lease_path);if(!$config_removed||!$lease_removed){$cleanup_ok=false;$payment_error=new RuntimeException('P05 exact private payment files were not removed.');}
  }
  if(null!==$payment_error)throw $payment_error;if(!is_array($result)||!$parent_absence||true!==($result['session_cleanup']??null)||true!==($result['installed_production_map']??null)||true!==($result['default_native_cache']??null)||true!==($result['private_config_0600']??null))throw new RuntimeException('P05 native payment attestation incomplete.');$result['parent_session_absence']=$parent_absence;return $result;
 };
 $prepare_fixture=static function()use(&$fixture,$wpdb,$snapshot,$track_create,$control_row,$control_before,&$control_prepared,&$control_latest):array {
   $fixture=new CetechPromiseHandoffNativeFixture($wpdb);
   try{$fixture->prepare(['anchor'=>'payment_confirmed','late_payment_rule'=>'relative_after_payment']);}
   finally{
    $prepared_row=$control_row();$tracked_options=(new ReflectionProperty(CetechNativeQuoteProviderFixture::class,'original_options'))->getValue($fixture->native->cart->native);$name=\CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore::OPTION_NAME;
    if(array_key_exists($name,$tracked_options)){
     if($tracked_options[$name]!==$control_before||null===$prepared_row)throw new RuntimeException('P05 native prepared control ownership unavailable.');$prepared_state=\CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState::from_physical(get_current_blog_id(),(int)$prepared_row['option_id'],$prepared_row['option_value']);
     if('enabled'!==$prepared_state->state||990001!==$prepared_state->revision||1!==$prepared_state->actor_user_id||'resume_verified'!==$prepared_state->reason_code)throw new RuntimeException('P05 native prepared control differs from its tracked fixture stimulus.');
     $control_prepared=$prepared_row;$control_latest=$prepared_row;
    }elseif($prepared_row!==$control_before){throw new RuntimeException('P05 untracked native preparation control change refused.');}
   }
$fixture->native->cart->native->set_option('cetech_de_enable_shipment_records','1');foreach([\CetechDeliveryEngine\Application\Shipment\ShipmentCreationFailureStore::INDEX_OPTION,\CetechDeliveryEngine\Application\Shipment\CodAwaitingShipmentStore::INDEX_OPTION] as $index){$fixture->native->cart->native->set_option($index,get_option($index,[]));}
  $container=Plugin::instance()->container();$shipments=$container->get(ShipmentRepositoryInterface::class);$creation=$container->get(ShipmentService::class);$runtime=$container->get(NativeShipmentPromiseRuntime::class);$control=$container->get(EmergencyControlService::class);
  // This fixture's explicit quote constructors do not activate the mounted
  // saved-order capture. Track the separate protected BASE adoption before
  // enabling it through the real expected-revision service for the fresh request.
  $base_option=get_option(QuotePlacementActivation::OPTION,null);if(null!==$base_option&&!is_string($base_option))throw new RuntimeException('P05 native BASE adoption shape unavailable.');
  $base_state=QuotePlacementActivation::decode($base_option);$fixture->native->cart->native->set_option(QuotePlacementActivation::OPTION,$base_option??\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteJson::encode([...$base_state,'revision'=>1]));
  $base_activation=$container->get(QuotePlacementActivation::class);$base_status=$base_activation->status();if(!$base_status['available']||!$base_status['ready']||(!$base_status['active']&&!$base_activation->change(true,$base_status['revision']))||!$base_activation->active())throw new RuntimeException('P05 protected native BASE adoption did not acknowledge.');
  $gateway=$fixture->native->register_gateway();try{$flow=new CetechQuotePlacementNativeFlow($fixture->native);}catch(Throwable $preparation){throw new RuntimeException('P05 genuine relative quote preparation unavailable.',0,$fixture->observation->preparation_error??$preparation);}$flow->payment_method=$gateway->id;$flow->create();$final=$flow->admission->final_order($flow->order,'classic');if(!$final->allowed)throw new RuntimeException('P05 actual original seal did not acknowledge.');$order=new WC_Order($flow->order->get_id());$track_create($order);$saved=$snapshot($order);
  return [$order,$saved,$base_activation,$gateway,$creation,$shipments,$runtime,$control];
 };
 try {
  [$order,$saved,$base_activation,$gateway,$creation,$shipments,$runtime,$control]=$prepare_fixture();
  $original_paid_sql=$paid_sql($order->get_id());$fake=new WC_Order($order->get_id());$fake->set_date_paid(time());$fake->set_status('processing');$forged_before=$history();$forged=$creation->create_for_paid_order($fake,ShipmentEventSource::System,true);do_action('woocommerce_payment_complete',$order->get_id());$native_after_fake=new WC_Order($order->get_id());$physical_paid_unchanged=$original_paid_sql===$paid_sql($order->get_id())&&null===$native_after_fake->get_date_paid()&&$native_after_fake->get_status()===$order->get_status();
  $check('NATIVE-W2P05-UNSAVED-PAID-OBJECT-AND-UNPAID-HOOK-NO-SHIPMENT',!$forged->outcome->is_success()&&[]===$shipments->findByOrderId($order->get_id())&&$forged_before===$history(),['unpersisted_timestamp_not_authority'=>!$forged->outcome->is_success(),'persisted_native_paid_fact_unchanged'=>$physical_paid_unchanged,'unpaid_native_hook_no_aggregate'=>[]===$shipments->findByOrderId($order->get_id()),'no_material_or_current_audit_effect'=>$forged_before===$history(),'saved_original_packet_unchanged'=>$saved===$snapshot(new WC_Order($order->get_id()))]);
  // Full Woo unpaid-hook listeners can alter their own stock/source rows.
  // The negative case owns its entire independent order/product fixture. Retire
  // it before capturing the paid-path quote, rather than rewriting that quote's
  // original receipts or weakening any saved-order source fence.
  $negative_audit_before=array_fill_keys(array_column($before['audit_log'],'id'),true);$negative_order_ids=array_fill_keys($fixture->native->orders,true);foreach($rows('audit_log')as$negative_row){if(isset($negative_audit_before[$negative_row['id']])||'order'!==$negative_row['entity_type']||!isset($negative_order_ids[(int)$negative_row['entity_id']])||!in_array($negative_row['action'],['shipment_creation_failed','shipment_creation_succeeded','shipment_creation_idempotent'],true))continue;if(1!==$wpdb->delete(TableNames::for('audit_log'),['id'=>(int)$negative_row['id'],'entity_type'=>'order','entity_id'=>(int)$negative_row['entity_id'],'action'=>$negative_row['action']]))throw new RuntimeException('P05 exact negative shipment audit cleanup failed.');}
  $negative_cleanup=$fixture->cleanup();if(in_array(false,$negative_cleanup,true))throw new RuntimeException('P05 negative native hook fixture cleanup did not restore its exact sources.');$fixture=null;$control_latest=$control_row();$control_prepared=$control_latest;
  [$order,$saved,$base_activation,$gateway,$creation,$shipments,$runtime,$control]=$prepare_fixture();
  wp_set_current_user(1);$created=$creation->create_from_historical_order_for_staff(new WC_Order($order->get_id()),1);$list=$shipments->findByOrderId($order->get_id());$service=$runtime->service_for_order(new WC_Order($order->get_id()));$shipment=$list[0]??null;$stored=null===$shipment||null===$service?null:$service->read_for_order($shipment,new WC_Order($order->get_id()));$promise_rows();
  if(null===$stored||1!==count($list))throw new RuntimeException('P05 original aggregate unavailable: outcome='.$created->outcome->value.' error='.($created->error_code?->value??'none').' shipments='.count($list).' native_service='.(null===$service?'no':'yes').' authenticated_stored='.(null===$stored?'no':'yes')); $original=$stored->row();$eta=[$shipment->eta_original,$shipment->eta_current];$events=$shipments->findEvents($shipment->id);$items=$shipments->findItems($shipment->id);
  $check('NATIVE-W2P05-ACKNOWLEDGED-ORIGINAL-ATOMIC-SHIPMENT-AGGREGATE',$created->outcome->is_success()&&2===$original['revision']&&null===$stored->current()&&'relative_window'===$stored->packet()->result_facts()['state']&&[]!==$items&&1===count($events),['native_historical_staff_creation'=>$created->outcome->is_success(),'separate_unpaid_hook_sources_restored'=>!in_array(false,$negative_cleanup,true),'exact_frozen_relative_original'=>'relative_window'===$stored->packet()->result_facts()['state'],'original_receipt_authenticated'=>2===$original['revision'],'items_and_created_event_same_aggregate'=>[]!==$items&&1===count($events),'unpaid_original_no_prediction'=>null===$stored->current()]);
  $aggregate_once=$history();$retry=$creation->create_from_historical_order_for_staff(new WC_Order($order->get_id()),1);$promise_rows();
  $check('NATIVE-W2P05-ORIGINAL-SHIPMENT-REPLAY-ONE-MATERIAL-EFFECT',$retry->outcome->is_success()&&$aggregate_once===$history(),['native_original_retry_succeeded'=>$retry->outcome->is_success(),'single_shipment_original_and_created_event'=>$aggregate_once===$history(),'saved_packet_exactly_preserved'=>$saved===$snapshot(new WC_Order($order->get_id()))]);
  // A separate native process pays the historical order through its actual
  // saved-order admission; the original request's continuation stays frozen.
  $payment=$pay_fresh(new WC_Order($order->get_id()));$paid=$refresh_order($order->get_id());$service=$runtime->service_for_order($paid);$paid_stored=$service?->read_for_order($shipment,$paid);$promise_rows();$current=$paid_stored?->current();$facts=$current?->private_facts();$paid_date=$paid->get_date_paid();$actual_paid=$paid_date instanceof DateTimeInterface?RuleTime::from_epoch_microseconds($paid_date->getTimestamp()*1000000):null;$absolute=null!==$facts&&'absolute_window'===$facts['state'];$native_relative=false;if($absolute&&null!==$actual_paid){$view=$facts['views'][0];$native_relative=RuleTime::parse($view['from'])->epoch_microseconds()-$actual_paid->epoch_microseconds()===3600000000&&RuleTime::parse($view['until'])->epoch_microseconds()-$actual_paid->epoch_microseconds()===7200000000;}
  $check('NATIVE-W2P05-GENUINE-NATIVE-PAYMENT-SEPARATE-CURRENT-PREDICTION','PASS'===$payment['status']&&$paid->is_paid()&&$absolute&&$native_relative&&$original['original_json']===$paid_stored?->row()['original_json'],['fresh_os_native_payment_request'=>is_int($payment['process_id'])&&getmypid()!==$payment['process_id'],'native_order_pay_get_session_acknowledged'=>true===($payment['native_payment_form_session']??null),'protected_base_adoption_active'=>$base_activation->active(),'actual_native_gateway_paid_once'=>$payment['native_gateway_paid_once']&&$paid->is_paid(),'persisted_paid_timestamp_anchor'=>null!==$actual_paid&&($facts['event_at']??null)===$actual_paid->sql(),'separate_current_absolute_window'=>$absolute&&$native_relative,'immutable_original_relative_bytes'=>$original['original_json']===$paid_stored?->row()['original_json'],'registered_native_payment_hook'=>'payment_confirmed'===($facts['source']??null),'owned_child_session_cleaned'=>$payment['session_cleanup']&&$payment['parent_session_absence'],'same_installed_production_php_map'=>$payment['installed_production_map'],'native_default_cache'=>$payment['default_native_cache'],'private_child_configuration_0600'=>$payment['private_config_0600']]);
  if(null===$current||null===$paid_stored)throw new RuntimeException('P05 genuine current prediction unavailable.');$paid_once=$history();do_action('woocommerce_payment_complete',$paid->get_id());$promise_rows();
  $check('NATIVE-W2P05-NATIVE-PAYMENT-REPLAY-ONE-CURRENT-EFFECT',$paid_once===$history(),['same_native_payment_event_replayed'=>true,'current_and_material_audit_once'=>$paid_once===$history(),'original_snapshot_bytes_frozen'=>$saved===$snapshot(new WC_Order($order->get_id()))]);
  $staff_facts=$current->private_facts();$staff_facts['source']='staff_revision';$staff_facts['event_key']=hash('sha256','p05-native-staff:'.$shipment->id);$staff_facts['event_at']=RuleTime::from_epoch_microseconds(time()*1000000)->sql();$staff_facts['reason']='Tracked native internal staff delay reason';$staff_current=ShipmentCurrentPromise::from_array($staff_facts);$staff_key=RequestContext::create()->request_id;$track_staff($shipment,$staff_key);$updated=$service->update_current(new WC_Order($paid->get_id()),$shipment->id,3,$staff_current,1,$staff_key);$staff_stored=$service->read_for_order($shipment,new WC_Order($paid->get_id()));$promise_rows();$staff_events=$shipments->findEvents($shipment->id);$last=$staff_events[array_key_last($staff_events)]??null;$fresh_shipment=$shipments->findById($shipment->id);
  $check('NATIVE-W2P05-STAFF-CURRENT-REASON-AUDIT-PRESERVES-ORIGINAL','accepted'===$updated->outcome->state&&4===$staff_stored?->row()['revision']&&$original['original_json']===$staff_stored?->row()['original_json']&&$last?->internal_note===$staff_facts['reason'],['native_staff_update_acknowledged'=>'accepted'===$updated->outcome->state,'current_revision_and_reason_event'=>4===$staff_stored?->row()['revision']&&$last?->internal_note===$staff_facts['reason'],'original_and_old_text_preserved'=>$original['original_json']===$staff_stored?->row()['original_json']&&$eta===[$fresh_shipment->eta_original,$fresh_shipment->eta_current],'staff_reason_not_public'=>!isset($staff_stored?->current()?->public_facts()['reason']),'payment_event_history_retained'=>3===count($staff_events)]);
  $staff_once=$history();$repeat=$service->update_current(new WC_Order($paid->get_id()),$shipment->id,3,$staff_current,1,$staff_key);$stale_key=RequestContext::create()->request_id;$track_staff($shipment,$stale_key);$stale=$service->update_current(new WC_Order($paid->get_id()),$shipment->id,3,$staff_current,1,$stale_key);$promise_rows();$material_after=$history();$material_unchanged=$staff_once['shipments']===$material_after['shipments']&&$staff_once['items']===$material_after['items']&&$staff_once['events']===$material_after['events']&&$staff_once['promise']===$material_after['promise'];
  $check('NATIVE-W2P05-STAFF-ORIGINAL-REPLAY-AND-STALE-CAS','accepted'===$repeat->outcome->state&&'accepted'!==$stale->outcome->state&&$material_unchanged,['same_key_original_outcome_reconciled'=>'accepted'===$repeat->outcome->state,'new_key_stale_revision_refused'=>'accepted'!==$stale->outcome->state,'no_second_current_or_reason_event'=>$material_unchanged]);
  $opened=$control->read(get_current_blog_id())->state;if(null===$opened)throw new RuntimeException('P05 native C07 state unavailable.');$pause_id=EmergencyControlCommand::identity(get_current_blog_id(),1,RequestContext::create()->request_id);$namespaces[$pause_id->namespace_digest()]=EmergencyControlCommand::OPERATION;$pause=$control->transition($pause_id,EmergencyControlCommand::payload($opened,'checkout_suspended','maintenance_pause'),RequestContext::create());$track_control($pause);$pause_key=RequestContext::create()->request_id;$track_staff($shipment,$pause_key);$paused_before=$promise_rows();$paused=$service->update_current(new WC_Order($paid->get_id()),$shipment->id,4,$staff_current,1,$pause_key);$paused_read=$service->read_for_order($shipment,new WC_Order($paid->get_id()));$paused_after=$promise_rows();
  $check('NATIVE-W2P05-C07-PAUSE-REFUSES-NEW-CURRENT-KEEPS-HISTORY','accepted'===$pause->outcome->state&&'accepted'!==$paused->outcome->state&&null!==$paused_read&&$paused_before===$paused_after,['actual_native_c07_transition'=>'accepted'===$pause->outcome->state,'new_current_revision_refused'=>'accepted'!==$paused->outcome->state,'authorized_original_current_history_readable'=>null!==$paused_read,'no_partial_current_effect'=>$paused_before===$paused_after]);
  $resume_opened=$control->read(get_current_blog_id())->state;$resume_id=EmergencyControlCommand::identity(get_current_blog_id(),1,RequestContext::create()->request_id);$namespaces[$resume_id->namespace_digest()]=EmergencyControlCommand::OPERATION;$resume=$control->transition($resume_id,EmergencyControlCommand::payload($resume_opened,'enabled','resume_verified'),RequestContext::create());$track_control($resume);if('accepted'!==$resume->outcome->state)throw new RuntimeException('P05 tracked C07 resume unavailable.');
  wp_set_current_user(0);$missing=new CetechQuotePlacementNativeFlow($fixture->native);$missing->payment_method=$gateway->id;$missing->create();if(!$missing->admission->final_order($missing->order,'classic')->allowed)throw new RuntimeException('P05 second original seal unavailable.');$track_create(new WC_Order($missing->order->get_id()));wp_set_current_user(1);$missing_created=$creation->create_from_historical_order_for_staff(new WC_Order($missing->order->get_id()),1);$missing_shipment=$shipments->findByOrderId($missing->order->get_id())[0]??null;$promise_rows();$removed=$fixture->remove_sources();
  // A later provider confirmation is a new native callback, after its original
  // admission ended. It does not inherit that request's free-payment continuation.
  $callback=$pay_fresh(new WC_Order($missing->order->get_id()),'provider_callback');$missing_paid=$refresh_order($missing->order->get_id());$missing_service=$runtime->service_for_order($missing_paid);$missing_stored=null===$missing_shipment?null:$missing_service?->read_for_order($missing_shipment,$missing_paid);$promise_rows();
  $check('NATIVE-W2P05-MISSING-FROZEN-CALENDAR-PREDICTION-UNAVAILABLE',$missing_created->outcome->is_success()&&$removed&&$missing_paid->is_paid()&&'unavailable'===$missing_stored?->current()?->private_facts()['state']&&'relative_window'===$missing_stored?->packet()->result_facts()['state'],['fresh_native_provider_callback'=>$callback['native_provider_callback']&&getmypid()!==$callback['process_id'],'same_installed_production_php_map'=>$callback['installed_production_map'],'owned_child_session_cleaned'=>$callback['session_cleanup']&&$callback['parent_session_absence'],'exact_tracked_live_calendar_removed'=>$removed,'genuine_native_payment_remains_paid'=>$missing_paid->is_paid(),'current_prediction_truthfully_unavailable'=>'unavailable'===$missing_stored?->current()?->private_facts()['state'],'no_partial_public_window'=>[]===$missing_stored?->current()?->public_facts()['views'],'frozen_original_relative_history'=>'relative_window'===$missing_stored?->packet()->result_facts()['state']]);
 } catch(Throwable $error){$failure=$error;throw $error;} finally {
  try {
   if(null!==$fixture){$promise_rows();$owned=array_fill_keys($fixture->native->orders,true);$owned_shipments=[];foreach($rows('shipments') as $row){if(isset($owned[(int)$row['order_id']])){$owned_shipments[(int)$row['id']]=(int)$row['order_id'];}}
    $control_current=$control_row();if($control_current!==$control_latest)throw new RuntimeException('P05 refuses changed or foreign checkout control cleanup.');if($control_current!==$control_prepared){if(null===$control_current)throw new RuntimeException('P05 owned checkout control cleanup unavailable.');$fence=" WHERE option_id=%d AND BINARY option_name=%s AND BINARY option_value=%s AND BINARY autoload=%s";$values=[(int)$control_current['option_id'],$control_current['option_name'],$control_current['option_value'],$control_current['autoload']];$sql=null===$control_prepared?"DELETE FROM `{$wpdb->options}`".$fence:"UPDATE `{$wpdb->options}` SET option_id=%d,option_value=%s,autoload=%s".$fence;if(null!==$control_prepared)$values=[(int)$control_prepared['option_id'],$control_prepared['option_value'],$control_prepared['autoload'],...$values];if(1!==$wpdb->query($wpdb->prepare($sql,...$values)))throw new RuntimeException('P05 exact owned checkout control restoration failed.');foreach([\CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore::OPTION_NAME,'alloptions','notoptions']as$name)wp_cache_delete($name,'options');}if($control_prepared!==$control_row())throw new RuntimeException('P05 prepared checkout control restoration incomplete.');
    foreach($namespaces as $namespace=>$operation){$records=$wpdb->get_results($wpdb->prepare('SELECT id FROM `'.TableNames::for('operation_records').'` WHERE site_id=%d AND namespace_hash=%s AND operation=%s LIMIT 2',get_current_blog_id(),$namespace,$operation),ARRAY_A);if(!is_array($records)||count($records)>1||''!==$wpdb->last_error)throw new RuntimeException('P05 exact operation cleanup unavailable.');foreach($records as $record){$cleanup_ok=false!==$wpdb->delete(TableNames::for('operation_changes'),['site_id'=>get_current_blog_id(),'operation_id'=>(int)$record['id']])&&$cleanup_ok;$cleanup_ok=1===$wpdb->delete(TableNames::for('operation_records'),['site_id'=>get_current_blog_id(),'id'=>(int)$record['id']])&&$cleanup_ok;}}
    foreach(['shipment_promises','shipment_events','shipment_items','audit_log','shipments'] as $suffix){$initial=array_fill_keys(array_column($before[$suffix],'id'),true);foreach($rows($suffix) as $row){if(isset($initial[$row['id']]))continue;$allowed='shipments'===$suffix?isset($owned_shipments[(int)$row['id']]):('audit_log'===$suffix?('order'===$row['entity_type']&&isset($owned[(int)$row['entity_id']])&&in_array($row['action'],['shipment_creation_failed','shipment_creation_succeeded','shipment_creation_idempotent'],true)):isset($owned_shipments[(int)$row['shipment_id']]));if(!$allowed)continue;if('shipment_promises'===$suffix&&($row['site_key']!==$fixture->binding->site_key()||(int)$row['order_id']!==$owned_shipments[(int)$row['shipment_id']]))throw new RuntimeException('P05 cleanup refuses foreign original row.');$cleanup_ok=1===$wpdb->delete(TableNames::for($suffix),['id'=>(int)$row['id']])&&$cleanup_ok;}}
    wp_set_current_user(0);$native=$fixture->cleanup();$cleanup_ok=!in_array(false,$native,true)&&$cleanup_ok;
   }
   foreach($suffixes as $suffix)$cleanup_ok=$before[$suffix]===$rows($suffix)&&$cleanup_ok;
  } catch(Throwable){$cleanup_ok=false;}
  wp_set_current_user($old_actor);
  try{$check('NATIVE-W2P05-TRACKED-NATIVE-SHIPMENT-CLEANUP',$cleanup_ok&&$old_actor===get_current_user_id(),['owned_shipment_original_current_rows_removed'=>$cleanup_ok,'owned_native_orders_and_sources_removed'=>$cleanup_ok,'original_material_operation_history_restored'=>$cleanup_ok,'original_checkout_control_restored'=>$control_before===$control_row(),'native_actor_restored'=>$old_actor===get_current_user_id()]);}catch(Throwable $cleanup_error){if(null===$failure)throw $cleanup_error;}
 }
};
