<?php

declare(strict_types=1);

use CetechDeliveryEngine\Application\DeliveryQuote\QuoteAdmissionAttempt;
use CetechDeliveryEngine\Application\DeliveryQuote\QuoteAdvisoryPublication;
use CetechDeliveryEngine\Application\DeliveryQuote\QuoteDurableService;
use CetechDeliveryEngine\Application\DeliveryQuote\QuoteIssueCommand;
use CetechDeliveryEngine\Application\DeliveryQuote\QuoteOperationProfile;
use CetechDeliveryEngine\Application\DeliveryQuote\QuoteProviderRegistry;
use CetechDeliveryEngine\Application\DeliveryQuote\QuoteRetentionService;
use CetechDeliveryEngine\Core\Versioning\MigrationStatus;
use CetechDeliveryEngine\Core\Versioning\SchemaVersion;
use CetechDeliveryEngine\Domain\Contracts\RequestContext;
use CetechDeliveryEngine\Domain\DeliveryQuote\QuoteOwner;
use CetechDeliveryEngine\Domain\DeliveryQuote\QuoteStoredRow;
use CetechDeliveryEngine\Domain\DeliveryQuote\QuoteTime;
use CetechDeliveryEngine\Domain\EmergencyControl\EmergencyControlState;
use CetechDeliveryEngine\Infrastructure\Persistence\DeliveryQuoteReadiness;
use CetechDeliveryEngine\Infrastructure\Persistence\EmergencyControlStore;
use CetechDeliveryEngine\Tests\Support\DeliveryQuote\QuoteFixtures;

/** Actual WordPress/native SQL, synthetic terms, explicit internal adopter only. */
return static function ( callable $check ): void {
	global $wpdb;
	if ( '1' !== getenv( 'CETECH_DE_NATIVE_OPENING_QUALIFICATION' ) || ! defined( 'WP_ADMIN' ) || ! WP_ADMIN || '1' !== (string) get_option( 'cetech_opening_qualification_disposable' ) || ! defined( 'DB_HOST' ) || 1 !== preg_match( '/^127\.0\.0\.1(?::[0-9]+)?$/D', DB_HOST ) || ! defined( 'DB_NAME' ) || 1 !== preg_match( '/^cetech_wp_opening_qualification(?:_[a-z0-9]+)?$/D', DB_NAME ) || ! $wpdb instanceof wpdb || wpdb::class !== get_class( $wpdb ) || is_multisite() || WP_Object_Cache::class !== get_class( $GLOBALS['wp_object_cache'] ) || is_file( WP_CONTENT_DIR . '/object-cache.php' ) || is_file( WP_CONTENT_DIR . '/db.php' ) ) { throw new RuntimeException( 'Q03 proof requires the marked native default-cache fixture.' ); }
	foreach ( get_included_files() as $included ) { if ( str_ends_with( str_replace( '\\', '/', $included ), '/tests/bootstrap.php' ) ) { throw new RuntimeException( 'Unit bootstrap is forbidden in native quote lifecycle proof.' ); } }
	$root = dirname( __DIR__, 2 );
	require_once $root . '/tests/Support/DeliveryQuote/QuoteFixtures.php';
	require_once __DIR__ . '/opening-quote-lifecycle-support.php';
	$main = $wpdb; $original = [];
	foreach ( [ 'wpdb', 'wp_roles', 'wp_user_roles', 'wp_object_cache', 'wp_rewrite', 'current_user', 'user_ID', 'blog_id' ] as $key ) { $original[$key] = [ array_key_exists( $key, $GLOBALS ), $GLOBALS[$key] ?? null ]; }
	$schema_options = static fn (): array => $main->get_results( $main->prepare( "SELECT option_id,option_name,option_value,autoload FROM `{$main->options}` WHERE option_name IN (%s,%s) ORDER BY option_name", SchemaVersion::OPTION_NAME, MigrationStatus::OPTION_NAME ), ARRAY_A );
	$main_history = static function () use ( $main ): array {
		$out = [];
		foreach ( [ 'operation_records', 'operation_changes', 'delivery_quotes', 'delivery_quote_bindings', 'delivery_quote_budget_windows' ] as $suffix ) { $out[$suffix] = $main->get_results( "SELECT * FROM `{$main->prefix}delivery_engine_{$suffix}` ORDER BY id", ARRAY_A ); }
		return $out;
	};
	$options_before = $schema_options(); $history_before = $main_history(); $fixture = null; $failure = null;
	try {
		( new DeliveryQuoteReadiness( $main ) )->assert_ready();
		$fixture = new CetechNativeQuoteLifecycleFixture( $main ); $fixture->install(); $fixture->select();
		$owner = QuoteOwner::from_array( array_replace( QuoteFixtures::owner()->facts(), [ 'site_id' => $fixture->site ] ) );
		$context = QuoteFixtures::context(); $at = QuoteFixtures::time(); $fixture->factory->fixture_time( $at );
		$fixture->write_option( CetechNativeQuoteLifecycleEvidence::OPTION, CetechNativeQuoteLifecycleEvidence::value( $owner, $context ) );
		$authority = true;
		// Capture the live permission value by reference, including revocation.
		$authorize = static function ( QuoteOwner $candidate, string $operation ) use ( &$authority, $owner ): bool { return $authority && $owner->equals( $candidate ) && str_starts_with( $operation, 'delivery_quote.' ); };
		$provider = new CetechNativeQuoteLifecycleProvider( $context, $fixture->factory ); $providers = new QuoteProviderRegistry( [ $provider ] ); $evidence = new CetechNativeQuoteLifecycleEvidence();
		$service = new QuoteDurableService( $fixture->factory, $providers, $authorize, evidence: $evidence );
		$command = static fn ( string $token, $ctx = null ): QuoteIssueCommand => QuoteIssueCommand::create( $owner, $ctx ?? $context, 'fixture_v1', 1, 'fixture_v1', 1, $token );
		$issue = static function ( string $token ) use ( $service, $command ) { $result = $service->issue( $command( $token ), QuoteAdmissionAttempt::generate(), RequestContext::create() ); if ( 'accepted' !== $result->attempt->outcome->state || null === $result->quote || null === $result->command?->reference() ) { throw new RuntimeException( 'Native synthetic durable issuance failed.' ); } return $result; };
		$row = static function ( $id ) use ( $fixture ): QuoteStoredRow { $rows = $fixture->rows( "SELECT * FROM `{$fixture->prefix}delivery_engine_delivery_quotes` WHERE quote_uuid=" . $fixture->literal( $id->value() ) ); if ( 1 !== count( $rows ) ) { throw new RuntimeException( 'Native quote physical identity is unavailable.' ); } return QuoteStoredRow::from_row( $rows[0] ); };
		$event_count = static fn (): int => count( $fixture->quote_history()['operation_changes'] );
		$first_command = $command( 'native-q03-first-original' ); $first = $service->issue( $first_command, QuoteAdmissionAttempt::generate(), RequestContext::create() );
		$first_history = $fixture->quote_history(); $first_quote = $first->quote; $first_reference = $first->command?->reference();
		$budgets = $first_history['delivery_quote_budget_windows']; $counts = []; foreach ( $budgets as $budget ) { $counts[$budget['slot_kind']] = (int) $budget['attempt_count']; }
		$check( 'NATIVE-W2Q03-OWNED-ISSUE-ATOMIC-QUOTE-EVENT-COMPLETION', 'accepted' === $first->attempt->outcome->state && true === $first->attempt->outcome->mutation_accepted && null !== $first_quote && null !== $first_reference && 'issued' === $first_quote->state() && 1 === $first_quote->revision() && 1 === count( $first_history['delivery_quotes'] ) && 1 === count( $first_history['operation_changes'] ) && 1 === count( $first_history['operation_records'] ) && 'accepted' === $first_history['operation_records'][0]['state'] && 'published' === $first_history['operation_records'][0]['publication_state'] && 1 === $provider->captures && $provider->outside_owned_unit && [ 'site_minute' => 1, 'session_minute' => 1, 'admission' => 1 ] === $counts && 'consumed' === $budgets[2]['lease_state'], [ 'actual_wp_load' => defined( 'ABSPATH' ), 'default_object_cache' => WP_Object_Cache::class === get_class( $GLOBALS['wp_object_cache'] ), 'synthetic_provider' => 'fixture_v1', 'capture_calls' => $provider->captures, 'capture_outside_owned_unit' => $provider->outside_owned_unit, 'atomic_effect_rows' => 1, 'atomic_material_events' => 1, 'native_woo_capture_claimed' => false ] );
		$replay = $service->issue( $first_command, QuoteAdmissionAttempt::generate(), RequestContext::create() );
		$check( 'NATIVE-W2Q03-ORIGINAL-ISSUE-REPLAY-NO-RECAPTURE-OR-EXPIRY-EXTENSION', 'accepted' === $replay->attempt->outcome->state && $replay->attempt->replayed && 1 === $provider->captures && $first_history === $fixture->quote_history() && $first_quote->row() === $replay->quote?->row() && $first->attempt->completion?->to_json() === $replay->attempt->completion?->to_json(), [ 'replayed' => $replay->attempt->replayed, 'capture_calls' => $provider->captures, 'exact_original_completion' => $first->attempt->completion?->to_json() === $replay->attempt->completion?->to_json(), 'history_unchanged' => $first_history === $fixture->quote_history() ] );
		$changed_context = QuoteFixtures::context( [ 'selection_digest' => QuoteFixtures::digest( 'native-q03-changed-selection' ) ] );
		$conflict = $service->issue( $command( 'native-q03-first-original', $changed_context ), QuoteAdmissionAttempt::generate(), RequestContext::create() );
		$check( 'NATIVE-W2Q03-CHANGED-ISSUE-INTENT-CANNOT-RECAPTURE', 'rejected' === $conflict->attempt->outcome->state && null === $conflict->attempt->completion && 1 === $provider->captures && $first_history === $fixture->quote_history(), [ 'known_refusal' => 'rejected' === $conflict->attempt->outcome->state, 'capture_calls' => $provider->captures, 'counter_quote_audit_history_unchanged' => $first_history === $fixture->quote_history() ] );
		$accepted = $service->accept( $owner, $first_reference, $first_quote->header(), $context, RequestContext::create() );
		$accepted_history = $fixture->quote_history();
		$check( 'NATIVE-W2Q03-ACCEPT-AND-REPLAY-ONE-MATERIAL-EVENT', 'accepted' === $accepted->attempt->outcome->state && 'accepted' === $accepted->quote?->state() && 2 === $accepted->quote?->revision() && 2 === $event_count() && $first_quote->header()->to_private_json() === $accepted->quote?->header()->to_private_json() && $first_quote->row()['private_body_json'] === $accepted->quote?->row()['private_body_json'], [ 'quote_revision' => $accepted->quote?->revision(), 'material_events' => $event_count(), 'immutable_body' => $first_quote->row()['private_body_json'] === $accepted->quote?->row()['private_body_json'] ] );
		$accept_replay = $service->accept( $owner, $first_reference, $first_quote->header(), $context, RequestContext::create() );
		$check( 'NATIVE-W2Q03-ACCEPTED-ORIGINAL-REPLAY-EXACT-COMPLETION', 'accepted' === $accept_replay->attempt->outcome->state && $accept_replay->attempt->replayed && $accepted->attempt->completion?->to_json() === $accept_replay->attempt->completion?->to_json() && $accepted_history === $fixture->quote_history() && 1 === $provider->captures, [ 'exact_completion' => $accepted->attempt->completion?->to_json() === $accept_replay->attempt->completion?->to_json(), 'history_unchanged' => $accepted_history === $fixture->quote_history(), 'capture_calls' => $provider->captures ] );
		$cache_key = QuoteAdvisoryPublication::key( $fixture->site, $owner->digest(), $first_quote->header()->id() ); $stale = [ 'state' => 'issued', 'revision' => 999, 'private' => [ 'body' => 'STALE-NATIVE-FIXTURE' ] ];
		wp_cache_set( $cache_key, $stale, QuoteAdvisoryPublication::GROUP ); $read = $service->current( $owner, $first_reference, $context, RequestContext::create() );
		$check( 'NATIVE-W2Q03-WARM-DEFAULT-CACHE-CURRENT-READ-IS-PHYSICAL', 'ready' === $read->status && null === $read->reason && $accepted->quote->row() === $read->quote?->row() && $stale === wp_cache_get( $cache_key, QuoteAdvisoryPublication::GROUP ) && $accepted_history === $fixture->quote_history(), [ 'default_object_cache' => WP_Object_Cache::class === get_class( $GLOBALS['wp_object_cache'] ), 'physical_revision' => $read->quote?->revision(), 'advisory_payload_unchanged' => $stale === wp_cache_get( $cache_key, QuoteAdvisoryPublication::GROUP ), 'read_has_no_effect_or_audit' => $accepted_history === $fixture->quote_history() ] );
		$authority = false; $denied = $service->current( $owner, $first_reference, $context, RequestContext::create() ); $authority = true;
		$check( 'NATIVE-W2Q03-CURRENT-AUTHORITY-DENIES-PRIVATE-DISCLOSURE', 'unavailable' === $denied->status && null === $denied->quote && $accepted_history === $fixture->quote_history(), [ 'private_row_disclosed' => null !== $denied->quote, 'history_unchanged' => $accepted_history === $fixture->quote_history() ] );
		$audit_issue = $issue( 'native-q03-audit-original' ); $audit_row = $audit_issue->quote; $before_audit = $event_count(); $before_budgets = $fixture->quote_history()['delivery_quote_budget_windows']; $rollbacks = $fixture->factory->acknowledged_rollbacks;
		$fixture->factory->arm( 'reject_quote_audit' ); $audit_refused = $service->accept( $owner, $audit_issue->command->reference(), $audit_row->header(), $context, RequestContext::create() );
		$check( 'NATIVE-W2Q03-REJECTED-AUDIT-ROLLS-BACK-QUOTE-ACCEPTANCE', 'rejected' === $audit_refused->attempt->outcome->state && false === $audit_refused->attempt->outcome->mutation_accepted && $audit_row->row() === $row( $audit_row->header()->id() )->row() && $before_audit === $event_count() && $before_budgets === $fixture->quote_history()['delivery_quote_budget_windows'] && 1 === $fixture->factory->rejected_audits && $fixture->factory->acknowledged_rollbacks > $rollbacks, [ 'audit_refusal_injected_before_dispatch' => 1 === $fixture->factory->rejected_audits, 'whole_unit_rollback_acknowledged' => $fixture->factory->acknowledged_rollbacks > $rollbacks, 'quote_unchanged' => $audit_row->row() === $row( $audit_row->header()->id() )->row(), 'no_new_material_event' => $before_audit === $event_count() ] );
		$audit_retry = $service->accept( $owner, $audit_issue->command->reference(), $audit_row->header(), $context, RequestContext::create() );
		$check( 'NATIVE-W2Q03-KNOWN-REJECTION-ORIGINAL-RETRY-ACCEPTS-ONCE', 'accepted' === $audit_retry->attempt->outcome->state && 2 === $audit_retry->quote?->revision() && $before_audit + 1 === $event_count() && 2 === $provider->captures, [ 'same_opened_header' => $audit_row->header()->to_private_json() === $audit_retry->command?->header()?->to_private_json(), 'material_event_delta' => $event_count() - $before_audit, 'capture_calls' => $provider->captures ] );
		$unsent_issue = $issue( 'native-q03-unsent-original' ); $unsent_row = $unsent_issue->quote; $before_unsent = $event_count(); $rollbacks = $fixture->factory->acknowledged_rollbacks;
		$fixture->factory->arm( 'unsent_quote_commit' ); $unsent = $service->accept( $owner, $unsent_issue->command->reference(), $unsent_row->header(), $context, RequestContext::create() );
		$check( 'NATIVE-W2Q03-PROVED-UNSENT-COMMIT-ROLLS-BACK', 'rejected' === $unsent->attempt->outcome->state && false === $unsent->attempt->outcome->mutation_accepted && 1 === $fixture->factory->unsent_quote_commits && $fixture->factory->acknowledged_rollbacks > $rollbacks && $unsent_row->row() === $row( $unsent_row->header()->id() )->row() && $before_unsent === $event_count(), [ 'commit_not_dispatched' => 1 === $fixture->factory->unsent_quote_commits, 'rollback_acknowledged' => $fixture->factory->acknowledged_rollbacks > $rollbacks, 'quote_unchanged' => $unsent_row->row() === $row( $unsent_row->header()->id() )->row(), 'material_event_delta' => $event_count() - $before_unsent ] );
		$lost_issue = $issue( 'native-q03-lost-ack-original' ); $lost_row = $lost_issue->quote; $before_lost = $event_count();
		$fixture->factory->arm( 'lost_quote_ack' ); $lost = $service->accept( $owner, $lost_issue->command->reference(), $lost_row->header(), $context, RequestContext::create() ); $committed_lost = $row( $lost_row->header()->id() );
		$check( 'NATIVE-W2Q03-ACTUAL-SENT-LOST-ACK-IS-UNKNOWN-AND-RETIRED', 'unconfirmed' === $lost->attempt->outcome->state && null === $lost->attempt->outcome->mutation_accepted && null === $lost->attempt->completion && 1 === $fixture->factory->masked_sent_quote_commits && $fixture->factory->fault_owner_retired() && 'accepted' === $committed_lost->state() && 2 === $committed_lost->revision() && $before_lost + 1 === $event_count(), [ 'native_commit_acknowledged_before_masking' => 1 === $fixture->factory->masked_sent_quote_commits, 'failed_owner_retired' => $fixture->factory->fault_owner_retired(), 'returned_outcome' => $lost->attempt->outcome->state, 'physical_revision' => $committed_lost->revision(), 'material_event_delta' => $event_count() - $before_lost ] );
		$reconciled = $service->reconcile( $lost->command, RequestContext::create() ); $reconciled_history = $fixture->quote_history();
		$check( 'NATIVE-W2Q03-REPLACEMENT-RECONCILIATION-NO-EFFECT-REPEAT', 'accepted' === $reconciled->attempt->outcome->state && $reconciled->attempt->replayed && $committed_lost->row() === $reconciled->quote?->row() && $before_lost + 1 === $event_count() && 4 === $provider->captures, [ 'replayed' => $reconciled->attempt->replayed, 'replacement_physical_row' => $committed_lost->row() === $reconciled->quote?->row(), 'material_event_delta' => $event_count() - $before_lost, 'capture_calls' => $provider->captures ] );
		$installed = dirname( (string) ( new ReflectionClass( CetechDeliveryEngine\Bootstrap\Plugin::class ) )->getFileName(), 3 );
		$child = CetechNativeQuoteLifecycleFixture::child( [ 'wp_load' => rtrim( ABSPATH, '/' ) . '/wp-load.php', 'plugin_root' => $installed, 'prefix' => $fixture->prefix, 'site' => $fixture->site, 'fixture_time' => $at->sql(), 'owner' => $owner->facts(), 'context' => $context->private_facts(), 'reference' => $lost_issue->command->reference()->public_fields(), 'header' => $lost_row->header()->to_private_json(), 'original_issue_token' => 'native-q03-lost-ack-original', 'completion_hash' => hash( 'sha256', $reconciled->attempt->completion->to_json() ), 'row_hash' => hash( 'sha256', json_encode( $committed_lost->row(), JSON_THROW_ON_ERROR ) ), 'history_hash' => hash( 'sha256', json_encode( $reconciled_history, JSON_THROW_ON_ERROR ) ) ] );
		$child_checks = [ 'wp_load', 'default_object_cache', 'installed_candidate_autoload', 'schema9', 'exact_completion', 'replayed', 'exact_row', 'unchanged_history', 'capture_not_called', 'no_capture_capability', 'all_owners_retired' ]; $child_ok = 'PASS' === $child['status'] && is_int( $child['process_id'] ) && getmypid() !== $child['process_id']; foreach ( $child_checks as $key ) { $child_ok = $child_ok && true === $child[$key]; }
		$check( 'NATIVE-W2Q03-FRESH-WP-LOAD-ORIGINAL-RECONCILIATION', $child_ok && $reconciled_history === $fixture->quote_history(), [ 'fresh_os_process' => is_int( $child['process_id'] ) ? getmypid() !== $child['process_id'] : null, 'actual_wp_load' => $child['wp_load'], 'installed_candidate_autoload' => $child['installed_candidate_autoload'], 'reader_status' => $child['status'], 'reader_phase' => $child['phase'], 'reader_error_class' => $child['error_class'], 'reader_transport' => $child['transport_code'], 'reader_exit_code' => $child['exit_code'], 'reader_signal' => $child['signal'], 'reader_stderr_present' => $child['stderr_present'], 'checks' => array_intersect_key( $child, array_flip( $child_checks ) ), 'unit_bootstrap' => false ] );
		$publication = new CetechNativeQuoteLifecyclePublication(); $pending_service = new QuoteDurableService( $fixture->factory, $providers, $authorize, evidence: $evidence, publication: $publication );
		$pending_cache_key = QuoteAdvisoryPublication::key( $fixture->site, $owner->digest(), $unsent_row->header()->id() ); wp_cache_set( $pending_cache_key, 'native-fixture-pending-marker', QuoteAdvisoryPublication::GROUP );
		$pending = $pending_service->accept( $owner, $unsent_issue->command->reference(), $unsent_row->header(), $context, RequestContext::create() ); $pending_row = $row( $unsent_row->header()->id() ); $pending_events = $event_count(); $quote_writes = $fixture->factory->quote_mutation_statements;
		$cache_pending = 'native-fixture-pending-marker' === wp_cache_get( $pending_cache_key, QuoteAdvisoryPublication::GROUP );
		$publication->accept = true; $published = $pending_service->reconcile( $pending->command, RequestContext::create() );
		$cache_invalidated = false === wp_cache_get( $pending_cache_key, QuoteAdvisoryPublication::GROUP );
		$check( 'NATIVE-W2Q03-FAILED-ADVISORY-PUBLICATION-RETRY-ONLY', 'unconfirmed' === $pending->attempt->outcome->state && true === $pending->attempt->outcome->mutation_accepted && $pending->attempt->outcome->publication_pending && 'accepted' === $pending_row->state() && 'accepted' === $published->attempt->outcome->state && $published->attempt->replayed && 2 === $publication->calls && $pending_events === $event_count() && $quote_writes === $fixture->factory->quote_mutation_statements && $pending_row->row() === $published->quote?->row() && $cache_pending && $cache_invalidated, [ 'accepted_sql_despite_pending_publication' => true === $pending->attempt->outcome->mutation_accepted, 'publication_calls' => $publication->calls, 'quote_write_repeated' => $quote_writes !== $fixture->factory->quote_mutation_statements, 'audit_repeated' => $pending_events !== $event_count(), 'pending_cache_marker_kept' => $cache_pending, 'actual_default_cache_invalidation_on_retry' => $cache_invalidated ] );
		$before_pause = $fixture->quote_history(); $capture_before_pause = $provider->captures; $fixture->write_option( EmergencyControlStore::OPTION_NAME, EmergencyControlState::record_json( $fixture->site, 'checkout_suspended', 2, 'maintenance_pause', 1, intdiv( $at->epoch_microseconds(), 1000000 ) ) );
		$paused = $service->issue( $command( 'native-q03-paused-original' ), QuoteAdmissionAttempt::generate(), RequestContext::create() );
		$check( 'NATIVE-W2Q03-CURRENT-C07-PAUSE-BEFORE-COUNTERS-CAPTURE-RESERVATION', 'rejected' === $paused->attempt->outcome->state && 'checkout_suspended' === $paused->reason && $capture_before_pause === $provider->captures && $before_pause === $fixture->quote_history(), [ 'same_native_control_source' => true, 'capture_calls_unchanged' => $capture_before_pause === $provider->captures, 'counter_effect_completion_event_history_unchanged' => $before_pause === $fixture->quote_history(), 'fixture_control_setup_only' => true ] );
		$fixture->execute( "DELETE FROM `{$fixture->prefix}options` WHERE option_name=" . $fixture->literal( EmergencyControlStore::OPTION_NAME ) );
		$retention_issue = $issue( 'native-q03-retention-original' ); $retention_row = $retention_issue->quote; $immutable_header = $retention_row->row()['header_json'];
		$before_grace = QuoteTime::from_epoch_microseconds( $retention_row->header()->expires_at()->plus_seconds( 1800 )->epoch_microseconds() - 1 ); $fixture->factory->fixture_time( $before_grace );
		$references = new CetechNativeQuoteLifecycleReferences( $owner ); $retention = new QuoteRetentionService( $fixture->factory, QuoteOperationProfile::registry(), static fn ( int $site ): bool => $site === $fixture->site, $references );
		$walk = static function ( QuoteRetentionService $worker ) use ( $fixture ) { $result = $worker->start( $fixture->site, RequestContext::create() ); for ( $i = 0; $i < 5 && null !== $result->checkpoint && ! $result->checkpoint->complete(); ++$i ) { $result = $worker->batch( $result->checkpoint, RequestContext::create() ); } if ( 'accepted' !== $result->attempt->outcome->state || null === $result->checkpoint || ! $result->checkpoint->complete() ) { throw new RuntimeException( 'Native quote retention checkpoint did not complete.' ); } return $result; };
		$early = $walk( $retention );
		$check( 'NATIVE-W2Q03-RETENTION-GRACE-ONE-MICROSECOND-BEFORE', 0 === $early->checkpoint->facts()['stripped'] && $retention_row->row() === $row( $retention_row->header()->id() )->row() && $fixture->factory->verified_fixture_clocks > 0, [ 'controlled_native_sql_clock' => true, 'verified_utc_timestamp6' => $fixture->factory->verified_fixture_clocks > 0, 'microseconds_before_boundary' => 1, 'stripped' => $early->checkpoint->facts()['stripped'], 'original_body_preserved' => $retention_row->row() === $row( $retention_row->header()->id() )->row() ] );
		$boundary = $retention_row->header()->expires_at()->plus_seconds( 1800 ); $fixture->factory->fixture_time( $boundary );
		$unknown = new QuoteRetentionService( $fixture->factory, QuoteOperationProfile::registry(), static fn ( int $site ): bool => $site === $fixture->site ); $protected = $walk( $unknown );
		$check( 'NATIVE-W2Q03-RETENTION-DEFAULT-UNKNOWN-REFERENCES-PROTECT', 0 === $protected->checkpoint->facts()['stripped'] && $retention_row->row() === $row( $retention_row->header()->id() )->row(), [ 'default_reference_state' => 'unknown', 'native_hpos_absence_claimed' => false, 'stripped' => $protected->checkpoint->facts()['stripped'], 'body_preserved' => $retention_row->row() === $row( $retention_row->header()->id() )->row() ] );
		$accepted_before_retention = $row( $first_quote->header()->id() )->row(); $before_boundary_events = $event_count(); $at_boundary = $walk( $retention ); $stripped = $row( $retention_row->header()->id() );
		$check( 'NATIVE-W2Q03-RETENTION-EXACT-GRACE-STRIPS-PRIVATE-BODY-ONLY', 1 === $at_boundary->checkpoint->facts()['stripped'] && 'stripped' === $stripped->state() && null === $stripped->row()['private_body_json'] && 2 === $stripped->revision() && 2 === $stripped->row()['retention_revision'] && $immutable_header === $stripped->row()['header_json'] && $retention_row->header()->body_digest() === $stripped->header()->body_digest() && $accepted_before_retention === $row( $first_quote->header()->id() )->row() && $event_count() > $before_boundary_events, [ 'controlled_native_sql_clock' => true, 'at_exact_grace_boundary' => $stripped->row()['transition_at'] === $boundary->sql(), 'stripped' => $at_boundary->checkpoint->facts()['stripped'], 'immutable_header_preserved' => $immutable_header === $stripped->row()['header_json'], 'accepted_body_preserved' => $accepted_before_retention === $row( $first_quote->header()->id() )->row(), 'reference_scope' => 'synthetic_binding_only', 'native_order_absence_claimed' => false ] );
		$before_retention_replay = $fixture->quote_history(); $retention_replay = $retention->reconcile( $at_boundary->request, RequestContext::create() );
		$check( 'NATIVE-W2Q03-RETENTION-ORIGINAL-CHECKPOINT-REPLAY-NO-REPEAT', 'accepted' === $retention_replay->attempt->outcome->state && $retention_replay->attempt->replayed && $at_boundary->attempt->completion->to_json() === $retention_replay->attempt->completion?->to_json() && $before_retention_replay === $fixture->quote_history(), [ 'replayed' => $retention_replay->attempt->replayed, 'exact_checkpoint_completion' => $at_boundary->attempt->completion->to_json() === $retention_replay->attempt->completion?->to_json(), 'effect_and_event_history_unchanged' => $before_retention_replay === $fixture->quote_history() ] );
	} catch ( Throwable $error ) { $failure = $error; throw $error; }
	finally {
		$cleanup = true;
		if ( null !== $fixture ) { try { $fixture->factory->fixture_time( null ); $cleanup = $fixture->factory->close_all(); } catch ( Throwable ) { $cleanup = false; } }
		foreach ( $original as $key => [ $exists, $value ] ) { if ( $exists ) { $GLOBALS[$key] = $value; } else { unset( $GLOBALS[$key] ); } }
		if ( null !== $fixture ) { $cleanup = $fixture->cleanup() && $cleanup; }
		$condition = $cleanup && $GLOBALS['wpdb'] === $main && $GLOBALS['wp_object_cache'] === $original['wp_object_cache'][1] && get_current_blog_id() === (int) $original['blog_id'][1] && $options_before === $schema_options() && $history_before === $main_history() && '9' === (string) get_option( SchemaVersion::OPTION_NAME );
		$proof = [ 'all_owned_tables_removed' => $cleanup, 'owned_counter_option_completion_event_stores_removed' => $cleanup, 'main_schema_options_unchanged' => $options_before === $schema_options(), 'main_quote_operation_history_unchanged' => $history_before === $main_history(), 'native_context_restored' => $GLOBALS['wpdb'] === $main ];
		if ( null === $failure ) { $check( 'NATIVE-W2Q03-ISOLATED-LIFECYCLE-FIXTURE-CLEANUP', $condition, $proof ); }
		else { try { $check( 'NATIVE-W2Q03-ISOLATED-LIFECYCLE-FIXTURE-CLEANUP', $condition, $proof ); } catch ( Throwable ) {} }
	}
};
