<?php
/** Separate P06 actual native HPOS/CPT bounds receipt after exact P05 primary proofs. */
declare(strict_types=1);
if ( '1' !== getenv( 'CETECH_DE_NATIVE_OPENING_QUALIFICATION' ) || ! defined( 'ABSPATH' ) || ! defined( 'WP_ADMIN' ) || true !== WP_ADMIN || '1' !== (string) get_option( 'cetech_opening_qualification_disposable' ) || ! defined( 'DB_HOST' ) || 1 !== preg_match( '/\A127\.0\.0\.1(?::[0-9]+)?\z/D', DB_HOST ) || ! defined( 'DB_NAME' ) || 1 !== preg_match( '/\Acetech_wp_opening_qualification(?:_[a-z0-9]+)?\z/D', DB_NAME ) || count( $args ) !== 5 || ! class_exists( WC_Order::class ) || is_multisite() || WP_Object_Cache::class !== get_class( $GLOBALS['wp_object_cache'] ) || is_file( WP_CONTENT_DIR . '/object-cache.php' ) || is_file( WP_CONTENT_DIR . '/db.php' ) ) { throw new RuntimeException( 'P06 bounds require marked native default-cache loopback and five arguments.' ); }
foreach ( get_included_files() as $file ) { if ( str_ends_with( str_replace( '\\', '/', $file ), '/tests/bootstrap.php' ) ) { throw new RuntimeException( 'P06 bounds forbid a unit bootstrap.' ); } }
[ $report_path, $mode, $p05_hpos, $p05_cpt, $p05_http ] = $args;
if ( ! is_dir( dirname( $report_path ) ) || file_exists( $report_path ) || is_link( $report_path ) || ! in_array( $mode, [ 'hpos_on', 'hpos_off' ], true ) || ( 'hpos_on' === $mode ) !== Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled() ) { throw new RuntimeException( 'P06 bounds require fresh receipt and exact native storage mode.' ); }
global $wpdb;
$root = dirname( (string) ( new ReflectionClass( CetechDeliveryEngine\Bootstrap\Plugin::class ) )->getFileName(), 3 );
$map = []; foreach ( [ 'src', 'database' ] as $directory ) { foreach ( new RecursiveIteratorIterator( new RecursiveDirectoryIterator( $root . '/' . $directory, FilesystemIterator::SKIP_DOTS ) ) as $file ) { if ( $file->isFile() && 'php' === $file->getExtension() ) { $map[substr( $file->getPathname(), strlen( $root ) + 1 )] = hash_file( 'sha256', $file->getPathname() ); } } }
foreach ( [ 'cetech-woocommerce-delivery-engine.php', 'uninstall.php' ] as $name ) { $map[$name] = hash_file( 'sha256', $root . '/' . $name ); } ksort( $map, SORT_STRING );
$source = (string) getenv( 'CETECH_DE_QUALIFICATION_HEAD' ); $candidate = (string) getenv( 'CETECH_DE_QUALIFICATION_CANDIDATE_HEAD' ); $tree = (string) getenv( 'CETECH_DE_QUALIFICATION_TREE' );
foreach ( [ $source, $candidate, $tree ] as $identity ) { if ( 1 !== preg_match( '/\A[0-9a-f]{40}\z/D', $identity ) ) { throw new RuntimeException( 'P06 immutable execution identity unavailable.' ); } }
$preceding = []; foreach ( [ 'p05_hpos' => [ $p05_hpos, 27 ], 'p05_cpt' => [ $p05_cpt, 27 ], 'p05_http' => [ $p05_http, 19 ] ] as $kind => [ $path, $count ] ) {
	if ( ! is_file( $path ) || filesize( $path ) > 16777216 ) { throw new RuntimeException( 'P06 requires complete P05 primary receipts.' ); }
	$prior = json_decode( (string) file_get_contents( $path ), true, 512, JSON_THROW_ON_ERROR );
	if ( ! is_array( $prior ) || 'PASS' !== ( $prior['status'] ?? null ) || $source !== ( $prior['source_head'] ?? null ) || $candidate !== ( $prior['candidate_head'] ?? null ) || $tree !== ( $prior['source_tree'] ?? null ) || $map !== ( $prior['installed_php_sources'] ?? null ) || ! is_array( $prior['cases'] ?? null ) || $count !== count( $prior['cases'] ) ) { throw new RuntimeException( 'P06 preceding identity, exact source or inventory differs.' ); }
	foreach ( $prior['cases'] as $case ) { if ( ! is_array( $case ) || 'PASS' !== ( $case['status'] ?? null ) ) { throw new RuntimeException( 'P06 cannot compensate for failed P05 evidence.' ); } }
	$preceding[$kind] = [ 'sha256' => hash_file( 'sha256', $path ), 'cases' => $count ];
}
$report = [ 'format' => 'cetech-opening-promise-qualification-native-bounds-v1', 'source_head' => $source, 'candidate_head' => $candidate, 'source_tree' => $tree, 'installed_php_sources' => $map, 'installed_php_sources_hash' => hash( 'sha256', json_encode( $map, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR ) ), 'environment' => [ 'php' => PHP_VERSION, 'wordpress' => get_bloginfo( 'version' ), 'woocommerce' => WC_VERSION, 'database_version' => (string) $wpdb->get_var( 'SELECT VERSION()' ), 'hpos' => (string) get_option( 'woocommerce_custom_orders_table_enabled' ), 'schema_before' => (string) get_option( 'cetech_de_db_version' ), 'context' => 'Fresh WP-CLI P06 actual loaded-cart boundaries and captured native source-owner query observation', 'background_requests' => 'WP Cron disabled; Action Scheduler async request runner suppressed in this process' ], 'limits' => [ 'Actual marked disposable Woo loaded-cart boundaries; cloned loaded members, no successful full 200-group placement claim.', 'Actual native capture and final source-owner fences; WordPress HTTP/query and authority callback observations are limited to these two operations.', 'Same Day and Standard are authorized hypothetical native previews; no registered shopper alternative-service breadth claim.', 'Default adoption and tracked sources are restored; no live operational acceptance, mounted capacity or provider payment.' ], 'preceding_receipts' => $preceding, 'status' => 'RUNNING', 'cases' => [] ];
$write = static function () use ( &$report, $report_path ): void { if ( false === file_put_contents( $report_path, json_encode( $report, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR ) . "\n" ) ) { throw new RuntimeException( 'P06 cannot persist bounds receipt.' ); } };
$check = static function ( string $id, bool $condition, array $evidence, array $observations ) use ( &$report, $write ): void {
	if ( 1 !== preg_match( '/\ANATIVE-W2P06-[A-Z0-9-]+\z/D', $id ) || [] === $evidence || [] === $observations ) { throw new RuntimeException( 'P06 bounds case has no exact observations.' ); }
	foreach ( $report['cases'] as $case ) { if ( $id === $case['id'] ) { throw new RuntimeException( 'P06 bounds source case duplicated.' ); } }
	foreach ( $evidence as $name => $value ) { if ( ! is_string( $name ) || 1 !== preg_match( '/\A[a-z0-9_]+\z/D', $name ) || ! is_bool( $value ) ) { throw new RuntimeException( 'P06 bounds evidence must be closed booleans.' ); } }
	foreach ( $observations as $name => $value ) { if ( ! is_string( $name ) || 1 !== preg_match( '/\A[a-z0-9_]+\z/D', $name ) || ! is_int( $value ) || $value < 0 || $value > 2000000 ) { throw new RuntimeException( 'P06 work observations must be bounded nonnegative integers.' ); } }
	$passed = $condition && ! in_array( false, $evidence, true ); $report['cases'][] = [ 'id' => $id, 'status' => $passed ? 'PASS' : 'FAIL', 'evidence' => $evidence, 'observations' => $observations ]; $write(); echo 'opening_pure_case=' . $id . ' result=' . ( $passed ? 'PASS' : 'FAIL' ) . PHP_EOL;
	if ( ! $passed ) { throw new RuntimeException( 'P06 bounds case failed; see receipt.' ); }
};
$write(); add_filter( 'action_scheduler_allow_async_request_runner', '__return_false', PHP_INT_MAX );
try { $module = require __DIR__ . '/opening-promise-qualification-native-bounds.php'; $module( $check, $mode ); $report['status'] = 'PASS'; $write(); echo 'opening_promise_qualification_native_bounds=PASS mode=' . $mode . ' native=' . count( $report['cases'] ) . PHP_EOL; }
catch ( Throwable $error ) { $report['status'] = 'FAIL'; $report['error'] = [ 'class' => get_class( $error ) ]; $write(); throw $error; }
