<?php
/** One fresh native saved-order payment request. Private key/configuration never enters output. */
declare(strict_types=1);

$path=$argv[1]??null;$phase='configuration';$result=['status'=>'FAIL','phase'=>$phase,'process_id'=>getmypid(),'private_config_0600'=>false,'installed_production_map'=>false,'default_native_cache'=>false,'native_admission'=>false,'native_payment_form_session'=>false,'native_gateway_paid_once'=>false,'native_provider_callback'=>false,'persisted_paid'=>false,'session_cleanup'=>false];$session=null;$session_id=null;$owned_session=false;$wpdb=null;ob_start();
try {
 if(PHP_SAPI!=='cli'||'1'!==getenv('CETECH_DE_NATIVE_OPENING_QUALIFICATION')||!is_string($path)||!is_file($path)||is_link($path)||filesize($path)>16384||(fileperms($path)&0777)!==0600)throw new RuntimeException('Native private payment configuration unavailable.');$result['private_config_0600']=true;
 $config=json_decode((string)file_get_contents($path),true,16,JSON_THROW_ON_ERROR);if(!is_array($config)||array_keys($config)!==['wp_load','plugin_root','php_map_hash','php_map_count','lease_path','parent_nonce','stimulus','order_id','order_key','method','mode','site_id','snapshot_digest']||!is_string($config['wp_load'])||!is_file($config['wp_load'])||!is_string($config['plugin_root'])||!is_dir($config['plugin_root'])||!is_string($config['php_map_hash'])||1!==preg_match('/\A[a-f0-9]{64}\z/D',$config['php_map_hash'])||!is_int($config['php_map_count'])||$config['php_map_count']<1||$config['php_map_count']>2000||!is_string($config['lease_path'])||!is_file($config['lease_path'])||is_link($config['lease_path'])||0!==filesize($config['lease_path'])||(fileperms($config['lease_path'])&0777)!==0600||!is_string($config['parent_nonce'])||1!==preg_match('/\A[a-f0-9]{64}\z/D',$config['parent_nonce'])||!in_array($config['stimulus'],['order_pay','provider_callback'],true)||!is_int($config['order_id'])||$config['order_id']<1||!is_int($config['site_id'])||$config['site_id']<1||!is_string($config['order_key'])||''===$config['order_key']||strlen($config['order_key'])>128||$config['method']!=='cetech_q06_native_gateway'||!in_array($config['mode'],['hpos_on','hpos_off'],true)||!is_string($config['snapshot_digest'])||1!==preg_match('/\A[a-f0-9]{64}\z/D',$config['snapshot_digest']))throw new RuntimeException('Native private payment configuration invalid.');
 $phase='wp_load';define('WP_ADMIN',true);require $config['wp_load'];
 if(!defined('DB_HOST')||1!==preg_match('/\A127\.0\.0\.1(?::[0-9]+)?\z/D',DB_HOST)||!defined('DB_NAME')||1!==preg_match('/\Acetech_wp_opening_qualification(?:_[a-z0-9]+)?\z/D',DB_NAME)||'1'!==(string)get_option('cetech_opening_qualification_disposable')||!$wpdb instanceof wpdb||get_class($wpdb)!==wpdb::class||is_multisite()||get_current_blog_id()!==$config['site_id']||('hpos_on'===$config['mode'])!==Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled())throw new RuntimeException('Native private payment fixture mismatch.');
 foreach(get_included_files() as $file){if(str_ends_with(str_replace('\\','/',$file),'/tests/bootstrap.php'))throw new RuntimeException('Unit bootstrap prohibited.');}
 if(!isset($GLOBALS['wp_object_cache'])||get_class($GLOBALS['wp_object_cache'])!==WP_Object_Cache::class||is_file(WP_CONTENT_DIR.'/object-cache.php')||is_file(WP_CONTENT_DIR.'/db.php'))throw new RuntimeException('Native default cache required.');$result['default_native_cache']=true;
 $phase='installed_source';$installed=realpath(WP_CONTENT_DIR.'/plugins/cetech-woocommerce-delivery-engine');$reflection_root=dirname((string)(new ReflectionClass(CetechDeliveryEngine\Bootstrap\Plugin::class))->getFileName(),3);if(false===$installed||$installed!==realpath($config['plugin_root'])||$installed!==realpath($reflection_root)||!in_array(realpath($installed.'/vendor/autoload.php'),array_map('realpath',get_included_files()),true))throw new RuntimeException('Exact installed production autoload unavailable.');$map=[];foreach(['src','database'] as $directory){foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($installed.'/'.$directory,FilesystemIterator::SKIP_DOTS)) as $file){if($file->isFile()&&'php'===$file->getExtension())$map[substr($file->getPathname(),strlen($installed)+1)]=hash_file('sha256',$file->getPathname());}}foreach(['cetech-woocommerce-delivery-engine.php','uninstall.php'] as $name)$map[$name]=hash_file('sha256',$installed.'/'.$name);ksort($map,SORT_STRING);if(count($map)!==$config['php_map_count']||hash('sha256',json_encode($map,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR))!==$config['php_map_hash'])throw new RuntimeException('Installed production byte map mismatch.');$result['installed_production_map']=true;
 add_filter('pre_wp_mail','__return_true',PHP_INT_MAX);add_filter('action_scheduler_allow_async_request_runner','__return_false',PHP_INT_MAX);
 require_once __DIR__.'/opening-quote-placement-support.php';wp_set_current_user(0);wc_load_cart();$session=WC()->session;if(!$session instanceof WC_Session_Handler||get_class($session)!==WC_Session_Handler::class||[]!==WC()->cart->get_cart())throw new RuntimeException('Fresh empty native guest session unavailable.');$session_id=$session->get_customer_id();if(!is_string($session_id)||!str_starts_with($session_id,'t_')||strlen($session_id)>191||1!==preg_match('/\A[a-zA-Z0-9_]+\z/D',$session_id))throw new RuntimeException('New native session identity unavailable.');$existing=$wpdb->get_results($wpdb->prepare("SELECT session_id FROM `{$wpdb->prefix}woocommerce_sessions` WHERE session_key=%s LIMIT 2",$session_id),ARRAY_A);if([]!==$existing||''!==$wpdb->last_error)throw new RuntimeException('Private payment refuses an existing session.');$owned_session=true;
 $phase='session_lease';$lease=json_encode(['format'=>1,'site_id'=>$config['site_id'],'session_key'=>$session_id,'child_pid'=>getmypid(),'parent_nonce'=>$config['parent_nonce']],JSON_THROW_ON_ERROR);if(strlen($lease)!==file_put_contents($config['lease_path'],$lease,LOCK_EX)||(string)file_get_contents($config['lease_path'])!==$lease)throw new RuntimeException('Native session lease did not acknowledge.');$session->set_customer_session_cookie(true);
 $order=new WC_Order($config['order_id']);$package=(new CetechDeliveryEngine\Application\Order\OrderDeliverySnapshotReader())->read_package($order);$envelope=$package->delivery_quote?->envelope;
 if($order->get_id()!==$config['order_id']||0!==$order->get_customer_id()||$order->is_paid()||!hash_equals($order->get_order_key('edit'),$config['order_key'])||null===$envelope||!$envelope->is_promise()||hash('sha256',$envelope->to_private_json())!==$config['snapshot_digest'])throw new RuntimeException('Exact saved native unpaid order unavailable.');
 $_GET['key']=$config['order_key'];$completed=0;add_action('woocommerce_payment_complete',static function($id)use(&$completed,$config):void{if($id===$config['order_id'])++$completed;},20,1);
 if('order_pay'===$config['stimulus']){$_POST['woocommerce_pay']='1';$_POST['payment_method']=$config['method'];$gateway=new CetechQuotePlacementNativeGateway();add_filter('woocommerce_available_payment_gateways',static function(array $gateways)use($gateway):array{$gateways[$gateway->id]=$gateway;return $gateways;},10,1);// Reproduce the ordinary native GET payment form before its POST. The
 // shortcode loads the exact order's billing location into WC_Customer and
 // saves that native session; an untouched empty CLI session has no dirty row.
 $phase='native_payment_form';global $wp;$wp->query_vars['order-pay']=$order->get_id();$_GET['pay_for_order']='true';unset($_POST['woocommerce_pay'],$_POST['payment_method']);$form_html='';ob_start();try{WC_Shortcode_Checkout::output([]);}finally{$form_html=(string)ob_get_clean();}
 $session->save_data();$session_rows=$wpdb->get_results($wpdb->prepare("SELECT session_id,session_value FROM `{$wpdb->prefix}woocommerce_sessions` WHERE session_key=%s LIMIT 2",$session_id),ARRAY_A);$result['native_payment_form_session']=str_contains($form_html,'woocommerce-pay-nonce')&&[]===WC()->cart->get_cart()&&is_array($session_rows)&&1===count($session_rows)&&''===$wpdb->last_error&&($session_rows[0]['session_value']??null)===CetechDeliveryEngine\Integrations\DeliveryQuote\QuotePlacementRuntime::session_bytes($session);unset($form_html);if(!$result['native_payment_form_session'])throw new RuntimeException('Native payment form/session lifecycle unavailable.');$_POST['woocommerce_pay']='1';$_POST['payment_method']=$config['method'];
 $phase='native_admission';$container=CetechDeliveryEngine\Bootstrap\Plugin::instance()->container();$decision=$container->get(CetechDeliveryEngine\Integrations\EmergencyControl\EmergencyControlRuntime::class)->final_order_decision($order,'order_pay');$result['native_admission']=$decision->allowed;if(!$decision->allowed){$placement=$container->get(CetechDeliveryEngine\Integrations\DeliveryQuote\QuotePlacementRuntime::class);$result['refusal_code']=$decision->code;$result['saved_order_authorized']=$placement->authorize_saved_order($order);$result['saved_order_history_valid']=CetechDeliveryEngine\Application\Order\QuoteNativeOrderHistory::verify($order);$result['saved_order_fingerprint_available']=null!==$placement->fingerprint($order);$result['saved_tax_hooks_supported']=CetechDeliveryEngine\Application\DeliveryQuote\QuoteSavedOrderNativeEvidence::hooks_supported();$result['saved_capture_service_present']=null!==$container->get(CetechDeliveryEngine\Bootstrap\PromiseQuoteComposition::class)->capture_service();$result['saved_order_evidence_ready']=null!==$container->get(CetechDeliveryEngine\Application\DeliveryQuote\QuoteSavedOrderPlacementEvidenceReader::class)->read($order,CetechDeliveryEngine\Domain\Contracts\RequestContext::create());$result['saved_order_validate_ready']=$placement->validate_order($order,'order_pay');throw new RuntimeException('Native saved-order admission refused.');}$phase='native_gateway';$available=WC()->payment_gateways()->get_available_payment_gateways();$guarded=$available[$gateway->id]??null;if(!$guarded instanceof CetechDeliveryEngine\Integrations\DeliveryQuote\QuoteOrderPayGateway)throw new RuntimeException('Native guarded gateway unavailable.');$order->set_payment_method($guarded);$order->save();$guarded->validate_fields();$payment=$guarded->process_payment($order->get_id());$result['native_gateway_paid_once']=1===$gateway->native_payment_calls()&&1===$completed&&'success'===($payment['result']??null);}
 else{$phase='native_provider_callback';$order->payment_complete();$result['native_provider_callback']=1===$completed;}
 $fresh=new WC_Order($order->get_id());$paid=$fresh->get_date_paid();$result['persisted_paid']=$fresh->is_paid()&&$paid instanceof DateTimeInterface&&$paid->getTimestamp()>0;$result['status']=('order_pay'===$config['stimulus']?$result['native_gateway_paid_once']:$result['native_provider_callback'])&&$result['persisted_paid']?'PASS':'FAIL';
}catch(Throwable $error){$result['error_class']=in_array(get_class($error),['RuntimeException','Error','TypeError','JsonException','InvalidArgumentException','LogicException'],true)?get_class($error):'other';}finally{
 if($owned_session&&$session instanceof WC_Session_Handler&&is_string($session_id)){
  try{$session->destroy_session();remove_action('shutdown',[$session,'save_data'],20);$remaining=$wpdb->get_results($wpdb->prepare("SELECT session_id FROM `{$wpdb->prefix}woocommerce_sessions` WHERE session_key=%s LIMIT 2",$session_id),ARRAY_A);$result['session_cleanup']=[]===$remaining&&''===$wpdb->last_error;}catch(Throwable){$result['session_cleanup']=false;}
 }
 $result['phase']=$phase;if(!$result['session_cleanup'])$result['status']='FAIL';ob_end_clean();echo json_encode($result,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);
}
