<?php

declare(strict_types=1);
namespace CetechDeliveryEngine\Application\DeliveryQuote;
use CetechDeliveryEngine\Domain\CustomerContext\DeliveryAddress;
use CetechDeliveryEngine\Domain\DeliveryQuote\QuoteJson;
use CetechDeliveryEngine\Domain\DeliveryQuote\QuoteShape;
use CetechDeliveryEngine\Domain\DeliveryQuote\QuoteOwner;
use CetechDeliveryEngine\Infrastructure\WooCommerce\Shipping\SelectedOfferShippingMethod;
/** Real already-calculated Woo cart capture. Never recalculates cart totals or writes an order. */
final class QuoteNativeWooSource implements QuoteNativeCaptureSource, \JsonSerializable {
 public const OPTIONS=['woocommerce_currency','woocommerce_price_num_decimals','woocommerce_calc_taxes','woocommerce_prices_include_tax','woocommerce_tax_round_at_subtotal','woocommerce_shipping_tax_class','woocommerce_tax_classes','woocommerce_default_country','woocommerce_default_customer_address','woocommerce_tax_based_on','woocommerce_store_address','woocommerce_store_address_2','woocommerce_store_city','woocommerce_store_postcode'];
 private array $objects=[];private ?string $binding=null;private ?object $wc=null;private int $user=0;private int $site=0;private array $option_names=[];
 public function current_owner():QuoteOwner{return (new QuoteNativeOwnerResolver())->current();}
 public function capture():QuoteNativeState {
  $owner=$this->current_owner();$identity_keys=QuoteNativeContextIdentity::from_server();if($identity_keys->key_epoch()!==$owner->key_epoch()){self::refuse();}$wc=WC();$cart=$wc->cart??null;$customer=$wc->customer??null;$session=$wc->session??null;
  if(!$cart instanceof \WC_Cart||get_class($cart)!=='WC_Cart'||!$customer instanceof \WC_Customer||get_class($customer)!=='WC_Customer'||get_class($session)!=='WC_Session_Handler'||!$cart->has_calculated_shipping()){self::refuse();}
  $this->wc=$wc;if(!self::hooks_supported(self::OPTIONS)){self::refuse();}$this->site=get_current_blog_id();$this->user=get_current_user_id();$shipping=$wc->shipping();$packages=$shipping->get_packages();$selected=$cart->get_shipping_methods();
  if(!is_array($packages)||[]===$packages||count($packages)>200||!is_array($selected)||count($selected)!==count($packages)){self::refuse();}
  $this->objects=[$cart,$customer,$session,$shipping];foreach($packages as $package){foreach($package['contents']??[] as $line){$product=$line['data']??null;if(!is_object($product)||!in_array(get_class($product),['WC_Product_Simple','WC_Product_Variation','WC_Product_Variable','WC_Product_Grouped','WC_Product_External'],true)){self::refuse();}}}if(!method_exists($cart,'get_fees')||[]!==$cart->get_fees()){self::refuse();}if(method_exists($cart,'fees_api')){$this->objects[]=$cart->fees_api();}$methods=[];$instances=[];$members=[];
  foreach($selected as $index=>$rate){if(!$rate instanceof \WC_Shipping_Rate||get_class($rate)!=='WC_Shipping_Rate'||$rate->get_method_id()!==SelectedOfferShippingMethod::METHOD_ID){self::refuse();}$instance=$rate->get_instance_id();if(!is_int($instance)||$instance<0){self::refuse();}
   $instance_name=$instance>0?'woocommerce_'.SelectedOfferShippingMethod::METHOD_ID.'_'.$instance.'_settings':'woocommerce_'.SelectedOfferShippingMethod::METHOD_ID.'_settings';if(!self::hooks_supported([$instance_name])){self::refuse();}
   $method=$instance>0?\WC_Shipping_Zones::get_shipping_method($instance):($shipping->get_shipping_methods()[SelectedOfferShippingMethod::METHOD_ID]??null);
   if(!$method instanceof SelectedOfferShippingMethod||!in_array($method->tax_status,['taxable','none'],true)){self::refuse();}$methods[$index]=$method;$instances[]=$instance;$this->objects[]=$rate;$this->objects[]=$method;
  }
  $precision=wc_get_price_decimals();$internal=wc_get_rounding_precision();if(!is_int($precision)||$precision<0||$precision>6||!is_int($internal)||$internal<0||$internal>6){self::refuse();}
  $currency=get_woocommerce_currency();if(!is_string($currency)||preg_match('/\A[A-Z]{3}\z/D',$currency)!==1){self::refuse();}
  $class=get_option('woocommerce_shipping_tax_class','inherit');if(!is_string($class)){self::refuse();}
  if('inherit'===$class){$classes=$cart->get_cart_item_tax_classes_for_shipping();if(!is_array($classes)){self::refuse();}if([]===$classes){self::refuse();}elseif(in_array('', $classes,true)){$class='';}elseif(count($classes)===1){$class=(string)reset($classes);}else{self::refuse();}}
  $location=\WC_Tax::get_tax_location($class,$customer);if(!is_array($location)||count($location)!==4){self::refuse();}foreach($location as $part){if(!is_string($part)||strlen($part)>256){self::refuse();}}
  $names=self::OPTIONS;foreach(array_unique($instances) as $instance){$names[]=$instance>0?'woocommerce_'.SelectedOfferShippingMethod::METHOD_ID.'_'.$instance.'_settings':'woocommerce_'.SelectedOfferShippingMethod::METHOD_ID.'_settings';}sort($names,SORT_STRING);$this->option_names=$names;
  $selectors=['option_names'=>$names,'tax_class'=>$class,'method_instance_ids'=>array_values(array_unique($instances)),'session_key'=>$session->get_customer_id(),'customer_id'=>$this->user];sort($selectors['method_instance_ids'],SORT_NUMERIC);
  $before=QuoteNativeReceiptGuard::read_physical($selectors);foreach($methods as $method){$name=$method->instance_id>0?'woocommerce_'.SelectedOfferShippingMethod::METHOD_ID.'_'.$method->instance_id.'_settings':'woocommerce_'.SelectedOfferShippingMethod::METHOD_ID.'_settings';$settings=null;foreach($before['option_rows'] as $row){if($row['option_name']===$name){$settings=self::physical_settings($row['option_value']);break;}}if(null!==$settings&&!is_array($settings)){self::refuse();}if($method->tax_status!==($settings['tax_status']??'taxable')){self::refuse();}if($method->instance_id>0){$matched=false;foreach($before['method_rows'] as $row){if((int)$row['instance_id']===$method->instance_id&&$row['method_id']===SelectedOfferShippingMethod::METHOD_ID&&$row['is_enabled']==='1'){$matched=true;}}if(!$matched){self::refuse();}}}
  foreach($before['option_rows'] as $row){$name=$row['option_name'];$effective=get_option($name,null);if(self::option_storage($effective)!==$row['option_value']){self::refuse();}}
  if(get_option('woocommerce_currency')!==$currency||(int)get_option('woocommerce_price_num_decimals',2)!==$precision){self::refuse();}
  $unsupported=!self::hooks_supported($names);$exempt=$customer->get_is_vat_exempt();if(!is_bool($exempt)){self::refuse();}$enabled=wc_tax_enabled();$rounding='yes'===get_option('woocommerce_tax_round_at_subtotal')?'subtotal':'per_line';
  if(!class_exists('WC_Cache_Helper')){self::refuse();}\WC_Cache_Helper::invalidate_cache_group('taxes');if(function_exists('wp_cache_delete')){wp_cache_delete('tax-rate-classes','taxes');}\WC_Tax::init();$native_rates=\WC_Tax::get_shipping_tax_rates(null,$customer);if(!is_array($native_rates)||count($native_rates)>200){self::refuse();}
  $captured=[];$destination=null;
  foreach($packages as $index=>$package){$rate=$selected[$index]??null;$method=$methods[$index]??null;$meta=$package['cetech_de']??null;$group=is_array($meta)?($meta['group_id']??null):null;
   if(!is_string($group)||''===$group||!isset($package['rates'][$rate->get_id()])||$package['rates'][$rate->get_id()]!==$rate||!is_array($package['contents']??null)||[]===$package['contents']||!is_array($package['destination']??null)){self::refuse();}
   if(($rate->get_meta_data()['cetech_de_group_id']??null)!==$group||$rate->get_tax_status()!==$method->tax_status||$rate->get_id()!==$method->get_rate_id(substr(hash('sha256',$group),0,12))){self::refuse();}
   $address=DeliveryAddress::fromInput($package['destination']);if(!$address->isComplete()){self::refuse();}$identity=$identity_keys->destination_digest($owner->site_id(),$package['destination']);if(null!==$destination&&!hash_equals($destination,$identity)){self::refuse();}$destination=$identity;
   $cost=self::native_decimal($rate->get_cost());$taxes=$rate->get_taxes();if(!is_array($taxes)||count($taxes)>200){self::refuse();}
   $fresh=$enabled&&!$exempt&&'taxable'===$method->tax_status&&(float)$cost>0?\WC_Tax::calc_shipping_tax((float)$cost,$native_rates):[];
   $tax_array=self::taxes($taxes);$fresh_array=self::taxes($fresh);$sum=0.0;foreach($taxes as $amount){$sum+='per_line'===$rounding?wc_round_tax_total($amount,$precision):(float)$amount;}$rounded=wc_round_tax_total($sum,$precision);
   $line_members=[];foreach($package['contents'] as $key=>$line){if(!is_string($key)||!is_array($line)||!is_int($line['product_id']??null)||!isset($line['quantity'])){self::refuse();}$var=$line['variation_id']??0;if(!is_int($var)||$var<0){self::refuse();}$line_members[]=['line_key'=>$key,'product_id'=>$line['product_id'],'variation_id'=>$var>0?$var:null,'quantity'=>self::native_decimal($line['quantity'])];if(isset($line['data'])&&is_object($line['data'])){$this->objects[]=$line['data'];}}
   $captured[]=['group_id'=>$group,'rate_id'=>$rate->get_id(),'method_id'=>$rate->get_method_id(),'instance_id'=>$rate->get_instance_id(),'tax_status'=>$rate->get_tax_status(),'label'=>$rate->get_label(),'cost'=>$cost,'taxes'=>$tax_array,'fresh_taxes'=>$fresh_array,'rounded_tax'=>wc_format_decimal($rounded,$precision),'display_total'=>wc_format_decimal((float)$cost+$rounded,$precision),'members'=>$line_members];
  }
  $after=QuoteNativeReceiptGuard::read_physical($selectors);if(QuoteJson::encode($before)!==QuoteJson::encode($after)){self::refuse();}
  $facts=['currency'=>$currency,'display_precision'=>$precision,'internal_precision'=>$internal,'exempt'=>$exempt,'tax_class'=>$class,'location_digest'=>$identity_keys->tax_location_digest($owner->site_id(),$location),'destination_digest'=>$destination,'key_epoch'=>$owner->key_epoch(),'rounding'=>$rounding,'tax_enabled'=>$enabled,'coupons'=>count($cart->get_applied_coupons()),'unsupported_effects'=>$unsupported,'cart_shipping_total'=>self::native_decimal($cart->get_shipping_total()),'cart_shipping_tax'=>self::native_decimal($cart->get_shipping_tax()),'packages'=>$captured,'source_facts'=>$before];
  $this->binding=$this->raw_binding();return QuoteNativeState::from_array($facts);
 }
 private static function taxes(array $taxes):array{$out=[];foreach($taxes as $id=>$amount){if((!is_int($id)&&!(is_string($id)&&ctype_digit($id)))||(int)$id<1){self::refuse();}$out[]=['rate_id'=>(int)$id,'amount'=>self::native_decimal($amount)];}usort($out,static fn(array $a,array $b):int=>$a['rate_id']<=>$b['rate_id']);return $out;}
 public static function native_decimal(mixed $value):string {if(!is_int($value)&&!is_float($value)&&!is_string($value)){self::refuse();}if(is_float($value)&&(!is_finite($value)||$value<0)){self::refuse();}if(is_string($value)&&preg_match('/\A(?:0|[1-9][0-9]{0,11})(?:\.[0-9]{1,6})?\z/D',$value)!==1){self::refuse();}$decimal=wc_format_decimal($value,false);return QuoteNativeState::decimal($decimal);}
 public function unchanged():bool {try{return null!==$this->binding&&$this->wc===($GLOBALS['woocommerce']??null)&&$this->site===(int)($GLOBALS['blog_id']??1)&&$this->user===self::raw_user_id()&&hash_equals($this->binding,$this->raw_binding());}catch(\Throwable){return false;}}
 /** Reflection reads only already-loaded raw values; never invokes Woo getters or filters. */
 private static function raw_user_id():int{$user=$GLOBALS['current_user']??null;if(!is_object($user)){self::refuse();}$r=new \ReflectionObject($user);if(!$r->hasProperty('ID')){self::refuse();}$p=$r->getProperty('ID');$id=method_exists($p,'getRawValue')?$p->getRawValue($user):$p->getValue($user);if(!is_int($id)){self::refuse();}return $id;}
 private function raw_binding():string {$data=['native_refs'=>$this->native_refs(),'native_cookies'=>$this->cookie_binding()];$nodes=0;$seen=[];foreach($this->objects as $i=>$object){$data['object_'.$i]=self::raw_object($object,0,$nodes,$seen);} $data['hooks']=self::hook_facts();foreach($this->option_names as $name){foreach(['pre_option_'.$name,'option_'.$name,'default_option_'.$name] as $hook){$data['option_hooks'][$hook]=self::option_hook_binding($hook);}}$data['option_hooks']['pre_option']=self::option_hook_binding('pre_option');$data['option_hooks']['default_option']=self::option_hook_binding('default_option');return hash('sha256',QuoteJson::encode($data));}
 private function cookie_binding():array{$names=[];if(defined('LOGGED_IN_COOKIE')){$names[]=(string)constant('LOGGED_IN_COOKIE');}foreach($this->objects as $object){if(!$object instanceof \WC_Session_Handler){continue;}$r=new \ReflectionObject($object);if(!$r->hasProperty('_cookie')){self::refuse();}$p=$r->getProperty('_cookie');$name=method_exists($p,'getRawValue')?$p->getRawValue($object):$p->getValue($object);if(!is_string($name)){self::refuse();}$names[]=$name;}$out=[];foreach($names as $name){$value=$_COOKIE[$name]??null;if(null!==$value&&(!is_string($value)||strlen($value)>4096)){self::refuse();}$out[$name]=null===$value?null:hash('sha256',$value);}return $out;}
 private function native_refs():array{$out=[];if(null===$this->wc){self::refuse();}foreach(['cart','customer','session','countries'] as $name){$r=new \ReflectionObject($this->wc);if(!$r->hasProperty($name)){self::refuse();}$p=$r->getProperty($name);if(!$p->isInitialized($this->wc)){self::refuse();}$value=method_exists($p,'getRawValue')?$p->getRawValue($this->wc):$p->getValue($this->wc);if(!is_object($value)){self::refuse();}$out[$name]=['class'=>get_class($value),'object'=>spl_object_id($value)];}$p=new \ReflectionProperty('WC_Shipping','_instance');$shipping=method_exists($p,'getRawValue')?$p->getRawValue():$p->getValue();if(!is_object($shipping)){self::refuse();}$out['shipping']=['class'=>get_class($shipping),'object'=>spl_object_id($shipping)];return $out;}
 private static function raw_object(object $object,int $depth,int &$nodes,array &$seen):array {if($depth>12||++$nodes>4096){self::refuse();}$id=spl_object_id($object);if(isset($seen[$id])){return ['reference'=>$id];}$seen[$id]=true;$class=get_class($object);$out=['class'=>$class,'object'=>$id];foreach(['data','changes','fees','cart_contents','totals','shipping_methods','applied_coupons','has_calculated_shipping','packages','_data','_customer_id','_cookie','_has_cookie','_session_expiration','_session_expiring','meta_data','current_data','instance_settings','settings','tax_status','enabled','instance_id'] as $name){$reflection=new \ReflectionObject($object);while($reflection&&!$reflection->hasProperty($name)){$reflection=$reflection->getParentClass();}if(!$reflection){continue;}$property=$reflection->getProperty($name);if(!$property->isInitialized($object)){self::refuse();}$out[$name]=self::raw_value((method_exists($property,'getRawValue')?$property->getRawValue($object):$property->getValue($object)),$depth+1,$nodes,$seen);}return $out;}
 private static function raw_value(mixed $value,int $depth,int &$nodes,array &$seen):mixed {if($depth>12||++$nodes>4096){self::refuse();}if(is_array($value)){$out=[];foreach($value as $key=>$item){$out[$key]=self::raw_value($item,$depth+1,$nodes,$seen);}if(!array_is_list($out)){$mapped=[];foreach($out as $key=>$item){$mapped[(is_int($key)?'i:':'s:').$key]=$item;}$out=$mapped;ksort($out,SORT_STRING);}return $out;}if(is_object($value)){if($value instanceof \WC_Product||$value instanceof \WC_Shipping_Rate||$value instanceof \WC_Shipping_Method||$value instanceof \WC_Meta_Data){return self::raw_object($value,$depth+1,$nodes,$seen);}if(in_array(get_class($value),['DateTime','DateTimeImmutable','WC_DateTime'],true)){return ['date_type'=>get_class($value),'date'=>self::raw_value((array)$value,$depth+1,$nodes,$seen)];}self::refuse();}if(is_float($value)){return ['native_float'=>sprintf('%.14F',$value)];}if(is_string($value)||is_int($value)||is_bool($value)||null===$value){return $value;}self::refuse();}
 private static function native_callbacks(object $entry):array{$r=new \ReflectionObject($entry);if(!$r->hasProperty('callbacks')){self::refuse();}$p=$r->getProperty('callbacks');if($p->getDeclaringClass()->getName()!=='WP_Hook'||!$p->isInitialized($entry)){self::refuse();}$raw=method_exists($p,'getRawValue')?$p->getRawValue($entry):$p->getValue($entry);if(!is_array($raw)){self::refuse();}return $raw;}
 private static function option_hook_binding(string $hook):array{$entry=$GLOBALS['wp_filter'][$hook]??null;if(null===$entry){return [];}if(!is_object($entry)||!property_exists($entry,'callbacks')){return ['unknown'=>true];}$out=[];foreach(self::native_callbacks($entry) as $priority=>$items){foreach($items as $item){$call=$item['function']??null;$out[]=['priority'=>(int)$priority,'accepted_args'=>(int)($item['accepted_args']??1),'callable'=>is_object($call)?spl_object_id($call):(is_array($call)&&count($call)===2&&(is_object($call[0])||is_string($call[0]))&&is_string($call[1])?hash('sha256',get_debug_type($call[0]).':'.(is_object($call[0])?spl_object_id($call[0]):(string)$call[0]).':'.(string)$call[1]):(is_string($call)?$call:'unknown'))];}}return $out;}
 private static function hook_facts():array {$out=[];foreach(self::hooks() as $hook){$entry=$GLOBALS['wp_filter'][$hook]??null;if(null===$entry){$out[$hook]=[];continue;}$callbacks=self::native_callbacks($entry);$facts=[];foreach($callbacks as $priority=>$items){foreach($items as $item){if(!is_array($item)||!is_int($item['accepted_args']??null)){$facts[]=['priority'=>(int)$priority,'unknown'=>true,'accepted_args'=>-1];continue;}$call=$item['function']??null;if(is_array($call)&&count($call)===2&&(is_object($call[0])||is_string($call[0]))&&is_string($call[1])){$facts[]=['priority'=>(int)$priority,'class'=>is_object($call[0])?get_class($call[0]):(string)$call[0],'method'=>(string)$call[1],'object'=>is_object($call[0])?spl_object_id($call[0]):0,'accepted_args'=>(int)($item['accepted_args']??1)];}elseif(is_string($call)){$facts[]=['priority'=>(int)$priority,'function'=>$call,'accepted_args'=>(int)($item['accepted_args']??1)];}else{$facts[]=['priority'=>(int)$priority,'unknown'=>true,'accepted_args'=>(int)($item['accepted_args']??1)];}}}$out[$hook]=$facts;}return $out;}
 private static function hooks():array {return ['salt','woocommerce_settings_api_get_option','woocommerce_get_cart_contents','woocommerce_cart_shipping_packages','woocommerce_shipping_packages','woocommerce_shipping_methods','woocommerce_shipping_rate_id','woocommerce_shipping_rate_method_id','woocommerce_shipping_rate_instance_id','woocommerce_shipping_rate_label','woocommerce_currency','wc_get_price_decimals','woocommerce_internal_rounding_precision','woocommerce_shipping_prices_include_tax','woocommerce_shipping_method_add_rate_args','woocommerce_shipping_method_add_rate','woocommerce_shipping_rate_cost','woocommerce_shipping_rate_taxes','woocommerce_shipping_rate_tax_status','woocommerce_get_shipping_tax','woocommerce_calc_shipping_tax','woocommerce_calc_tax','woocommerce_tax_round','wc_round_tax_total','woocommerce_customer_get_is_vat_exempt','woocommerce_customer_get_shipping_country','woocommerce_customer_get_shipping_state','woocommerce_customer_get_shipping_city','woocommerce_customer_get_shipping_postcode','woocommerce_customer_get_billing_country','woocommerce_customer_get_billing_state','woocommerce_customer_get_billing_city','woocommerce_customer_get_billing_postcode','woocommerce_apply_base_tax_for_local_pickup','woocommerce_local_pickup_methods','woocommerce_product_get_tax_status','woocommerce_product_get_tax_class','woocommerce_product_variation_get_tax_status','woocommerce_product_variation_get_tax_class','woocommerce_customer_taxable_address','woocommerce_get_tax_location','woocommerce_shipping_tax_class','woocommerce_matched_rates','woocommerce_find_rates','woocommerce_rate_compound','woocommerce_cart_get_shipping_total','woocommerce_cart_get_shipping_tax','woocommerce_calculated_total','woocommerce_calculate_totals','woocommerce_before_calculate_totals','woocommerce_after_calculate_totals','woocommerce_package_rates'];}
 private static function physical_settings(string $bytes):array{if(!str_starts_with($bytes,'a:')){self::refuse();}$value=unserialize($bytes,['allowed_classes'=>false]);if(!is_array($value)){self::refuse();}$nodes=0;self::option_value($value,0,$nodes);return $value;}
 /** Matches native WordPress scalar caching to the exact serialized storage bytes. */
 private static function option_storage(mixed $value):string {$nodes=0;self::option_value($value,0,$nodes);if(is_array($value)){return serialize($value);}if(is_string($value)&&function_exists('is_serialized')&&is_serialized($value,false)){return serialize($value);}return (string)$value;}
 private static function option_value(mixed $value,int $depth,int &$nodes):void {if($depth>8||++$nodes>512){self::refuse();}if(is_array($value)){foreach($value as $key=>$item){if(!is_int($key)&&!is_string($key)){self::refuse();}self::option_value($item,$depth+1,$nodes);}return;}if(!is_string($value)&&!is_int($value)&&!is_bool($value)&&null!==$value){self::refuse();}}
 private static function hooks_supported(array $names):bool {
  $allowed=[
   'woocommerce_cart_shipping_packages'=>[['CetechDeliveryEngine\\Application\\Shipping\\ShippingPackageBuilder::filter_packages',20,1],['CetechDeliveryEngine\\Integrations\\EmergencyControl\\EmergencyControlRuntime::decorate_packages',PHP_INT_MAX,1]],
   'woocommerce_shipping_methods'=>[['CetechDeliveryEngine\\Application\\Shipping\\SelectedOfferShippingIntegration::register_shipping_method',10,1]],
   'woocommerce_package_rates'=>[['CetechDeliveryEngine\\Application\\Shipping\\SelectedOfferShippingIntegration::filter_managed_package_rates',100,2],['CetechDeliveryEngine\\Integrations\\EmergencyControl\\EmergencyCheckoutHooks::package_rates',PHP_INT_MAX,2]],
   'woocommerce_before_calculate_totals'=>[['CetechDeliveryEngine\\Application\\Cart\\CartDeliverySelectionReconciler::reconcile_cart',5,1]],
   // Pinned Woo11.1.2 wc-core-functions.php registers this pure native label sanitizer.
   'woocommerce_shipping_rate_label'=>[['sanitize_text_field',10,1]],
  ];
  foreach(self::hook_facts() as $hook=>$items){foreach($items as $item){$key=$item['function']??(($item['class']??'').'::'.($item['method']??''));$tuple=[$key,$item['priority'],$item['accepted_args']??1];if(!in_array($tuple,$allowed[$hook]??[],true)){return false;}}}
  foreach($names as $name){foreach(['pre_option_'.$name,'option_'.$name,'default_option_'.$name] as $hook){if(function_exists('has_filter')&&false!==has_filter($hook)){return false;}}}return !function_exists('has_filter')||(false===has_filter('pre_option')&&false===has_filter('default_option'));
 }
 public function jsonSerialize():never{throw new \LogicException('Native quote capture state is private.');}
 public function __serialize():never{throw new \LogicException('Native quote capture state is private.');}
 public function __unserialize(array $data):never{throw new \LogicException('Native quote capture state cannot be reconstructed generically.');}
 private static function refuse():never {throw new \RuntimeException('Native quote context unavailable.');}
}
