<?php

declare(strict_types=1);
namespace CetechDeliveryEngine\Tests\Unit\ServicePromise\Handoff;

use CetechDeliveryEngine\Domain\DeliveryQuote\{DeliveryQuote, QuoteContext, QuoteHeader, QuoteJson, QuoteStoredRow, QuoteTerms, QuoteTime};
use CetechDeliveryEngine\Domain\ServicePromise\{PromiseInput, PromiseJson, PromiseResult};
use CetechDeliveryEngine\Domain\ServicePromise\Handoff\{PromiseHistoricalPacket, PromiseQuotePacket};
use CetechDeliveryEngine\Tests\Support\DeliveryQuote\QuoteFixtures;
use CetechDeliveryEngine\Tests\Support\ServicePromise\Calculation\CalculationFixture;
use CetechDeliveryEngine\Tests\Support\ServicePromise\Handoff\PromiseHandoffFixture as F;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

require_once dirname( __DIR__, 3 ) . '/Support/ServicePromise/Handoff/PromiseHandoffFixture.php';

final class PromiseQuoteHandoffTest extends TestCase {
	public function test_v1_base_bytes_and_digest_domains_remain_identical(): void {
		$base = F::base_context(); $terms = F::base_terms(); $context = F::context(); $forward = F::terms();
		self::assertSame( $base->to_private_json(), $context->base_context()->to_private_json() ); self::assertSame( $terms->to_private_json(), $forward->base_terms()->to_private_json() );
		self::assertSame( hash( 'sha256', 'cetech-quote-material-v1:' . $base->to_private_json() ), $base->digest() ); self::assertSame( hash( 'sha256', 'cetech-quote-terms-v1:' . $terms->to_private_json() ), $terms->digest() );
		self::assertSame( $base->digest(), $context->base_material_digest() ); self::assertNotSame( $base->digest(), $context->digest() ); self::assertSame( $base, $base->base_context() ); self::assertSame( $terms, $terms->base_terms() ); self::assertNull( $terms->promise_packet() );
		$header = F::header( $base, $terms, 'legacy_fixed_base_v1' ); self::assertSame( 1, $header->format_version() ); self::assertSame( hash( 'sha256', 'cetech-quote-body-v1:' . QuoteJson::encode( [ 'context' => $base->private_facts(), 'terms' => $terms->private_facts() ] ) ), $header->body_digest() );
	}
	public function test_v2_binds_capture_results_and_retains_original_money_providers(): void {
		$quote = F::quote(); $header = $quote->header(); $context = $quote->context(); $terms = $quote->terms();
		self::assertSame( [ 2, 2, 2 ], [ $header->format_version(), $context->format_version(), $terms->format_version() ] ); self::assertSame( 'service_promise_v1', $header->profile() ); self::assertSame( 300000000, $header->expires_at()->epoch_microseconds() - $header->created_at()->epoch_microseconds() );
		self::assertSame( F::base_terms()->private_facts()['groups'], $terms->private_facts()['groups'] ); self::assertSame( hash( 'sha256', 'cetech-quote-body-v2:' . QuoteJson::encode( [ 'context' => $context->private_facts(), 'terms' => $terms->private_facts() ] ) ), $header->body_digest() );
		self::assertNull( $quote->reason_at( F::time() ) ); $terms->promise_packet()->assert_quote_capture( $header, $context ); self::assertSame( F::packet()->customer_text(), $terms->promise_packet()->group( F::input()->private_facts()['material']['group_id'] )->customer_text() );
	}
	public function test_new_and_retained_stored_rows_are_exact_and_detached(): void {
		$row = F::row( 'accepted' ); $hydrated = QuoteStoredRow::from_row( $row ); self::assertSame( $row, $hydrated->row() ); self::assertSame( 2, $hydrated->header()->format_version() ); self::assertSame( F::time()->plus_seconds( 1 )->sql(), $hydrated->accepted_at()->sql() );
		$row['format_version'] = 1; $this->expectException( \InvalidArgumentException::class ); QuoteStoredRow::from_row( $row );
	}
	public function test_historical_decode_preserves_removed_timezone_and_runtime_without_live_validation(): void {
		$facts = F::packet()->private_facts(); $input = PromiseJson::decode( $facts['input_json'] ); $result = PromiseJson::decode( $facts['result_json'] ); $input['policy']['promise_timezone'] = 'Removed/Historical_Zone'; $input['runtime']['timezone_data_version'] = 'historic-tz-release'; $result['input'] = $input; $result['body']['display_timezone'] = 'Removed/Historical_Zone';
		$facts['input_json'] = PromiseJson::encode( $input ); $facts['input_digest'] = hash( 'sha256', 'cetech-service-promise-input-v1:' . $facts['input_json'] ); $result['input_digest'] = $facts['input_digest']; $facts['result_json'] = PromiseJson::encode( $result ); $facts['result_digest'] = hash( 'sha256', 'cetech-service-promise-result-v1:' . $facts['result_json'] ); $facts['public_views'][0]['fields']['display_timezone'] = 'Removed/Historical_Zone';
		$packet = PromiseHistoricalPacket::from_array( $facts ); self::assertSame( $facts['input_json'], $packet->private_facts()['input_json'] ); self::assertSame( 'Removed/Historical_Zone', $packet->public_facts()['views'][0]['display_timezone'] ); self::assertSame( 'historic-tz-release', $packet->input_facts()['runtime']['timezone_data_version'] ); self::assertTrue( $packet->feasibility_at( F::time() ) );
		$this->expectException( \InvalidArgumentException::class ); PromiseInput::from_array( $input );
	}
	public function test_payment_anchored_original_stays_relative_and_honest(): void {
		$input = F::input( [ 'anchor' => 'payment_confirmed', 'late_payment_rule' => 'relative_after_payment' ] ); $packet = F::packet( F::result( $input ) ); self::assertSame( 'relative_window', $packet->result_facts()['state'] ); self::assertSame( 'after_payment_confirmation', $packet->public_facts()['views'][0]['relative_explanation'] ); self::assertArrayNotHasKey( 'from', $packet->public_facts()['views'][0] ); self::assertSame( $packet->to_private_json(), PromiseHistoricalPacket::from_json( $packet->to_private_json() )->to_private_json() );
	}
	public function test_optional_refusal_freezes_no_fake_window_and_required_refusal_is_denied(): void {
		$input = F::input( [ 'promise_required' => false ] ); $result = PromiseResult::from_array( [ 'format_version' => 1, 'state' => 'unavailable', 'input' => $input->private_facts(), 'input_digest' => $input->digest(), 'graph_digest' => $input->policy()->graph()->digest(), 'body' => null, 'reason_codes' => [ 'estimate_unavailable' ] ] ); $packet = PromiseHistoricalPacket::capture( $result, 'Delivery estimate unavailable' );
		self::assertSame( 'unavailable', $packet->public_facts()['views'][0]['state'] ); self::assertArrayNotHasKey( 'from', $packet->public_facts()['views'][0] ); self::assertArrayNotHasKey( 'min', $packet->public_facts()['views'][0] ); self::assertTrue( F::terms( $packet )->feasibility_at( F::time()->plus_seconds( 299 ) ) );
		$required = F::input(); $result = PromiseResult::from_array( [ 'format_version' => 1, 'state' => 'ineligible', 'input' => $required->private_facts(), 'input_digest' => $required->digest(), 'graph_digest' => $required->policy()->graph()->digest(), 'body' => null, 'reason_codes' => [ 'outside_service_window' ] ] ); $this->expectException( \InvalidArgumentException::class ); PromiseHistoricalPacket::capture( $result, 'Delivery unavailable' );
	}
	public function test_acceptance_deadline_is_exclusive_and_replay_preserves_original_history(): void {
		$input = F::input( [ 'anchor' => 'order_accepted' ], F::time()->plus_seconds( 60 )->sql() ); $quote = F::quote( $input ); self::assertTrue( $quote->usable_at( F::time()->plus_seconds( 59 ) ) ); self::assertSame( 'quote_unavailable', $quote->reason_at( F::time()->plus_seconds( 60 ) ) ); self::assertTrue( $quote->header()->valid_at( F::time()->plus_seconds( 60 ) ) );
		$h = $quote->header(); $ref = QuoteFixtures::reference( $h->id() ); $accepted = $quote->accept( F::owner(), $ref, $quote->context(), F::time()->plus_seconds( 59 ), 1, $h->body_digest(), $h->expires_at() ); self::assertSame( $accepted, $accepted->accept( F::owner(), $ref, $quote->context(), F::time()->plus_seconds( 3600 ), 1, $h->body_digest(), $h->expires_at() ) ); self::assertSame( $quote->terms()->to_private_json(), $accepted->terms()->to_private_json() );
	}
	public function test_capture_endpoint_deadlines_are_original_and_exclusive(): void {
		$input = F::input()->private_facts(); $input['policy']['graph']['components'][0]['duration']['min'] = 1; $input['policy']['graph']['components'][0]['duration']['max'] = 1; $packet = F::packet( F::result( PromiseInput::from_array( $input ) ) ); self::assertTrue( $packet->feasibility_at( F::time()->plus_seconds( 60 ) ) ); self::assertFalse( $packet->feasibility_at( QuoteTime::from_epoch_microseconds( F::time()->epoch_microseconds() + 60000001 ) ) ); self::assertFalse( $packet->feasibility_at( F::time()->plus_seconds( -1 ) ) ); self::assertFalse( F::packet()->feasibility_at( F::time()->plus_seconds( 300 ) ) );
	}
	public function test_capacity_and_policy_deadlines_are_exclusive_without_renewing_price_ttl(): void {
		$input = F::input( [ 'capacity_mode' => 'required', 'capacity_source' => CalculationFixture::source( 'capacity' ), 'effective_until' => F::time()->plus_seconds( 90 )->sql() ] )->private_facts(); $input['capacity']['valid_until'] = F::time()->plus_seconds( 60 )->sql(); $packet = F::packet( F::result( PromiseInput::from_array( $input ) ) ); self::assertTrue( $packet->feasibility_at( F::time()->plus_seconds( 59 ) ) ); self::assertFalse( $packet->feasibility_at( F::time()->plus_seconds( 60 ) ) ); self::assertSame( F::time()->plus_seconds( 300 )->sql(), $packet->input_facts()['anchor']['quote_expires_at'] );
		$packet = F::packet( F::result( F::input( [ 'effective_until' => F::time()->plus_seconds( 45 )->sql() ] ) ) ); self::assertTrue( $packet->feasibility_at( F::time()->plus_seconds( 44 ) ) ); self::assertFalse( $packet->feasibility_at( F::time()->plus_seconds( 45 ) ) );
	}
	#[DataProvider( 'historical_structure_changes' )]
	public function test_recomputed_checksums_cannot_bypass_closed_historical_structure( string $change ): void {
		$facts = F::packet()->private_facts(); $input = PromiseJson::decode( $facts['input_json'] ); $result = PromiseJson::decode( $facts['result_json'] );
		match ( $change ) { 'input-extra' => $input['unknown'] = true, 'policy-extra' => $input['policy']['unknown'] = true, 'runtime-extra' => $input['runtime']['unknown'] = true, 'source-changed' => $input['source_receipts'][0]['version'] = 2, 'ttl-changed' => $input['anchor']['quote_expires_at'] = F::time()->plus_seconds( 301 )->sql(), 'result-extra' => $result['unknown'] = true, 'terminal-changed' => $result['body']['terminal_windows'][0]['component_id'] = 'foreign', 'window-reversed' => $result['body']['terminal_windows'][0]['until'] = F::time()->sql() };
		$facts['input_json'] = PromiseJson::encode( $input ); $facts['input_digest'] = hash( 'sha256', 'cetech-service-promise-input-v1:' . $facts['input_json'] ); $result['input'] = $input; $result['input_digest'] = $facts['input_digest']; $facts['result_json'] = PromiseJson::encode( $result ); $facts['result_digest'] = hash( 'sha256', 'cetech-service-promise-result-v1:' . $facts['result_json'] );
		$this->expectException( \InvalidArgumentException::class ); PromiseHistoricalPacket::from_array( $facts );
	}
	public static function historical_structure_changes(): array { return array_map( static fn( string $change ): array => [ $change ], [ 'input-extra', 'policy-extra', 'runtime-extra', 'source-changed', 'ttl-changed', 'result-extra', 'terminal-changed', 'window-reversed' ] ); }
	public function test_typed_capture_and_history_require_canonical_terminal_and_public_view_order(): void {
		$a = CalculationFixture::component( 'alpha' ); $z = CalculationFixture::component( 'zulu' ); $input = F::input( [ 'graph' => [ 'format_version' => 1, 'components' => [ $z, $a ], 'terminal_component_ids' => [ 'zulu', 'alpha' ] ], 'endpoint_terminal_component_ids' => [ 'zulu', 'alpha' ] ] ); $packet = F::packet( F::result( $input ) );
		self::assertSame( [ 'alpha', 'zulu' ], array_column( $packet->result_facts()['body']['terminal_windows'], 'component_id' ) ); self::assertSame( [ 'alpha', 'zulu' ], array_column( $packet->private_facts()['public_views'], 'terminal_component_id' ) );
		$data = $packet->private_facts(); $result = PromiseJson::decode( $data['result_json'] ); $result['body']['terminal_windows'] = array_reverse( $result['body']['terminal_windows'] ); $data['result_json'] = PromiseJson::encode( $result ); $data['result_digest'] = hash( 'sha256', 'cetech-service-promise-result-v1:' . $data['result_json'] ); try { PromiseHistoricalPacket::from_array( $data ); self::fail( 'Reordered result must refuse.' ); } catch ( \InvalidArgumentException ) { self::assertTrue( true ); }
		$data = $packet->private_facts(); $data['public_views'] = array_reverse( $data['public_views'] ); $this->expectException( \InvalidArgumentException::class ); PromiseHistoricalPacket::from_array( $data );
	}
	public function test_typed_relative_calendar_references_preserve_canonical_id_order(): void {
		$a = CalculationFixture::calendar( [ 'calendar_id' => 'alpha' ] )->reference()->private_facts(); $z = CalculationFixture::calendar( [ 'calendar_id' => 'zulu' ] )->reference()->private_facts(); $input = F::input( [ 'anchor' => 'payment_confirmed', 'late_payment_rule' => 'relative_after_payment', 'calendars' => [ $z, $a ] ] );
		$result = PromiseResult::from_array( [ 'format_version' => 1, 'state' => 'relative_window', 'input' => $input->private_facts(), 'input_digest' => $input->digest(), 'graph_digest' => $input->policy()->graph()->digest(), 'body' => [ 'display_timezone' => 'UTC', 'awaited_event' => 'woocommerce_payment_confirmed', 'terminal_windows' => [ [ 'component_id' => 'delivery', 'min' => 10, 'max' => 20, 'unit' => 'elapsed_minutes', 'calendar_refs' => [ $z, $a ], 'known_zero' => false ] ] ], 'reason_codes' => [] ] ); $packet = PromiseHistoricalPacket::capture( $result, '10–20 minutes after payment confirmation' ); self::assertSame( [ 'alpha', 'zulu' ], array_column( $packet->result_facts()['body']['terminal_windows'][0]['calendar_refs'], 'calendar_id' ) );
		$data = $packet->private_facts(); $result = PromiseJson::decode( $data['result_json'] ); $result['body']['terminal_windows'][0]['calendar_refs'] = array_reverse( $result['body']['terminal_windows'][0]['calendar_refs'] ); $data['result_json'] = PromiseJson::encode( $result ); $data['result_digest'] = hash( 'sha256', 'cetech-service-promise-result-v1:' . $data['result_json'] ); $this->expectException( \InvalidArgumentException::class ); PromiseHistoricalPacket::from_array( $data );
	}
	#[DataProvider( 'invalid_carriers' )]
	public function test_closed_carriers_refuse_unknown_changed_and_cross_linked_facts( string $kind, string $change ): void {
		$this->expectException( \InvalidArgumentException::class );
		if ( 'context' === $kind ) { $data = F::context()->private_facts(); match ( $change ) { 'extra' => $data['unknown'] = true, 'base' => $data['promise_capture']['base_digest'] = QuoteFixtures::digest( 'changed' ), 'group' => $data['promise_capture']['groups'][0]['component_key'] = QuoteFixtures::digest( 'foreign' ), 'input' => $data['promise_capture']['groups'][0]['input_digest'] = QuoteFixtures::digest( 'foreign' ), 'policy' => $data['promise_capture']['groups'][0]['policy_reference']['version'] = 2, 'missing' => $data['promise_capture']['groups'] = [], 'future' => $data['format_version'] = 3 }; QuoteContext::from_array( $data ); }
		elseif ( 'terms' === $kind ) { $data = F::terms()->private_facts(); match ( $change ) { 'extra' => $data['unknown'] = true, 'group' => $data['promise_packets'][0]['component_key'] = QuoteFixtures::digest( 'foreign' ), 'provider' => $data['groups'][0]['provider']['code'] = 'service_promise_v1', 'missing' => $data['promise_packets'] = [], 'future' => $data['format_version'] = 3 }; QuoteTerms::from_array( $data ); }
		elseif ( 'header' === $kind ) { $data = F::header()->private_facts(); match ( $change ) { 'extra' => $data['unknown'] = true, 'profile' => $data['profile'] = 'legacy_fixed_base_v1', 'future' => $data['format_version'] = 3, 'ttl' => $data['expires_at'] = F::time()->plus_seconds( 301 )->sql() }; QuoteHeader::from_array( $data ); }
		else { $data = F::packet()->private_facts(); match ( $change ) { 'extra' => $data['unknown'] = true, 'input' => $data['input_digest'] = QuoteFixtures::digest( 'foreign' ), 'result' => $data['result_digest'] = QuoteFixtures::digest( 'foreign' ), 'view' => $data['public_views'][0]['fields']['from'] = F::time()->sql(), 'terminal' => $data['public_views'][0]['terminal_component_id'] = 'foreign', 'html' => $data['customer_text'] = '<script>', 'future' => $data['format'] = 2, 'text' => $data['customer_text'] = str_repeat( 'x', 2049 ) }; PromiseHistoricalPacket::from_array( $data ); }
	}
	public static function invalid_carriers(): array { $out = []; foreach ( [ 'context' => [ 'extra', 'base', 'group', 'input', 'policy', 'missing', 'future' ], 'terms' => [ 'extra', 'group', 'provider', 'missing', 'future' ], 'header' => [ 'extra', 'profile', 'future', 'ttl' ], 'packet' => [ 'extra', 'input', 'result', 'view', 'terminal', 'html', 'future', 'text' ] ] as $kind => $changes ) { foreach ( $changes as $change ) { $out[$kind . ':' . $change] = [ $kind, $change ]; } } return $out; }
	public function test_mixed_format_body_and_clock_renewal_are_denied(): void { $this->expectException( \InvalidArgumentException::class ); F::header( F::context(), F::terms(), 'service_promise_v1', F::time()->plus_seconds( 1 ) ); }
	public function test_mixed_v1_v2_terms_are_denied(): void { $this->expectException( \InvalidArgumentException::class ); F::header( F::context(), F::base_terms() ); }
	public function test_recomputed_header_cannot_bypass_original_owner_link(): void { $data = F::header()->private_facts(); $data['owner']['principal_hash'] = QuoteFixtures::digest( 'foreign' ); $header = QuoteHeader::from_array( $data ); $this->expectException( \InvalidArgumentException::class ); $header->assert_body( F::context(), F::terms() ); }
	public function test_required_snapshot_packet_has_own_digest_domain_and_blocks_generic_serialization(): void { $packet = F::terms()->promise_packet(); self::assertSame( hash( 'sha256', 'cetech-required-promise-snapshot-v1:' . $packet->to_private_json() ), $packet->digest() ); self::assertSame( $packet->to_private_json(), PromiseQuotePacket::from_json( $packet->to_private_json() )->to_private_json() ); $this->expectException( \LogicException::class ); serialize( $packet ); }
	public function test_whole_packet_byte_overflow_refuses_instead_of_truncating(): void { $group = F::terms()->promise_packet()->private_facts()['groups'][0]; $groups = []; for ( $i = 0; $i < 20; ++$i ) { $groups[] = $group; } self::assertGreaterThan( QuoteJson::MAX_BYTES, strlen( json_encode( [ 'format' => 1, 'groups' => $groups ], JSON_THROW_ON_ERROR ) ) ); $this->expectException( \InvalidArgumentException::class ); PromiseQuotePacket::from_array( [ 'format' => 1, 'groups' => $groups ] ); }
}
