<?php

declare(strict_types=1);
namespace CetechDeliveryEngine\Infrastructure\Persistence;
use CetechDeliveryEngine\Application\Operation\OperationStorageException;
use CetechDeliveryEngine\Domain\ServicePromise\Shipment\ShipmentRecordedPromiseReference;
use CetechDeliveryEngine\Domain\Operation\OperationSession;
use CetechDeliveryEngine\Domain\ServicePromise\Shipment\{ShipmentPromiseCommand,ShipmentPromiseStored};
use CetechDeliveryEngine\Domain\ServicePromise\Persistence\PromiseSiteBinding;
use CetechDeliveryEngine\Domain\Shipment\Shipment;
use CetechDeliveryEngine\Application\Order\PromiseSnapshotCore;

/** Same-owner primitives; no transaction, host callback or reconnection is opened here. */
final class WpdbShipmentPromiseRepository {
 private string $table;
 public function __construct(private OperationSession $session,private PromiseSiteBinding $binding){$binding->assert_session($session);$this->table=ShipmentPromiseSchema::tables($session->table_prefix())[0];}
 public function time():string{$row=$this->session->get_row('SELECT UTC_TIMESTAMP(6) AS accepted_at');if(!is_array($row)||!is_string($row['accepted_at']??null)){self::fail();}return \CetechDeliveryEngine\Domain\RuleLifecycle\RuleTime::parse($row['accepted_at'])->sql();}
 public function load(int $shipment_id,bool $lock=false):?ShipmentPromiseStored{
  $this->owned();$fields=[];foreach(ShipmentPromiseSchema::columns() as $name=>$spec){$fields[]=isset(ShipmentPromiseSchema::payload_limits()[$name])?"CASE WHEN OCTET_LENGTH(`{$name}`)<=65536 THEN `{$name}` ELSE NULL END AS `{$name}`":"`{$name}`";}foreach(ShipmentPromiseSchema::payload_limits() as $name=>$limit){$fields[]="OCTET_LENGTH(`{$name}`) AS `__{$name}_bytes`";}
  $rows=$this->session->get_results($this->session->prepare('SELECT '.implode(',',$fields)." FROM `{$this->table}` WHERE site_id=%d AND site_key=%s AND shipment_id=%d LIMIT 2".($lock?' FOR UPDATE':''),$this->binding->native_site_id(),$this->binding->site_key(),$shipment_id));if(false===$rows||count($rows)>1){self::fail();}if([]===$rows){return null;}$row=$rows[0];foreach(ShipmentPromiseSchema::payload_limits() as $name=>$limit){$marker='__'.$name.'_bytes';$bytes=$row[$marker]??null;if(null!==$bytes&&(!is_string($row[$name])||(string)strlen($row[$name])!==(string)$bytes||strlen($row[$name])>$limit)){self::fail();}if(null===$bytes&&null!==$row[$name]){self::fail();}unset($row[$marker]);}return ShipmentPromiseStored::from_row($row,$this->binding);
 }
 public function assert_ack(ShipmentPromiseStored $stored):void{$stored->assert_receipts(fn(string $namespace):array=>$this->receipt($namespace));}
 private function receipt(string $namespace):array{
  $records=WpdbOperationRecordRepository::table_name($this->session,OperationStoreSchema::RECORDS_SUFFIX);$changes=WpdbOperationRecordRepository::table_name($this->session,OperationStoreSchema::CHANGES_SUFFIX);$projection='id,site_id,namespace_hash,intent_hash,namespace_format,intent_format,record_format,operation,operation_version,target_hash,state,publication_state,CASE WHEN OCTET_LENGTH(completion_json)<=16384 THEN completion_json ELSE NULL END AS completion_json,audit_id,row_version,created_at,updated_at,completed_at';$rows=$this->session->get_results($this->session->prepare("SELECT {$projection} FROM `{$records}` WHERE site_id=%d AND namespace_hash=%s LIMIT 2",$this->binding->native_site_id(),$namespace));if(false===$rows||1!==count($rows)){self::fail();}$events=$this->session->get_results($this->session->prepare("SELECT id,site_id,operation_id,event_format,CASE WHEN OCTET_LENGTH(event_json)<=16384 THEN event_json ELSE NULL END AS event_json,created_at FROM `{$changes}` WHERE site_id=%d AND operation_id=%d LIMIT 2",$this->binding->native_site_id(),(int)$rows[0]['id']));if(false===$events||1!==count($events)){self::fail();}return [$rows[0],$events[0]];
 }
 /** Creates shipment/items/Created event and immutable original on this same material owner. */
 public function create(ShipmentPromiseCommand $command):array {
  $this->owned();$draft=$command->shipment;$shipments=WpdbOperationRecordRepository::table_name($this->session,ShipmentSchema::SHIPMENTS_SUFFIX);$rows=$this->session->get_results($this->session->prepare("SELECT id,order_id,delivery_group_id FROM `{$shipments}` WHERE order_id=%d AND BINARY delivery_group_id=%s LIMIT 2 FOR UPDATE",$draft->order_id,$draft->delivery_group_id));if(false===$rows||count($rows)>1){self::fail();}
  if([]!==$rows){$stored=$this->load((int)$rows[0]['id'],true);if(null===$stored){self::fail();}$this->assert_ack($stored);$shipment=$draft->withId((int)$rows[0]['id']);$reference=ShipmentRecordedPromiseReference::from_recorded($shipment,$command->envelope,$command->linkage);if($reference->digest()!==$stored->row()['original_digest']){self::fail();}return ['stored'=>$stored,'changed'=>false];}
  $at=$this->time();$row=get_object_vars($draft);unset($row['id']);$row['status']=$draft->status->value;$row['created_at']=substr($at,0,19);$row['updated_at']=substr($at,0,19);$id=$this->insert($shipments,$row);$shipment=$draft->withId($id);
  $items=WpdbOperationRecordRepository::table_name($this->session,ShipmentSchema::ITEMS_SUFFIX);foreach($command->items as $item){$row=get_object_vars($item);unset($row['id']);$row['shipment_id']=$id;$row['created_at']=substr($at,0,19);$this->insert($items,$row);}
  $events=WpdbOperationRecordRepository::table_name($this->session,ShipmentSchema::EVENTS_SUFFIX);$this->insert($events,['shipment_id'=>$id,'event_type'=>'created','from_status'=>null,'to_status'=>$draft->status->value,'public_note'=>null,'internal_note'=>null,'actor_user_id'=>$command->actor_user_id,'source'=>$command->source->value,'event_at'=>substr($at,0,19),'created_at'=>substr($at,0,19)]);
  $reference=ShipmentRecordedPromiseReference::from_recorded($shipment,$command->envelope,$command->linkage);$group=PromiseSnapshotCore::group($command->envelope,$draft->delivery_group_id);$packet=$command->envelope->promise_packet()->group($group['key']);$record=['site_id'=>$this->binding->native_site_id(),'site_key'=>$this->binding->site_key(),'shipment_id'=>$id,'order_id'=>$draft->order_id,'delivery_group_id'=>$draft->delivery_group_id,'revision'=>2,'original_json'=>$reference->to_private_json(),'original_digest'=>$reference->digest(),'packet_json'=>$packet->to_private_json(),'packet_digest'=>$packet->digest(),'current_json'=>null,'current_digest'=>null,'original_namespace_hash'=>$command->identity->namespace_digest(),'original_intent_hash'=>$command->intent()->fingerprint(),'current_namespace_hash'=>null,'current_intent_hash'=>null,'created_at'=>$at,'updated_at'=>$at];$record['id']=$this->insert($this->table,$record);return ['stored'=>ShipmentPromiseStored::from_row($record,$this->binding),'changed'=>true];
 }
 public function update(ShipmentPromiseStored $before,ShipmentPromiseCommand $command):ShipmentPromiseStored {
  $row=$before->row();$at=$this->time();if($at<$row['updated_at']||$command->current->private_facts()['original_packet_digest']!==$row['packet_digest']){self::fail();}$values=['revision'=>$row['revision']+1,'current_json'=>$command->current->to_private_json(),'current_digest'=>$command->current->digest(),'current_namespace_hash'=>$command->identity->namespace_digest(),'current_intent_hash'=>$command->intent()->fingerprint(),'updated_at'=>$at];$set=[];$args=[];foreach($values as $field=>$value){$set[]="`{$field}`=".(is_int($value)?'%d':'%s');$args[]=$value;}$args[]=$row['id'];$args[]=$row['revision'];$args[]=$row['original_digest'];$sql=$this->session->prepare("UPDATE `{$this->table}` SET ".implode(',',$set).' WHERE id=%d AND revision=%d AND original_digest=%s',...$args);if(1!==$this->session->query($sql)){self::fail();}
  $events=WpdbOperationRecordRepository::table_name($this->session,ShipmentSchema::EVENTS_SUFFIX);$this->insert($events,['shipment_id'=>$row['shipment_id'],'event_type'=>'eta_updated','from_status'=>null,'to_status'=>null,'public_note'=>null,'internal_note'=>$command->current->private_facts()['reason'],'actor_user_id'=>$command->actor_user_id,'source'=>$command->source->value,'event_at'=>substr($at,0,19),'created_at'=>substr($at,0,19)]);return ShipmentPromiseStored::from_row(array_replace($row,$values),$this->binding);
 }
 private function insert(string $table,array $row):int{$fields=[];$formats=[];$args=[];foreach($row as $name=>$value){$fields[]='`'.$name.'`';$formats[]=null===$value?'NULL':(is_int($value)?'%d':'%s');if(null!==$value){$args[]=$value;}}$sql=$this->session->prepare("INSERT INTO `{$table}` (".implode(',',$fields).') VALUES ('.implode(',',$formats).')',...$args);if(1!==$this->session->query($sql)||$this->session->insert_id()<1){self::fail();}return $this->session->insert_id();}
 private function owned():void{if(!$this->session->in_transaction()||$this->session->is_retired()){self::fail();}}
 private static function fail():never{throw new OperationStorageException();}
}
