<?php
declare(strict_types=1);
// Isolated loaded-native-shape fixture; no claim of actual WordPress execution.
require dirname( __DIR__, 3 ) . '/vendor/autoload.php';
use CetechDeliveryEngine\Application\DeliveryQuote\NativeCartQuoteEnvironment;
use CetechDeliveryEngine\Domain\Operation\OperationConnectionFactory;
use CetechDeliveryEngine\Domain\Operation\OperationSession;

define( 'AUTH_KEY', str_repeat( 'a', 32 ) ); define( 'AUTH_SALT', str_repeat( 'b', 32 ) ); define( 'LOGGED_IN_COOKIE', 'native_logged_in' );
final class NativeCalls { public static int $getters = 0; public static int $queries = 0; public static function forbidden(): never { ++self::$getters; throw new LogicException( 'A native callback was called.' ); } }
class WC_Cart { public array $cart_contents = []; public function get_cart(): never { NativeCalls::forbidden(); } public function get_shipping_packages(): never { NativeCalls::forbidden(); } public function get_total(): never { NativeCalls::forbidden(); } }
class WC_Customer { protected array $data = [ 'shipping' => [ 'country'=>'GH', 'state'=>'AA', 'city'=>'Accra', 'postcode'=>'GA-001', 'address_1'=>'PRIVATE ADDRESS', 'address_2'=>'' ] ]; protected array $changes=[]; public function address():void { $this->changes['shipping']['address_1']='NEW PRIVATE ADDRESS'; } }
class WC_Session_Handler { protected string $_customer_id = '9'; protected bool $_has_cookie = true; protected array $_data = []; public function __construct( array $methods ) { $this->_data['chosen_shipping_methods'] = serialize( $methods ); } public function get_customer_id(): never { NativeCalls::forbidden(); } public function get(): never { NativeCalls::forbidden(); } public function customer( string $id ): void { $this->_customer_id = $id; } public function methods( mixed $v ): void { $this->_data['chosen_shipping_methods'] = $v; } }
class CartTokenSessionHandler extends WC_Session_Handler {}
class WC_Shipping { protected static ?self $_instance = null; public array $packages = []; public static function install( self $v ): void { self::$_instance = $v; } public function get_packages(): never { NativeCalls::forbidden(); } }
class WP_Object_Cache { private array $cache; private string $blog_prefix; protected array $global_groups; private bool $multisite; public function __construct( string $prefix = '', bool $global = false ) { $this->blog_prefix = $prefix; $this->global_groups = $global ? [ 'options' => true ] : []; $this->multisite = '' !== $prefix; $this->cache['options'][( $global ? '' : $prefix ) . 'alloptions'] = [ 'woocommerce_currency' => 'GHS', 'woocommerce_price_num_decimals' => '2' ]; } public function clear(): void { $this->cache = []; } }
class WP_Hook { public array $callbacks = []; }
function WC(): never { NativeCalls::forbidden(); } function get_option(): never { NativeCalls::forbidden(); } function get_current_user_id(): never { NativeCalls::forbidden(); } function get_current_blog_id(): never { NativeCalls::forbidden(); } function wc_get_product(): never { NativeCalls::forbidden(); } function wp_salt(): never { NativeCalls::forbidden(); }
$selection = [ 'contract_version' => '1', 'product_id' => 10, 'variation_id' => null, 'target_type' => 'product', 'target_id' => 10, 'display_key' => 'in_warehouse:delivery:20', 'fulfilment_availability' => 'in_warehouse', 'fulfilment_choice' => 'delivery', 'delivery_offer_id' => 20, 'rule_id' => 1 ];
$line = [ 'product_id' => 10, 'variation_id' => 0, 'quantity' => 2, 'data' => new stdClass(), 'cetech_de_delivery_selection' => $selection, 'cetech_de_delivery_selection_hash' => hash( 'sha256', 'selection' ), 'cetech_de_customer_context' => [ 'contract_version' => 1, 'fulfilment_choice' => 'delivery', 'delivery_offer_id' => 20, 'delivery_address' => [ 'country' => 'GH', 'state' => 'AA', 'city' => 'Accra', 'postcode' => 'GA-001', 'address_1' => 'PRIVATE ADDRESS', 'address_2' => '', 'recipient' => [ 'first_name' => 'PRIVATE NAME' ] ] ] ];
$cart = new WC_Cart(); $cart->cart_contents = [ 'line_one' => $line ]; $shipping = new WC_Shipping(); $shipping->packages = [ [ 'contents' => $cart->cart_contents, 'cetech_de' => [ 'managed' => true, 'group_id' => 'delivery|20|endpoint' ], 'destination' => [ 'country' => 'GH', 'state' => 'AA', 'city' => 'Accra', 'postcode' => 'GA-001', 'address' => 'PRIVATE ADDRESS', 'address_2' => '' ] ] ]; WC_Shipping::install( $shipping );
$session = new WC_Session_Handler( [ 'delivery_engine_selected_offer:1:abc' ] ); $GLOBALS['woocommerce'] = (object) [ 'cart' => $cart, 'customer' => new WC_Customer(), 'session' => $session ]; $GLOBALS['current_user'] = (object) [ 'ID' => 9 ]; $GLOBALS['blog_id'] = 1; $GLOBALS['wp_filter'] = []; $GLOBALS['wp_object_cache'] = new WP_Object_Cache(); $_COOKIE[LOGGED_IN_COOKIE] = 'name|2000000000|first-auth-session|signature';
$access = new class implements \CetechDeliveryEngine\Application\DeliveryQuote\QuotePreparationAccess { public int $observations=0; public function observe(\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteOwner $owner):?int { ++$this->observations; return null; } public function confirm(\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteOwner $owner,int $revision):bool { return false; } };
$factory = new class implements OperationConnectionFactory { public function open(): OperationSession { ++NativeCalls::$queries; throw new LogicException( 'An owned SQL session was opened.' ); } };
$environment = new NativeCartQuoteEnvironment( $factory, $access ); $mode = $argv[1] ?? 'baseline';
switch ( $mode ) { case 'multisite': $GLOBALS['wp_object_cache'] = new WP_Object_Cache( '1:' ); break; case 'global_options': $GLOBALS['wp_object_cache'] = new WP_Object_Cache( '1:', true ); break; case 'fresh_request': $shipping->packages=[]; $session->methods(null); break; case 'missing_cache': $GLOBALS['wp_object_cache']->clear(); break; case 'cart_token': $GLOBALS['woocommerce']->session = new CartTokenSessionHandler( [ 'delivery_engine_selected_offer:1:abc' ] ); break; case 'malformed_session': $session->methods( 'a:1:{i:0;O:4:"Trap":0:{}}' ); break; case 'wrong_session': $session->customer( '10' ); break; case 'salt_hook': $hook = new WP_Hook(); $hook->callbacks = [ 10 => [ [ 'function' => [ NativeCalls::class, 'forbidden' ] ] ] ]; $GLOBALS['wp_filter']['salt'] = $hook; break; case 'no_auth_cookie': unset( $_COOKIE[LOGGED_IN_COOKIE] ); break; }
$draft = $environment->draft(); $out = [ 'available' => null !== $draft, 'getters' => NativeCalls::$getters, 'queries' => NativeCalls::$queries ];
if ( null !== $draft ) {
	$out['session_authorized'] = $environment->authorize( $draft->owner(), 'delivery_quote.session' ); $out['unknown_authorized'] = $environment->authorize( $draft->owner(), 'unrelated.delete' ); $out['owner_digest'] = $draft->owner()->digest(); $out['draft_digest'] = $draft->draft_digest(); $out['recipient_omitted'] = ! isset( $draft->private_facts()['lines'][0]['customer_context']['delivery_address']['recipient'] );
	if ( in_array($mode,['paused_original','changed_original'],true) ) {
		$fixture=\CetechDeliveryEngine\Tests\Support\DeliveryQuote\QuoteFixtures::context()->private_facts(); $fixture['selection_digest']=hash('sha256',\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteJson::encode(['line_one'=>$line['cetech_de_delivery_selection_hash']])); $fixture['destination']['key_epoch']=$draft->owner()->key_epoch();
		$context=\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteContext::from_array($fixture); $command=\CetechDeliveryEngine\Application\DeliveryQuote\QuoteIssueCommand::create($draft->owner(),$context,'legacy_fixed_base_v1',1,'legacy_fixed_base_v1',1,'original-issue-token'); $id=\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteId::generate();
		$header=\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteHeader::issue($id,$draft->owner(),$context,\CetechDeliveryEngine\Tests\Support\DeliveryQuote\QuoteFixtures::terms(),\CetechDeliveryEngine\Domain\DeliveryQuote\QuoteTime::now(),$command->namespace_hashes($id),'legacy_fixed_base_v1');
		if('changed_original'===$mode){$command=\CetechDeliveryEngine\Application\DeliveryQuote\QuoteIssueCommand::create($draft->owner(),$context,'legacy_fixed_base_v1',1,'legacy_fixed_base_v1',1,'different-token');}
		$out['evidence_available']=null!==$environment->evidence($command,$header,$draft); $out['control_reads']=$access->observations;
	}
	if ( 'rotate_auth' === $mode ) { $_COOKIE[LOGGED_IN_COOKIE] = 'name|2000000000|second-auth-session|signature'; $fresh = $environment->draft(); $out['original_authorized'] = $environment->authorize( $draft->owner(), 'delivery_quote.session' ); $out['new_owner_differs'] = null !== $fresh && ! $fresh->owner()->equals( $draft->owner() ); $out['new_draft_differs'] = null !== $fresh && $fresh->draft_digest() !== $draft->draft_digest(); }
	if ( 'auto_chosen' === $mode ) { $shipping->packages=[]; $session->methods(serialize(['another-auto-chosen-rate'])); $fresh=$environment->draft(); $out['draft_unchanged']=null!==$fresh && $fresh->draft_digest()===$draft->draft_digest(); }
	if ( 'native_destination' === $mode ) { $GLOBALS['woocommerce']->customer->address(); $fresh=$environment->draft(); $out['draft_changed']=null!==$fresh && $fresh->draft_digest()!==$draft->draft_digest(); }
	if ( 'quantity' === $mode ) { $cart->cart_contents['line_one']['quantity'] = 3; $shipping->packages[0]['contents'] = $cart->cart_contents; $fresh = $environment->draft(); $out['draft_changed'] = null !== $fresh && $fresh->draft_digest() !== $draft->draft_digest(); $out['owner_unchanged'] = null !== $fresh && $fresh->owner()->equals( $draft->owner() ); }
}
$out['getters'] = NativeCalls::$getters; $out['queries'] = NativeCalls::$queries; echo json_encode( $out, JSON_THROW_ON_ERROR );
