<?php
declare(strict_types=1);
// Actual retained resolver/validator and native receipt codecs; synthetic host facts only.
function wp_salt( string $scheme = 'auth' ): string { return str_repeat( 'key', 16 ); }
class WooCommerce {}
class WC_Cache_Helper { public static function invalidate_cache_group( string $group ): void {} }
require dirname( __DIR__, 3 ) . '/tests/bootstrap.php';
use CetechDeliveryEngine\Application\DeliveryQuote\{LegacyQuoteSourceSeedRows,LegacyQuoteNativeSourcePreparer,NativeCartQuotePreparation,QuoteCartDraft,QuoteNativeContextIdentity,QuoteNativeCaptureSource,QuoteNativeState,QuoteNativeReceiptCapture,QuoteNativeGroupRequest};
use CetechDeliveryEngine\Application\Cart\CartDeliverySelectionFingerprint;
use CetechDeliveryEngine\Domain\CustomerContext\{CustomerCartContext,DeliveryAddress};
use CetechDeliveryEngine\Domain\DeliveryQuote\{QuoteOwner,QuoteMoney,QuoteTime};
use CetechDeliveryEngine\Domain\Operation\{OperationConnectionFactory,OperationSession};
class CartContextProduct extends WC_Product {
	public function get_status(): string { return 'publish'; } public function is_purchasable(): bool { return true; } public function get_stock_status(): string { return 'instock'; } public function get_stock_quantity(): int { return 4; } public function managing_stock(): bool { return true; } public function backorders_allowed(): bool { return false; } public function has_enough_stock( int $quantity ): bool { return $quantity <= 4; } public function is_in_stock(): bool { return true; } public function get_backorders(): string { return 'no'; } public function get_stock_managed_by_id(): int { return $this->get_id(); }
}
$GLOBALS['cetech_de_test_options'] = [ 'cetech_de_enable_product_delivery_selector' => 1, 'woocommerce_currency' => 'GHS' ]; $GLOBALS['wp_filter'] = [];
$mode = $argv[1] ?? 'baseline'; $identity = QuoteNativeContextIdentity::from_server(); $owner = QuoteOwner::from_array( [ 'site_id' => 1, 'kind' => 'guest', 'principal_hash' => hash( 'sha256', 'principal' ), 'session_hash' => hash( 'sha256', 'session' ), 'key_epoch' => $identity->key_epoch() ] );
$address = DeliveryAddress::fromInput( [ 'country' => 'GH', 'state' => 'AA', 'city' => 'Accra', 'postcode' => 'GA-001', 'address_1' => 'PRIVATE ADDRESS' ] ); $items = []; $rules = [];
foreach ( [ 10, 11 ] as $id ) {
	$GLOBALS['cetech_de_test_wc_products'][$id] = new CartContextProduct( [ 'id' => $id, 'type' => 'simple', 'name' => 'Product' ] );
	$intent = [ 'contract_version' => '1', 'product_id' => $id, 'variation_id' => null, 'target_type' => 'product', 'target_id' => $id, 'display_key' => 'in_warehouse:delivery:20', 'fulfilment_availability' => 'in_warehouse', 'fulfilment_choice' => 'delivery', 'delivery_offer_id' => 20, 'rule_id' => $id ];
	$items['line_' . $id] = CustomerCartContext::delivery( 20, null, $address )->applyToCartItem( [ 'product_id' => $id, 'variation_id' => 0, 'quantity' => 2, 'cetech_de_delivery_selection' => $intent, 'cetech_de_delivery_selection_hash' => CartDeliverySelectionFingerprint::fromIntent( $intent ) ] );
	$rules[] = [ 'id' => (string) $id, 'target_type' => 'product', 'target_id' => (string) $id, 'target_label_snapshot' => null, 'fulfilment_availability' => 'in_warehouse', 'fulfilment_choice' => 'delivery', 'delivery_offer_ids' => '[20]', 'pickup_location_id' => null, 'supplier_id' => '33', 'origin_id' => null, 'logistics_profile_id' => null, 'priority' => '1', 'status' => 'active' ];
}
if ( 'mixed_supplier' === $mode ) { $rules[1]['supplier_id'] = '99'; }
if ( 'stock_aggregate' === $mode ) { $items['line_11']['product_id'] = 10; $items['line_11']['quantity'] = 3; $items['line_11']['cetech_de_delivery_selection'] = $items['line_10']['cetech_de_delivery_selection']; $items['line_11']['cetech_de_delivery_selection_hash'] = $items['line_10']['cetech_de_delivery_selection_hash']; }
if ( 'selection_changed' === $mode ) { $rules[1]['priority'] = '2'; $rules[1]['id'] = '12'; }
if ( 'address_changed' === $mode ) { $items['line_11'] = CustomerCartContext::delivery( 20, null, DeliveryAddress::fromInput( [ 'country' => 'GH', 'state' => 'AA', 'city' => 'Accra', 'postcode' => 'GA-001', 'address_1' => 'SECOND PRIVATE ADDRESS' ] ) )->applyToCartItem( $items['line_11'] ); }
$destination = $address->toWcPackageDestination(); $loaded_destination=array_intersect_key($destination,array_flip(['country','state','city','postcode','address','address_2'])); $group_id = 'delivery|20|captured-endpoint'; $component = NativeCartQuotePreparation::component_key( $group_id );
$packages = [ [ 'contents' => $items, 'cetech_de' => [ 'managed' => true, 'group_id' => $group_id ], 'destination' => $destination ] ]; $draft = QuoteCartDraft::from_loaded_cart( $owner, $items, $loaded_destination, 'GHS', 2, $identity );
$rows = [ 'legacy_rules' => $rules, 'offers' => [ [ 'id' => '20', 'status' => 'active', 'public_label' => 'Delivery', 'route' => 'normal_delivery' ] ], 'scopes' => [], 'scope_fields' => [], 'scope_collections' => [], 'options' => [], 'zones' => [ [ 'id' => '50', 'internal_code' => 'ghana', 'status' => 'inactive_zone' === $mode ? 'inactive' : 'active', 'priority' => '1' ] ], 'zone_rules' => [ [ 'id' => '1', 'zone_id' => '50', 'rule_type' => 'country', 'rule_value' => 'GH', 'match_mode' => 'exact', 'priority' => '1' ] ] ];
if ( 'missing_offer' === $mode ) { $rows['offers'] = []; }
$seed = new LegacyQuoteSourceSeedRows( $rows, QuoteTime::now() ); $members = [];
foreach ( $items as $key => $item ) { $members[] = [ 'line_key' => $key, 'product_id' => $item['product_id'], 'variation_id' => null, 'quantity' => (string) $item['quantity'] ]; }
if ( 'native_quantity' === $mode ) { $members[1]['quantity'] = '3'; }
$native_facts = [ 'currency' => 'native_currency' === $mode ? 'USD' : 'GHS', 'display_precision' => 2, 'internal_precision' => 4, 'exempt' => false, 'tax_class' => '', 'location_digest' => $identity->tax_location_digest( 1, [ 'GH', 'AA', 'GA-001', 'Accra' ] ), 'destination_digest' => $identity->destination_digest( 1, $destination ), 'key_epoch' => $identity->key_epoch(), 'rounding' => 'per_line', 'tax_enabled' => false, 'coupons' => 0, 'unsupported_effects' => false, 'cart_shipping_total' => '7', 'cart_shipping_tax' => '0', 'packages' => [ [ 'group_id' => $group_id, 'rate_id' => 'delivery_engine_selected_offer:1:abc', 'method_id' => 'delivery_engine_selected_offer', 'instance_id' => 1, 'tax_status' => 'none', 'label' => 'Delivery', 'cost' => '7', 'taxes' => [], 'fresh_taxes' => [], 'rounded_tax' => '0.00', 'display_total' => '7.00', 'members' => $members ] ], 'source_facts' => [ 'option_rows' => [], 'tax_rows' => [], 'tax_class_rows' => [], 'tax_location_rows' => [], 'method_rows' => [], 'session_row' => [], 'customer_rows' => [], 'selectors' => [ 'option_names' => [ 'woocommerce_currency' ], 'tax_class' => '', 'method_instance_ids' => [ 1 ], 'session_key' => 'fixture', 'customer_id' => 0, 'site_id' => 1, 'table_prefix' => 'wp_' ] ] ];
$source = new class( $owner, $native_facts ) implements QuoteNativeCaptureSource { public function __construct( private QuoteOwner $owner, private array $facts ) {} public function current_owner(): QuoteOwner { return $this->owner; } public function capture(): QuoteNativeState { return QuoteNativeState::from_array( $this->facts ); } public function unchanged(): bool { return true; } };
$native = ( new QuoteNativeReceiptCapture( $source ) )->capture( $owner, [ new QuoteNativeGroupRequest( $component, $group_id, QuoteMoney::from_array( [ 'amount' => '7', 'currency' => $native_facts['currency'], 'precision' => 6 ] ) ) ] );
$factory = new class implements OperationConnectionFactory { public int $calls = 0; public function open(): OperationSession { ++$this->calls; throw new LogicException( 'Context assembly cannot open a SQL session.' ); } };
try {
	$package_facts = [ [ 'package_key'=>'0', 'legacy_group_id'=>$group_id, 'line_keys'=>array_keys($items), 'destination'=>$destination ] ];
	$context = ( new NativeCartQuotePreparation( $factory ) )->context_from_observed( $draft, $seed, $native, $package_facts ); $facts = $context->private_facts();
	if ( str_starts_with( $mode, 'evidence_' ) ) {
		$receipt = $native->group( $component ); $final = $receipt->final_money()->facts();
		$terms = \CetechDeliveryEngine\Domain\DeliveryQuote\QuoteTerms::from_array( [ 'format_version' => 1, 'groups' => [ [ 'component_key' => $component, 'customer_label' => $receipt->customer_label(), 'provider' => [ 'code' => 'legacy_fixed_base_v1', 'version' => 1 ], 'policy_digest' => $seed->digest(), 'list' => $final, 'final' => $final, 'tax' => $receipt->tax_money()->facts(), 'total' => $receipt->total_money()->facts(), 'promotion' => $receipt->promotion(), 'cost' => [ 'state' => 'unavailable', 'reason' => 'cost_provider_unavailable' ], 'route' => [ 'state' => 'not_recorded' ], 'native_tax_receipt' => $receipt->native_tax_receipt(), 'native_money_receipt' => $receipt->native_money_receipt() ] ] ] );
		$command = \CetechDeliveryEngine\Application\DeliveryQuote\QuoteIssueCommand::create( $owner, $context, 'legacy_fixed_base_v1', 1, 'legacy_fixed_base_v1', 1, 'original-issue-token' ); $id = \CetechDeliveryEngine\Domain\DeliveryQuote\QuoteId::generate();
		$header = \CetechDeliveryEngine\Domain\DeliveryQuote\QuoteHeader::issue( $id, $owner, $context, $terms, QuoteTime::now(), $command->namespace_hashes( $id ), 'legacy_fixed_base_v1' );
		if ( 'evidence_wrong_provider' === $mode ) { $command = \CetechDeliveryEngine\Application\DeliveryQuote\QuoteIssueCommand::create( $owner, $context, 'unknown_provider', 1, 'legacy_fixed_base_v1', 1, 'original-issue-token' ); }
		if ( 'evidence_new_token' === $mode ) { $command = \CetechDeliveryEngine\Application\DeliveryQuote\QuoteIssueCommand::create( $owner, $context, 'legacy_fixed_base_v1', 1, 'legacy_fixed_base_v1', 1, 'replacement-token' ); }
		if ( 'evidence_new_quantity' === $mode ) { $items['line_10']['quantity'] = 3; $packages[0]['contents'] = $items; $draft = QuoteCartDraft::from_loaded_cart( $owner, $items, $loaded_destination, 'GHS', 2, $identity ); }
		if ( 'evidence_wrong_owner' === $mode ) { $other = $owner->facts(); $other['session_hash'] = hash( 'sha256', 'another-auth-session' ); $draft = QuoteCartDraft::from_loaded_cart( QuoteOwner::from_array( $other ), $items, $loaded_destination, 'GHS', 2, $identity ); }
		if ( 'evidence_header_material' === $mode ) { $changed = $header->private_facts(); $changed['material_digest'] = hash( 'sha256', 'forged-material' ); $header = \CetechDeliveryEngine\Domain\DeliveryQuote\QuoteHeader::from_array( $changed ); }
		$evidence = ( new NativeCartQuotePreparation( $factory, $source ) )->evidence( $command, $header, $draft );
		echo json_encode( [ 'available' => null !== $evidence, 'factory_calls' => $factory->calls, 'header_unchanged' => $header->id()->equals( $id ) && $header->expires_at()->equals( $header->created_at()->plus_seconds( 300 ) ), 'original_context_unchanged' => $command->context()->digest() === $context->digest() ], JSON_THROW_ON_ERROR ); exit;
	}
	echo json_encode( [ 'available' => true, 'acceptable' => $context->checkout_acceptable(), 'members' => count( $facts['lines'] ), 'candidate_count' => $facts['groups'][0]['candidate_count'], 'observed_seed_digest' => $facts['groups'][0]['candidate_digest'] === $seed->digest(), 'supplier' => $facts['groups'][0]['supplier'], 'native_tax_exact' => $facts['tax'] === $native->tax_facts(), 'source_routes' => array_column( array_column( $facts['lines'], 'source' ), 'route' ), 'private_address_absent' => ! str_contains( $context->to_private_json(), 'PRIVATE' ), 'factory_calls' => $factory->calls ], JSON_THROW_ON_ERROR );
} catch ( Throwable $e ) { echo json_encode( [ 'available' => false, 'error_class' => get_class( $e ), 'safe_error' => ! str_contains( $e->getMessage(), 'PRIVATE' ), 'factory_calls' => $factory->calls ], JSON_THROW_ON_ERROR ); }
